### ISSUE TITLE
Unnecessary / Redundant Nested Data 

### ISSUE THREAD

**Issue by DylanTallchiefGit** [construct/construct#1000]
I'm working with a bit of prefixed data.  The only important part (to me) is the string, but because it's surrounded by other consistent data that needs to be there, I wrap it in a Struct. Quick example below:

```
'name' / Prefixed(Int32ul, Struct(
                Const(b'1234'),
                'name' / PascalString(Int32ul, 'utf8'),
                Padding(4)
)),
```
This works great but results in a container like:

```
{'name': {
        'name':<name>  }
}
```
It would nice to parse and build something like `{'name':<name>}` but still have the const and padding and other unnamed members inside the Prefix.

I could solve this with an Adapter or pre/post processing the data, but I was wondering if there is a native solution that I'm not thinking of. Or am I trying to use Construct in a way it wasn't designed for?
There are other formatting issues I have but I'm wondering if formatting for presentational purposes should be done entirely separately and not to do it with Construct.

**Comment by arekbulski** [comment]
Yeah, your question is entirely valid. For that purposes a FocusedSeq class was developed:
https://construct.readthedocs.io/en/latest/misc.html?highlight=focusedseq#focusedseq
