### ISSUE TITLE
Abstract base class throwing wrong exception

### ISSUE THREAD

**Issue by leonardmgh** [construct/construct#1001]
https://github.com/construct/construct/blob/35cfad42bbc392a4c2946195036418846736ed11/construct/core.py#L482
Should throw ```NotImplementedError```.

Current implementation causes problems with pylance as described [here](https://github.com/microsoft/pylance-release/issues/3532#issue-1422340177)

**Comment by arekbulski** [comment]
It is an interesting read. Unfortunately simply replacing that raise line of code would break current expectations so I am not going to do that. Construct is totally broken when it comes to VSCode btw. Talk with Timmy from construct-typed. Maybe he can fix it on his side? @timrid 
https://github.com/timrid/construct-typing

**Comment by timrid** [comment]
I am not quite sure where your error occurs? In the example you linked, there is only code that has nothing to do with this library. Can you please show a short example with your error?

Maybe it could be fixed in`construct-typing`. But `construct-typing` currently only implements stubs for the "public" API of `construct`. So everything private (starting with an underscore) like `_sizeof()` has currently no type hints.

**Comment by leonardmgh** [comment]
@timrid 
```python
import construct

CommonStackParams = construct.Struct(
    "BluetoothAdapterId" / construct.Int32ul,
)

CommonStackParams.sizeof()

print("This code is marked as unreachable!")
```
This illustrates the problem using construct. The code is also marked as unreachable in vscode when type checking is disabled.
The code analyzer resolves ```sizeof()``` to be calling ```_sizeof()``` of the abstract class ```Construct``` instead of ```Struct```.
The example originates from [here](https://github.com/project-chip/connectedhomeip/blob/b9d32ecefd004adb7cc4c70a5f4a567dca199da0/src/controller/python/chip/native/__init__.py#L185)

@arekbulski 
I'm sorry for that, I have pushed an updated that (at least I think so) doesn't break the current expectations

**Comment by leonardmgh** [comment]
@arekbulski I agree that my solution is far from clean, but had hoped it could fix this small annoyance without changing the current implementation too much. I don't have the time to implement a better solution considering the severity of the problem.

**Comment by timrid** [comment]
You don't have to change your implementation at all. You just have to
```
pip install construct-typing
```
As I said, construct-typing implements stubs for the public API of construct. So it implements [type hints for `sizeof()`](https://github.com/timrid/construct-typing/blob/v0.5.2/construct-stubs/core.pyi#L108).

When pylance don't find any type hints, it analyses the code to detect the correct types. So it detects the `raise SizeofError(path=path)`. But if you have type stubs installed, pylance will use these types.

**Comment by arekbulski** [comment]
Thank you on behalf of everyone benefiting. @timrid
