### ISSUE TITLE
How to use Switch where multiple cases have the same "default" structure?

### ISSUE THREAD

**Issue by StohanzlMart** [construct/construct#1005]
Hello again!

In reality I have 20 cases to switch and of those, 10 cases share one Structure (will be default= ofc) and 3 share another. For the sake of simplicity, I'm going to use another example like this:

Let's say I have a Switch where "case" 1, 3, 5 have subcon Struct A and 2, 4, 6 have subcon Struct B. How would you do this without code repetition?

Currently I have:
```python
ct.Switch(ct.Int16ul, {
  1: Struct-A,
  3: Struct-A,
  5: Struct-A,
  }, default = 
  Struct-B
)
```

I know that in C you have to `break` cases to prevent the desired behavior, but can you `continue` or something similar in Python?

**Comment by arekbulski** [comment]
Please forgive me for waiting the entire of 2 weeks to reply to your question. I really did not feel like engaging anyone in a discussion. There is not much to say here, but I will share with you what I know to be true.

Switch cases have an implicit break semantic (ie. they do not have a fallthrough semantic). The Switch class does not care at all in which order the cases were made, the cases are in a dictionary and not an Ordered Dictionary, thus making potential fallthough a road to nonsense. There is no such a thing as a "continue semantic" in switch cases, not in C, not in Python, not in Construct. You have to elaborate more what it is that you mean by it. I assume you did not yourself had an idea what that would be, but if I am wrong then please, feel free to elaborate on the idea. 

"Struct-A" is not a valid identifier in Python. I presume it was a pseudocode.

I definitely do not recommend using the default case. You want garbage data to yield clear errors and not parse into nonsense and even possibly raising strange errors down the line. Do NOT DO IT.

To avoid duplicating the code you should, and I presume you already know this, to define say variables A and B and assign some Structs to them, then in Switch cases reuse A and B. In other words, DO NOT do following:

```py
Switch(this.opcode, {
    1: Struct(a=Byte, b=Byte, c=Byte),
    2: Struct(a=Byte, b=Byte, c=Byte),
    3: Struct(a=Byte, b=Byte, c=Byte),
})
```

instead to this

```py
A = Struct(a=Byte, b=Byte, c=Byte)

Switch(this.opcode, {
    1: A,
    2: A,
    3: A,
})
```
