### ISSUE TITLE
Iterate Container's items, unexpected `_io` field

### ISSUE THREAD

**Issue by waszil** [construct/construct#1007]
Hello,
Let's say I have a Structure like this:
```python
MyStruct = construct.Struct(
    "field1" / construct.Int32ul,
    "field2" / construct.Float32l)
```
If I parse a bytestream with this, I'll have a Container instance:
```python
obj = MyStruct.parse(b'*\x00\x00\x00\xc3\xf5H@')
print(obj)
# Container:
#     field1 = 42
#     field2 = 3.140000104904175
```
I'd like to iterate through the items of this Container (that is essentially an OrderedDict), but there is this `_io` field as well:
```python
for fname, fval in obj.items():
    print(fname, fval)
# _io <_io.BytesIO object at 0x0000027FE7A92EA0>
# field1 42
# field2 3.140000104904175
```
Is there a built-in way to do this? Of course, I can always skip this field, however from a user's perspective, it would be nice to be able just to iterate as expected.
Thanks!

**Comment by waszil** [comment]
Could something like this be added to the `Container` class? This would solve it:

```python
def __iter__(self):
    for fname, fval in self.items():
        if not fname.startswith("_"):
            yield fname, fval
# or
def iter_items(self):
    ...
```
And then it would work like a charm:
```python
for fname, fval in obj:
    print(fname, fval)
# or
for fname, fval in obj.iter_items():
    print(fname, fval)
# field1 42
# field2 3.140000104904175
```

**Comment by arekbulski** [comment]
No gonna happen. This would change an existing semantic. However you can write such a filter function, and use it in your code. There is no necessity to change the library.

**Comment by waszil** [comment]
I know I can write such a filter, it just seems unintuitive for me that a defined Struct magically has an unexpected field. This `_io` field seems for me as an inner machinery, that shouldn't be visible in such cases.

**Comment by arekbulski** [comment]
I think it was added along with KSY Exporter tool, not entirely sure.
