### ISSUE TITLE
OffsettedEnd missing from latest version

### ISSUE THREAD

**Issue by waszil** [construct/construct#1008]
OffsettedEnd is not found in latest release (2.10.68), documented here:
https://construct.readthedocs.io/en/latest/api/core.html#construct.core.OffsettedEnd
https://construct.readthedocs.io/en/latest/api/streaming.html#construct.OffsettedEnd
When will it be released? Thanks!

**Comment by arekbulski** [comment]
Yeah I merged the stuff people has sent me and forgot to push it to pypi. Please give me some more time.

**Comment by glalejos** [comment]
Is there a work around to this until a fixed version is released? I could really make use of `OffsettedEnd` in one of my developments now.

**Comment by arekbulski** [comment]
Pypi is up-to-date now.
