### ISSUE TITLE
Finding stream length inside struct

### ISSUE THREAD

**Issue by demberto** [construct/construct#1009]
I have a struct whose size can be 32 or 60 bytes. I am using this construct to check stream size:
```py
...   # fields of first 32 bytes
If(len_(this) % 60 == 0, c.Bytes(28))
```
It doesn't work. I tried also `this._io` but it evaluates to `None` at runtime.

**Comment by arekbulski** [comment]
"this" is the context dictionary built by a Struct parsing class so "len(this)" is a number of keys in the context dictionary.

**Comment by demberto** [comment]
So a lambda is the only way to go?

**Comment by arekbulski** [comment]
That is not what I am saying. I merely pointed out that you were measuring number of keys in a dict and not a number of bytes in the stream. I suggest you consult the source for the steam (_io) object.
https://github.com/construct/construct/blob/master/construct/core.py#L2199-L2202

**Comment by demberto** [comment]
Ahh never mind, I have a wrapper around these structs in my code, I now use the `contextkw` to pass a boolean indicating whether the size is a multiple of 60 or not.
