### ISSUE TITLE
Support Question: Bitwise array with alignment padding at end

### ISSUE THREAD

**Issue by warriorstar-orion** [construct/construct#1010]
Hey there,

I'm very new to this sort of programming so I can't even really tell if this is a dumb question or not.

I'm working on parsing a binary format which contains:

1. A value equal to the expected length of an array that follows the value, called `palette_size`.
2. A value equal to the expected length of an array that follows the value, and each element of the array is an index into the `palette` array.
3. This second array is bit-encoded (sorry if that's not the right terminology), and the size of each element is the size of the number of bits required to represent `palette` values up to `palette_size`. So if there are 16 palettes, we need 5 bits to represent them. At the end of this array is extra padding to align the array to the nearest byte.
4. I believe these values are "flipped" so if the bit length is 2, and the first bytes in this array are `0011 1001`, I'd want the result [1, 2, 3, 0]. If the bit length is 3, and the first bytes are `0011 1001 0XXX`, I'd want the result [2, 6, 1], and to discard the remaining bits of the last byte.

Here's a concrete example with a small sample file, `shards.dmi` (in this ZIP file [shards.zip](https://github.com/construct/construct/files/10369514/shards.zip)):
```py
f = Struct(
   "signature" / Const(b"\x04DMI"),
   "dircount" / Int8ul,
   "palette_size" / Int16ul,
   "palettes" / Array(lambda this: this.palette_size, Byte[3]),
   "state_count" / Int16ul,
   #"states" / Array(lambda this: this.state_count,
       "state" / Struct(
           "dirs" / Int16ul,
           "frame_count" / Int16ul,
           "delay" / Byte[2],
           "bitflags" / Byte,
           "namelen" / Int16ul,
           "name" / Bytes(lambda this: this.namelen),
           "frames" / Array(lambda this: this.dirs * this.frame_count,
               Struct(
                   "icon_id" / Int32ul,
                   "run_count" / Int16ul,
                   "run_lengths" / Array(lambda this: this.run_count, Int8ub),
                   "colors" / Bitwise(Array(lambda this: this.run_count + this._._.palette_size.bit_length(), Nibble)),
               )
           ),
       ),
  # ),
)

In [328]: f.parse(dmi_data)
Out[328]: Container(
  signature=b'\x04DMI',
  dircount=1,
  palette_size=5,
  palettes=ListContainer([ListContainer([192, 192, 192]), ListContainer([0, 255, 0]), ListContainer([0, 255, 102]), ListContainer([0, 255, 153]), ListContainer([0, 255, 204])]),
  state_count=3,
  state=Container(
    dirs=1,
    frame_count=1,
    delay=ListContainer([1, 0]),
    bitflags=0,
    namelen=6,
    name=b'large\x00',
    frames=ListContainer([
      Container(
        icon_id=2,
        run_count=137,
        run_lengths=ListContainer([137, 1, 30, 1, 1, 1, 28, 1, 3, 1, 26, 1, 5, 1, 23, 2, 1, 1, 1, 2, 2, 1, 21, 1, 3, 5, 2, 1, 19, 1, 4, 5, 3, 1, 17, 1, 5, 2, 1, 4, 1, 1, 16, 1, 5, 3, 3, 2, 2, 1, 15, 1, 5, 3, 3, 3, 1, 1, 15, 1, 5, 1, 4, 4, 1, 1, 15, 1, 6, 2, 1, 4, 2, 1, 15, 1, 8, 5, 3, 1, 14, 1, 9, 5, 2, 1, 15, 1, 15, 1, 15, 1, 16, 1, 14, 1, 16, 1, 14, 1, 16, 1, 14, 1, 16, 1, 14, 1, 17, 1, 14, 1, 16, 1, 15, 1, 13, 2, 17, 2, 9, 2, 21, 1, 7, 1, 24, 1, 4, 2, 26, 1, 1, 2, 29, 1, 54]),
        colors=ListContainer([0, 8, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 9, 10, 10, 6, 2, 0, 9, 10, 8, 2, 6, 8, 0, 10, 10, 2, 7, 1, 0, 10, 10, 2, 7, 1, 0, 10, 10, 2, 7, 1, 0, 10, 10, 2, 7, 1, 0, 10, 10, 2, 7, 1, 0, 10, 10, 2, 2, 9, 8, 8, 10, 6, 2, 0, 0, 10, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 0, 10, 10, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7, 0, 0, 6, 13, 6, 5, 6, 4, 6, 9, 7, 5, 6, 13, 0, 0]))])))
```

This is really close to what I want, but the values in the `colors` `ListContainer` are all much higher than the number of possible palettes (`palette_size` is 5 but `colors` contains values like 8, 10, 13, etc), and the length of `colors` should be equal to `run_count`, which it's not in this case (136 vs 140).

I can _sort of_ tell that I need to use padding here but I can't seem to implement it properly. Any thoughts you might have would be greatly appreciated.

Also there is a bit of a reverse engineered spec but I can't guarantee it is 100% accurate, though it has been up to this point: https://www.byond.com/forum/post/189170#comment1077677

**Comment by arekbulski** [comment]
Its the middle of the night here. I will try to answer your question tomorrow. Stay tuned.

**Comment by arekbulski** [comment]
For a start, let me welcome you on the forum. Do not concern yourself with whether this is an easy question or not. For the most part all questions are welcome. It is true that on occasion I yelled at people when they asked things that are more than well covered in the docs. However, your issue isnt trivial, nor am I in a mood to yell at anyone.

One thing I that strikes me as unclear was your use of the phrase "length of array". There is a difference between a count of elements and a count of bytes of an array. Construct has classes for both. However, your code clearly refers to element count. So there is that.

I am not able to answer your question at this time, it is too complicated for me.

**Comment by warriorstar-orion** [comment]
Thanks for taking a look! I'll hack on it more and see what I can do. I have no doubt construct can represent this schema.
