### ISSUE TITLE
Collecting fragmented data

### ISSUE THREAD

**Issue by elyashiv** [construct/construct#1016]
Hi, great library!

I hope you can help me with the following scenario:

I have data that roughly like this:
```python
chunk = Struct(
    "len" / Int32ub,
    "hash" / Bytes(8),
    "data" / Bytes(this.len),
)

Struct(
    "cunk_count" / Int32ub,
    "chunks" / Array(this.chunk_count, chunk),
)
```

I will want access to the data in the chunks as one blob for further processing (decryption and then subtree parsing). What will be a good way to do this? Currently I added a computed field with the data concatenated, and a Reparsed field to do the decryption, but this feels hacky, and it won't work with building...

**Comment by arekbulski** [comment]
First thing: the field name is wrong. Its "cunk_count" but then its "chunk_count". This wont work.

Secondly: you are asking about a code that is nowhere to be seen here. Paste it all?

**Comment by elyashiv** [comment]
Hi, thaks for the reply!

Here is a working example:
```python
chunk = PrefixedArray(Int32ub, Byte)

def abbr_chunk(ctx):
    return bytes(sum(ctx.chunks, []))

whole = Struct(
    "chunks" / PrefixedArray(Int32ub, chunk),
    "all_chunks" / Computed(abbr_chunk),
)
```

Is there a cleaner way to get the "all_chunks" field?

**Comment by arekbulski** [comment]
Not really. You could make that a lambda instead of a separate function but I would hardly call that improvement over what you have now.
