### ISSUE TITLE
Checksums in middle of stream

### ISSUE THREAD

**Issue by RyanHope** [construct/construct#1019]
I am trying to build/parse a file where the checksum is located in the files header (or somewhere in the middle of the file). I can't figure out how to do this. I have tried modifying the Checksum example, but my attempt fails when parsing the built file because the checksum offset is within the range of bytes getting passed to the checksum function. Here is a minimal example of where I am at.

```
import os
import uuid
import fastcrc.crc32
from construct import *


_file: Struct = Struct(
    "body"
    / RawCopy(
        Struct(
            "header" / Const(uuid.uuid3(uuid.NAMESPACE_X500, "O=GitHub, Inc.").bytes),
            "padding" / Padding(8),
            "offset" / Tell,
            "checksum" / Padding(8),
            "data" / Default(Bytes(64), os.urandom(64)),
            "footer" / Const(uuid.uuid5(uuid.NAMESPACE_DNS, "github.com").bytes),
        )
    ),
    "checksum"
    / Pointer(
        this.body.value.offset, Checksum(Int32ub, fastcrc.crc32.cksum, this.body.data)
    ),
)

_f: bytes = _file.build(None)
for _b in range(0, len(_f), 16):
    print(" ".join(f"{_b:02x}" for _b in _f[_b : _b + 16]))
f: Container = _file.parse(_f)
print(f)
```

I know that I need exclude the checksum bytes from the computation but I am not sure how to go about doing that.

**Comment by arekbulski** [comment]
I cannot say. This is difficult.
