### ISSUE TITLE
Returning enums from parsing

### ISSUE THREAD

**Issue by twam** [construct/construct#1023]
I want to encode and decode Python enums with `construct`. The problem is similar to #699, but I not only want to be able to compare, but want to hide the fact that construct does the parsing.

A minimal example would be

```
import enum
import construct

class MyEnum(enum.IntEnum):
    Foo = 1
    Bar = 2

FORMAT = construct.Struct(
    "EnumValue" / construct.Enum(construct.Byte, MyEnum),
).compile()

print(type(FORMAT.parse(bytes([2])).EnumValue))
```
and I like `FORMAT.parse(bytes([2])).EnumValue` to be of type `MyEnum`.

Is there already a possibility to do something like this?

Maybe something like
```
FORMAT = construct.Struct(
    "EnumValue" / construct.Map(construct.Enum(construct.Byte, MyEnum), lambda x: MyEnum(x)),
).compile()
```
(if there would be something like `construct.Map`) could work?

**Comment by arekbulski** [comment]
The answer is both yes and no.

Yes, by a Map I think you mean an Adapter, or an ExprAdapter (they do same thing). If you can convert string labels into enum values, then there is your solution.

No, enum module is officially not supported nor recommended anymore. Enum parsing class was designed to parse into strings (and ints if necessary) but not emum.IntEnum objects. Do not use it, unless you must.
