### ISSUE TITLE
Parsing multiple content with `Switch`

### ISSUE THREAD

**Issue by soda92** [construct/construct#1024]
Hello, 

I'm working on a format like this:

```python
import construct as c
from construct import *

DATA_ID = Enum(Byte, TEMPERATURE=1, LOCATION=2)

DATA_TEMPERATURE = Struct(
    "temperature" / Float16b,
)

DATA_LOCATION = Struct(
    "longitude" / Float64b,
    "latitude" / Float64b,
    "height" / Float16b,
)

DATA = Struct(
    "seq" / Rebuild(Byte, this._._index + 1),
    "id" / DATA_ID,
    "len" / Rebuild(Byte, len_(this.data) + 8),
    "data"    / Switch(        this.id,
        {
            1: DATA_TEMPERATURE,
            2: DATA_LOCATION,
        },
    ),
)

FORMAT = Struct(
    "header" / Const(b"\xDE\xAD"),
    "length" / Rebuild(Byte, len_(this.data_seq) + 12),  # how to calculate full size
    "data_seq" / GreedyRange(DATA),
)

x = FORMAT.build(
    dict(
        data_seq=[
            dict(id=1, data=dict(temperature=11.1)),
            dict(id=2, data=dict(longitude=48.8566, latitude=2.3522, height=500)),
        ]
    )
)

print(x)
print(FORMAT.parse(x))
```
Result:
```
b'\xde\xad\x0e\x01\x01\tI\x8d\x02\x02\x0b@Hm\xa5\x11\x9c\xe0v@\x02\xd1N;\xcd5\xa8_\xd0'
Container:
    header = b'\xde\xad' (total 2)
    length = 14
    data_seq = ListContainer:
        Container:
            seq = 1
            id = (enum) TEMPERATURE 1
            len = 9
            data = None
        Container:
            seq = 73
            id = (enum) (unknown) 141
            len = 2
            data = None
        Container:
            seq = 2
            id = (enum) (unknown) 11
            len = 64
            data = None
        Container:
            seq = 72
            id = (enum) (unknown) 109
            len = 165
            data = None
        Container:
            seq = 17
            id = (enum) (unknown) 156
            len = 224
            data = None
        Container:
            seq = 118
            id = (enum) (unknown) 64
            len = 2
            data = None
        Container:
            seq = 209
            id = (enum) (unknown) 78
            len = 59
            data = None
        Container:
            seq = 205
            id = (enum) (unknown) 53
            len = 168
            data = None
```

The parsed result is not right
plus I don't know how to calculate the full size

Regards

**Comment by arekbulski** [comment]
I allowed myself to fix some stylistic issues with your code, if you dont mind. Please do not use "c." anymore.

What is wrong with it? Dunno yet. Your parsing classes dont have any obvious issues with them. I think the way you are using Rebuild-s is what causes it. Let me sleep on it for a while okay?

To calculate full size of what? FORMAT? Its len(x).

**Comment by soda92** [comment]
> I allowed myself to fix some stylistic issues with your code, if you dont mind. Please do not use "c." anymore.

That's OK. I use it because my IDE doesn't recognize these data types (pylance)

> What is wrong with it? Dunno yet. Your parsing classes dont have any obvious issues with them. I think the way you are using Rebuild-s is what causes it. Let me sleep on it for a while okay?
> 
> To calculate full size of what? FORMAT? Its len(x).

I want to include the full size  of `FORMAT` in the `length` field

> > "len" / Rebuild(Byte, len_(this.data) + 8),
> 
> Here, there is the culprit I think. Your "len_(...)" measures numer of keys in the dict and not bytes size.
> 
> Why not use the Prefix class for that instead?

```python
DATA = Struct(
    "seq" / Rebuild(Byte, this._._index + 1),
    "id" / DATA_ID,
    "len" / Rebuild(Byte, len_(this.data) + 8),
    "data"
    / Switch(
        this.id,
        {
            1: DATA_TEMPERATURE,
            2: DATA_LOCATION,
        },
    ),
)
```

sorry.. I got this wrong. the `len` field is expected to contain the size of `DATA`. I want to add the other field's size, and there might be some other fields between `len` and `data`, so I cannot use `Prefixed`

**Comment by arekbulski** [comment]
Like this?
```python
$ ipython3 
Python 3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from construct import *

In [2]: ID=Enum(Byte, A=1, B=2)

In [3]: ID.build("A")
Out[3]: b'\x01'

In [4]: ID.build("B")
Out[4]: b'\x02'
```

**Comment by soda92** [comment]
I want c-like enum-as-value syntax, but this is a minor problem. The main thing is that parsing error and how to calculate length information

**Comment by arekbulski** [comment]
Then split the format into 2 phases. Build the sequence first and then build format with a Bytes field.

**Comment by soda92** [comment]
OK, thanks.
