### ISSUE TITLE
Create a repository with commonly contructs

### ISSUE THREAD

**Issue by ErezAmihud** [construct/construct#1026]
Hi, I had an Idea
Lets create a repository that contains a lot of community supported constructs.

People who create things will create a mr

Those things may break over time but it is nicer then the alternative today which is searching and hoping someone parsed the things you want to parse :)

**Comment by arekbulski** [comment]
Already exists:
https://github.com/construct/construct/tree/master/gallery
https://github.com/construct/construct/tree/master/deprecated_gallery

Feel free to improve on anything in the deprecated gallery.

**Comment by ErezAmihud** [comment]
I saw only the deprecated one, oops
Thank you
