### ISSUE TITLE
How to get number of consumed bytes?

### ISSUE THREAD

**Issue by philpagel** [construct/construct#1028]
I am parsing a data stream from an external device that continuously sends a few different types of packages with different length.

```
package = Struct(
            "signature" / Const(b"\xab\xcd"),
            "length"    / Rebuild(Int8ub, len_(this.payload)+2),
            "payload"   / Bytes(this.length-2),
            "checksum"  / Int16ub,
            )

foo = package.parse(buf)
```

Parsing the first package works fine even if the buffer contains lots of trailing data. But, in order to parse the next package in the stream, I need to remove the bytes that have been parsed successfully from the buffer. Is there a way to find out how many bytes were consumed in parsing a Struct? Or to automatically remove the parsed bytes from the buffer? Or should I take a different approach, entirely? I know, I could nest the `package` Struct into a stream of an arbitrary number of such packages, but that would mean that I won't get any results before the entire stream has been consumed. I need to act on each package as soon as it is received (and add a timestamp) so consuming the entire stream is not an option.

Thanks in advance
  Phil

**Comment by arekbulski** [comment]
The Struct is a bit wonky. Instead of Rebuild/Bytes why not use Prefixed/GreedyBytes?

Instead of parse() use a parse_stream() in a loop?

**Comment by philpagel** [comment]
Thanks for the hints!
I now have rewritten the struct as

```
package = Struct(
            "signature" / Const(b"\xab\xcd"),
            "payload"   / Prefixed(Int8ub, GreedyBytes),
            )
```
I can parse the payload into data and checksum, later – no problem.

And I am now using:
```
while True:
    package = self.package.parse_stream(self)
```
Which seems to work, in principle, but now there is a different challenge: At the beginning of the stream, it often happens that I don't get a clean start – i.e. I need to discard a few bytes before finding the first signature. Before, I was handling that manually by dropping bytes until I hit a valid signature. So I guess I am looking for something like this now:
```
package = Struct(
            "junk"         / ArbitraryAmountOfStuffBeforeSignature,
            "signature" / Const(b"\xab\xcd"),
            "payload"   / Prefixed(Int8ub, GreedyBytes),
            )
```

**Comment by arekbulski** [comment]
I guess you need to implement ArbitraryAmountOfStuffBeforeSignature as a custom parsing class. There is no obvious way to make that happen with existing classes, I think.
