### ISSUE TITLE
Is that possible to use build as below in comment?

### ISSUE THREAD

**Issue by simplmax** [construct/construct#1043]
```python
from construct import *

msg_1 = Struct(
    'A' / Default(Int8ub, 0),
    'B' / Bitwise(Struct(
        'b0' / Default(BitsInteger(13), 0),
        Padding(3),
    ))
)

if __name__ == "__main__":
    a= msg.build(dict(B=Container(b0=1), A=1))     # expected: a = msg.build(dict(b0=1, A=1))
    print(a)
```

**Comment by arekbulski** [comment]
I don't see why not.

**Comment by simplmax** [comment]
using build as comments, the parameter b0 is not work, as image below; so my definition of msg is not allowed?
![image](https://github.com/construct/construct/assets/16898031/17b0a432-3154-429c-8b5b-afe67a160fab)

**Comment by arekbulski** [comment]
Well, my initial thought was that yeah b0 is defaultable (dont need a build value) but the Bitwise/Struct B is not defaultable. Its true that a struct can be dafaultable if all its subcons are defaultable, which is the case here, but the Bitwise is not defaultable, period. Therefore you need to include B in build value, albeit an empty dict. 

`msg.build(B=dict()) ` would be a minimum working example.
