### ISSUE TITLE
Creating constructs with ksc

### ISSUE THREAD

**Issue by sensinsane** [construct/construct#1044]
There are several issues with creating more "advanced" .ksy files and creating constructs out of them.

Not really sure if thats a KSC or construct issue.

Instances are pain. Especially if one does stuff like:

io: _root._io
pos: _io.pos

Also apparently value instances dont seem to work.

**Comment by arekbulski** [comment]
Yeah, the KSY support is sketchy at best. Basic stuff works. Many things simply cannot, because the two frameworks are not 1:1 compatible. There are things that simply do not exist in one or the other. Or if you use lambdas, there is no way to introspect those either.

**Comment by arekbulski** [comment]
I dont speek .ksy, I would be a poor teacher on how to read or write them.
