### ISSUE TITLE
Container's __repr__ with recursion_lock is not thread safe

### ISSUE THREAD

**Issue by redfern314** [construct/construct#105]
It's possible this is by design (I'm not even sure if Construct supports threading officially), but I wanted to point it out - using threads with Containers will cause weird behavior, due to the design of recursion_lock. There's a neat suggestion here for handling the issue: https://stackoverflow.com/questions/2858921/how-do-i-handle-recursive-reprs-in-python

**Comment by arekbulski** [comment]
By all information that I have, it was never thread safe. Nothing is thread safe.

**Comment by arekbulski** [comment]
FYI you can help reviewing the project. Look

**Comment by redfern314** [comment]
Great, thanks for the info @arekbulski . Not thread safe it is.

**Comment by redfern314** [comment]
+ I'll look into the sticky issues - didn't see than one up there before. Closing this issue.
