### ISSUE TITLE
[Example] ELF64 parser

### ISSUE THREAD

**Issue by aidenfoxivey** [construct/construct#1060]
(sorry if this is not appropriate to open an issue for - I couldn't think of a better way)

Hi there - I just developed an ELF64 and 32 parser using Construct in a very similar way to how the existing ELF32 parser was developed.

This one actually is compliant with both 32 and 64 bit ELF files as well as big/little endian compatibility.

Would it be desired for me to make a pull request to add it in as an example?

**Comment by arekbulski** [comment]
Yes!

**Comment by aidenfoxivey** [comment]
#1062

**Comment by aidenfoxivey** [comment]
I might actually have some additions to the ELF parser - something regarding the dynamic section.

**Comment by aidenfoxivey** [comment]
I'll close this for now and re-open if/when I have more relevant stuff to add.
