### ISSUE TITLE
BitStruct/BitField bits order

### ISSUE THREAD

**Issue by pohmelie** [construct/construct#145]
Since first time I touch awesome construct :+1: I have only one missed feature: order of bits in bit structures and fields. Some things I need to parse in the past was written with different bit order sequence, so I need to reverse every byte from sequence. Don't really know how difficult to implement or important for library this feature is. But, if there were some way to reverse bits in byte with construct, my parser code will be much simpler.

**Comment by arekbulski** [comment]
Look at ByteSwapped class, which I added btw. If you can show me a small example, I can work it out for you.

**Comment by arekbulski** [comment]
There is also Bytewise added, by me also, that lets you use byte fields inside bitwise. Please note that docs are currently stale, both site and docstrings so you really should look at the code or wait few days.

**Comment by pohmelie** [comment]
This code from real project:
``` python
LBitStruct("info",
    LNibble("animation_mode"),
    Flag("section2_exists"),
    If(lambda ctx: ctx["section2_exists"],
        LBitField("npc_stats", lambda ctx: ctx["_"]["npc_type"]["stats_length"])
    ),
    Flag("section3_exists"),
    If(lambda ctx: ctx["section3_exists"],
        Struct("npc_flags",
            Flag("champion"),
            Flag("unique"),
            Flag("super_unique"),
            Flag("minion"),
            Flag("ghostly")
        )
    ),
    Padding(2),
)
```
`LBitStruct` is defined as:
``` python
def LBitStruct(name, *subcons):
    """a struct of bitwise fields with little endian bit order
    * name - the name of the struct
    * subcons - the subcons that make up this structure
    """
    return Bitwise(Struct(name, *subcons), endian="little")
```
And so on, until `int_to_bin` (now this function have another name), where I've implemented `endian` keyword argument, which affect byte-to-bit conversion.

As you can see I need `section2_exists` to make conditional parsing of data, and definitely authors of protocol just choose some order of bits. Which is not the same as construct is :smile:

**Comment by arekbulski** [comment]
Making bitstructure little endian on byte level seems idiotic to me. I have no idea why anyone in their right mind do this. But of course we can handle it. Look at ByteSwapped, it was requested exactly to handle something like that. Its subcon must be fixed size tho. Otherwise there is no way to know which bytes to swap. Unless its the order of bits within each byte that is reversed? b00000001 -> b10000000? You can easily do that using the new Restreamed class. I will post exact code later on.

**Comment by arekbulski** [comment]
BTW `lambda ctx: ctx["_"]["npc_type"]["stats_length"]` is equivalent to `lambda ctx: ctx._.npc.stats` and even shorter `this._.npc.stats` but please note that `this` singleton has a bug where during building context is not correctly nested/embedded. So use 2nd or wait few days for 3rd to work out.

**Comment by arekbulski** [comment]
Offtopic. I think the nomenclature is totally wrong. Little endian refers specifically to reversing bytes in a larger many bytes field. Reversing bits within a byte is not endianness by definition. Its an analog.

**Comment by pohmelie** [comment]
@arekbulski this project is couple of years old, so there is no need to make it better, since nobody use it :smile: 
> Reversing bits within a byte is not endianness by definition

Of course, it was just fast dirty hack and I did not get proper name.
I got about `Restreamed`, this is what I need if I will write something similar. Thanks.

**Comment by arekbulski** [comment]
Since someone asked me to add Byteswapped, well, I will add BitsSwapped as well. Just to keep the symmetry. Can you send me your piece of code?

**Comment by pohmelie** [comment]
I don't remember what exactly I add, so here is whole [binary.py](http://pastebin.com/DBU8uHXw) file

**Comment by arekbulski** [comment]
It looks like a reinvention of the https://github.com/construct/construct/blob/master/construct/lib/binary.py . I was asking, could you show me how you used Restreamed?

**Comment by pohmelie** [comment]
Oh, I misunderstood your request. I have no code with Restreamed and actually I don't know how to use it.

**Comment by arekbulski** [comment]
I will provide you with the code, in few hours.

**Comment by arekbulski** [comment]
Just added BitsSwapped. Here is definition
```py
def BitsSwapped(subcon):
    return Restreamed(subcon,
        lambda s: bits2bytes(bytes2bits(s)[::-1]), 1,
        lambda s: bits2bytes(bytes2bits(s)[::-1]), 1,
        lambda n: n)
```
and testcases
```py
assert BitsSwapped(Bytes(2)).parse(b"\x0f\x01") == b"\xf0\x80"
assert BitsSwapped(Bytes(2)).build(b"\xf0\x80") == b"\x0f\x01"
assert Bitwise(Bytes(8)).parse(b"\xf2") == b'\x01\x01\x01\x01\x00\x00\x01\x00'
assert BitsSwapped(Bitwise(Bytes(8))).parse(b"\xf2") == b'\x00\x01\x00\x00\x01\x01\x01\x01'
assert BitStruct("a"/Nibble, "b"/Nibble).parse(b"\xf1") == Container(a=15)(b=1)
assert BitsSwapped(BitStruct("a"/Nibble, "b"/Nibble)).parse(b"\xf1") == Container(a=8)(b=15)
```

**Comment by arekbulski** [comment]
Here is the equivalent of your code:
```py
def LBitStruct(*subcons):
    return BitsSwapped(BitStruct(*subcons))
assert LBitStruct("num"/Octet).parse(b"\x01") == Container(num=0x80)
```

**Comment by arekbulski** [comment]
Here is equivalent of your code, @pohmelie 
```py
def LBitStruct(*subcons):
    return BitsSwapped(BitStruct(*subcons))

assert LBitStruct("num"/Octet).parse(b"\x01") == Container(num=0x80)
```

**Comment by pohmelie** [comment]
@arekbulski, got it! Thanks :+1:
