### ISSUE TITLE
Container: wrong print order

### ISSUE THREAD

**Issue by dcochlin** [construct/construct#16]
The order of the structure definition is not preserved when printing. Here is an example...

from construct import *

d = Struct("foo",
           UBInt8("a"),
           SLInt16("b"),
           LFloat32("c"),
           )

final = d.parse("\x07\x00\x01\x00\x00\x00\x01")

print final

Results in...
Container:
    a = 7
    c = 2.350988701644575e-38
    b = 256

**Comment by arekbulski** [comment]
Bug is back.

**Comment by arekbulski** [comment]
Added regression tests. Still need a fix tho.
https://github.com/construct/construct/commits/fix-container-iter

**Comment by arekbulski** [comment]
Merged into Issue 82.
