### ISSUE TITLE
EmbededBitsStruct is not usable?

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#171]
I don't know whether it is a bug. but it really confuses me 
- OS: Ubuntu14.04
- Construct: 2.8.2
- Python: 3.4
 
The below code is my test. 
```
from construct import *
attributes = Struct(
    "attr" / Array(3, BitStruct(
        "attrCode" / BitsInteger(16),
        "attrValue" / Switch(this.attrCode, {
            34: BitsInteger(8),
            205: BitsInteger(2),
            512: BitsInteger(2)
        })
    ))
)

blob = b"\x00\x22\x82\x00\xCD\x80\x80\x09"
print(attributes.parse(blob))
```
I expect a result like this
```
Container :
    attributes : ListContainer
        Container:
            attrCode : 34
            attrValue : 130
        Container:
            attrCode : 205
            attrValue : 2
        Container:
            attrCode : 512
            attrValue : 1
```
But code execution result is 
```
ValueError: closing stream but 6 unread bytes remain, 1 in decoded unit
```

It raises error when Construct parses stream to **\x00\xCD\x80** 
**\x00\xCD** is my attrCode and the construct is  **attrCode / BitsInteger(16)**
then Construct parses **\x80** and the construct is **205: BitsInteger(2)**
Until this, everything it's ok!
Then construct stream2.close() , raise ValueError
But**\x80** back six bit  should parse in next array item.

Then I change my BitStruct to EmberBitStruct
It raise the same error too

Is it a bug? if not, could you tell how to write the struct to parse my blob

Thanks!
Your timely reply would be appreciated

**Comment by arekbulski** [comment]
Just woken up. Expect a reply in a bit.

**Comment by arekbulski** [comment]
No, your code is wrong. `BitStruct(...) = Bitwise(Struct(...))` and Bitwise requires that whatever is inside it consumes or produces a multiple of 8 bits. The inner anonymous BitStruct in  `"attr" / Array(3, BitStruct(` either reads 3 bytes or 2 bytes  bits (which is an error). You can go about it two ways, depends on the data format:

Use `205: Padded(8, BitsInteger(2))` which will discard the remaining 6 bits on `each` of 3 instances.

Use `EmbeddedBitStruct` only on most outter one and `Struct` on other. Then add `GreedyBytes` at the very end to consume whatever was left in the stream.

**Comment by arekbulski** [comment]
Testing your code, need a moment.

**Comment by arekbulski** [comment]
Here is what you wanted:
```py
attributes = BitStruct(
    "attr" / Aligned(Array(3, Struct(
        "attrCode" / BitsInteger(16),
        "attrValue" / Switch(this.attrCode, {
            34: BitsInteger(8),
            205: BitsInteger(2),
            512: BitsInteger(2)
        }),
    )), modulus=8),
)
blob = b"\x00\x22\x82\x00\xCD\x80\x80\x09"
print(attributes.parse(blob))
```

**Comment by arekbulski** [comment]
Well, the result is slightly different. Tell me, which is wrong? BTW next time please include a repr not a str of the expected result because then I dont have to retype it into the test suite.
```py
assert attributes.parse(blob) == Container(attr=[
    Container(attrCode=34,attrValue=130),
    Container(attrCode=205,attrValue=2),
    Container(attrCode=512,attrValue=1), ])
```

**Comment by OhBonsai** [comment]
@arekbulski 
    I'am sorry to have bothered you, and thanks for your patient explanation.
   ```
attributes = BitStruct(
    "attr" / Aligned(Array(3, Struct(
        "attrCode" / BitsInteger(16),
        "attrValue" / Switch(this.attrCode, {
            34: BitsInteger(8),
            205: BitsInteger(2),
            512: BitsInteger(2)
        }),
    )), modulus=8),
)

blob = b"\x00\x22\x82\x00\xCD\x80\x80\x10"

assert attributes.parse(blob) == Container(attr=[
    Container(attrCode=34, attrValue=130),
    Container(attrCode=205, attrValue=2),
    Container(attrCode=512, attrValue=1)])
   ```



    Actually, It's my first time to commit a issue. 
    I apologize for the wrong format issue ●﹏●
    Thanks again arekbulski  ლ(╹◡╹ლ )

**Comment by arekbulski** [comment]
Oh you are welcome, Bonsai. Actually you helped me improve the code.

If you want to be of help, then try to attach expected repr next time. :wink:

**Comment by arekbulski** [comment]
Oh, in case you are using HEAD. Aligned just changed syntax so it is now `Aligned(8, ...)` not `Aligned(..., modulus=8)`.
