### ISSUE TITLE
Where is ipstack now?

### ISSUE THREAD

**Issue by hunnble** [construct/construct#174]
In the old version I wrote:
`from construct.protocols.ipstack import ip_stack`
I found that some changes were commited a day ago,and I cannot find protocols any more,where is ipstack now?
Thanks.

**Comment by harvimt** [comment]
There's an issue filled, it needs to be rewritten for this version of
construct.

**Comment by arekbulski** [comment]
Here is the code:
https://github.com/construct/construct/blob/master/construct/examples/protocols/ipstack.py
Here is the tutorial:
http://construct.readthedocs.io/en/latest/transition.html

If you can help with fixing ipstack to 2.8 code, please please submit a pull request. Even if it partially works.

**Comment by arekbulski** [comment]
Ah forgot to mention I am talking about HEAD. Last release seems to be stale. Oops.

**Comment by arekbulski** [comment]
Should also mention that there seems to be no GreedyRange construct in ipstack, only single frames can be processed.

**Comment by arekbulski** [comment]
@hunnble  @harvimt  Would either of you be willing to help with bringing ipstack to date?

**Comment by arekbulski** [comment]
Update: ipstack is pretty close to being fixed. DNS and DHCP are possibly broken but its hard to tell. Any fixes are welcome.

**Comment by arekbulski** [comment]
You should know that ipstack uses newly introduced Rebuild wrapper that updates the count fields from the related field in obj dict during building. You do NOT have to provide a value for `question_count` etc, it can be missing or wrong.
```py
"question_count" / Rebuild(Int16ub, len_(this.questions)),
"questions" / Array(this.question_count, query_record),
```
