### ISSUE TITLE
How to Computed with a Function?

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#175]
I have a Strange demand like below code
```
def comp(num_array):
    sum_value = 0
    for i in range(0, len(num_array)):
        sum_value += num_array[i] << ((len(num_array)-1-i)*8)
    return sum_value

test = Struct(
    "numArray" / RepeatUntil(lambda x, ctx: x < 128, Byte),
    "value" / Computed(comp(this.numArray))
)

blob = b'\x87\0f'
result = test.parse(blob).value
expect_result = 34575
assert result == expect_result

```
**TypeError: 'Path' object is not iterable**  raised when run it .

It's seem like in function **comp** , the param value isn't the **numArray** but the path type.
So , the question come..
.How can i computed with a function or some else way to solve it.

**Comment by arekbulski** [comment]
Docstring example:
https://github.com/construct/construct/blob/master/construct/core.py#L1819
Website documentation:
http://construct.readthedocs.io/en/latest/misc.html#computed

**Comment by arekbulski** [comment]
Just updated both.

**Comment by OhBonsai** [comment]
So... Does this mean that I can't use computed like what I code.. :sob: 
Maybe I need store the numArray in Global env..
But still thank you arekbulski

**Comment by arekbulski** [comment]
Oh slow down, Bonsai. You posted a general question so I provided a general help. Once you posted some code, you should post a notification.

**Comment by arekbulski** [comment]
`Computed(comp(this.numArray))` is wrong because Computed takes a lambda and comp() does not return a lambda. Fix is simple.
```py
def test_from_issue_175(self):
    def comp(num_array):
        return sum(x << ((len(num_array)-1-i)*8) for i,x in enumerate(num_array))

    test = Struct(
        "numArray" / RepeatUntil(lambda x, ctx: x < 128, Byte),
        "value" / Computed(lambda ctx: comp(ctx.numArray))
    )

    assert test.parse(b'\x87\0f').value == 34575
```
Perhaps the expected value is wrong?

**Comment by arekbulski** [comment]
Please tell me Bonsai if the code is wrong or the output.

**Comment by OhBonsai** [comment]
Oh... now is 00:13 in China...
Thanks for your Patiently answer.

You are right~   
The blob miss a **\x**
It should change to **b'\x87\x0f'**
```
def test_from_issue_175(self):
    def comp(num_array):
        return sum(x << ((len(num_array)-1-i)*8) for i,x in enumerate(num_array))

    test = Struct(
        "numArray" / RepeatUntil(lambda x, ctx: x < 128, Byte),
        "value" / Computed(lambda ctx: comp(ctx.numArray))
    )

    assert test.parse(b'\x87\x0f').value == 34575
```

You help me a lot !!   
 I sincerely  appreciate for the charming and amazing **construct**  :+1: :+1:

**Comment by arekbulski** [comment]
You accidentally found out that putting this.x into a function does not return a lambda. I made a new feature request so that you can use `len(this.items)` instead of `lambda ctx: len(ctx.items)`. Look at #198 .

**Comment by arekbulski** [comment]
Another update: there is `obj_` analog to `this` so you can write code below. Look at #206 .
```py
@PathFunc
def comp_(num_array):
    return sum(x << ((len(num_array)-1-i)*8) for i,x in enumerate(num_array))

test = Struct(
    "numArray" / RepeatUntil(obj_ < 128, Byte),
    "value" / Computed(comp_(this.numArray))
)
```
