### ISSUE TITLE
RepeatUntil add a stop number

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#199]
A feature request.
In Doc, RepeatUnitl means An array that repeats until the predicate indicates it to stop. 
But sometimes, The blob need  stop when array length greater than one number~ 
Eg:
```
blob = b"\xf0\xf1\x05"
var_uint16 = RepeatUntil(lambda x, ctx: x < 128, Int8ub)
assert var_uint16.parse(blob) == ListContainer([240, 241, 5])
```
But the result I want is ```ListContainer([240, 241])```

**Comment by arekbulski** [comment]
For clarity, RepeatUnil is not an Array/Range. But I understand what you mean. Do you want the 5 element to be consumed? And how should it build?

**Comment by arekbulski** [comment]
How about a DropLast adapter?

**Comment by OhBonsai** [comment]
Good  idea~~
You are right! arekbulski
Construct is a reversible function. We can't destroy the amazing reversibility~

**Comment by arekbulski** [comment]
```py
>>> def DropLast(subcon):
...     return ExprAdapter(subcon, None, decoder=lambda obj,ctx: obj[:-1])
... 
>>> d = DropLast(RepeatUntil(lambda x,ctx: x<128, Byte))
>>> d.parse(b"\xf0\xf1\x05")
[240, 241]
```

**Comment by arekbulski** [comment]
It would be okay to introduce a new wrapper that by design breaks reversiblity but it should be justified and documented explicitly.
