### ISSUE TITLE
construct-2.8.4: Build errors with Python 3.4 and 3.5

### ISSUE THREAD

**Issue by tgurr** [construct/construct#204]
I'm running into the following build errors when trying to build construct with Python 3.4 and/or 3.5:
```
*** Error compiling '/var/tmp/paludis/build/dev-python-construct-2.8.4/image//usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/construct/examples/protocols/application/dns.py'...
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/dns.py", line 124
SyntaxError: cannot mix bytes and nonbytes literals

*** Error compiling '/var/tmp/paludis/build/dev-python-construct-2.8.4/image//usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/construct/examples/protocols/layer3/dhcpv4.py'...
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/dhcpv4.py", line 176
SyntaxError: cannot mix bytes and nonbytes literals

*** Error compiling '/var/tmp/paludis/build/dev-python-construct-2.8.4/image//usr/x86_64-pc-linux-gnu/lib/python3.5/site-packages/construct/examples/protocols/layer3/icmpv4.py'...
  File "/usr/x86_64-pc-linux-gnu/lib/python3.5/icmpv4.py", line 79
SyntaxError: cannot mix bytes and nonbytes literals
```

**Comment by arekbulski** [comment]
It's probably b strings and u strings being added together. Need to see the code. Also use HEAD and note that ipstack is kind of broken.

**Comment by arekbulski** [comment]
Also it seems you use ancient ipstack code with newest library, which is wrong since 2.8 changed everything.

**Comment by arekbulski** [comment]
It's probably b strings and u strings being added together. Need to see the code. Also use HEAD and note that ipstack is kind of broken.  Also it seems you use ancient ipstack code with newest library, which is wrong since 2.8 changed everything.

**Comment by arekbulski** [comment]
Release 2.8.5 just pushed out on githhub and pypi, in case you were not using HEAD. Try it again and show me the actual code.

**Comment by arekbulski** [comment]
You should know that ipstack uses newly introduced Rebuild wrapper that updates the count fields from the related field in obj dict during building. You do NOT have to provide a value for `question_count` etc, it can be missing or wrong.
```py
"question_count" / Rebuild(Int16ub, len_(this.questions)),
"questions" / Array(this.question_count, query_record),
```

**Comment by tgurr** [comment]
2.8.5 builds fine for Python 2.7 and also 3.3, 3.4 and 3.5 for me so I suppose the problem I had was fixed and this bug can be closed. Thanks!
