### ISSUE TITLE
SeqOfOne for 2.8

### ISSUE THREAD

**Issue by matwey** [construct/construct#211]
Hello,

What is the replacement for SeqOfOne for construct 2.8? It is not highlighted in Transition docs.

**Comment by arekbulski** [comment]
It was removed, I will update the docs. Do you need it? I would need a particular example of what you would need it for.

**Comment by matwey** [comment]
Hello,

I use it here https://github.com/matwey/pybeam/blob/master/pybeam/eetf_construct.py#L239
Now I am working on migration the project to construct 2.8

**Comment by arekbulski** [comment]
Can you remind me what the semantics were exactly? How it worked?

**Comment by matwey** [comment]
As far as I remember:

    external_term = SeqOfOne("external_term",erl_version_magic,term)

should skip ```erl_version_magic``` (but parse) and return only parsed ```term```

**Comment by arekbulski** [comment]
So it parses both but returns only the second?

**Comment by matwey** [comment]
Yes.

**Comment by arekbulski** [comment]
Does it build both? And do you provide only the second value when building?

**Comment by matwey** [comment]
The first term is a magic constant term. So I'll have to provide only the second value to build the whole stuff.

**Comment by arekbulski** [comment]
That is all I needed to know, will add a class later today. Just on a side note, there is no Magic anymore, Const takes a bytes value easily.

**Comment by matwey** [comment]
As far as I can see from 2.5 source, SeqOfOne is basically IndexingAdapter

**Comment by arekbulski** [comment]
No, Indexing is similar to range not sequence.

**Comment by arekbulski** [comment]
Focused class was added in HEAD. Do you need a release?

**Comment by matwey** [comment]
Thank you, I am fine with master.
