### ISSUE TITLE
LazyBound docs are outdated for 2.8

### ISSUE THREAD

**Issue by matwey** [construct/construct#212]
Hello, LazyBound docs here http://construct.readthedocs.io/en/latest/lazy.html#lazybound
seems to be related to 2.5 branch.

**Comment by arekbulski** [comment]
Yeah, the `**` is used in the docs to mark stale. It is marked stale. But I will fix it. Was a particular thing that you needed help with?

**Comment by matwey** [comment]
AFAIU

```
LazyBound("name", lambda : term)
```

should be just replaced with

```
LazyBound(lambda ctx: term)
```

**Comment by arekbulski** [comment]
Seriously? You are aware that you are speaking with the guy that made this thing in the first place? :smile:

**Comment by matwey** [comment]
That is why I am asking :)

**Comment by arekbulski** [comment]
I am busy with several features. Please update the entire section and send a pull request?

**Comment by arekbulski** [comment]
Just wondering,  are you willing to work a bit on Construct? If so, we can find few easier things to get you into it. You can always make a Pull Request.

**Comment by arekbulski** [comment]
Docs updated in dd73c84
http://construct.readthedocs.io/en/latest/lazy.html
