### ISSUE TITLE
TunnelAdapter in 2.8

### ISSUE THREAD

**Issue by matwey** [construct/construct#215]
Hello,

I am sorry to ask again. In 2.5 I was able to do the following:

        TunnelAdapter(
            PascalString("data", encoding = "zlib"),
            GreedyRange(UBInt16("elements"))
        )

in order to first unpack some bytes, and then parse unpacked bytes according to the grammar.
There is no TunnelAddapter in 2.8, what is the recommended replacement?

**Comment by arekbulski** [comment]
Look at Tunnel and more specifically Compressed. And do NOT use string classes to handle bytes lol. Can't craft a code right now.

**Comment by arekbulski** [comment]
Oh and Prefixed

**Comment by arekbulski** [comment]
You are probably looking for a well tested construction `Prefixed(VarInt, Compressed(GreedyBytes))`. You should use Bytes and GreedyBytes when working with raw byte strings, not string classes. They work but it look kind of wrong.

**Comment by matwey** [comment]
Yes, thank you.

**Comment by arekbulski** [comment]
I guess partly to blame is the docs site, the tunneling chapter is not written yet. Here are the examples from just pushed docstrting. Hope this sheds some light on what Compressed can do.
```py
Compressed(GreedyBytes, "zlib")

Prefixed(VarInt, Compressed(GreedyBytes, "zlib"))
Struct("inner"/above)

Compressed(Struct(...), "zlib")
```

**Comment by matwey** [comment]
By the way, do you know the workaround for python 3.3?

```
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/construct/core.py", line 185, in parse_stream

    return self._parse(stream, context)

  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/construct/core.py", line 348, in _parse

    data = self._decode(data, context)

  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/construct/core.py", line 2175, in _decode

    return codecs.decode(data, self.encoding)

LookupError: unknown encoding: zlib
```

**Comment by arekbulski** [comment]
The test suite skips this on 3.2 and 3.3 because these python versions simply do not have the zlib encoding in the codecs module. It looke like there is a zlib module tho.
https://docs.python.org/3.3/library/zlib.html#zlib.compress
https://docs.python.org/3.3/library/zlib.html#zlib.compress

**Comment by arekbulski** [comment]
Well, I could extend the Compressed class so it uses both codecs and zlib modules, or it uses a user provided lambda to compress and decompress. I will add it today. Request #218

**Comment by matwey** [comment]
Hm, AFAIU it is called ```zlib_codec``` on python 3.3.

**Comment by arekbulski** [comment]
Just added the `zlib gzip bzip2 lzma` modules in addition to codecs module. Use HEAD before it gets released.
