### ISSUE TITLE
Need more people to work with

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#223]
I could use some hands on deck with upgrading the project. Here are few things that you can surely help with. If you post below to offer some involvment, then I can guide you.
- [ ] translating formats and protocols to 2.8
- [ ] upgrading test suite

Pull requests are preferred over paste-ins.

**Comment by hyOzd** [comment]
I'm just starting to use this awesome library. I want to thank you for your work. It really makes things easy.

I'm playing with `Enum`s and I was wondering if there is a better way of reporting errors other than:

    MappingError: no decoding mapping for 2

It would more helpful if exception at least included the field name.

I was thinking if something like a wrapper is possible for custom error messages, for example:

    Struct('SOF' / Const(b'\x7e'),
           'size' / Int8ul, Error(Check(this.size > 1), "Invalid size."),
           'type' / Error(Enum(Byte, x=1, y=2), "Invalid frame type.")

**Comment by arekbulski** [comment]
@hyOzd  Could you move it to a new issue? I will reply there.

**Comment by arekbulski** [comment]
Exceptions do not provide a name because naming is done by a non-mutating wrapper so the name almost never not in the instance that raised it. And Error is a singleton that raises ExplicitError whenever processed. So either we give it a new name or rename Error to Raise maybe?

**Comment by domenzain** [comment]
I would like to get involved with the last two.

**Comment by arekbulski** [comment]
Welcome onboard! :smiley: There were quite few people so far that offered pieces of code but you are the first to offer regular maintanence. Either is, of course, welcomed.

**Comment by domenzain** [comment]
Yes.

I can get started with that without much guidance, too. I've recently transitioned a non-trivial code-base to `2.8`.

Have you heard of `doctest`? That could also help keep the examples in documentation current with every commit.

**Comment by arekbulski** [comment]
I know what doctest is, but I had some doubts if it will be of any use.
Would you like to bring the docs up to test site standard?

4 gru 2016 10:49 AM "domenzain" <notifications@github.com> napisał(a):

**Comment by domenzain** [comment]
Well, it would force developments to keep the documentation up to date with the code.

After updating the examples this would be a good goal.

**Comment by arekbulski** [comment]
I think all examples are up to date. When I redesign some class I update the docstrings and docs site at same time... at least I try to.
