### ISSUE TITLE
Porting to Micropython

### ISSUE THREAD

**Issue by dmazzella** [construct/construct#224]
Hi folks, 
any interest to port to [Micropython](http://www.micropython.org/)?

**Comment by arekbulski** [comment]
If you request it, why not. Can you run this on Travis CI?

**Comment by dmazzella** [comment]
Yes, it  run on Trevis CI

**Comment by arekbulski** [comment]
I know that Micro is tested on Travis. Can you make Travis run Construct test using Micro?

**Comment by dmazzella** [comment]
I'm new to Construct, frankly I found it yesterday trying libraries that can help in the development of a driver for [RF-SPBTLE ](http://www.st.com/content/st_com/en/products/wireless-connectivity/bluetooth-bluetooth-low-energy/spbtle-rf.html)on Micropython.

I can start doing some testing as soon as possible

**Comment by arekbulski** [comment]
Posted the question on https://github.com/micropython/micropython/issues/2469.

**Comment by arekbulski** [comment]
Oh dude, you write drivers for real hardware? Now that is something. Of course I will support your effort. If some piece of the library must be changed because Micro supports a subset of Python specs, I can do that. But I need a way to run the pytest (or at least nosetest?) on Micro on Travis.

**Comment by dmazzella** [comment]
Construct and Micropython are a perfect combination for work with the hardware.
I hope to soon see a porting, could facilitate the work of micropython.

**Comment by arekbulski** [comment]
Found how to build it on Ubuntu. Maybe there is an apt-get package?
https://github.com/micropython/micropython/wiki/Getting-Started

**Comment by arekbulski** [comment]
Asked for Travis to preinstall Micropython for us:
https://github.com/travis-ci/travis-ci/issues/6666

**Comment by arekbulski** [comment]
Test runner can be called with ipython but fails with pypy and micro. Importing pytest fails.
```py
$ ../micropython/unix/micropython tests/manual_pytest.py 
Traceback (most recent call last):
  File "tests/manual_pytest.py", line 3, in <module>
ImportError: no module named 'pytest'
```

**Comment by arekbulski** [comment]
I had problems installing pytest on pypy as well. Solved on AskUbuntu.
http://askubuntu.com/questions/834466/installing-pytest-for-pypy

**Comment by arekbulski** [comment]
Thread was abandoned. If anyone is able to bring pytest into Micro runtime, please reopen.
