### ISSUE TITLE
add Encrypted Authenticated classes

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#225]
Should use some cryptographic library so user just has to supply a string like "aes" or "ctr" mode for convenience. Could take crypto primitives from:
https://pypi.python.org/pypi/pycryptodome

**Comment by beardypig** [comment]
This would be very cool. I am planning on writing and ASN.1 parser for X509 certs and the like, so I may have something to contribute towards this :)

**Comment by arekbulski** [comment]
pycryptodome looke very nice, look at the example recipies
https://pycryptodome.readthedocs.io/en/latest/src/examples.html

**Comment by arekbulski** [comment]
Since assigning (or recovering) keys and nonces would be instance methods on the AE subconstruct, there becomes a problem when AE itself is nested declaratively. Then we gonna need some way to "extract" the AE from Struct members. I suggest adding `getmember` method.
```py
st = Struct("inner" / Strut("inner2" / Struct("encrypted" / AuthenticatedEncrypted(int32))))
st.getmember("inner.inner2.encrypted").keys = bytes 
# ^ or assign None to generate random and then get those keys 
st.build(dict(...))
```

**Comment by arekbulski** [comment]
Idea is fine but I wont find time and energy to work on this, especially that this is not a general purpose class but a very specialized one, wont be used by many people. If someone writes it up to standard I will include it tho.
