### ISSUE TITLE
add a way to define custom error messages in place

### ISSUE THREAD

**Issue by hyOzd** [construct/construct#235]
I'm playing with `Enum`s and I was wondering if there is a better way of reporting errors other than:

    MappingError: no decoding mapping for 2

It would more helpful if exception at least included the field name.

I was thinking if something like a wrapper is possible for custom error messages, for example:

    Struct('SOF' / Const(b'\x7e'),
           'size' / Int8ul, Error(Check(this.size > 1), "Invalid size."),
           'type' / Error(Enum(Byte, x=1, y=2), "Invalid frame type.")

----

And in response to @arekbulski 's comment:

I didn't know `Error` already existed. I couldn't find it in the documentation. Can you give an example of it?

Now looking at the example code I added above, I'm not happy with how it looks. `Error` looks too much in the face. And since it merely defines the 'error message', maybe it should be named `ErrorMessage`. Can we have something like this instead of my first proposal:

    Struct('SOF' / Const(b'\x7e'),
           'size' / Int8ul, Check(this.size > 1) + ErrorMessage("Invalid size."),
           'type' / Enum(Byte, x=1, y=2) + ErrorMessage("Invalid frame type."))

I've repurposed the `+` operator but to be honest I haven't thought about it much. Maybe there are better options.

**Comment by arekbulski** [comment]
Exceptions do not provide a name because naming is done by a non-mutating wrapper so the name almost never not in the instance that raised it. And Error is a singleton that raises ExplicitError whenever processed. So either we give it a new name or rename Error to Raise maybe? Another way to go about it would be to name your field `frametype` and then only add printing the names of all instances on the way to the raising line of code. This would be the most useful feature for the users.

**Comment by arekbulski** [comment]
This is the first time that anybody suggrested a new operator other than Tomer's  / >> [ ] . I would like the + operator to be used for something, but this one we gonna solve differently. I am gonna make exceptions print a path (chain of names) that led to raising. If you rename your field "frametype" it will just do what you wanted without any additional code.

**Comment by hyOzd** [comment]
I agree that '+' operator is too valuable for this usecase : )

Printing the path sound good enough for me. Can you add the 'path' as a list in the exception? That would make it easier to check which field caused the problem.

**Comment by arekbulski** [comment]
Yeah, I am already on it.

**Comment by arekbulski** [comment]
Added as requested.

**Comment by arekbulski** [comment]
I shall add + operator that makes Struct - s.

**Comment by hyOzd** [comment]
@arekbulski  thanks for implementing this. It's already being very helpful to me : )

**Comment by arekbulski** [comment]
Your welcome. And you dont need to at me, dude. :smiley:
