### ISSUE TITLE
creating Default subconstruct

### ISSUE THREAD

**Issue by yuzvir** [construct/construct#241]
I want to make a Default Subconstruct, that could build data from a passed value or use a default value, It should work like this:
```python
>>> Struct("a"/Default(Byte, 0), "b"/Default(Byte, 1)).build(dict(a=1, c=2))
'\x01\x01'
```
So, I used a Const class as a base class
```python
class Default(Const):
    def _parse(self, stream, context, path=None):
        return self.subcon._parse(stream, context, path=path)
    def _build(self, obj, stream, context, path=None):
        value = self.value if obj is None else obj
        return self.subcon._build(value, stream, context, path=path)
```
But, I've found that problem is little deeper - `obj` is always `None` beacause of  `self.flagbuildnone == True`. So when `Struct._build` is called I recieve a `None` as `obj` according to this piece of code:
```python
            if sc.flagembedded:
                subobj = obj
            elif sc.flagbuildnone:
                subobj = None
            else:
                subobj = obj[sc.name]
```
and I can't just set `self.flagbuildnone` to `False` because in this case accessing `obj[sc.name]` will raise an exception. Is there any other way to do this?

**Comment by arekbulski** [comment]
Select is what you were looking for but the Struct build semantics had to be changed so `flagbuildnone` is not respected anymore and the value is provided from when it exists.
```py
class Struct2(Struct):
    def _build(self, obj, stream, context, path):
        context = Container(_ = context)
        context.update(obj)
        for i,sc in enumerate(self.subcons):
            if sc.flagembedded:
                subobj = obj
            else:
                subobj = obj.get(sc.name, None)
            buildret = sc._build(subobj, stream, context, path)
            if buildret is not None:
                if sc.flagembedded:
                    context.update(buildret)
                if sc.name is not None:
                    context[sc.name] = buildret
        return context


def Default(subcon, value):
    return Select(subcon, Const(subcon, value))

assert Struct2("a"/Default(Byte,0), "b"/Default(Byte,0)).build(dict(a=1)) == b"\x01\x00"
```
Now I am thinking, maybe I should change the main Struct semantics...

**Comment by yuzvir** [comment]
Thank you, It would be nice to see this update.

**Comment by arekbulski** [comment]
Here you go, you need to update to HEAD or wait for a release.
```py
def Default(subcon, value):
    return Select(subcon, Const(subcon, value))

assert Struct("a"/Default(Byte,0), "b"/Default(Byte,0)).build(dict(a=1)) == b"\x01\x00"
```

**Comment by arekbulski** [comment]
I decided to add Default to the library.

**Comment by arekbulski** [comment]
Default is now part of the library.

**Comment by yuzvir** [comment]
Thanks a lot, but using Select is not an option for me, because it hasn't `_sizeof()` method. Anyway I still able to use Default class inherited from Const.

**Comment by arekbulski** [comment]
Oh I see where the problem is, I will update `Default` to meet your need.

**Comment by arekbulski** [comment]
Update requested and delivered, all in 16 minutes. :smile:

**Comment by yuzvir** [comment]
Could you also add `_parse` method?
```    def _parse(self, stream, context, path):
        v = self.subcon._parse(stream, context, path)
        if v is not None:
            return v
        else:
            return self.value
```
I think it would be useful in case if you decide to support structures for different protocol versions, and some fields are exist in one version, but not in other. I know I could use `"field1" / Pass` and check if it is not `None` in my main code, but it would be easier if I could just use `"filed1" / Default(Pass, 0)` and parse it like if it existed.

**Comment by arekbulski** [comment]
What would be the use case for a Default _parse? Pass does literally nothing.
