### ISSUE TITLE
Can Array get current index?

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#244]
Hi,
I am trying to understand if I can get current index in Array.
```
blob = b'\x12\x8f\xf9'
double_array_structure = Struct(
    'firstArr' / Array(3, Byte),
    'firstArrIter' / Computed(lambda ctx: iter(ctx.firstArr)),
    'secondArr' / Array(3, Computed(lambda ctx: next(ctx.firstArrIter) - 1))
)
result = double_array_structure.parse(blob)
del(result['firstArrIter'])
assert result == Container(
    firstArr=ListContainer([18, 143, 249]),
    secondArr=ListContainer([17, 142, 248])
)
```
As shown in code above. Basically I have two arrays, and the second array have a reference match item-for-item with the first array. I don't need to create a temp Iter if I can get the index in Array.
Have I make myself clear? Put in plain language...
```
def _parse(self, stream, context):
        count = self.count(context) if callable(self.count) else self.count
        try:
            obj = ListContainer()
            for i in range(count):
                obj.append(self.subcon._parse(stream, context)) # can I get *ｉ* in Array Struct
            return obj
        except ConstructError:
            raise ArrayError("expected %d, found %d" % (count, len(obj)))
```
Does construct have something which is a better fit for this task?

Thanks

**Comment by arekbulski** [comment]
I did not figure out how to achieve this using existing lego, but you can always create your own adapters, in particula using ExprAdapter. Code below works on ranges of structs, arrays are ranges in particular, and assumes it is a list of Containers.
```py
class AddIndexes(Adapter):
    def __init__(self, subcon):
        super(AddIndexes, self).__init__(subcon)
    def _decode(self, obj, context):
        for i,con in enumerate(obj):
            con.index = i
        return obj

assert AddIndexes(Struct("num"/Byte)[4]).parse(b"abcd") == [Container(num=97)(index=0),
Container(num=98)(index=1),Container(num=99)(index=2),Container(num=100)(index=3),]
```

**Comment by arekbulski** [comment]
I did not figure out how to achieve this using existing lego, but you can always create your own adapters, in particula using ExprAdapter. Code below works on ranges of structs, arrays are ranges in particular, and assumes it is a list of Containers.
```py
class AddIndexes(Adapter):
    def __init__(self, subcon):
        super(AddIndexes, self).__init__(subcon)
    def _decode(self, obj, context):
        for i,con in enumerate(obj):
            con.index = i
        return obj

assert AddIndexes(Struct("num"/Byte)[4]).parse(b"abcd") == [Container(num=97)(index=0),
Container(num=98)(index=1),Container(num=99)(index=2),Container(num=100)(index=3),]
```

**Comment by OhBonsai** [comment]
Thanks~  arekbulski ~~~(^_^)
Your give me a elegant way to fix it

**Comment by arekbulski** [comment]
Index class was added 
https://construct.readthedocs.io/en/latest/api/misc.html#construct.Index
