### ISSUE TITLE
Parsing MPEG-4 Part 12 

### ISSUE THREAD

**Issue by beardypig** [construct/construct#247]
I am trying to write a parser for MPEG-4 Part 12. 

The files are made of a Sequence of Boxes (aka Atoms), which have common fields `size` and `type`, each different `type` has a number of different fields. 

Some types of Boxes can be made up of a Sequence of boxes. 

I have the following so far,

``` python
BoxBase = Struct("size" / Int32ub,
                 "type" / String(4, padchar=b" ", paddir="right"),
                 If(this.size == 1, "largesize" / Int64ub),
                 If(this.type == "uuid", "usertype" / Array(8, Byte))
                 )

RawBox = Struct("data" / Array(lambda ctx: (ctx._.size - 8), Byte))

FileTypeBox = Struct("major_brand" / String(4),
                     "minor_version" / String(4),
                     "compatible_brands" / Array(lambda ctx: (ctx._.size - 16) / 4, String(4))
                     )

FreeBox = Struct("data" / Array(lambda ctx: ctx._.size - 8, Byte))

ContainerBox = Struct("boxes" / GreedyRange(RawBox))

Box = BoxBase + Switch(this.type, {
                           "ftyp": FileTypeBox,
                           "free": FreeBox,
                           "moov": ContainerBox
                       }, default=RawBox)

MP4 = GreedyRange(Box)
```

But when I parse an MP4 I get an output 

```
ListContainer:
    Container:
        size = 28
        type = ftyp
    Container:
        size = 69
        type = free
```

I was hoping that the fields in the Switch would be added to the Box Construct, what am I doing wrong? 

Thanks!

**Comment by beardypig** [comment]
Using a combination of `Peek` and `Embedded` I have manged to get the result that I wanted for parsing a Box.

```python
RawBox = Struct("type" / String(4, padchar=b" ", paddir="right"),
                "data" / Array(lambda ctx: (ctx._.size - 8), Byte))

FileTypeBox = Struct("type" / Const(b"ftyp"),
                     "major_brand" / String(4),
                     "minor_version" / String(4),
                     "compatible_brands" / Array(lambda ctx: (ctx._.size - 16) / 4, String(4)))

Box = Struct("size" / Int32ub,
             "type" / Peek(String(4, padchar=b" ", paddir="right")),
             Embedded(Switch(lambda ctx: ctx.type, {
                 "ftyp": FileTypeBox
             }, default=RawBox)
             ))

MP4 = GreedyRange(Box)
```

This produces the following output when parsing an MP4:

```
ListContainer:
    Container:
        size = 28
        type = ftyp
        major_brand = iso5
        minor_version =
        compatible_brands = ListContainer:
            iso5
            avc1
            dash
    Container:
        size = 69
        type = free
        data = ListContainer:
            73
            115
            111
            77
            ....
```

I am still have problems with nesting types, `ContainerBox` needs to contain a number of other Boxes. I am unsure how or if it is possible to a circular reference, that is a `Box` can contain a `ContainerBox`, which is in turn made up of `Boxes`.

**Comment by arekbulski** [comment]
Wow, this is quite some code. I am only able to produce general suggestions right now. `If` wrapper should be named itself, not its subcon, at least as a principle. This expression could be used where `lambda ctx` is used. Arrays can be created using `Byte[this.count]` syntax. ContainerBox is greedy and unconstrained so the first occurence of it will eat up rest of the stream. Maybe you need Prefixed or PrefixedArray or something. Recurssion is usually made with `LazyBound`, look it up. Finally embedded switch is something that I never seen or tested or anticipated. Mad scientist's dream.

**Comment by arekbulski** [comment]
After you are done with it, would you add it to the examples and submit a Pull Request? Others could benefit from this code and I will help you test it and make it clean. Attach a sub-megabyte file to be tested on.

**Comment by beardypig** [comment]
Sure thing. I have sorted out the recursion now.

I have pushed what I have to my fork,
https://github.com/beardypig/construct/blob/mpeg4/construct/examples/formats/graphics/mp4.py any suggestions would be most welcome. 

Should I open a PR, not to be merged (yet), and we can move the discussion to the PR?

**Comment by beardypig** [comment]
My end goal for the parser is to be able to mux audio and video streams from fragmented audio and video streams :)

**Comment by arekbulski** [comment]
No, I will clone your repository and send patches to you. You make a Pull Request when it is close to being final. Joining audio video is probably something that an Adapter would do.

**Comment by beardypig** [comment]
That works for me. 

For the `ContainerBox` I could not find a better way to do this.

```python
ContainerBox = Struct("type" / String(4, padchar=b" ", paddir="right"),
                      "children" / RepeatUntil(lambda o, c: o["_end"] == c._._start + c._.size, Box))
```

The number of child boxes is determined by the size of the parent box, ie. you keep reading boxes until the end of the parents data.

**Comment by arekbulski** [comment]
Make `lambda o, c: o["_end"]` into `lambda obj,ctx: obj._end` or better use `obj_._end`. Read the tutorial, the meta chapter.

**Comment by beardypig** [comment]
OK, cool. Where are the tutorials?

**Comment by arekbulski** [comment]
http://construct.readthedocs.io/en/latest/

**Comment by beardypig** [comment]
Oh right, I thought there was something extra. Which is the meta chapter?

**Comment by arekbulski** [comment]
http://construct.readthedocs.io/en/latest/meta.html

**Comment by beardypig** [comment]
Do you have any suggestions for rebuilding the size, particularly in the `ContainerBox` which uses `RepeatUntil` to parse the child boxes...

**Comment by beardypig** [comment]
I managed to `Rebuild` the size of the `ContainerBox` using this function
```python
def sizeof_box(ctx):
    if hasattr(ctx, "children"):
        return 8 + sum(map(sizeof_box, ctx.children))
    else:
        return ctx.size
```
But I have not worked out how find the size from the fields that are actually in the `Box`.

I also managed to `build` the `ContainerBox`, but I had to write a custom `Construct` - which I guess is not the best way to do it ... 

```python
class ChildBoxConstruct(RepeatUntil):
    def __init__(self):
        super(ChildBoxConstruct, self).__init__(lambda obj, ctx: obj.end == ctx._.start + ctx._.size, Box)

    def _build(self, obj, stream, context, path):
        try:
            super(ChildBoxConstruct, self)._build(obj, stream, context, path)
        except RangeError:
            # ignore the range error
            pass


ContainerBox = Struct("type" / String(4, padchar=b" ", paddir="right"),
                      "children" / ChildBoxConstruct())
```

**Comment by arekbulski** [comment]
You can use this `RawCopy` to obtain offsets and lenghts.
http://construct.readthedocs.io/en/latest/tunneling.html#obtaining-raw-bytes-as-well

**Comment by arekbulski** [comment]
ChildBoxConstruct looks suspicious, I dont see why anyone would want to ignore errors on building. Something is probably wrong with this one.

**Comment by beardypig** [comment]
Yep, definitely wrong. More a hack to get the mental juices flowing than an actual solution. 
What I was trying to achieve was to read an unknown  number of Boxes from a ContainerBox until the data in the ContainerBox had been exhausted, and then during build to simply write all of the Boxes in the ContainerBox ignoring the predicate.

**Comment by arekbulski** [comment]
Can you provide me with a basic example? Make it short but clear.

**Comment by arekbulski** [comment]
I refactored your code from commit b4cfd9612f34311011c7cdcecbedcb1059138243
https://github.com/construct/construct/commits/mp4-arek
Forgive me for not being able to send you a PR, dunno how to.

**Comment by arekbulski** [comment]
Ah please add a file or hexlified dump to the test suite.

**Comment by arekbulski** [comment]
So how is it going @beardypig ? No hurry to close this thread, just checking up on ya.

**Comment by arekbulski** [comment]
Feel free to reopen or create a new one when you have a need. :)
