### ISSUE TITLE
Knowing how much data has been read?

### ISSUE THREAD

**Issue by beardypig** [construct/construct#248]
Is is possible to find the amount of data that has been read by the current context?

For example, if I had a `Struct` like 

```python
Struct("size" / Int32ub,
       "data" / Array(this.size - 4, Byte))
```

Is is possible to find out that 4 bytes has been read by the time data is reached? To avoid hardcoding the amount that should have been read.

**Comment by arekbulski** [comment]
`Tell` is in the docs, although the page is marked stale.
http://construct.readthedocs.io/en/latest/streaming.html#construct.core.Tell

**Comment by beardypig** [comment]
Cool, perfect. 

Is there a way to tell from a Context? ie. in a `lambda` like 
```python
Struct("size" / Int32ub,
       "data" / Array(lambda ctx: ctx.size - ctx.tell(), Byte))
```

**Comment by arekbulski** [comment]
Yeah but not the way you portrayed it. Tell is a singleton construct, you give it a name, put it in a Struct, and the context will have a value when parsing or building.

**Comment by beardypig** [comment]
Yeah, I got that working. I just wondered if there are a cleaner way to do it than having an extra Tell.
```python
Struct("start" / Tell,
       "type" / String(4, padchar=b" ", paddir="right"),
       "offset" / Tell,
       "data" / Array(this.size - (this.offset - this.start), Byte))
```

**Comment by beardypig** [comment]
Thanks for the help @arekbulski

**Comment by arekbulski** [comment]
Context is a Container and only have members that were added to it, like a dict, it does not have any tell() method or other goodies. Whatever you want to get out of context (pun unintended) you must put there yourself in the first place. I can add however that you can use [ ] array range syntax.
```py
"data" / Byte[this.size - this.offset + this.start]
```

**Comment by beardypig** [comment]
Cool, also good to know. Thanks.
