### ISSUE TITLE
2.5.5 Documentation

### ISSUE THREAD

**Issue by redfern314** [construct/construct#252]
Hey @arekbulski - is there a way to view the old version of the documentation for 2.5.5? I'm still using that until I'm able to update to 2.8.

**Comment by arekbulski** [comment]
Oh oh, good point. AFAIK readthedocs site does not allow branches the way github does. So I cannot maintain two websites. But I am pretty sure that we can download a pdf version of the site for any historical commit.

**Comment by redfern314** [comment]
Actually, doing some research it looks like readthedocs does allow multiple builds. You can set it to build on any tagged releases of your git repo. Obviously I can't go in and look at the admin page for construct's readthedocs, but the readthedocs docs (heh) make it sound pretty easy.

https://docs.readthedocs.io/en/latest/features.html#versions
https://docs.readthedocs.io/en/latest/versions.html

**Comment by arekbulski** [comment]
I do not have admin access to the site because Tomer did not transfer the ownership to me (not yet anyway). I will upload the PDF version in minute for your convenience.

**Comment by arekbulski** [comment]
Here is the PDF and rest:
https://github.com/construct/construct/tree/stable25/docs_pdfetc

**Comment by redfern314** [comment]
Awesome - thanks! Should we keep this issue open for when Tomer transfers ownership to you?

**Comment by arekbulski** [comment]
Nah.
