### ISSUE TITLE
How predicate works in If?

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#254]
- Python: 3.4
- construct: 2.8.7

I write two struct have only on difference in Predicate. One use **this**, another use **lambda**.
And the test code below
```
a = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(this.flag1 and this.flag2, BitsInteger(6)),
)))

b = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(lambda ctx: ctx.flag1 and ctx.flag2, BitsInteger(6)),
)))

assert b.parse(b'\x61') == Container(dict(flag1=False, flag2=True, v=None))
assert b.parse(b'\x61') == a.parse(b'\x61')
```
It seems like **this** way  in Predicate can't support **and**, The  result is determined by **this.flag1** which is the first **Path** i wrote

And then I test whether **this** useful with **OR** condition.  It also just use **this.flag1**. test like below
```
a = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(this.flag1 or this.flag2, BitsInteger(6)),
)))

b = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(lambda ctx: ctx.flag1 or ctx.flag2, BitsInteger(6)),
)))


assert b.parse(b'\x61') == Container(dict(flag1=False, flag2=True, v=33))
assert b.parse(b'\x61') == a.parse(b'\x61')
```

So, am I use **this** in a wrong way?  

PS: The code can run without error but get a unexcept result.  In a complex format, need a lot of time to find this logic....Maybe we can add this in Doc to avoid this situation If my code use **this** wrong -^ ^-*

**Comment by OhBonsai** [comment]
Eh....
I just test **not** 
```
a = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(not this.flag1, BitsInteger(6)),
)))
a.parse(b'\x61')
```
Finnaly get ```TypeError: 'bool' object is not callable``` error, 
So can't use ```and or not``` in Predicate with ```this```?

**Comment by beardypig** [comment]
Unfortunately you cannot override the `and`, `or`, or `not` operators in python. However, the bitwise operators `&`, `|`, and `~` should work in their place. 

```python
a = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(this.flag1 | this.flag2, BitsInteger(6)),
)))
```

**Comment by OhBonsai** [comment]
You are right~  beardypig
```
a = Bitwise(Aligned(8, Struct(
    'flag1' / Flag,
    'flag2' / Flag,
    'v' / If(~this.flag1, BitsInteger(6))
)))
assert a.parse(b'\x61') == Container(dict(flag1=False,flag2=True, v=33))
```

**Comment by beardypig** [comment]
Glad to be of help.

**Comment by arekbulski** [comment]
I confirm, and or not operators are not usable in this expressions.

You made a good point to update the docs.
