### ISSUE TITLE
Printing a Container with a large GreedyBytes field could be truncated

### ISSUE THREAD

**Issue by beardypig** [construct/construct#255]
When you print a `Container` that has a `GreedyBytes` (or similar) field that is large (>80 bytes?) all of the data is currently printed which can is sometimes inconvenient. For example, if you are parsing a file format that contains blobs of data, video perhaps, and you print the parsed `Container` you may get something like
```
Container:
    size = 1000
    has_data = True
    data = ^@^@^@^B     <E0>^@^@^@^TA<9B><A2><E2>^D^?^@
    O<B2>^Zc<BD><80><B9><E1><E1><94>j!^@^@^@^B  <E0>^@^@^@^NA<9B><C2><E2>^D^?^@^@^EQ<C4>H<8B>8^@^@^@^B  <E0>^@^@^@^NA
<9B><E2><E2>^D^?^@^V?<B0>*<C0><B2><81...
```
It might be better to truncate the output for very long strings.
```
Container:
    data = data = ^@^@^@^B     <E0>^@^@^@^TA<9B><A2><E2>^D^?^@
    O<B2>^Zc<BD><80><B9><E1><E1><94>j!^@^@^@^B  <E0>^@^@^@^NA<9B><C2><E2>^D^?^@^@^EQ<C4>H<8B>8^@^@^@^B  <E0>^@^@^@^NA
<9B><E2><E2>^D^?^@^V?<B0>*<C0>
    [truncated]
```

**Comment by arekbulski** [comment]
Should it be printed in repr or hex or both?

**Comment by beardypig** [comment]
Yeah, like hexdump style or?

**Comment by arekbulski** [comment]
Exactly but we need to add new function to handle the data like
`hexdumpsiple(data) -> "BEEF010101... printable... (total 111111 bytes)"`
Are you up implementing it, Beardy? Tests and all?

**Comment by beardypig** [comment]
Sure, I can do it :-)

**Comment by beardypig** [comment]
Is Python 2.7 the earliest supported version of Python?

**Comment by arekbulski** [comment]
Yeah, if you create a PR then test suite will be run through all the supported versions.

**Comment by arekbulski** [comment]
I dropped 2.6 some weeks ago, due to dict syntax and no OrderedDict there.

**Comment by beardypig** [comment]
OK. That's cool, that means I can use `bytes`. 

How about a method that prints something like this ?
```python
>>> print(construct.Struct("a" / construct.GreedyBytes).parse(b"This is a test string that has some unprintable characters in it: '\x01\x02\x03\n'. It is also quite long!"))
Container:
    a = b'This is a test string that has some unprintable characters in it: \'\x01\x02\x03\n\'. It is ' [truncated, total 96 bytes]

>>> print(construct.Struct("a" / construct.GreedyBytes).parse(b"\x01\x03short string"))
Container:
    a = b'\x01\x03short string'
```

In the case of `GreedyString(encoding="utf8")` in _will_ attempt to print the full string, and print any special characters - as is the case now. 

Any comments on how many characters it should be truncated to?

**Comment by arekbulski** [comment]
I would suggested a format earlier, what do you think of it?
`hexdumpsimple(data) -> "BEEF010101... printable... (total 1024 bytes)"`

Cap might be say 64 bytes? 

You should put a new method `hexdumpsimple` and call if from `Container.__str__`.

Also there should be a method `setfullprinting` analog to `setglobalencoding` that enables full printing, so there is no additional parameters passed to str or anything. And then there is documentation on the website... easily eats away half of your day. :smile: 

Now that you mentioned it, we might apply same capping to printing unicode strings, the same way. What do you think? I think its reasonable to cap both.

**Comment by beardypig** [comment]
Can you give a full example, if I understand you format correctly then it might be slightly confusing. 
ie. You might not be able to tell the difference between the bytes '\x01\x02' and '0102', unless I misunderstood. 

I wanted to stick as closely as possible to the way that bytes are printed in Python 3, but with truncating. 

64 bytes sounds reasonable. 

For truncating unicode string, I'm not sure. I might be useful to print string in full, generally they will be shorter and contain printable characters. Dunno...

**Comment by arekbulski** [comment]
`hexdumpsimple(b"\x0102abcde....") -> "01029798991011... ??abcde... (total 1024 bytes)"`
String would be printed only the second and third part, and characters not bytes. The non printable bytes (<32 I think) are replaced by dots in hexdump, might use dots here too.

**Comment by arekbulski** [comment]
Or below. Just notice that hexdump replaces <32 bytes with dot, doesnt print \x01.
`hexdumpsimple(b"\x0102abcde....") -> "01029798991011... \x01\x02abcde... (total 1024 bytes)"`

**Comment by beardypig** [comment]
Should there be a line break, or do you want it all on one line? Still not 100% sure I get your example. 

Here are the 3 options, in the order that I prefer them ;)
```
Container:
    a = b"This is a test string that has some unprintable characters in it: '\x01\x02\x03\n'. It is " (truncated, total 96 bytes)

Container:
    a = 0000   54 68 69 73 20 69 73 20 61 20 74 65 73 74 20 73   This is a test s
        0010   74 72 69 6E 67 3A 20 27 01 02 03 0A 27 2E 20 54   tring: '....'. T
        0020   68 6F 73 65 20 77 65 72 65 20 73 6F 6D 65 20 75   hose were some u
        0030   6E 70 72 69 6E 74 61 62 6C 65 20 63 68 61 72 61   nprintable chara
        (truncated, total 93 bytes)

Container:
    a = 546869732069732061207465737420737472696E673A20270102030A272E2054686F7365207765726520736F6D6520756E7072696E7461626C65206368617261 This is a test string: '....'. Those were some unprintable chara (truncated, total 93 bytes)
```

I think that it is important to include "truncated" at the end, so that users are not unsure of what exactly has been printed.

**Comment by arekbulski** [comment]
You know what, you made a point. No 1 it is. Maybe add ... after the string? No 2 would fubar in a sub sub nested container, because all lines would get indentated leaving little space, each column would be split in half, yare yare. No 3 sucks, I admit that now.

**Comment by arekbulski** [comment]
One liner, the way it is now.

**Comment by beardypig** [comment]
Cool. I'll submit a PR in a bit, maybe tomorrow.

**Comment by beardypig** [comment]
Just gotta add some tests and update the docs, then fix the bugs and then we can review it in the PR.

**Comment by arekbulski** [comment]
Haha, sounds like a day wasted on something that could take 30 minutes to complete. Happened to me too. You can PR whatever you have, doesnt have to green (pass test suite) or whatever. Work in progress is fine.

**Comment by beardypig** [comment]
Well, I had done it like that before, but I was thinking it might be of some general use. Plus, I was working on other stuff too :-)

**Comment by arekbulski** [comment]
Please PR whatever you have right now. I get to work on it in a secon and finish it.

**Comment by arekbulski** [comment]
Feature added. This was a nice one.

**Comment by beardypig** [comment]
Works great in Python3. Would be cool if the output was the same in Python 2 :)

**Comment by arekbulski** [comment]
Can you add identical test for py3?

**Comment by arekbulski** [comment]
Oh and pick another task?

**Comment by beardypig** [comment]
When printing an `Enum` field, the name of the `Enum` is printed like so:
```
Container:
    is_leading: UNKNOWN (total 7)
```
I don't think this is part of the desired behaviour. Perhaps it should only print truncate when the type is `bytes`? It doesn't solve it for Python2 though, because `bytes == str` in Python2. 
Something to consider at least.

**Comment by arekbulski** [comment]
Bytes is bytes. Container does not know what construct it produced.

**Comment by arekbulski** [comment]
So essentially, the printing format has changed for Enum-produced strings, so now it also includes the string length. It wasnt intended but I would not count it as a bug. I'd say let it slide?
