### ISSUE TITLE
Prefixed should support an option that includes the size of the lengthfield in the size

### ISSUE THREAD

**Issue by beardypig** [construct/construct#257]
When using `Prefixed` it should be possible to include the size of the lengthfield as part of the length of the full `Construct`. 

With a signature something like:
```python
Prefixed(lengthfield, subcon, include_length_field=False)
```
eg. `Prefixed(Byte, Byte[3], include_length_field=True)` should write a length of 4 and followed by the 3 bytes in the array. 

Tests that should pass
```python
assert Prefixed(Byte, Int16ul, include_length_field=True).parse(b"\x03\xff\xffgarbage") == 65535
assert Prefixed(Byte, Int16ul, include_length_field=True).build(65535) == b"\x03\xff\xff"
assert Prefixed(Byte, GreedyBytes, include_length_field=True).build(b"\x01\x02\x03") == b"\x04\x01\x02\x03"
assert Prefixed(Byte, Int16ul, include_length_field=True).sizeof() == 3
```
Possibly supporting `VarInt` for `lengthfield` when using `include_length_field`
```python
assert Prefixed(VarInt, GreedyBytes, include_length_field=True).parse(b"\x02\x00\xff\xff") == b'\x00'
assert Prefixed(VarInt, GreedyBytes, include_length_field=True).build(b"\x01" * 127) == b"\x81\x01" + b"\x01" * 127
```
This would require serialising the `length` multiple times, to determine the full size of the `Construct`.

**Comment by arekbulski** [comment]
I do not think this should belong to the core library, not many people will use it. Although I would welcome a generic way to manipulate the byte count after reading it. Maybe an optional lambda that takes both parsed lengthfield an context, and returns new length.
`Prefixed(VarInt, GreedyBytes, modlength=lambda length,ctx: length-len(VarInt.build(length))`
This would be generic enough to allow for more elaborate usage.

Second option would be to copy paste its source and modify it to your own needs. You can always implement your own construct and attach them to the mp4 module. Doesnt have to be in core.

**Comment by arekbulski** [comment]
Maybe even
`Prefixed(VarInt, GreedyBytes, modlength=lambda length,lengthbytes,ctx: length-lengthbytes)`

**Comment by arekbulski** [comment]
Oh just so you know, I figured that what you need could be made with a macro using FocusedSeq but I didnt get aroun to test it yet. Am totally congested today.

**Comment by beardypig** [comment]
OK, no problem. If I find a lot of file formats that use this version of type-length-value encoding I'll suggest it again ;)
I main advantage with the `Prefixed` construct is that it works over a `BoundBytesIO` stream, which means `GreedyBytes` works very nicely :)
Perhaps some kind of `Bounded` Subconstruct could be added, to wrap the stream in a `BoundBytesIO`. This doesn't already exist does it?

**Comment by arekbulski** [comment]
BoundBytesIO was added for performance only. It doesnt change semantics, just avoids re-reading bytes.  In fact, now that I think of it, I would not have added it in the first place. 

What would you want Bounded to do? What semantics?

**Comment by arekbulski** [comment]
Implementing a macro with FocusedSeq would be very easy for parsing, but a pain to make it build. I would prefer to modify Prefixed copypasta than macro it, so building works too.

**Comment by beardypig** [comment]
`Bounded` would wrap the stream in `BoundBytesIO` with a `func` to define the bounded the size. But maybe it is not so useful. 
```python
# contrived example 
Box = FocusedSeq(
    1,
    "size" / Int8ub,
    Bounded(Struct("a" / GreedyBytes), this.size - 1)
)
```

What was the one-liner that got replaced with `BoundBytesIO`?

**Comment by arekbulski** [comment]
That doesnt build correctly, so more or less:
```py
Box = FocusedSeq(1,
    "size" / Rebuild(Byte, len_(this.data+1)),
    "data" / Bounded(GreedyBytes, this.size - 1)
)
```

**Comment by beardypig** [comment]
Yeah, that's a better example ;)

**Comment by arekbulski** [comment]
One liner was in 3cb79d89a61510dd8d63816bb32380e7e1a2b1c9
```py
-        data = _read_stream(stream, length)
-        return self.subcon.parse(data, context)
```

**Comment by beardypig** [comment]
Ah OK, to avoid reading all the bytes upfront. Gotcha.

**Comment by beardypig** [comment]
Maybe I will just have to include a modified version of `Prefixed`, unless you have a good way to do it. 

A generic way to go back and modify the stream would be super useful, but I cannot think of an elegant way to do it :D

**Comment by arekbulski** [comment]
It was to avoid reading bytes twice (or even once in case of lazy parsing that never happened),

**Comment by arekbulski** [comment]
Yeaaah, just copy paste and change +sizeof -sizeof to it and be done with it. Not worth poindering upon a feature that no one will use anyway.

**Comment by arekbulski** [comment]
Lets focus on capped printing instead.

**Comment by beardypig** [comment]
Yeah, true enough. Wasted enough time on it :-) Should get back to the job at hand, muxing mp4 tracks... 

Thanks.
