### ISSUE TITLE
Revert to old Struct syntax?

### ISSUE THREAD

**Issue by bitcraft** [construct/construct#261]
Is it possible to not use the / operator overload syntax for declaring new Structs (and use the old way?)  I have a few times built Structs dynamically and I'm not sure how new syntax would support doing that.  Its nice to see this very useful library get some more attention.

**Comment by arekbulski** [comment]
No, either use the 2.5 with the bugs and missing features or transition over. Show us your code and we gonna help you with it.

**Comment by bitcraft** [comment]
Nah.  I'll just stick to the old version.

**Comment by arekbulski** [comment]
You give up on much that was added. I bet we can work it out in a day.

**Comment by bitcraft** [comment]
You might be right, but I'm not interested in relearning it just to avoid a few bugs.
