### ISSUE TITLE
container.recursion_lock adds "__recursion_lock__" as a key to Containers

### ISSUE THREAD

**Issue by dpitch40** [construct/construct#264]
One of the users of my code employing construct was experiencing a perplexing problem involving attempting to step through the numerical keys of a Container mapping to dicts and outputting subvalues of those dicts. The basic code he was trying to run was like this:

    some_Container = parse_data() # Returns a construct.Container mapping integer keys to subdicts
    for key in some_Container:
        print some_Container[key]["Attribute"] # "Attribute" should be a key of all the subdicts

Running this, however, gave him the exception `TypeError: 'bool' object has no attribute '__getitem__'`. I was perplexed, since just before this my user had outputted the entire contents of the Container to a log file, in which I could clearly see that none of the keys in some_Container mapped to boolean values.

After some digging through the source code, I realized what was going on. The recursion_lock decorator of the Container.`__pretty_str__` method sets the attribute "`__recursion_lock__`" for that Container. But the Container class's `__setattr__` method is mapped to its `__setitem__` method, which adds the set attribute as a dictionary key. So in addition to the expected numerical keys mapping to subdicts, my user was also encountering the key "`__recursion_lock__`" mapping to the value False, which was causing the error.

Changing the setattr calls in container.recursion_lock to dict.`__setattr__` calls resolved this issue for me; this allowed setting `__recursion_lock__` as an attribute of the Container instance rather than as a dictionary key.

I am using version 2.5.2, but looking at the current source code the issue still seems to be present.

**Comment by arekbulski** [comment]
I see, you found a bug indeed. Would you be willing to send a PR for head?

**Comment by arekbulski** [comment]
I see, you found a bug indeed. Would you be willing to send a PR for head? Also a unit test for regression.

**Comment by dpitch40** [comment]
How do I run the unit tests? Running `python test_all.py` doesn't seem to work, and running `python setup.py test` after building gives me the output:

    running test
    running egg_info
    creating construct.egg-info
    writing construct.egg-info\PKG-INFO
    writing top-level names to construct.egg-info\top_level.txt
    writing dependency_links to construct.egg-info\dependency_links.txt
    writing manifest file 'construct.egg-info\SOURCES.txt'
    reading manifest file 'construct.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'construct.egg-info\SOURCES.txt'
    running build_ext

    ----------------------------------------------------------------------
    Ran 0 tests in 0.000s

    OK

Which doesn't seem very useful.

**Comment by arekbulski** [comment]
Run `python/python3/pypy -m pytest` from within either project directory or from within tests. You need to pip install `pytest` within the runtime that you use for testing. 

Easier for you, if you submit a PR its commit will be tested on all runtimes by Travis. FYI.

**Comment by arekbulski** [comment]
On side note, I stumbled upon the same problem when I wanted to reimplement Container using OrderedDict. Everything seems nice and dandy until I realised that all attribute assignments get caught up in the key assignment "trap" and in the end I gave up on that.

**Comment by dpitch40** [comment]
Actually, I just realized 2.8.8 deletes the "__recursion_lock__" attribute instead of setting it to False after the recursive call. So I don't think this issue is still in the latest version. Changing setattr calls to __dict.__setattr__ might still work for your issue, though.

**Comment by arekbulski** [comment]
Would you add some regression test to check that?
