### ISSUE TITLE
Referencing nested fields doesn't work when calculating size

### ISSUE THREAD

**Issue by Schamper** [construct/construct#266]
Let's say I have the following structs:
```
child = 'child' / Struct(
    'field_a' / Int16ub,
    'field_b' / If(this.field_a)  # etc
)

parent = 'parent' / Struct(
    'nested' / child,
    'field_c' / If(this.nested.field_a)  # etc
)
```

Referencing nested fields like this works as expected when building and parsing. The parent has to explicitly reference the complete "path" to the field, whereas the nested field can just reference its own fields. Quickly scanning over the code, this seems to be handled by the `_build` and `_parse` functions in the `Struct` class.

However, say I want to use `.sizeof(container)` on `parent`. The container will be passed as context, but it won't be "traversed" correctly when it encounters nested structs. The `field_b` conditional will be called with the original "parent" container as context, so it can't find `this.field_a` (because it'll be under `this.nested.field_a`).

**Comment by arekbulski** [comment]
Ah I can see what the problem is. Implementing nesting containers in parse and build was tricky and toook me half a day. Sizeof is gonna need to be fixed, but first we need a unit test for it. Would you send a  PR with the test for this? Please simplify the fields, usual `a b c` are fine. Look at how test suite is written.

**Comment by arekbulski** [comment]
I started working on the fix but got stuck. You can see the testing and disabled fix. Feel free to review or just wait until I work it out.

**Comment by Schamper** [comment]
Not that pretty, but this seems to work?
```
def nest(context, sc):
    # sc is a Renamed(Struct), good idea, wont work
    if isinstance(sc, Renamed) and isinstance(sc.subcon, Struct) and sc.name in context:
        context2 = context[sc.name]
        context2._ = context
        return context2
    else:
        return Container()
```

**Comment by arekbulski** [comment]
This piece looks so horrible but also probably works. I will use it.

**Comment by arekbulski** [comment]
Your code wont work on an anonymous struct or a renamed renamed renamed struct. I will update your code and finally resolve this issue.

**Comment by arekbulski** [comment]
Fixed! :laughing:  Took me only half a year to fix this one... a record.
