### ISSUE TITLE
Switch should inherit flagbuildnone if all members have it

### ISSUE THREAD

**Issue by Schamper** [construct/construct#269]
This fails with a `KeyError: 'b'`:
```
Struct("a" / Byte, "b" / If(this.a == 1, Padding(2))).build(Container(a=1))
```

Though this succeeds, even though the `b` key is useless:
```
Struct("a" / Byte, "b" / If(this.a == 1, Padding(2))).build(Container(a=1, b=0))
```

Let me know if you want a unit test added for this.

**Comment by arekbulski** [comment]
Does making IF anonymous make it work?
`Struct("a" / Byte, If(this.a == 1, Padding(2))).build(Container(a=1))`
Unit test is welcomed.

**Comment by arekbulski** [comment]
You should know that `flagbuildnone` isnt dynamic, it doesnt change depending on context. We could make Switch turn on flagbuildnone when all its members have it. Would work for IF at least.

**Comment by Schamper** [comment]
`If` was just as an example, but in my case I have a `Switch` that can return a `Pass` as the default.
 It's not that big a deal in my personal case but merely an interesting detail I noticed.

https://github.com/construct/construct/blob/master/construct/core.py#L870-L873

Maybe add a `flagbuildoptional` which will behave the same as `flagbuildnone`?

**Comment by arekbulski** [comment]
Show me your piece of code then. 

What would be the exact semantics of `flagbuildoptional`?

**Comment by Schamper** [comment]
Something along these lines.

```
message = 'message' / Struct(
    'header' / header,
    'payload' / Switch(
        this.header.pkt_type, {
            pkt_type_a: payload_a,
            pkt_type_b: Pass
        },
        Pass
    )
)
```

Not passing a `payload` key/value in `.build(obj)` would raise an exception.

**Comment by arekbulski** [comment]
Yeah, this Switch should definately be an IF. And we gonna add the semantics I proposed and then its gonna work fine. Do you want to implement it and PR?

**Comment by Schamper** [comment]
I should remark that the second Pass is actually supposed to become a `payload_b` later on. Just wasn't implemented yet so I forgot to change it in the example ;)

**Comment by arekbulski** [comment]
Well, for the record, the current semantics are correct. During parsing the `If` always returns something, None or an int or whatever, so its reasonable for it to always expect an input during building. However, I see the benefit of flagging it buildnone when all its members are such.

**Comment by arekbulski** [comment]
Updated. Note that `If` is anonymous although doesnt have to be.
```py
st = Struct("enabled" / Byte, If(this.enabled, Padding(2)))
assert st.build(dict(enabled=1)) == b"\x01\x00\x00"
assert st.build(dict(enabled=0)) == b"\x00"
```

**Comment by Schamper** [comment]
Looks fine to me.

**Comment by arekbulski** [comment]
Does this update satisfy your particular needs?

**Comment by Schamper** [comment]
Yeah it's fine. Cheers.
