### ISSUE TITLE
ULInt32 is not defined

### ISSUE THREAD

**Issue by illera88** [construct/construct#271]
`ULInt32` should be exported by construct right? It seems that it is not anymore.

```C:\Users\user\Downloads\pdbparse-master\examples>python pdb_get_syscall_table.py "C:\Symbols\kernel32.pdb\A5F376CBC24445E6B5DB50E72E7A1DC51\kernel32.pdb"
Traceback (most recent call last):
  File "pdb_get_syscall_table.py", line 6, in <module>
    from pdbparse.pe import Sections
  File "C:\Python27\lib\site-packages\pdbparse\pe.py", line 3, in <module>
    from pdbparse.info import GUID
  File "C:\Python27\lib\site-packages\pdbparse\info.py", line 21, in <module>
    ULInt32("Version"),
NameError: name 'ULInt32' is not defined

Thanks

**Comment by arekbulski** [comment]
You did not transition to 2.8 yet. Look up the docs site, transition chapter.

Classes you can use are `Int{8,16,24,32,64}{u,l}{s,u} VarInt BytesInteger BitsInteger`.

**Comment by illera88** [comment]
So how should I represent now `ULInt32("Version")`

It should be `Int32ub("Version")` ?

Thanks

**Comment by arekbulski** [comment]
Everything was redisgned in the library. Read the docs end to end first.
It should be `"Version"/Int32ul`.

**Comment by illera88** [comment]
thanks
