### ISSUE TITLE
Parsing collection including Union gives peculiar result

### ISSUE THREAD

**Issue by VanhaKehno** [construct/construct#273]
Hello,
I am not able to parse data properly when Union is involved. The same construction builds correctly as below, but parsing yields to a wrong 'str' value. Seems to me that str contains also data which belongs to previous Union (in example below). 
```
from construct import Struct, Union, Int8ub, Int32ub, GreedyBytes
>>> t = Struct(
        'a' / Int8ub,
        'u' / Union
	   (
	   'c' / Int8ub[4],
           'd' / Int32ub,
           ),
        'str' / GreedyBytes,
        )
>>> t.build(dict(a=1, u=dict(d=20), str="foobar"))
'\x01\x00\x00\x00\x14foobar'
>>> t.parse('\x01\x00\x00\x00\x14foobar')
Container(a=1)(u=Container(c=[0, 0, 0, 20])(d=20))(str='\x00\x00\x00\x14foobar')
```
Could someone point out what i am doing wrong?

**Comment by arekbulski** [comment]
Union fallbacks to same starting point before parsing each member and at the end. It does not forward the stream forward by 4 bytes in a way you expect it. Either use `Seek(4)` or request some semantic change to the Union.

**Comment by arekbulski** [comment]
There used to be a paramter that would specify how many bytes to forward after parsing, and it could be an int or min/max builtin functions. I dont remember why it was removed (probably it was just confusing). The problem is essentially that Union works like a combination of Peeks and its members can have different sizes, so its not implicitly clear how it should forward.

**Comment by VanhaKehno** [comment]
I may have missed that in the docs, but luckily it seems that in my case i don't need to build, only parse, so i can use extra padding to get parsing to work. 

It is very good to know this behaviour though.

**Comment by arekbulski** [comment]
I am planning to restore `skipfrom` parameter. Please forward your input to #278 .
