### ISSUE TITLE
computed Struct name

### ISSUE THREAD

**Issue by Gheoan** [construct/construct#274]
I have the following bytes:
```python
b'\x0A\x00\x00\x05\x54\x6F\x74\x61\x6C'
```
which I parse with:
```python
Struct(None, ULInt16('count'), ULInt8('id'), PascalString('name'))
```
which outputs:
```python
Container({'count': 10, 'id': 0, 'name': b'Total'})
```
However, what I would like to get is:
```python
Container({'count': 10, '0': {'name': b'Total'})
```
How can I model my `Struct` to get the desired `Container`? If it is not possible I could manipulate the `Container` directly. Feel free to give answers in either version 2.5 or 2.8.

**Comment by arekbulski** [comment]
Hmm this is a tricky one. You could look at `Computed` but probably wont fit your particular need. Frankly, I am clueless on this one. Maybe just write your own subconstruct that does this, or a oneliner that adds and removes keys on a Container. Its not hard to extend Construct.

**Comment by arekbulski** [comment]
Ah, silly me, just look at `Adapter` class.

**Comment by Gheoan** [comment]
`Adapter` seems to be the solution here. Thank you @arekbulski.
