### ISSUE TITLE
examples/formats/executable/pe32.py is broken

### ISSUE THREAD

**Issue by brupelo** [construct/construct#275]
I've just installed construct on `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32`, that example is not working. Ie:

    NameError: name 'ULInt16' is not defined

**Comment by arekbulski** [comment]
Yeah, it probably is. Some of the formats were translated to 2.8 syntax and classes and some remained unusable. If you translate it, please PR and I will review it and put into the release.

**Comment by brupelo** [comment]
@arekbulski I'd like to give it a shot, but starting with the minimal version i've already face some errors, https://bpaste.net/show/b3e694732983 . Pip installed me 2.8.8

**Comment by arekbulski** [comment]
You should read entire docs tutorial. You still think in terms of old C 2.5

15 lis 2016 12:25 PM "Bruno Pedrosa" <notifications@github.com> napisał(a):

**Comment by brupelo** [comment]
@arekbulski I don't think in terms of 2.5 cos i haven't even tried construct before, it's my first attempt with the library. I've read the tutorial... i've tried parse or parse_stream and both of them have the same problem, did you try the example i've posted? I'm just trying this library because one python guy recommended me as a much better alternative to ctypes... my first impression is a really awesome promising library wich has broken examples/test. Anyway, could you explain me what's wrong? If parse or parse_stream are broken/deprecated, why are they still there?

**Comment by brupelo** [comment]
Ok, i've figured it out, now i'm able to get a `<class 'construct.lib.container.Container'>` after parsing, still I think that's a buggy behaviour.

**Comment by arekbulski** [comment]
Examples are provided because some are working and some just need upgrade
to 2.8. There is a lot of working examples in the docs.
Show your latest.

15 lis 2016 1:13 PM "Bruno Pedrosa" <notifications@github.com> napisał(a):

Ok, i've figured it out, now i'm able to get a <class
'construct.lib.container.Container'> after parsing, still I think that's a
buggy behaviour.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/construct/construct/issues/275#issuecomment-260625672>,
or mute the thread

**Comment by arekbulski** [comment]
Ah sorry for misconception.

15 lis 2016 1:27 PM "Arek Bulski" <arek.bulski@gmail.com> napisał(a):

**Comment by brupelo** [comment]
@arekbulski Here's my current test:

    from construct import *

    msdos_header = Struct(
        "signature" / Const(b"MZ"),
        "partPag" / Int16ul,
        # "page_count" / Int16ul,
        # "relocation_count" / Int16ul,
        # "header_size" / Int16ul,
        # "minmem" / Int16ul,
        # "maxmem" / Int16ul,
        # "relocation_stackseg" / Int16ul,
        # "exe_stackptr" / Int16ul,
        # "checksum" / Int16ul,
        # "exe_ip" / Int16ul,
        # "relocation_codeseg" / Int16ul,
        # "table_offset" / Int16ul,
        # "overlay" / Int16ul,
        # Padding(8),
        # "oem_id" / Int16ul,
        # "oem_info" / Int16ul,
        # Padding(20),
        # "coff_header_pointer" / Int32ul,
        # "_assembly_start" / Anchor,
        # OnDemand(
        #     HexDumpAdapter(
        #         Field("code",
        #               lambda ctx: ctx.coff_header_pointer - ctx._assembly_start
        #               )
        #     )
        # ),
    )

    pe32_file = Struct(
        msdos_header,
    )


    def chunks(l, n):
        for i in range(0, len(l), n):
            yield l[i:i + n]

    if __name__ == "__main__":
        import binascii

        filename = "notepad.exe"

        with open(filename, 'rb') as f:
            print('\n{0:-^80}'.format('FILE_CONTENT'))
            content = f.read()
            data = binascii.hexlify(content)
            print('\n'.join(' '.join(chunks(x, 4))
                            for x in chunks(data.decode("utf-8"), 32))[:39])

        # print (pe32_file.parse_stream(open("example1_crinkler.exe", "rb")))
        x = pe32_file.parse(open(filename, "rb").read())
        print(x.__class__)
        print(list(x.keys()))
        try:
            print(x.signature, x.partPag)
        except Exception as e:
            print("x.signature and x.partPag ---> Error {0}".format(e))

        try:
            print(x["signature"], x["partPag"])
        except Exception as e:
            print("x['signature'] and x['partPag'] ---> Error {0}".format(e))

And here's the output:

    ----------------------------------FILE_CONTENT----------------------------------
    4d5a 9000 0300 0000 0400 0000 ffff 0000
    <class 'construct.lib.container.Container'>
    []
    x.signature and x.partPag ---> Error signature
    x['signature'] and x['partPag'] ---> Error 'signature'

Could you advice here? I'm not interested on reading the whole PE file, only a little subset at this
moment, how can I do that? Btw, for not polluting github issues with these type of questions, are you available on #freenode/python?

**Comment by arekbulski** [comment]
But Issues are meant to solve these kind of questions. And I am not, sorr. Maybe some day on Gitter, some day.

**Comment by arekbulski** [comment]
`pe32_file ` has a non-named member.

**Comment by arekbulski** [comment]
I think Anchor was dropped (use Tell) and OnDemand does something completely different than it used to.

**Comment by brupelo** [comment]
I've tried:

    pe32_file = Struct(
        "msdos_header" / msdos_header,
    )

and I still get the same errors than before, shouldn't be now this the proper way to create [nested structs](https://construct.readthedocs.io/en/latest/basics.html#nesting-and-embedding)?

**Comment by arekbulski** [comment]
Yeah it should. Sorry but I am at apex of flu so gonna have to get back to
you.

15 lis 2016 2:11 PM "Bruno Pedrosa" <notifications@github.com> napisał(a):

**Comment by brupelo** [comment]
I've found the issue with my last snippet :)

**Comment by arekbulski** [comment]
Ah yeah, you forgot about the middle struct.

**Comment by brupelo** [comment]
@arekbulski  And about my last question of saving/dumping a Container to disk? I'm reading the [docs](https://construct.readthedocs.io/en/latest/api/core.html) and I don't find anything realted to disk operations.

**Comment by arekbulski** [comment]
Well, you build from it into a stream, and provide a binary file as that stream.

**Comment by brupelo** [comment]
@arekbulski Yeah, but how do you get the 'bytes' out of the `<class 'construct.lib.container.Container'>`? said otherwise: which one is the method to get the data (bytes instance) to be used with file.write method?

**Comment by arekbulski** [comment]
Oh you just build the obj with the construct used to parse it (unless you used some specific classes that do not allow rebuilding, which I do not see here). Perhaps just this?
```py
with open("file","wb") as f:
    pe32_file.build_stream(obj, f)
```

**Comment by brupelo** [comment]
@arekbulski Thanks, it think that's in the right direction, but I'm still missing something take a look to this trivial foo dummy example:


    from construct import *

    msdos_header = Struct(
        "signature" / Const(b"MZ"),
        "partPag" / Int16ul
    )

    pe32_file = Struct(
        "msdos_header" / msdos_header,
    )


    def print_first_bytes(filename, n=39):
        import binascii

        def chunks(l, n):
            for i in range(0, len(l), n):
                yield l[i:i + n]

        with open(filename, 'rb') as f:
            print('\n{0:-^80}'.format('FILE_CONTENT'))
            content = f.read()
            data = binascii.hexlify(content)
            print('\n'.join(' '.join(chunks(x, 4))
                            for x in chunks(data.decode("utf-8"), 32))[:39])

    if __name__ == "__main__":
        # Read original file
        print_first_bytes("notepad.exe")
        x = pe32_file.parse(open("notepad.exe", "rb").read())
        print(x)

        # Modify some values
        x.msdos_header.signature = b"BP"
        x.msdos_header.partPag = 256
        print(x)

        # Dump to file
        with open("file","wb") as f:
            pe32_file.build_stream(x, f)

        print_first_bytes("file")
        x = pe32_file.parse(open("file", "rb").read())
        print(x)

The output is this one:

----------------------------------FILE_CONTENT----------------------------------
    4d5a 9000 0300 0000 0400 0000 ffff 0000
    Container: 
        msdos_header = Container: 
            signature = b'MZ'
            partPag = 144
    Container: 
        msdos_header = Container: 
            signature = b'BP'
            partPag = 256

    ----------------------------------FILE_CONTENT----------------------------------
    4d5a 0001
    Container: 
        msdos_header = Container: 
            signature = b'MZ'
            partPag = 256

Question is, I've modified the signature of the new file to b'BP'... but when i dump it to disk it remains the same, why would be that?

**Comment by brupelo** [comment]
@arekbulski I'm trying to port the broken example to 2.8.x but I'm struggling to understand how to port these [lines](https://github.com/construct/construct/blob/master/construct/examples/formats/executable/pe32.py#L85-L91) to the new syntax, as far as I've read `HexDumpAdapter` is now `HexDump` and `Field` now has become `Bytes`.

Btw, would this msdos_header handle the fact of sometimes PeHeader & PeOptionalHeader structs can overlap with the msdos_header? ie: in some packed executables you'll see this.

For instance, read this:

_The PE format begins with a MS-DOS stub (a header plus executable code) which makes it a valid MS-DOS executable. The MS-DOS header begins with the magic code 0x5A4D and is 64 bytes long, followed by real-mode executable code. The standard stub used almost universally is 128-bytes long (including header and executable code) and simply outputs "This program cannot be run in DOS mode." Despite many utilities that with PE files are hard coded to expect the PE header to start at exactly 128 bytes in, this is incorrect since in some linkers, including Microsoft's own Link, it is possible to replace the MS-DOS stub with one of your own choosing, and many older programs did this to allow the developer to bundle a MS-DOS and Windows version into a single file. The correct way is to read a formerly reserved 4-byte address inside the MS-DOS header located at 0x3C (field commonly known as e_lfanew) which contains the address at which PE file signature is found, and PE file header follows immediately. Usually this is a pretty standard value (most of the time this field is set to 0xE8 by the default link.exe stub). Microsoft seemingly recommends aligning the PE header on an 8 byte boundary (http://msdn.microsoft.com/en-us/gg463119.aspx, page 10, figure 1)._

The trick here is understanding `e_lfanew`

**Comment by brupelo** [comment]
Full post about previous question [here](http://stackoverflow.com/questions/40633001/how-to-parse-overlapping-structs-on-construct)

**Comment by arekbulski** [comment]
Look at Seek class.

**Comment by brupelo** [comment]
I've tried using Pointer class and it definitely applies here... but, what do you mean by using Seek?

**Comment by arekbulski** [comment]
Ah Pointer is also able to read from specified addresses, but cannot write to them the way I remember?

**Comment by arekbulski** [comment]
These lines should be LazyStruct HexDump Bytes?

**Comment by arekbulski** [comment]
Even, if you cant finish translating this module, please PR what you have.
