### ISSUE TITLE
Support indexing on this.

### ISSUE THREAD

**Issue by hardkrash** [construct/construct#276]
Simply adding a `__getitem__` to the Path, we then have the this expression to work with `[]`

This addition allows the following expression to work.
`this['flag with spaces'] == 0`

```
diff --git a/construct/expr.py b/construct/expr.py
index f20c6a0..5a5371e 100644
--- a/construct/expr.py
+++ b/construct/expr.py
@@ -146,6 +146,8 @@ class Path(ExprMixin):
         return context2[self.__name]
     def __getattr__(self, name):
         return Path(name, self)
+    def __getitem__(self, name):
+        return Path(name, self)
```

**Comment by beardypig** [comment]
@hardkrash why not create a PR? It sounds like a good suggestion to me :-)

**Comment by arekbulski** [comment]
Yeah, a PR would be nice. Please also look how test suite was written and add appropriate test cases for the indexing.

**Comment by arekbulski** [comment]
PR merged. This (forgive me the pun) was helpful, thanks. :)
