### ISSUE TITLE
How to deal with max-length C strings?

### ISSUE THREAD

**Issue by domenzain** [construct/construct#281]
While reading a protocol specification (PTP/IP) for implementation in the near future, I found a `CString` of `Int16ul` (UTF8) with a maximum length: that is, the length of the string is determined by the terminator but it cannot be longer than a fixed value.

Is there a sane way of parsing and building such strings?

**Comment by arekbulski** [comment]
You could look at `Check` for validation, or build your own  adapter or validator.

**Comment by domenzain** [comment]
I can indeed check after the fact that at most a certain number of characters were read before a terminator.
But when parsing I still need to wait until a terminator comes along (which might not be the case for a malformed sequence of bytes). That would lead parsing to consume the entire stream before I can know if the length has been exceeded.

On the other hand, if I read up to the maximum number of bytes and then verify that a `CString` is amongst them, then I need to wait until the stream gives at least that amount of bytes, which also might not happen.

Ideally what I would expect is that parsing on a stream for this sort of condition stops if the expected length is exceeded, but also if a predicate (in this case presence of a terminator) is `True`.

**Comment by arekbulski** [comment]
I see. I think you might need to copy-paste the CString implementation and tweak it. Using RepeatUntil would not work, because the pradicate only uses one element and not previous elements or an index.

**Comment by domenzain** [comment]
Thanks for the lead. I'll cook up a pull request for this.

I think it's better to add the general case of an arbitrary predicate. 
Would you prefer I add an optional argument to `RepeatUntil` to have a condition on the number of bytes read, or just make a new `Subconstruct` for this purpose with an obligatory argument?

**Comment by domenzain** [comment]
This could also be a condition on the number of `Subconstruct`s that have been read. That would make more sense.

**Comment by arekbulski** [comment]
Extending RepeatUntil predicate with an index or the in-progress container (preferred) would be easiest and most general solution. Then there would be no need for a PredicateRange. How about that?

**Comment by domenzain** [comment]
That sounds reasonable.
I'll give it a go in a second pull request and then we can compare the two alternatives.

Is there a set of conventions for the in-progress `Container`s besides the parent context as `_`?

**Comment by arekbulski** [comment]
Range puts indexes into the context I think.

4 gru 2016 10:42 AM "domenzain" <notifications@github.com> napisał(a):

**Comment by domenzain** [comment]
This was actually extremely easy to implement...
A single `subobj` was replaced by `obj` in `RepeatUntil`.

I find the alternative in #283 much more logical and clean. But it breaks a few things and the inherent meaning of the context that is made available by mechanisms like `obj_` will have to change.

The solution in #282 has minimal impact to other `Subconstruct`s but is less natural and requires complicated code for a specific case.

What do you think?

**Comment by arekbulski** [comment]
I think PredicateRange is a subset of ReapetUntil with history variable and we should provide our users with most general blocks. This is what made LEGO so popular after all.

**Comment by arekbulski** [comment]
If you need to redesign half of the library, fine... as long as it is justified. The way I see it, RepeatUntil and list containers could use some upgrades.

**Comment by domenzain** [comment]
I'll close #282. Certainly a better-designed library is more valuable for users. In the coming weeks I will incrementally rework what's needed to make in-progress `Container`s available with a consistent interface through #283.

I'm certain the more general `RepeatUntil` will be much more powerful and would accommodate many changes that would otherwise require copy-pasted code with subtle modifications.

**Comment by arekbulski** [comment]
The pile you made is quite substantial but I agree on that a well designed library with fewer but powerful components is a good choice.
