### ISSUE TITLE
RFC: ByteSwapped is really just ByteReversed, and what to do to improve it.

### ISSUE THREAD

**Issue by hardkrash** [construct/construct#284]
I have a structure that is two ```Int32ul``` combined.  It maps from a product where they access the data linearly for register reads over the communication interface, but access it as structs with little ending integer mapping...  Thus requiring heavy mental gymnastics to make sure that I don't introduce a bit/byte order bug.

Here is the structure of question in C.

```C
struct foo {
  uint32_t field1;
  uint32_t field2;
};

flag_0 = field_1 >> 0 && 1;
flag_1 = field_1 >> 1 && 1;
my_int_0 = field_1 >> 12 && 0xFF;
// etc...
```

This makes ```flag_0``` the 7th bit from the beginning of memory, Uggh!

The documentation is written as follows.
register x
bit 31 - blah
...
bit 1 flag_1
bit 0 flag_0

Naïvely start writing the following bitstruct 
```python
c2.Bitstruct(
# Byte 0
    'bit7' / c2.Flag,
    'bit6' / c2.Flag,
    'bit5' / c2.Flag,
    'bit4' / c2.Flag,
    'bit3' / c2.Flag,
    'bit2' / c2.Flag,
    'bit1' / c2.Flag,
    'bit0' / c2.Flag,
# Byte 1
    'bit15' / c2.Flag,
    'bit14' / c2.Flag,
    'bit13' / c2.Flag,
    'bit12' / c2.Flag,
    'bit11' / c2.Flag,
    'bit10' / c2.Flag,
    'bit9' / c2.Flag,
    'bit8' / c2.Flag,
)
```

Unfortunately this breaks for ````field_2````  where a ```BitInteger``` spans a byte boundary!

I need two nibbles and an adapter to combine them and that is very unclear to me 6 months from now...

I then think let's use ```ByteSwapped```, but```ByteSwapped``` is really ```ByteReversed``` i.e. ```data[::-1]```.  So, we must break the bitstructs into the integer size (4) of the data struct and then byte swap.  Leading the to following struct.  Switched to bytes of the python input sequence and bits of the 32bit integer (for clarity :confused:)

```python
import construct as c2
foo = c2.Struct(
    c2.Embedded(c2.ByteSwapped(c2.BitStruct(
        'byte3_bit2**31' / c2.Flag(),
        c2.padding(11),
        'my_int_0' / c2.BitInteger(8),
        c2.padding(11),
        'byte0_bit2**0' / c2.Flag(),
    ))),
    c2.Embedded(c2.ByteSwapped(c2.BitStruct(
        'byte7_bit2**0' / c2.Flag(),
        c2.padding(30),
        'byte4_bit2**0' / c2.Flag(),
    ))),
)
```

This code feels cumbersome,  I would prefer to perform 4 byte swap of the whole structure, not have to manually impress the swap every 4 bytes.

So now to my ideal case. (Presuming that all my data is byte swapped the same way.)

I add a int_size keyword to ```ByteSwapped``` where 1 or none is the current mode, 2 is ```Int16u```, 3 is ```Int24u```, and etc...
Then allowing the natural bit ordering of the structure.

```python
# The byte numbers below are listed as if they were from a python bytes containing the 8 bytes.
import construct as c2
foo = c2.ByteSwapped(c2.BitStruct(
        # field_1
        'byte3_bit2**31' / c2.Flag(),
        c2.padding(11),
        'my_int_0' / c2.BitInteger(8),
        c2.padding(11),
        'byte0_bit2**0' / c2.Flag(),

       # field_2
        'byte7_bit2**31' / c2.Flag(),
        c2.padding(30),
        'byte4_bit2**0' / c2.Flag(),
    ),
    int_size=4,
)
```

I guess I could have written it cleanly as follows.
I consider this form necessary for mixed sizes of little endian registers. As it would be less confusing.
Iterating through a list for byte swapped sizes would be more complicated to follow.

```python
import construct as c2

field_1 = c2.Embedded(c2.ByteSwapped(c2.BitStruct(
    'byte3_bit2**31' / c2.Flag(),
    c2.padding(11),
    'my_int_0' / c2.BitInteger(8),
    c2.padding(11),
    'byte0_bit2**0' / c2.Flag(),
)))

field_2 = c2.Embedded(c2.ByteSwapped(c2.BitStruct(
    'byte7_bit2**0' / c2.Flag(),
    c2.padding(30),
    'byte4_bit2**0' / c2.Flag(),
)))

foo = c2.Struct(
    field_1,
    field_2,
)
```

This conveys the fact that each field is little endian and composes a larger struct.
I still prefer a single definition with ByteSwapped learning about partitioned integers.

Opinions folks, before I go and implement some code?

Unless, I have entirely messed up this bit ordering nonsense ;-)
Note: I cringe on the IBM documentation on 64bit PPC interface logic where bit 0 was the left bit on the register.  Leading to bit 0 representing ```2**63``` Ugh!

**Comment by arekbulski** [comment]
This is so TL'DR for me at 5:50am. I can point you to BitsSwapped class and suggest that you take the closest class and modify it to suit your needs. If existing classes are not enough to suit your needs then just reimplement what you need. Source is open. Copypasta and mod it, man.
