### ISSUE TITLE
Create range based on number of bytes?

### ISSUE THREAD

**Issue by sam-bristow** [construct/construct#285]
I am trying to parse a data format which has a header and a series of one or more "entries" which are of varying sizes. The header contains a field "length" which is the size of the "entries" block in bytes, not the number of entries.

I haven't been able to work out how to handle this. Range() etc take an element-count rather than a size in bytes.

Can you please point me in the right direction?

Simplified Example:
```python
header = "header" / Struct(
    "length" / Rebuild(Int8ub, len_(this.entries),
    "other_stuff" / Bytes(4),
)

entry = "entry" / Struct(
    "tag" / Byte,
    "data" / Switch(
        0: Byte,
        1: Pass,
        2: Struct(
            "foo": Byte,
            "bar": Bytes(2),
           ),
        3: Byte,
    )
)

packet = "packet" / Struct(
    "header" = header,
    "entries = ???
)

series = "series" / GreedyRange(packet)
```

**Comment by arekbulski** [comment]
Look at `Prefixed` and `GreedyRange`.

**Comment by sam-bristow** [comment]
I've had a look at those, but I can't work out how to handle the case where the length and the Range aren't stored together (that "other_stuff" in the example).

Sorry if I'm missing something obvious.

**Comment by sam-bristow** [comment]
I was able to get parsing working with a combination of `Prefixed`, `Computed`, and `GreedyRange`:

```python
header = "header" / Struct(
    "length" / Rebuild(???),
    "other_stuff" / Bytes(4),
)

entry = "entry" / Struct(
    "tag" / Byte,
    "data" / Switch(
        this.tag, {
            0: Byte,
            1: Pass,
            2: Struct(
                "foo": Byte,
                "bar": Bytes(2),
               ),
            3: Byte,
        }
    ),
)

packet = "packet" / Struct(
    "header" / header,
    "entries / cs.Prefixed(cs.Computed(this.header.length), GreedyRange(entry))
)

series = "series" / GreedyRange(packet)
```

But I'm now stuck on building. I can easily grab the count (in elements) with `Rebuild(Int8ub, len_(this.entries)`, but not the length in bytes.

 I've tried using a combination of `RawCopy` and `Rebuild` to grab the `length` of the entries field but I just get a key error when I try to use any of the extra fields that `RawCopy` provides.

**Comment by arekbulski** [comment]
You can copy one of those classes and modify it somehow to meet your needs.

**Comment by arekbulski** [comment]
I just fixed a bug in RawCopy. Please checkout HEAD and see you can use it now.

**Comment by arekbulski** [comment]
Check `Prefixed(FocusedSeq(0, Byte, other), GreedyRange(entry)).`
https://construct.readthedocs.io/en/latest/misc.html#focusedseq
oer perhaps `Prefixed(Padded(Byte, 5), GreedyRange(entry))` if you can just drop the other field.
