### ISSUE TITLE
Error from misaligned bitwise parse doesn't make sense

### ISSUE THREAD

**Issue by eevee** [construct/construct#286]
```py
>>> Bitwise(BitsInteger(19)).parse(b'\x00\x00\x00\x00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "construct/core.py", line 175, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "construct/core.py", line 186, in parse_stream
    return self._parse(stream, context, "parsing")
  File "construct/core.py", line 1775, in _parse
    self.stream2.close()
  File "construct/lib/bitstream.py", line 40, in close
    raise ValueError("closing stream but %d unread bytes remain, %d is decoded unit" % (len(self.rbuffer), self.decoderunit))
ValueError: closing stream but 5 unread bytes remain, 1 is decoded unit
```

5 unread _bits_ remain, and I have no idea what "decoded unit" means.

**Comment by arekbulski** [comment]
The `RestreamedBytesIO` that works inside `Bitwise` context uses two functions to encode and decode byte strings. Encoding function takes "encoded units" amount of bytes and outputs however much it wants, decoding units is analogous. In case of Bitwise, encoder processes 8:1 and decoder 1:8 bytes, unless I got thoese the other way around. After processing the subcon, it cannot have any bytes (well bits) unprocessed. You are trying to read a non-multiple of 8. Use a Padding or GreedyBytes to consume remaining bytes, well bits.

**Comment by eevee** [comment]
Well, yes, I know it's not a sensible operation  :)  The error just isn't very helpful when it happens in the middle of a larger struct — it doesn't mention bits at all.

**Comment by arekbulski** [comment]
Docs updated, warning of the situation that you encountered.
