### ISSUE TITLE
Is Construct suitable for binary data with random order?

### ISSUE THREAD

**Issue by UsernameFor2017** [construct/construct#290]
The binary data I need to process is, for all intents and purposes, randomly ordered. It contains a limited, well-defined number of records, but the order in which they appear is unknown prior to its arrival. I have to consume a byte to find out what follows - could be a PascalString, could be one of 20 punctuation marks, could be a literal integer. Some strings need to be decrypted and re-examined. 

What I've read to date suggests Construct is only suited to predictable ordering(?) The switch statement hints at the capability I'm after, together with Lazy/OnDemand parsing and Validators...

**Comment by UsernameFor2017** [comment]
@harvimt - why the downvote?

**Comment by harvimt** [comment]
You're describing the `Switch` construct which changes which subcon parses based on some condition. If `Switch` is not sufficient, you may request additional features obviously.

**Comment by harvimt** [comment]
@UsernameFor2017 Generally I downvote when I can't think of anything nice to say.

**Comment by UsernameFor2017** [comment]
Thanks for your assistance.

**Comment by arekbulski** [comment]
Issues are also meant as a forum where our userbase can ask for support, so this question is highy appropriate.

**Comment by arekbulski** [comment]
I do not understand what you mean by predictable ordering. Switch parses one subcon and selects a second based on first value. You would need to provide more details.
