### ISSUE TITLE
Protocols repository

### ISSUE THREAD

**Issue by pohmelie** [construct/construct#291]
First of all, awesome project! I use it for long long time… So, the idea is to create repo for protocols (like tcp/ip stack in examples). This is good for searching and sorting protocols, contributing, have single style for protocols and so on.

**Comment by arekbulski** [comment]
There is no need for a separate repository. What we need is someone to rewrite the code to 2.8 syntax and classes.

**Comment by pohmelie** [comment]
I don't understand. I mean not «example» directory, which is «proof os concept», but strict repository, where construct protocols lives. I don't think this is a good idea to mix construct and it's protocols.

**Comment by arekbulski** [comment]
You are right that that the examples folder has half unfinished constructs but those that are huge and complete in implementation usually just are their own projects. 

I leave you with a suggestion: you can create or clone a repository and maintain it for some time. If you prove it useful, then you can transfer it to me.
