### ISSUE TITLE
LazySequence problems

### ISSUE THREAD

**Issue by pohmelie** [construct/construct#293]
Can't get how to work with `LazySequence`
``` python
>>> from construct import *
>>> s = LazySequence(Struct("foo" / Int8ul))
>>> s
<LazySequence: None>
>>> f = open("bar.bin", "rb")
>>> s.parse_stream(f)
<LazySequenceContainer: 1 possible items, 0 cached>
>>> x = _
>>> x
<LazySequenceContainer: 1 possible items, 0 cached>
>>> for i in x: print(x)
... 
ListContainer: 
    Container: 
        foo = 212
>>> 
```
How to iterate over lazy sequence? I want this to work with big file with repeated structures. Right now I'm just `parse_stream` in loop, but this looks dirty a bit.

**Comment by arekbulski** [comment]
LazySequence works exactly the way a Sequence does. Parse returns a container which supports index access, len, and iterable protocol. Only difference is that actual item parsing happens at first access per index.

**Comment by arekbulski** [comment]
What do you mean iterate over a lazy sequence?
`for i in x: print(i)`

**Comment by pohmelie** [comment]
I mean that I have big file with sequence of structures and I want to iterate over them. But I don't understand how to do it. In first example I have big file and I want to iterate with `for` where every next iteration I get my `Struct("foo" / Int8ul)`. But I got only first one and then `for` stops.

**Comment by arekbulski** [comment]
Ah because you used a Sequence not a Range. Look up the docs on basics.

**Comment by pohmelie** [comment]
`Range` have `min` and `max` it does not fits when I don't know how much structs are sits there, but with `GreedyRange`:
``` python
>>> from construct import *
>>> s = LazySequence(GreedyRange(Struct("foo" / Int8ul)))
>>> s
<LazySequence: None>
>>> f = open("telegram-worker.py")
>>> p = s.parse_stream(f)
>>> p
<LazySequenceContainer: 1 possible items, 1 cached>
>>> for x in p: print(x)
... 
ListContainer: 
>>> 
```

**Comment by arekbulski** [comment]
Using LazySequence like this makes no sense because when you access the only member of it, the entire greedyrange gets parsed. Maybe you should use LazyRange.

**Comment by pohmelie** [comment]
@arekbulski 
`LazyRange` can't be infinite, that is the problem.

**Comment by arekbulski** [comment]
Well, you could use `LazyRange(0, sys.maxsize, subcon)` as this is how GreedyRange is constructed, it is just a macro around the base Range.

**Comment by pohmelie** [comment]
@arekbulski 
This works, thanks. The only 'bad' thing is `sys.maxsize`, since if stream is pretty big/long (from network, for example) it definitely will become bigger, that `sys.maxsize`. So, two points here:
* Make possible infinite range for `LazyRange`
* Make `LazyGreedyRange` alias.
What do you think?

**Comment by arekbulski** [comment]
But maxsize is 2^64 which is unobtainable by mere incrementation.

**Comment by pohmelie** [comment]
@arekbulski it's platform depended. But, anyway, this is «known history» mistake. Many times someone told: «oh, it's damn big number! No one will reach limit, believe me!». And many times limits was reached.

**Comment by arekbulski** [comment]
Yes but this not the case here. I believe that maxsize is 2**64 on all Python runtimes, 32bit and 2.7 included, and if you do the math then you realize that with todays processors its not possible to incrementally achieve this limit realistically. 

Do not at me, that is just annoying.

**Comment by pohmelie** [comment]
As python documentation said: 
> sys.maxsize
> 
>     An integer giving the maximum value a variable of type Py_ssize_t can take. It’s usually 2**31 - 1 on a 32-bit platform and 2**63 - 1 on a 64-bit platform.
> 

https://docs.python.org/3/library/sys.html?highlight=sys.maxsize#sys.maxsize

But, anyway, thanks for working solution.
