### ISSUE TITLE
Enum must be tested against both name and value in If()

### ISSUE THREAD

**Issue by SzieberthAdam** [construct/construct#298]
Assume that
```Python
ctx.ctrl = Enum(Bytes(1),
      default = b'\x02',
      STX = b'\x02',
      ACK = b'\x06',
      NAK = b'\x15',
  )
```
.
Now in an `If()` construct I would expect to be able to do
```Python
If(lambda ctx: ctx.ctrl.name == 'STX', Pass)
```

instead of

```Python
If(lambda ctx: ctx.ctrl in ('STX', b'\x02'), Pass)
```
.

The expected behavior should work when default value was used as well.

At least the current behavior should be added to the appropriate parts of the documentation.

**Comment by arekbulski** [comment]
This is a reasonble change. If you write a PR and appropriate test suite case, it will be welcomed.

**Comment by arekbulski** [comment]
The problem is that parse returns only a string but the context gets a (string,value) tuple instead. This can be easily fixed.

**Comment by arekbulski** [comment]
Rejected, works fine. 
```py3
def test_from_issue_298(self):
    st = Struct(
        "ctrl"/Enum(Bytes(1),
            default = b'\x02',
            STX = b'\x02',
            ACK = b'\x06',
            NAK = b'\x15',
        ),
        "optional"/If(this.ctrl == "NAK", Byte),
    )
    assert st.parse(b"\x15\xff") == Container(ctrl='NAK')(optional=255)
    assert st.parse(b"\x02") == Container(ctrl='STX')(optional=None)
```

**Comment by yairchu** [comment]
To elaborate, as I understand the reported bug is about building rather than parsing. Adding the equivalent build to the parse in the new test - `assert b"\x15\xff" == st.build(Container(ctrl='NAK')(optional=255))` illustrates that building fails.

**Comment by arekbulski** [comment]
I understand what the problem is now. Below test shows context entries after both parsing and building. When parsing, entry value is NAK unicode. When building, its \x15 bytes. This is definately not a consistent behavior and therefore a bug.

**Comment by arekbulski** [comment]
The problem is not even in Enum or Mapping classes. Its how Struct (properly) works. Struct calls a field's _build() and that method returns a possibly new value, that gets replaced in dictionary. Mapping class translates NAK unicode into \x15 bytes, and properly, Struct puts that into context dict.

**Comment by yairchu** [comment]
I checked with my code where the issue was noticed and it now works fine. Thanks!
