### ISSUE TITLE
API compatibility layer?

### ISSUE THREAD

**Issue by hillu** [construct/construct#299]
Breaking, ahem, redesigning the modules API and telling users who wonder about breakage to (re)read the fine manual is not a great recipe for attracting developers who care about long-term stability. It also brings about problems for Linux distributions that ship construct as a library dependency for other software packages.

Is it feasible to provide an API compatibility layer so that code which was written for 2.5.x can still be used with the current version?

**Comment by arekbulski** [comment]
If you want to use the old version, 2.5 is still downloadable. That is it. Project has moved forward.

**Comment by redfern314** [comment]
I think it's reasonable not to have a compatibility layer, especially for such a small project, but I might suggest using semantic versioning for the next API-breaking change: http://semver.org/

**Comment by arekbulski** [comment]
True enough, but the change is in main docs at the top in red bold. And semantic won't work because construct 3 is a different project.
