### ISSUE TITLE
2.5 / 2.8 Compatibility

### ISSUE THREAD

**Issue by redfern314** [construct/construct#300]
Hey @arekbulski - are 2.5 and 2.8 messages designed to be compatible? That is, if one system is running 2.5 and another is running 2.8, will they be able to build/parse each others' messages? (Assuming structs on the 2.8 system have been reformatted to use the new `"name" / Int32sl` format, etc.)

**Comment by arekbulski** [comment]
Well, 2.8 was entirely rewritten and several things were changed. It is not only a matter of using the name division operator. You sould look into the page below and see if the semantics were changed.
https://construct.readthedocs.io/en/latest/transition.html

**Comment by redfern314** [comment]
I did check the transition page, but it deals more with "how do I change my codebase to be compatible" by describing interface changes and new features. It doesn't say much about whether the messages built by the 2 versions will be the same.

**Comment by arekbulski** [comment]
I guess you can look into the  particular blocks you are using and see if they do what you need to do, regardless of what old version did.

**Comment by redfern314** [comment]
OK, based on this discussion I'm thinking it's best not to mix them given that there doesn't seem to be an explicit contract on compatibility. Thanks for the help! Closing.

**Comment by arekbulski** [comment]
Correct, there is no backwards or forward compatibility between versions.
