### ISSUE TITLE
2.8.10 source tarball is not published on PyPI

### ISSUE THREAD

**Issue by apevec** [construct/construct#301]
Only wheel[1] which cannot be used as the source in Fedora[2]
Previously published version 2.8.8 had source tarball.

[1] https://pypi.python.org/simple/construct/
[2] https://fedoraproject.org/wiki/PythonWheels#Python_Wheels_in_fedora

**Comment by arekbulski** [comment]
I apologize. If this is a priority request then I will get right on it, otherwise the next release will have both.

**Comment by arekbulski** [comment]
Published. Further releases will not miss this again.
