### ISSUE TITLE
Interoperability with Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [construct/construct#302]
I guess we need import/export tools to convert ```construct``` definitions to [```Kaitai Struct```](https://github.com/kaitai-io/kaitai_struct/) ones and back.

**Comment by arekbulski** [comment]
I do not think that people who use Construct use Kaitai at same time. But if you really want it then submit a PR and a comprehensive test suite. Nobody is going to do it for you, I am pretty sure. But you are welcomed to make a case and ask people to join your endeaver, both here and in #223 .
