### ISSUE TITLE
Partially parse the message and getting length dynamically

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [construct/construct#303]
Hi,

I have a protocol that uses type,length,payload fields.
type=what type of message is in payload
length=length of payload
payload=another_message_or_blob

type and length fields are fixed-length. Once I build the message (type+length+payload), and send  it over a socket to some other peer, I am trying to make the peer decode the message by first trying recv only X bytes (i.e. type and length fields) to inspect them, and then subsequently once the type and length are known, recv the rest of the data from the socket. 

Can some one help me on two fronts:
1. How can I know the length of the first two fields (say X) in the packed/built message that correspond to only type and length fields?
1. How to dynamically compute the length field of the payload, what kind of Struct declaration would be suitable for this?

Thanks,
Arvind

**Comment by arekbulski** [comment]
You kind of lost me theer. Please, explain in simple example.

**Comment by arekbulski** [comment]
Thread abandoned?
