### ISSUE TITLE
StopIf: stopping parsing on condition

### ISSUE THREAD

**Issue by rytilahti** [construct/construct#306]
Hi there and thanks for this awesome module, a quick question, what would be the sanest way to stop parsing when encountering a specific condition? I have a structure where a byte indicates the index for upcoming data, or end-of-list:

```
Struct(
  "id" / Byte,
  "some" / Byte,
  "more" / Byte,
  "data" / GreedyBytes,
)
```

In case the byte is 0xff, I would like parsing to stop there. Wrapping the rest of the elements into a separate struct, and If() to see whether to read them? Seeking to the end?

**Comment by arekbulski** [comment]
Look into `RepeatUntil` and check if the predicate can work for you.

**Comment by rytilahti** [comment]
To clarify the question, I'm not sure what I could use as a predicate and subcon here, and how would it differ from wrapping the rest of the element into If()s?

I was thinking something like 
```
Struct(
  "id" / Byte,
  If(this.id < 255, "some" / Byte),
  If(this.id < 255, "more" / Byte),
)
```
or 
```
Struct(
  "id" / Byte,
  If(this.id < 255, Embedded(Struct(
    "some" / Byte,
    "more" / Byte,
  )))
)
```
but both of them feel noisy.
```
Struct(
  "id" / Byte,
  StopIf(this.id < 255),
  "some" / Byte,
  "more" / Byte,
)
```
would feel nicer?

**Comment by arekbulski** [comment]
I have no idea about this one. Dont have the time to add StopIf but I would welcome such an addition it if supported both Structs Sequences Ranges...

**Comment by domenzain** [comment]
@arekbulski, this looks a lot like a modal switch discussed in #295.
This could be solved by having a `RepeatUntil` with a switch where one of the subcons is a `Pass`.

**Comment by domenzain** [comment]
```python
payload = Struct("some" / Byte, "more" / Byte)
packet = Struct(
     'id' / Byte,
     'switch' / Switch(
         this.id,
         {0xff: Pass},
         default=payload))
stopat255 = RepeatUntil(
     lambda s, ss, ctx: getattr(s, "switch", ()) is None, 
     packet)
stopat255.parse(b"\x00\x01\x02\x03\x04\x05\x06\xFF\xFF\xFF\xFF")
```

**Comment by arekbulski** [comment]
Jesus christ, nobody is going to use this contraption. In fact, I would like to have a StopIf class added, that works on both Struct Sequence Range RepeatUntil...

**Comment by arekbulski** [comment]
Done.

**Comment by rytilahti** [comment]
Thanks a lot, I'll let you know if I have any problems when I find some time to convert my code to use it!
