### ISSUE TITLE
add Short and others

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#309]
I suggest adding analogous to Byte=Int8ub also Short=Int16ub and few others. Please vote.

**Comment by domenzain** [comment]
For Byte, Nibble and Bit, there is no ambiguity on endianness.

But for all higher sizes there is. The Int{bits}{sign}{endianness} is clear and unambiguous.

**Comment by arekbulski** [comment]
Good point there.

**Comment by arekbulski** [comment]
Good point there... However, network and ondisk protocols usually use big endianess so Short is usually the Int16ub.
