### ISSUE TITLE
Embedded Unions interferes with parsing following fields

### ISSUE THREAD

**Issue by sam-bristow** [construct/construct#310]
I am trying to write a parser for in which a 'size' field is overloaded to signify if the packet is actually an ACK/NACK rather than a standard message. The approach I have taken to this is to treat the size/type value as a Union of an Integer and an Enum of alternate values.

# Simplified example packet

```python
from binascii import unhexlify

from construct import *


foo = Struct(
    Embedded(
        Union(
            "size" / Int16ub,
            "type" / Enum(
                Int16ub,
                ACK=0xFFFF,
                NACK=0xFFFE,
                default="message"
            ),
        ),
    ),
    "bar" / Int16ub,
    "payload" / If(this.type=="message", Bytes(this.size))
)
```
However, when I try to parse a message using this code I am getting incorrect values for the fields following the Union. It appears that the data which is part of the Union is parsed again for the following fields.

# Parsing
```
sample_ack = unhexlify("FFFE 22".replace(" ", ""))
print(foo.parse(sample_ack))

Container: 
    size = 65534
    type = NACK
    bar = 65534
    payload = None
```
In the example above I would expect:
- type = NACK
- bar = 0x22 
- payload = None
```
sample_message = unhexlify("0004 22 33445566".replace(" ", ""))
print(foo.parse(sample_message))

Container: 
    size = 1
    type = message
    bar = 1
    payload = b'"3DU'  ( 0x22334455 )
```
In the example above I would expect:
- type =message
- size = 1
- bar = 0x22 
- payload = 0x33445566

**Comment by domenzain** [comment]
That is the intended behaviour.

You'd need to pass a `buildfrom` argument to `Union`.
The parsing would then use that field's size to jump forward in the stream once the parsing has finished.

However that is also broken... There is a one-off error there.

**Comment by arekbulski** [comment]
Union is broken? How?

**Comment by domenzain** [comment]
Apologies, I had local modifications that introduced unexpected results.
So `buildfrom` should be enough to address this.

**Comment by arekbulski** [comment]
I was going to say that we should put a warning in the docs about the buildfrom parameter, but it is right there. People just do not see it. 
https://construct.readthedocs.io/en/latest/misc.html#union

**Comment by arekbulski** [comment]
Put a huge warning in ee0fb90b8a84d3c430621803124364295d11af11. Solved.
