### ISSUE TITLE
Switch does not carry embedded flag

### ISSUE THREAD

**Issue by rupran** [construct/construct#312]
Currently, `Switch` only looks at the `flagbuildnone` flags of its subconstructs but does not consider `flagembedded`. In `stable25`, the constructor of `Switch` calls 
```
self._inherit_flags(*cases.values())
```
which inherits all flags from its children whereas the current implementation just seems to forget `flagembedded`.

This led to errors that the inner members are not defined inside `outer` in a struct definition like the following (from a binary parser):
```
bar = 'outer'/Struct(
        'name'/CString(),
        If(lambda ctx: len(ctx.name) != 0,
            Embedded(Struct(
                'index'/Int64ub,
             ))
        ))
```

Is this the expected behaviour or should something like
```
if any(sc.flagembedded for sc in cases.values()):
    self.flagembedded = True
```
be added to `Switch.__init__()`?

**Comment by arekbulski** [comment]
I think this is expected behaviour, and reason is this: embedded flag should not change dynamically, and that would have to be the case with Switch. You cannot just apply embeding to all subcons if only one of them is. Consider a Struct with two members, a Struct and Embedded Struct, and you parse the first one.

**Comment by arekbulski** [comment]
I reconsidered, and I think Switch should indeed work with embedded subcons. It will need to change flagembedded dynamically during each parsing and building. It cannot just treat all subcons as embedded if only one is embedded.

**Comment by arekbulski** [comment]
You got it half right. It is impossible to Switch Embedded because flagembedded is checked before building. We CANNOT change that flag dynamically. On the other hand... Embedded Switch or Embedded If works just fine. Test case added.
```py
def test_embeddedswitch_issue_312(self):
    st = Struct(
        'name'/CString(encoding="utf8"),
        Embedded(If(len_(this.name) > 0,
            Struct('index'/Byte),
        )),
    )
    assert st.parse(b'bob\x00\x05') == Container(name='bob')(index=5)
    assert st.parse(b'\x00') == Container(name='')

@pytest.mark.xfail(reason="this cannot work, Struct cheks flagembedded before building")
def test_embeddedswitch_issue_312_cannotwork(self):
    st = Struct(
        'name'/CString(encoding="utf8"),
        If(len_(this.name) > 0,
            Embedded(Struct('index'/Byte)),
        ),
    )
    assert st.parse(b'bob\x00\x05') == Container(name='bob')(index=5)
    assert st.parse(b'\x00') == Container(name='')
```
