### ISSUE TITLE
For-loop construct

### ISSUE THREAD

**Issue by gdonval** [construct/construct#314]
Context
-----------

I am using your excellent library to parse Fortran binary files (if you don't know about it, they are platform-/compiler- dependent files written by Fortran's built-in serialisation procedure).

Problem
-----------

Consider this kind of structure (in pseudocode):

    people:    ["Bob", "Anna", "Beth"]
    flags:     [True, False, True]
    numbers:   [8, 3, 5]

That structure was obtained by parsing the file until the current point.

The *problem* is that I now need to use the provided information to parse arrays in the remaining part of the file:

* For each person of index ``i``, look at the corresponding flags[``i``].
* If the flag is True: parse an array of length numbers[``i``].
* If not: do nothing.

Is there a way to express that using this library? I have thought about an ``Adapter`` (which I already use in other parts), but it seems I am just not taking the problem by the right end.

Solution
-----------

Well, this is a bug report. So, unless there is something I missed, I would suggest providing a way to get the current index if we are building an array. But looking at the code, this would seem like a very invasive change to ``Range`` (and ultimately ``Array``).

**Comment by gdonval** [comment]
So, at least I could create a proper index object:

```
class _Index:
    def __init__(self):
        self.i = -1
        self.parent_ctx = None
        
    def __call__(self, ctx):
        if ctx._ is not self.parent_ctx:
            self.parent_ctx = ctx._
            self.i = -1
        self.i += 1
        return self.i
    
def Index():
    return cst.Computed(_Index())
```

That way, I don't have to use a new parser if I need to parse another file. \O/

The only remaining problem is that I **cannot** use: ``"myarray" / Real[this.numbers[this.index]]`` because this.index is not a proper number...

**Comment by gdonval** [comment]
And success! I had problems with my ``Computed``, but it is solved:

```
"index"   / Index(),
"num"     / cst.Computed(lambda x: x._.numbers[x.index] if x._.flags[x.index] else 0),
"myarray" / Real[this.num]
```

**Comment by arekbulski** [comment]
We could just make Range and RepeatUntil add special entry to the context that is the current count/index. In fact I think this functionality existed earlier but now I cant find it.
