### ISSUE TITLE
Packing of data (endianness wrong?)

### ISSUE THREAD

**Issue by nikhilkalige** [construct/construct#315]
I am having problems with how the data is packet when it is not in byte boundary. For example

```python
header = construct.BitStruct(
    "rec_type"/construct.BitsInteger(8),
    "length"/construct.BitsInteger(8),
    "axis"/construct.BitsInteger(7),
    construct.Padding(1),
    "hall"/construct.BitsInteger(3),
    "rfu"/construct.BitsInteger(5)
)

encoder = Struct("header"/header)

header_val = dict(rec_type=5, length=1, axis=100, hall=6, rfu=29)
encoder_val = dict(header=header_val)

e = encoder.build(encoder_val)
print(e)

b'\x05\x01\xc8\xdd'
```

The values for `rec_type` and `length` are proper.  And this is how the data is packed now

```
axis = ax = 100 = b110 0100
hall = h = 6 = b110
rfu = r = 29 = b1 1101

\xddc8 = 110 - 11101 - 1100100 - 0
     hall |   rfu    |    axis     | padding
```

But I expected it to be as below

```
11101 - 110 - 0 - 110 0100
rfu | hall | padd | axis
```

**Comment by arekbulski** [comment]
You lost me there... but it is 3am so no wonder. Can you PR a test case that shows exactly what should be parsed or built?

**Comment by nikhilkalige** [comment]
Sorry If I was not clear. The python test case would pass because the following works well
```python
hex_out = encoder.build(encoder_val) ## b'\x05\x01\xc8\xdd'

encoder.parse(hex_out) ## Output value is same as the input dictionary encoder_val
```
However, I have a problem with how the bits are packed. I expect the hex output from `build` to be
`\x05\x01\x64\xee`.

If I write a simple c program to perform the conversion as below.
```C
#include <stdio.h>

struct Header {
    unsigned char rec_type;
    unsigned char length;
    unsigned char axis : 7;
    unsigned char padding : 1;
    unsigned char hall : 3;
    unsigned char rfu : 5;
};


int main()
{
    struct Header header;
    unsigned char* ptr;

    header.rec_type = 5;
    header.length = 1;
    header.axis = 100;
    header.padding = 0;
    header.hall = 6;
    header.rfu = 29;

    ptr = (unsigned char*)&header;

    printf("%02x %02x %02x %02x\n", ptr[0], ptr[1], ptr[2], ptr[3]);
}
```

This program outputs `05 01 64 ee` which is what I was expecting in the first place.

**Comment by nikhilkalige** [comment]
![img_20170330_212631](https://cloud.githubusercontent.com/assets/1267404/24536538/e9096eca-158f-11e7-9942-d93ec118c36d.jpg)

**Comment by nikhilkalige** [comment]
The following example in `core.py` line `1302` is probably the simplest example of what I am talking about.

```python
format = BitStruct(
    "a" / Flag,
    "b" / Nibble,
    "c" / BitsInteger(10),
    "d" / Padding(1),
)

cont = format.parse(b"\xbe\xef")
print(cont)
hexout = format.build(cont)
print(hexout)
```

Corresponding output.
```python
Container: 
    a = True
    b = 7
    c = 887
    d = None
b'\xbe\xee'
```

**Comment by nikhilkalige** [comment]
The following changes in file `bitstream.py` fixes the above problem,  but the tests breakdown. So I am probably mistaken about something..

`RestreamedBytesIO.write` function
change from `self.wbuffer += data` to `self.wbuffer = data + self.wbuffer`

`RestreamedBytesIO.read` function
change from `data, self.rbuffer = self.rbuffer[:count], self.rbuffer[count:]`  to `data, self.rbuffer = self.rbuffer[-count:], self.rbuffer[:-count]`

**Comment by arekbulski** [comment]
The picture looks like a pirate's treasure map, I love it... 

You seem to be struggling with little endianness somewhere. Look at `BytesSwaped` and `BitsSwapped`.
https://construct.readthedocs.io/en/latest/tunneling.html#endianness

**Comment by nikhilkalige** [comment]
Hahah.. :)

`Byteswapped` would not fix it, because that would change the order of bytes. The data across bytes is proper for me. 

`Bitswapped` would reverse the data in the byte.

For example:
if I try to join three values:
```
msg = BitStruct(
    "f1"/BItsInteger(2),
     "f2"/BItsInteger(3),
    "f3"/BItsInteger(2)
)

msg_val = dict(f1=2, f2=7, f3=5)
```
My expected out would be `\xbe` =  ` 101 111 10`

`msg.build` output  '\xbd` = `101 111 01`

`ByteSwapped` would not help as there is only one byte.

`BitsSwapped` would give me `101 111 01` which is wrong too..

The problem lies in which bit i considered the high bit in a byte ([Bit Numbering](https://en.wikipedia.org/wiki/Bit_numbering)). I think the implementation currently thinks the highbit is on the right side (MSB 0 bit numbering), where as I expected it to be (LSB 0 bit numbering).

**Comment by arekbulski** [comment]
The BirStruct does layout subcons from left to right. Is that unexpected?

**Comment by arekbulski** [comment]
On the paper you layout hall--rfu in right to left bit ordering. We can devise an adapter.

**Comment by nikhilkalige** [comment]
Let me check the docs for adapters. If you have any thoughts on that, let me know. I could get some PR for that if you think it needs integrated into the code base.

**Comment by arekbulski** [comment]
Wrote a piece on short notice. If you could correct it, and PR with a test case?
```py3
def ReversedBitsOrdering(struct):
    result = []
    chunk = []
    chunksize = 0
    for subcon in struct.subcons:
        chunk.append(subcon)
        chunksize += subcon.sizeof()
        if chunksize % 8 == 0:
            result.extend(reversed(chunk))
            chunk = []
            chunksize = 0
    if chunk:
        raise AdaptationError("Cannot pack these subcons in 8 bits boundary.")
    return result
```

**Comment by arekbulski** [comment]
Wrote a piece on short notice. If you could correct it, and PR with a test case?
```py3
def ReversedBitsOrdering(struct):
    result = []
    chunk = []
    for sc in struct.subcons:
        chunk.append(sc)
        if sum(sc.sizeof() for sc in chunk) % 8 == 0:
            result.extend(reversed(chunk))
            chunk = []
    if chunk:
        raise AdaptationError("Cannot pack these subcons in 8 bits boundary.")
    return Struct(*result)
```

**Comment by arekbulski** [comment]
Wrote a piece on short notice. If you could correct it, and PR with a test case?
```py3
def ReversedOrderingBitStruct(struct):
    result = []
    chunk = []
    for sc in struct.subcons:
        chunk.append(sc)
        if sum(sc.sizeof() for sc in chunk) % 8 == 0:
            result.extend(reversed(chunk))
            chunk = []
    if chunk:
        raise AdaptationError("Cannot pack these subcons in 8 bits boundary.")
    return Struct(*result)
```

**Comment by arekbulski** [comment]
Or does this work?
`Struct(*reversed(subcons))`

**Comment by nikhilkalige** [comment]
The function you wrote works well when the split data fits into 8 bits. 

But when the data is like this

```python
enc16_field = ReversedOrderingBitStruct(
    "position"/construct.BitsInteger(16, swapped=True),
    "latency"/construct.BitsInteger(7),
    "error_count"/construct.BitsInteger(5),
    "status"/construct.BitsInteger(4),
)
```
But the bytes are swapped for the `(latency, error_count and status)` fields. The output I get is 
`00101110 00110000 11101000 01100011`.

The first 2 bytes are for `position` thats good. 
The last 2 bytes should have been `01100011 11101000`. But the bytes are now swapped, because we reversed the positions.

**Comment by arekbulski** [comment]
Have you tried `Struct(*reversed(subcons))`?

**Comment by nikhilkalige** [comment]
Do you mean like this
```
def ReversedOrderingBitStruct(*subcons):
    return construct.Bitwise(Struct(*reversed(subcons)))
```
This doesn't work though

**Comment by arekbulski** [comment]
Can you show me the algorithm how C packs a struct? I can help you with an Adapter at least.

**Comment by nikhilkalige** [comment]
@arekbulski I can work it out.. Thanks for your help

**Comment by arekbulski** [comment]
Sorry, didnt mean to make it sound like I dont care. I appologise. Just got shocked and dismayed seeing how this entire thing works. If I can support you with advice, please just ask. What I meant was I dont see much worth in reproducing a behavior that is broken to begin with. Oh well, maybe one man's broken is another man's encoding. :disappointed:
