### ISSUE TITLE
RepeatUntil drop the lambda?

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#319]
RepeatUntil  used to insert special keys into the context for current index, and I think it could also keep last element and entire list so far. What do you think if we replace the entire lambda x,l,ctx with just some context entries and perhaps add something like `last_ == this._last` to access those fields? Please vote.

**Comment by domenzain** [comment]
Adding a `last_` just adds more implicit abstractions to keep in mind while coding.

I'd vote for keeping lambda support, they are standard Python and explicit.

**Comment by arekbulski** [comment]
Agreed, rejected.
