### ISSUE TITLE
Is there any reason the Checksum is limited to bytes list ?

### ISSUE THREAD

**Issue by potens1** [construct/construct#323]
Hi,

Is there any (technical) reason for the Checksum construct to be limited to bytes ?

It is possible to use it with functions returning int or others, but, as soon there is an exception (when checksum does not match), the exception raise another exception since it is limited to bytes like object so there is a type error in the exception.

```py3
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from construct import *
from construct import ChecksumError

testme = Struct(
    "vals" / Byte[2],
    "checksum" / Checksum(
        Byte,
        lambda vals: sum(vals) & 0xFF,
        this.vals)
)

testme.parse(b"\x00\x00\x00")
try:
    testme.parse(b"\x00\x00\x01")
except ChecksumError:
    print("Everything is alright")
except TypeError as e:
    print(e)
    print("This should not happend")
```

**Comment by arekbulski** [comment]
You found two bugs, one is missing ChecksumError export and other is what you describe. Next time please PR a proper test case instead of uploading gz.
```py3
def test_nonbytes_checksum_issue_323(self):
    st = Struct(
        "vals" / Byte[2],
        "checksum" / Checksum(
            Byte, lambda vals: sum(vals) & 0xFF, this.vals)
    )
    assert st.parse(b"\x00\x00\x00") == Container(vals=[0, 0])(checksum=0)
    assert raises(st.parse, b"\x00\x00\x01") == ChecksumError
```

**Comment by arekbulski** [comment]
I fixed the export but unsure what is wrong with this TypeError. I will get back to you.

**Comment by potens1** [comment]
Sorry about the PR, I edited my comment (before posting) since, at the beginning my comment was mentioning doing it, but since I did not knew if it was a bug or something desired, I asked the question.

What is wrong with the TypeError is that it should not be raised when Checksum are different, ChecksumError should be raised, not TypeError. 

TypeError is raised because the Exception code is something like 
```
raise ChecksumError(" blabla %r blabla %r" % (hexlify(checksum1), hexlify(checksum2)) 
```
and hexlify does not work as expected.
The only reason why it can be is because only bytes should be accepted as checksum (and it was my question).

PR is coming for that.

**Comment by arekbulski** [comment]
It was fixed. If you feel like it, you may PR bugfixes next time. :smiley:

**Comment by arekbulski** [comment]
Thread is still open for chit chat...

**Comment by potens1** [comment]
Just saw it ;-)
