### ISSUE TITLE
Does the Prefixed should add the prefix to the context ?

### ISSUE THREAD

**Issue by potens1** [construct/construct#339]
I guess (but not sure) when Prefixed is used, the prefix should be added to the context. 

See #338

**Comment by arekbulski** [comment]
This one is half right, Prefixed itself should be named, lenghtfield should be anonymous.
```py3
 +    def test_prefixed_check(self):
 +        test = Struct(Prefixed("length" / Byte, "vals" / Byte),
 +                      "pointer" / Pointer(-this.length, Byte))
 +        indata = b"\x01\x01\x01"
 +        assert indata == test.build(test.parse(indata))
```
Short answer is no. Prefixed was designed to be opaque, so you dont care what the lenght in bytes was, library handles that for you. If you want the access: use RawCopy.

**Comment by arekbulski** [comment]
You know, we could make EVERY class attach raw bytes and stream offsets as well just like RawCopy does... problem is this does a lot of computation when not needed, and context gets polluted.

**Comment by potens1** [comment]
That was almost the point of my other question, attach raw bytes to every class. I did not thought it was heavy computation (had memoryview in head) and, about the context pollution, I was thinking of __len__ on the classes or something like that (but I confess I did not go very deep in the analysis)
