### ISSUE TITLE
Is it possible to change the parsing code to always attach parsed data ?

### ISSUE THREAD

**Issue by potens1** [construct/construct#340]
The aim of it should be to use some attribute to every value parsed to access the parsed bytes at anytime without needing more subconst.

This way, RawCopy is less required, same for Seek and Pointers.

This could be some kind of "auto" Union.

I don't have (yet) any implementation in my mind, but if you see some value to it, I can think more on it.

**Comment by arekbulski** [comment]
I have no idea what you mean. Please provide an example use.

**Comment by potens1** [comment]
My point was, the parsing call, from the user point of view is very nice and sleek, only one arg, easy. The problem (from my point of view) is when you build things that require some specific structure (like CRC), you have to introduce more subconstructs that are not strictly related to the data you want to build but are needed by the lib, In example, you can easily get some things needing two RawCopy so, when you must build, you end up with things like mystruct.build(dict(a=.., b=dict(value=(dict(c=..., d=dict(value(e=...,f=...,g=...))) and it ends up that it is very easy for the user to get lost in levels. (at least for me :-$ )

Right now the main use I had was for checksums, but I'm pretty sure there are other usages when sublevels are required to be able to achieve some operations but do not add something useful else.

Don't take me wrong, I'm fully convinced this lib makes parsing _very_ easier and nice.

**Comment by arekbulski** [comment]
You want RawCopy build to take the object itself instead of a dict with data or value items? That would require the data item to be somewhere else in the context, which not entirely great. In fact it would break shit up. Implementation wise its major architectural change with little benefit and crazy dev time cost.
