### ISSUE TITLE
Rebuild and len_ not working with Struct

### ISSUE THREAD

**Issue by anormann** [construct/construct#342]
Consider this:

```python
frame = Struct(
    "sof" / Const(Int8ul, 0xFF),
    "len" / Rebuild(Int8ul, len_(this.data)),
    "cmd" / Int8ul,
    "data" / Struct(
        "a" / Byte,
        "b" / Byte,
        "c" / Range(0, 5, Byte)
        )
    )
```
Given a raw string, it's decoded properly
```py
>>> f = '\xff\x07\x01\x02\x03\x04\x05'
>>> print repr(frame.parse(f))
Container(sof=255)(len=7)(cmd=1)(data=Container(a=2)(b=3)(c=[4, 5]))
```

But when I try to build a frame, the length is .. 3?

```py
>>> b = frame.build(dict(cmd=1, data=dict(a=1,b=2,c=[3,4])))
>>> print repr(frame.parse(b))
Container(sof=255)(len=3)(cmd=1)(data=Container(a=1)(b=2)(c=[3, 4]))
```

Is this intentional? Am I misunderstanding Rebuild?

How can I make sure the length field is calculated correctly during build?

**Comment by arekbulski** [comment]
Int8ul is same as Byte, becayse swapping happens byte wise. Just saying.

**Comment by arekbulski** [comment]
You misunderstand. `this.data` is a dict, and it does have 3 items.  `len_` was supposed to be used with GreedyRange and GreedyBytes. Rebuild is fine. Perhaps you wanted Prefixed or PrefixedArray?
```py
len(dict(a=1,b=2,c=[3,4])) == 3
```

**Comment by aslakrin** [comment]
I see, thanks. 

The thing is, the 'data' construct in the example is different for different frame types, and what I would want is really *sizeof* for whatever 'data' happens to be. I thought len was this. I couldn't get my head around rawcopy for this use.

If this is possible, would you mind giving an example? 

Often in the serial protocols i must use, frames are wrapped in frames, and wrapped again.

Eg [sof, len, type, status, [struct/array/etc], crc], where the middle bit is swapped out based on type, for example.

This means len and crc must be parsed first but built last, crc last of all.

I've used construct in its earlier iterations before, but I've never been able to build len or CRC declaratively. This seems like it should be possible now.

**Comment by arekbulski** [comment]
Check out RawCopy and Checksu in main docs site. Note you can make your own macro:
```py3
def macro(inner):
frame = Struct(
    "sof" / Const(Int8ul, 0xFF),
    "len" / Rebuild(Int8ul, len_(?)),
    "cmd" / Int8ul,
    "data" / inner,
    )
```

**Comment by aslakrin** [comment]
Wonderful idea with macro. Yes, I mean the number of bytes of the inner. So that a recipient will know how long the frame is. Possibly adding the constant known length of the checksum.

Incidentally, how would you have made a 'routing' scheme for parsing and handling based on type in the outer frame?

**Comment by arekbulski** [comment]
I suppose... you could edit Prefixed class to use a lambda instead of lenghtfield. Would solve the problem.

**Comment by anormann** [comment]
Yes, but, how would the lambda figure out the size of the struct? I'm sorry if I'm dense here.

I tried using a lambda inside the `Rebuild` and `RawCopy`, but at the time the lambda runs, the context doesn't contain the serialized version of the struct (RawCopy.data).

**Comment by arekbulski** [comment]
Oh shit, thats right. I think you need to write yourself a class similar to the macro we talked about earlier (or two macros for parsing and building), that builds  a separate inner first, and then builds outer struct. LIke
```py3
inner = Struct(...)
data = inner.build(...)
frame = Struct(sof, len, cmd, data=Bytes(this.len))
data = frame.build(dict(len=len(data), cmd, data=data))
```
