### ISSUE TITLE
Anchor, Terminator, UBInt16, SBInt64 are missing in construct 2.8.11

### ISSUE THREAD

**Issue by mhbkb** [construct/construct#345]
Hey,

I am bumping construct 2.5 to 2.8 for supporting Python 3.5 in my application. However, I found Anchor, Terminator, UBInt16, SBInt64 are missing after the upgrade. Any substituted classes?

**Comment by arekbulski** [comment]
Have you bothered to even look at this? Notification says in bold red that entire library was redesigned.
https://construct.readthedocs.io/en/latest/transition.html

**Comment by mhbkb** [comment]
Thanks for the prompt response. Closing this issue.
