### ISSUE TITLE
small documentation glitch?

### ISSUE THREAD

**Issue by yoelk** [construct/construct#347]
Hi,
I've been reading about **PrefixedArray** in the API reference and saw that for cases where the number of bytes is precedes the data (instead of the number of elements), I should read about the **Array** class. But I think the relevant class you should be directing to is **Prefixed**

Thanks for this great module!

**Comment by arekbulski** [comment]
I know what you refer to. Point out what should be instead?
https://construct.readthedocs.io/en/latest/tunneling.html#working-with-bytes-subsets

**Comment by yoelk** [comment]
I meant it should refer here instead:
https://construct.readthedocs.io/en/latest/api/core.html#construct.core.Prefixed

**Comment by arekbulski** [comment]
I am not sure what exactly you want to suggest. If you could just edit the docs (its part of this repo) and PR it then I will be able to sort it out.

**Comment by arekbulski** [comment]
Did you mean this?
https://construct.readthedocs.io/en/latest/tunneling.html#working-with-bytes-subsets

**Comment by yoelk** [comment]
ok, I did a PR:
https://github.com/construct/construct/pull/349

It's just a small change.

**Comment by arekbulski** [comment]
Ah now I see what you meant. Thank you, merged your correction and added mine as well.
