### ISSUE TITLE
Union parsing fails with variable sized subcons

### ISSUE THREAD

**Issue by yoelk** [construct/construct#348]
Hello,
My name is Joel Koenka.
I've developed a communication protocol (running over PySerial) for sending binary data between an Arduino and an attached PC.
The protocol has a variable-sized list of data blocks.
The block's list is prefixed by the number of blocks (1 byte).
Each block has an ID field (1 byte), then its data length in bytes (2 bytes) and then the actual data.

An example for a data block (ID=1, LENGTH=4):
`packet = bytearray(b'\x01\x00\x04\xAA\xBB\xCC\xDD')`
The data itself might be parsed as a list of Int8ub, Int16ub or Int32ub, which for the example packet will produce:
Int8ub: four data points: [0xAA, 0xBB, 0xCC, 0xDD]
Int16ub: two data points: [0xAABB, 0xCCDD]
Int32ub: one data point: [0xAABBCCDD]

So I thought of using a Union and to address each representation separately when I need it.
But I must have used it incorrectly, because it doesn't work for me. It's ok for a single block, but when I have two blocks in a list, the second block isn't parsed correctly.

Please see below a short testing code that shows the problem:
```
from construct.core import Struct, Int8ub, Int16ub, Int32ub, PrefixedArray, Union, Prefixed

block_format = Struct(block_id=Int8ub, data=Union(Int8=Prefixed(Int16ub, Int8ub[:]),
                                                                   Int16=Prefixed(Int16ub, Int16ub[:]),
                                                                   Int32=Prefixed(Int16ub, Int32ub[:])))
'''A data block in a data packet
'''

blocks_list_format = Struct(data_blocks=PrefixedArray(lengthfield=Int8ub, subcon=block_format))
'''A list of data blocks:
[blocks_num, 1] 
[block1_id, 1][block1_length, 2][block1_data, ?]
[block2_id, 1][block2_length, 2][block2_data, ?] ...
'''

block1 = block_format.parse(b'\x01\x00\x04\x11\x22\x33\x44')
block2 = block_format.parse(b'\x02\x00\x04\xAA\xBB\xCC\xDD')
blocks_list = blocks_list_format.parse(b'\x02\x01\x00\x04\x11\x22\x33\x44\x01\x00\x04\xAA\xBB\xCC\xDD')

print('\nBLOCK 1')
print(block1)

print('\nBLOCK 2')
print(block2)

print('\nTOGETHER IN A LIST')
print(blocks_list)
exit()
```

In the output for this code, you can clearly see that each block is parsed correctly when it's parsed alone, but when they are together in the list, the second block's parsing is messed up:
```
BLOCK 1
Container: 
    block_id = 1
    data = Container: 
        Int8 = ListContainer: 
            17
            34
            51
            68
        Int16 = ListContainer: 
            4386
            13124
        Int32 = ListContainer: 
            287454020

BLOCK 2
Container: 
    block_id = 2
    data = Container: 
        Int8 = ListContainer: 
            170
            187
            204
            221
        Int16 = ListContainer: 
            43707
            52445
        Int32 = ListContainer: 
            2864434397

TOGETHER IN A LIST
Container: 
    data_blocks = ListContainer: 
        Container: 
            block_id = 1
            data = Container: 
                Int8 = ListContainer: 
                    17
                    34
                    51
                    68
                Int16 = ListContainer: 
                    4386
                    13124
                Int32 = ListContainer: 
                    287454020
        Container: 
            block_id = 0
            data = Container: 
                Int8 = None
                Int16 = None
                Int32 = None
```

Any ideas about how to implement such a thing?
Thanks a lot!
Joel

**A small update:**
I added a byte field after the blocks list to see where the parser is, and it seems the parser went backwards after parsing the first block:
```
from construct.core import Struct, Int8ub, Int16ub, Int32ub, PrefixedArray, Union, Prefixed

block_format = Struct(block_id=Int8ub, data=Union(Int8=Prefixed(Int16ub, Int8ub[:]),
                                                  Int16=Prefixed(Int16ub, Int16ub[:]),
                                                  Int32=Prefixed(Int16ub, Int32ub[:])))
'''A data block in a data packet
'''

blocks_list_format = Struct(data_blocks=PrefixedArray(lengthfield=Int8ub, subcon=block_format),
                            where_am_I=Int8ub[4])
'''A list of data blocks:
[blocks_num, 1] 
[block1_id, 1][block1_length, 2][block1_data, ?]
[block2_id, 1][block2_length, 2][block2_data, ?] ...
'''

block1 = block_format.parse(b'\x01\x00\x04\x11\x22\x33\x44')
block2 = block_format.parse(b'\x02\x00\x04\xAA\xBB\xCC\xDD')
blocks_list = blocks_list_format.parse(b'\x02\x01\x00\x04\x11\x22\x33\x44\x01\x00\x04\xAA\xBB\xCC\xDD')

print('\nTOGETHER IN A LIST')
print(blocks_list)

exit()
```

The test field **where_am_I** gets these values:
```
where_am_I = ListContainer: 
        4
        17
        34
        51
```
which are the b'\x04\x11\x22\x33' in the first block. Maybe this might help find out the problem

**Comment by arekbulski** [comment]
TL;DL

When you said you had a problem with Union I knew immediately what is wrong. **buildfrom** paramterer is missing. Everybody gets that one wrong the first time. In fact if you look at the docs there is a (using Colonel Tie's voice, "big fuckin red light right there") red warning. I put it there after the previous 100 guys complained about this issue. 

Your welcome

**Comment by yoelk** [comment]
Hi,
Thanks for the answer. But adding buildfrom simply makes the code not run
at all.

Try and see yourself.
Here is an even shorter code (which I think should be working) that throws
an exception because of unknown size:

from construct.core import Int8ub, Int16ub, Int32ub, Union, Prefixed

block_format = Union(Int8=Prefixed(Int16ub, Int8ub[:]),
                     Int16=Prefixed(Int16ub, Int16ub[:]),
                     Int32=Prefixed(Int16ub, Int32ub[:]),
                     buildfrom=0)
block1 = block_format.parse(b'\x00\x04\x11\x22\x33\x44')

**Comment by arekbulski** [comment]
You found a bug in Union, actually even few. If you can wait few days then I will fix it for you. Otherwise you can use a workaround that doesnt use Union, just use a Prefixed inside some custom Adapter.

**Comment by yoelk** [comment]
Oh, cool! :)
I can wait, no prob.

Thanks!

**Comment by arekbulski** [comment]
Will you mind if I call you the cowboy guy?... :sweat_smile:

**Comment by yoelk** [comment]
Go right ahead! eeehaa!

On Sun, Apr 23, 2017 at 12:21 PM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
You remind me of the instructor of Discrete Optimization classes, he wears hats like that during lectures. In fact its sometimes hard to differentiate him from Indiana Jones.

**Comment by arekbulski** [comment]
Bugfix commited. Do you want me to push a release to pypi as well?

**Comment by yoelk** [comment]
That would be cool

**Comment by yoelk** [comment]
Hi again,
I took the updated core.py file from GitHub and indeed I can use *parse*
for my Union.
But now that I specify *buildfrom*, I can't used the *build* method.

This is something I don't really understand about buildfrom. You can only
specify it in the Union's definition but then it limits you to building
this union only from one of the options.

In this example, I want to be able to build a stream either by using the *Int8
*option or the *Int16 *option, but it doesn't work.
Please look at the code, I kept it really short.
This code works if you drop *buildfrom *from the Union definition.

from construct.core import Struct, Int8ub, Int16ub, Int32ub,
PrefixedArray, Union, Prefixed

block = Union(Int8=Prefixed(Int8ub, Int8ub[:]),
              Int16=Prefixed(Int8ub, Int16ub[:]),
              Int32=Prefixed(Int8ub, Int32ub[:]),
              buildfrom=0)

print(block.build(dict(Int8=[0xAA, 0xBB])))
print(block.build(dict(Int16=[0xAABB])))

**Comment by arekbulski** [comment]
That is correct, if buildfrom=None as default then it takes the first subcon that has an entry in the dict, if you select by int or string then it only works with that subcon. Hmm this is problematic indeed. It would be possible to separate the parameter into two, in fact, that was the case few months ago but people complained because no one bother to read the docs and didnt put these two parameters and then code didnt work as expected, so I dropped the other `skipfrom` and just left combined `buildfrom`. Workaround: use two similar declarations, with different params. Solution: yet to come.

**Comment by arekbulski** [comment]
After giving it some thought, about a 30 seconds of it, I think the second parameter should be added back. I would name it `parsefrom` thought.

**Comment by yoelk** [comment]
ok, I'll do something else then.

Still, I fail to see why *buildfrom* should exist at all.

When you parse something containing a Union, you anyway want to have all
possible options parsed.
When you build, you anyway have to specify which option you're using for
the Union in the initialization dict (e.g. *Int8=[0xAA, 0xBB]* or
*Int16=[0xAABB]*)

**Comment by arekbulski** [comment]
The problem is that Union can be followed by other classes, and since Union subcons can be of different size, there is an ambiguity where the stream should be left after parsing is done. This is what `skipfrom` used to define.
Also when building, you may wish to specify explicitly from which entry you want to build because the dict may have several entries that build to different blobs. Although now that I think of it, you probably are right on this one. Perhaps buildfrom should be removed (but the other added).

**Comment by arekbulski** [comment]
Also note, `sizeof()` can only be computed if buildfrom is set.

**Comment by yoelk** [comment]
I agree. *parsefrom* should be there instead of *buildfrom* so there is a
default parsing subcon.
I'd call it *default* instead, and make this an optional argument. If it's
not stated, the first subcon should be used for parsing.

**Comment by arekbulski** [comment]
No, I cannot use the first subcon by default because no one will use Union with that expectation in mind and this will lead to bugs. Python Zen, in face of ambiguity, resist the tempation to guess...

**Comment by yoelk** [comment]
ok master Yoda :)
Agree there as well

**Comment by arekbulski** [comment]
Update commited to HEAD

**Comment by arekbulski** [comment]
Ahh you know what... I just got a clue how to completely overhaul Union. I will update it later on again.

**Comment by yoelk** [comment]
ok, looking forward

On Tue, Apr 25, 2017 at 10:34 AM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
I redesigned the class, look at the docs. Commit in HEAD.

**Comment by arekbulski** [comment]
Updated commited. Tell me how this works for you, cowboy.

**Comment by yoelk** [comment]
Thanks! works like a charm!
Just don't forget to update the examples in core.py. Right now they don't
use parsefrom.

You're welcome to use these examples if you wish:

from construct.core import Struct, Int8ub, Int16ub, Int32ub,
PrefixedArray, Union, Prefixed

block = Struct(id=Int8ub, data=Union(Int8=Prefixed(Int8ub, Int8ub[:]),
                                     Int16=Prefixed(Int8ub, Int16ub[:]),
                                     Int32=Prefixed(Int8ub, Int32ub[:]),
                                     parsefrom='Int8'))
data_packet_format = PrefixedArray(lengthfield=Int8ub, subcon=block)

b1 = block.build(dict(id=0xFF, data=dict(Int8=[0x01, 0x01])))
b2 = block.build(dict(id=0xEE, data=dict(Int16=[0x0001])))
print(b1)
print(b2)
print(b1+b2)
print(data_packet_format.parse(b'\x02'+b1+b2))


On Tue, Apr 25, 2017 at 12:03 PM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
You are using the wrong version, I dropped the parsefrom and buildfrom.

**Comment by yoelk** [comment]
What do you mean?
In core.py, parsefrom is still there:
https://github.com/construct/construct/blob/46b7e8559184d59c679b62ab91c12a5c95e27f19/construct/core.py

**Comment by arekbulski** [comment]
That is a historic blob, not HEAD. 
https://github.com/construct/construct/blob/master/construct/core.py#L1328

**Comment by yoelk** [comment]
Oh, that's strange. I copy-pasted from GitHub so I thought this would be
the latest verison of core.py
Now that I did *git pull* I see that you removed *parsefrom*, but
unfortunately it's not working well.
The version from 2 hours ago, where *parsefrom* existed worked just fine.

See this code for verification:
After parsing, the ID of the second block should be 0x11 but instead it's 2.

block = Struct(id=Int8ub, data=Union(Int8=Prefixed(Int8ub, Int8ub[:]),
                                     Int16=Prefixed(Int8ub, Int16ub[:]),
                                     Int32=Prefixed(Int8ub, Int32ub[:]),
                                     # parsefrom='Int8'
                                     ))
data_packet_format = PrefixedArray(lengthfield=Int8ub, subcon=block)

b1 = block.build(dict(id=0x10, data=dict(Int8=[0x01, 0x01])))
b2 = block.build(dict(id=0x11, data=dict(Int16=[0x0101])))
print(b1)
print(b2)
print(b1+b2)
print(data_packet_format.parse(b'\x02'+b1+b2))

**Comment by arekbulski** [comment]
Ah perhaps I misphrased it. Parsefrom is there but as positional explicit argument, not a kw argument. You should use 
```py
Union(0, Int8=Prefixed(Int8ub, Int8ub[:]), Int16=Prefixed(Int8ub, Int16ub[:]), Int32=Prefixed(Int8ub, Int32ub[:]), )
```

**Comment by yoelk** [comment]
Ah, got it.
All good

**Comment by arekbulski** [comment]
Your welcome.
