### ISSUE TITLE
Easy question: return a literal value in a switch

### ISSUE THREAD

**Issue by sjuxax** [construct/construct#350]
I have code like this:

```
    "hasStuff" / IfThenElse(
        this._.tag_type == 'OLD',
        False,
        Flag,
    ),
```

I'm using it to parse a file format that in some versions, has this field and should read it, and in other versions, doesn't. When the old version is being read, I just want to return a hard value of `False`, and in the new versions, I want it to read out the actual value.

When I try to run the code, I get:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import stuff_construct as g
  File "/home/me/stuff_construct.py", line 269, in <module>
    Flag,
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1602, in IfThenElse
    False : elsesubcon,
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1561, in __init__
    self.flagbuildnone = all(sc.flagbuildnone for sc in cases.values())
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1561, in <genexpr>
    self.flagbuildnone = all(sc.flagbuildnone for sc in cases.values())
AttributeError: 'bool' object has no attribute 'flagbuildnone'
```

This seems to be because `IfThenElse` takes a subcon, and I can't seem to figure out how to build a subcon that will always return a fixed value in this way without moving the stream.

I could leave this as an If and then manually fix it in a post-processing step, but I was hoping to be able to fold it in to the standard parsing here. Any advice appreciated.

**Comment by arekbulski** [comment]
Yes, you understand how it works. Most classes require subcons and not work with literal values. Instead of literal `False` just use `Computed(False)` or `Computed(lambda ctx: False)`. I suppose you could make this into a feature request, I could change IfThenElse to support your usage as well?
