### ISSUE TITLE
Existence of CopyRaw? (misnamed RawCopy in docs)

### ISSUE THREAD

**Issue by ConnorKrammer** [construct/construct#352]
The [docs for `Tell`](http://construct.readthedocs.io/en/latest/streaming.html#construct.core.Tell) mention that it's almost always better to use `CopyRaw`:

> **See also**
> Better to use CopyRaw() wrapper in almost any case.

However, `CopyRaw` doesn't seem to exist. Has it been removed or renamed? If so, what's the latest recommended alternative to `Tell`, and why?

**Comment by arekbulski** [comment]
What? No, RawCopy is still there. Some people used Tell to manually extract bytes from blob for a specific  substructure to compute checksum, but RawCopy makes it automatic.

**Comment by ConnorKrammer** [comment]
I see the problem, then: the docs erroneously call `RawCopy` by the name `CopyRaw`.

**Comment by arekbulski** [comment]
https://construct.readthedocs.io/en/latest/tunneling.html#obtaining-raw-bytes
http://construct.readthedocs.io/en/latest/streaming.html#construct.core.Tell

**Comment by arekbulski** [comment]
I fixed it.
