### ISSUE TITLE
Need advice and help, still problems with Checksum, Rebuild, len_ and RawCopy...

### ISSUE THREAD

**Issue by potens1** [construct/construct#354]
Here is a part of what I'm trying to get working...

```
Version = Struct(
    "major" / Short,
    "installer" / Short
)

func_map = {
    # "GetVersion": GetVersion,
    # "Status": Status,
    "Version": Version,
}

BaseFrame = Struct(
    Const(b"\x01"),
    "msg_type" / RawCopy(Enum(Short,
                              Version=0x8010,   # list shortened for the example
                              )
                         ),
    Probe(),
    "length" / Rebuild(
        RawCopy(Short),
        lambda ctx: dict(value=len_(this.datamsg.value)(ctx))),
    Probe(),
    Seek(1, 1),
    "datamsg" / RawCopy(
        Switch(
            this.msg_type.value,
            func_map
        )
    ),
    Seek(5),
    "chksum" / Checksum(
        Byte,
        lambda data: reduce(xor, data, 0),
        this.msg_type.data + this.length.data + this.datamsg.data
    ),
    Seek(-1, 2),
    Const(b"\x03")
)
```
I'm able to parse some data, i.e:
```
>>> src=b'\x01\x80\x10\x00\x04\x9c\x124Vx\x03'
>>> foo=BaseFrame.parse(src)
>>> print(foo)
Container: 
    msg_type = Container: 
        data = \x80\x10 (total 2)
        value = Version (total 7)
        offset1 = 1
        offset2 = 3
        length = 2
    length = Container: 
        data = \x00\x04 (total 2)
        value = 4
        offset1 = 3
        offset2 = 5
        length = 2
    datamsg = Container: 
        data = \x124Vx (total 4)
        value = Container: 
            major = 4660
            installer = 22136
        offset1 = 6
        offset2 = 10
        length = 4
    chksum = 156

```
Everything is alright, but, if I try to build, the show begins...
```
BaseFrame.build(foo)
...

/home/nic/dev/zigbee/env/src/construct/construct/core.py in _build(self, obj, stream, context, path)
   2268         return hash1
   2269     def _build(self, obj, stream, context, path):
-> 2270         hash2 = self.hashfunc(self.bytesfunc(context))
   2271         self.checksumfield._build(hash2, stream, context, path)
   2272         return hash2

...
/home/nic/dev/zigbee/env/src/construct/construct/expr.py in __call__(self, context, *args)
    144             return context
    145         context2 = self.__parent(context)
--> 146         return context2[self.__name]
    147     def __getattr__(self, name):
    148         return Path(name, self)

KeyError: 'data'
ipdb> print(context)
Container: 
    msg_type = Container: 
        data = \x80\x10 (total 2)
        value = Version (total 7)
        offset1 = 1
        offset2 = 3
        length = 2
    length = {'value': 2}
    datamsg = Container: 
        data = \x124Vx (total 4)
        value = Container: 
            major = 4660
            installer = 22136
        offset1 = 6
        offset2 = 10
        length = 4
    chksum = 156
```
So two things are wrong here, first the length computed is bad, there is indeed two values, but the length I expect is four (2 values x 2 bytes).
The other thing is my checksum computing does not work since there is no "data" key for the length, only (bad) "value"

After that, it is even worse if I try to build with only the required args (as it should be in real life)
```
 parser.BaseFrame.build(dict(msg_type=dict(value='Version'), datamsg=dict(value=dict(major=4660, installer=22136))))
================================================================================
Probe <unnamed 9>
path is building, func is None
EOF reached
Container: 
    msg_type = Container: 
        value = None
        data = \x80\x10 (total 2)
        offset1 = 1
        offset2 = 3
        length = 2
    datamsg = {'value': {'major': 4660, 'installer': 22136}}
================================================================================
================================================================================
Probe <unnamed 10>
path is building, func is None
EOF reached
Container: 
    msg_type = Container: 
        value = None
        data = \x80\x10 (total 2)
        offset1 = 1
        offset2 = 3
        length = 2
    datamsg = {'value': {'major': 4660, 'installer': 22136}}
    length = {'value': 2}
================================================================================
---------------------------------------------------------------------------
SwitchError                               Traceback (most recent call last)
/home/nic/dev/zigbee/env/src/construct/construct/core.py in _build(self, obj, stream, context, path)
   2716             path += " -> %s" % (self.name)
-> 2717             return self.subcon._build(obj, stream, context, path)
   2718         except ConstructError as e:

/home/nic/dev/zigbee/env/src/construct/construct/core.py in _build(self, obj, stream, context, path)
   2146             offset1 = stream.tell()
-> 2147             value = self.subcon._build(value, stream, context, path)
   2148             offset2 = stream.tell()

/home/nic/dev/zigbee/env/src/construct/construct/core.py in _build(self, obj, stream, context, path)
   1572         case = self.cases.get(key, self.default)
-> 1573         case._build(obj, stream, context, path)
   1574     def _sizeof(self, context, path):

/home/nic/dev/zigbee/env/src/construct/construct/core.py in _build(self, obj, stream, context, path)
   1549         def _build(self, obj, stream, context, path):
-> 1550             raise SwitchError("no default case defined")
   1551         def _sizeof(self, context, path):

SwitchError: no default case defined

```
So, I know that I've at least 3 things not working...and I guess the whole BaseFrame design is not good.

Any clue for those problems ? (len_, Checksum and Enum)

**Comment by arekbulski** [comment]
Oh wow this is so TL;DR.... I will happily look at it but am too tired right now.

**Comment by potens1** [comment]
Will try to do shorter...

In the next (and stripped down example), I still have at least two problems, `this.datamsg.length` is unavailable while building if in a Switch (#357), and, if I replace it by `lambda ctx: 4` for the example, if `Seek(-1,2)` is in use (end of code), I'm able to parse, but the building is wrong, and if I use `Seek(0, 2)`, building is good, but parsing is 1 byte too short to complete...

When that will work, still have to mess with the Checksum without using RawCopy (or I have to change everything again) 

Does someone has a comment on if this is the way you would do it or absolutely not ?

```
Version = Struct(
    "major" / Short,
    "installer" / Short,
    "length" / Computed(lambda ctx: 4),
)

BaseFrame = Struct(
    Const(b"\x01"),
    "msg_type" / RawCopy(Enum(Short,
                              Version=0x8010,   # list shortened for the example
                              )),
    Probe(),
    "datamsg" / Pointer(6, Switch(
            this.msg_type,
            func_map = {
                "Version": Version,
            }
        )),
    Probe(),
    "length" / Rebuild(
        Short,
        this.datamsg.length
    ),
    Probe(),
    "crc" / Default(Byte[1], b'\x00'), # Fake, one problem at a time...
    Probe(),
    Seek(-1, 2),
    Const(b"\x03")
)
```

**Comment by arekbulski** [comment]
In Switch the `this.msg_type` is a dict, not directky a value. And WTF is `msg_type` wrapped in RawCopy? There is no point in doing that. Also Byte[1] builds from a list of integers [0] and not a b-string. Also why messing all this with Seeks? This code is so strange that I wonder if it doesn anything at all.

**Comment by arekbulski** [comment]
Man, strip this code to few basic fields and see how it builds and parses. Then add more fields. Right now you have a mess that makes no sense.

**Comment by potens1** [comment]
Hi, 

`msg_type` -> bad copy/paste from code on top (sorry), but it was there since I need (In the version where I try to compute the checksum) the bytes [1:5] (`msg_type` and `length`), and then [7:-1] (`datamsg`), so I needed three RawCopy for that, or Union. It is in the 'stripped down version'  `Enum(Short,...` without the RawCopy. So, in my last example msg_type is a Short, not a RawCopy, and so, its value in the Switch is also a Short.

Seeks where there the do the `datamsg` part before the Checksum (but in the packet, the Checksum is between the first half of the values needed for it's computation, and the second half, after the length of `datamsg` and before `datamsg`).
If the proto was designed to be easy to parse, I guess I would be length, data, chksum, but, I have no choice here. 

About simplifying, it was what I had done in #353 (only length problem) and in #357 (only switch problem) but the two are part of this big mess, and yes it does something, but almost nothing good :/ (more or less able to parse, not to build)

Thank you

**Comment by potens1** [comment]
Yay, at least something working... (some functions are missing but it is for the example)

Not very happy with the usage of RawCopy, but I tried hard not to have to use it, but was not able to, did not found how to reread the stream while building it...

```python

Version = Struct(
    "major" / Short,
    "installer" / Short,
)

func_map = {
    "GetVersion": GetVersion,
    "Status": Status,
    "Version": Version,
}

BaseFrame = Struct(
    Const(b"\x01"),
    "_start_crc1" / Tell,
    "msg_type" / RawCopy(Enum(Short,
                              GetVersion=c.GET_VERSION,
                              Status=c.STATUS,
                              Version=c.VERSION_LIST,
                              )),
    Padding(2, b"\xFF"),
    "_end_crc1" / Tell,
    Padding(1, b"\xFF"),
    "_start_crc2" / Tell,
    "datamsg" / RawCopy(Switch(
            this.msg_type.value,
            func_map
        )),
    "_end_crc2" / Tell,
    "length" / Pointer(3, Rebuild(
        RawCopy(Short),
        lambda ctx: {
            "value": ctx._end_crc2 - ctx._start_crc2,
            "data": int(ctx._end_crc2 - ctx._start_crc2).to_bytes(2, "big")}
    )),
    "crc" / Pointer(
        5, Checksum(
            Byte,
            lambda data: reduce(xor, data, 0),
            this.msg_type.data + this.length.data + this.datamsg.data
        )),
    Seek(this._end_crc2),
    Const(b"\x03")
)
```

**Comment by arekbulski** [comment]
1. If CRC1 should contain padding then use RawCopy(Struct(Enum... Padding...))? 
2. Rebuild(RawCopy()) should contain either value or data, no need for both
3. drop all Tell and use this.datamsg.length
4. I think Seek is not needed, Pointer returns back to original position?

**Comment by potens1** [comment]
Hi thank you for the look,

1. CRC does not need the padding, the padding is just there to let me compute the CRC later and put it there but to have some size reserved in the stream, same for the length, the two require the datamsg to be already in the context
1. Initially, I only used value (since doing manually the data is defeating the whole point, by requiring you to know the exact size of things and so on), but it was not working, when the Checksum was computed, only value was in the context at build time ( :/ ). Seems to me that rebuild, on RawCopy, is not setting the value _and_ data
1. Great ! I don't know why I did not tried that sooner, I tried len_(), len(), sizeof... and not the length attribute...
1. Indeed, I'm certain I had a problem where the final byte (b'\x03') was written not at its good place, but I had to rewrite those lines so many times it must be I did not use Pointer then but something else (don't remember)


Thx a lot !

The current code is now (no Tell, no Seek, only two Pointers and 1 fake padding):
```
BaseFrame = Struct(
    Const(b"\x01"),
    "msg_type" / RawCopy(Enum(Short,
                              GetVersion=c.GET_VERSION,
                              Status=c.STATUS,
                              Version=c.VERSION_LIST,
                              )),
    Padding(3, b"\xFF"),
    "datamsg" / RawCopy(Switch(
            this.msg_type.value,
            func_map
        )),
    "length" / Pointer(3, Rebuild(
        RawCopy(Short),
        lambda ctx: {
            "value": ctx.datamsg.length,
            "data": int(ctx.datamsg.length).to_bytes(2, "big")}
        )),
    "crc" / Pointer(
        5, Checksum(
            Byte,
            lambda data: reduce(xor, data, 0),
            this.msg_type.data + this.length.data + this.datamsg.data
        )),
    Const(b"\x03")
)
```

Looks better ! (still have to remove the data in length)

**Comment by arekbulski** [comment]
Why is msg_type wrapped in RawCopy? Why not just use an Enum?

**Comment by potens1** [comment]
Because I need the raw bytes of it to be able to compute the checksum, the values in it are two bytes int, and the chksum function is doing xor on single byte

**Comment by potens1** [comment]
What do you think about the `data` not computed by `Rebuild` (your point 2. and my answer about that) ? I can understand that, since Rebuild is for building, it's job is to get the "value" of the RawCopy, not the "data"
To illustrate it:
```python
a = Struct(
    "val" / Rebuild(
        RawCopy(Byte),
        lambda ctx: {"value": 4}
    ),
    "dat" / Rebuild(
        RawCopy(Byte),
        lambda ctx: {"data": b"\x04"}
    ),
    Probe()
)
```

```
Probe <unnamed 1>
path is building, func is None
EOF reached
Container: 
    val = {'value': 4}
    dat = {'data': b'\x04'}
```

**Comment by arekbulski** [comment]
> since Rebuild is for building, it's job is to get the "value" of the RawCopy, not the "data"
Well, you are overstating this. RawCopy build supports both, for sheer practicality. Please note that it is possible to obtain data from value, but not vice versa.

**Comment by arekbulski** [comment]
I suspect you could also make it `RawCopy(Rebuild(Byte, 4))` since rebuild 2nd parameter doesnt need to be a lambda, just like in most classes, it can be a literal.

**Comment by arekbulski** [comment]
Month passed.
