### ISSUE TITLE
Doc enhancement proposal: real big hard examples

### ISSUE THREAD

**Issue by potens1** [construct/construct#355]
The lib documentation is huge and well written, but, I feel it miss big examples requiring interaction between lots of elements.

There are plenty of examples in the doc, but most of them are limited to only one thing without any interaction with something else. (and are obvious)

I feel (having tried to write three different parsers with the lib) there are a lot of "traps" and corner cases when elements are combined.

The chosen thing to parse should not be obvious and require some tricks to be able to parse (Rebuild, RawCopy and Seek, I'm looking at you !). It does not need to be a real protocol, can be made up especially to showcase what to do in certain circumstances.

Those examples could provide more explanations on things and give emphasis on "good practices" (Seek or RawCopy, sizeof or len_ or len(), and so on).

In fact, I guess this could be some kind of "tutorial".

I can give an hand on this, but as you already saw, right now, I'm not even able to use the lib the way it should be.

Edit: I know there are big examples in the example dir, but there are no explanation attached, and i.e. not a single Checksum or Compressed. Maybe what I propose is nonsense since there is no need for that for the complete ipstack and ext2 ... or I'm trying particularly rotten proto...

**Comment by arekbulski** [comment]
If you want to work on it, then I would suggest two things. Please feel free to split your work among PRs, it doesnt have to be one huge PR. 

1. Improve examples in any way, but bear in mind that those are supposed to showcase only one feature at a time. Nothing contrived there.
2. Add a new chapter at the end of list in main index page, and put anything you want there. You can take from Examples directory. Note that some examples are from before 1.8 update.

**Comment by johnwbyrd** [comment]
This, please.  As I understand it, your parser is basically a binary bit packer.  That's cool, but it's not quite what your library promises it will do.  Your GIF parser, for example, doesn't implement all the possible GIF decoding modes, and it leaves LZW encoding as an exercise for the reader.  Implement, for example, a ZIP compressor in the language, without yourself relying on an external ZIP library.  I came here hoping to get a WAV parser that permitted viewing the WAV file as arrays of audio data per channel.  I understand the elegance of the concept of making a context-free parser in Python, but real-world file formats contain a great deal of parser state.  For a tour-de-force, try implementing a full audio compression or decompression protocol, such as MP3 or Ogg Vorbis, in it.  I suspect the compressor part cannot practically be implemented in your language as it standard.  Anyway, thanks for your contribution to open source in any case.

**Comment by arekbulski** [comment]
John, you are writing on the wrong forum. You should look for the we-have-everything-you-ever-need-coded repository and post there. Yes, THIS IS A BINARY PACKER.

**Comment by johnwbyrd** [comment]
Actually, I came here looking for a framework that was sufficiently "powerful" for me to implement a WAV parser myself.  But since both the library and its author seem simultaneously pedantic and defensive, I'll follow your advice to the letter.

**Comment by johnwbyrd** [comment]
https://wiki.python.org/moin/LanguageParsing

**Comment by arekbulski** [comment]
We got on the wrong foot, so let me appologize and respond again. Your seem like a troll. I am very particular with what I say, so when you said that library doesnt deliver what it promises it made me boil. Take following words as kind and accurate response, but choose your words carefully when you say to someone who is maintaining a free code that he doesnt deliver what he promised. If you have asked, I would have asnwered. You made accusations, this gets you something else. And there  is nowhere in the docs that says this library promises anything. I know. I wrote the damn docs.

This is a binary packer, not an audio library, not a graphics library, etc. The examples are basic, and I really mean basic. Not to mention unmaintained. They are meant to show how to parse the formats only. There is no one active to even rewrite those examples to new 2.8 syntax, forget about any algorithms that would go with those.

**Comment by arekbulski** [comment]
I could update the docs, saying examples are unmaintained. But I dont think this was your main point.

**Comment by johnwbyrd** [comment]
[Kaitai](http://kaitai.io) is a bit like your project, except it supports more target languages and has a web-based IDE.  I wrote [a WAV parser]( https://github.com/kaitai-io/kaitai_struct_formats/blob/master/media/wav.ksy) for it in an afternoon.  Perhaps you can use my work to write a WAV parser in the construct dsl.

**Comment by arekbulski** [comment]
I have looked at Kaitai when I initially took over this project. Its definately impressive, because it supports more than 1 language, like protobuf for example. I totally agree on that it is formidable alternative to Construct.
