### ISSUE TITLE
RawCopy lost its inputed value in its context with Enum

### ISSUE THREAD

**Issue by potens1** [construct/construct#358]
I'm not sure that I can reproduce this without Enum but:
```
Struct("foo" / RawCopy(Enum(Byte, bar=255)), Probe()).build({"foo":{"value": 255}})
```
If I try this, I expect being able to get the foo.value in the context, but this is set to None
The value is overwritten [here]( https://github.com/construct/construct/blob/881cc323275cf12e368b02c63d1187dbc58ac7de/construct/core.py#L2130) since `self.subcon._build(value, stream, context, path)` is, at the end,
`_write_stream(stream, self.sizeof(), packer.pack(self.fmtstr, obj))` that returns nothing.

Is there a reason to overwrite the input value ?

Feel free to delete the issue if I'm wrong

Edit:

This is the output of the Probe:
```
================================================================================
Probe <unnamed 5>
path is building, func is None
EOF reached
Container: 
    foo = Container: 
        value = None
        data = \xff (total 1)
        offset1 = 0
        offset2 = 1
        length = 1
================================================================================
```

**Comment by arekbulski** [comment]
Why...are you...using...RawCopy...again?

**Comment by potens1** [comment]
Because I need to compute a CheckSum, so I need the rawbytes...

It's not that I love the RawCopy, in fact I utterly hate it (when you build you have add a lot of `{'value':...}` because of it and it seems each time it touch it, I break something)

In fact, I've read what the code do in RawCopy, and at the moment, I'm trying to use Tell and so on to remove all those RawCopy's, only getting the whole buffer is missing me now to to be able to remove all the RawCopy (looking in the doc)

**Comment by potens1** [comment]
Also the doc recommend to use RawCopy instead of manual Bytes extraction ;-)

**Comment by arekbulski** [comment]
Yes that is true :) Extracting the bytes manually would be not a great idea. I just expected RawCopy to contain a Struct with several fields then. Using it on only one Short is erm looked strange.

**Comment by arekbulski** [comment]
Also, you actually found a bug in RawCopy. Fixing it.

**Comment by potens1** [comment]
Starting to understand why working on stream is a bad idea... not so easy to get the stream itself...

**Comment by arekbulski** [comment]
Bug fixed and pushed to HEAD. You need to pull main repository instead of pip upgrading to get the fix.

**Comment by potens1** [comment]
Thx !
