### ISSUE TITLE
How do you support variable length bit fields?

### ISSUE THREAD

**Issue by movermeyer** [construct/construct#359]
I have a bit format that looks something like:

```python
MY_MESSAGE = BitStruct(
    "field_1_exists" / Flag,
    "field1" / If(lambda ctx: ctx.field_1_exists, BitsInteger(3)),
    "field2" #This is a variable amount of bits. How do I represent this?
    "field3" / BitsInteger(3)
)
```
(In reality, it's much more complicated, but the essence is there)

`field2` can be any number of bits from a fixed set of lengths (ex. 10, 138, 266,...,650), but there is no way to know which length it is besides knowing the total number of bits for the whole message and subtracting the sizes of the other fields.

Since `field3` is a fixed size, in a traditional program I'd just do a slice on the bitstring:

```python
field_1_exists = bool(int(my_bitstring[0]))
field1 = int(my_bitstring[1:4], 2) if field_1_exists else None
field2 = my_bitstring[4:-3]
field3 = int(my_bitstring[-3:], 2)
```

How do I represent _"`field2` is all bits after `field1` and before `field3`"_?

**Comment by arekbulski** [comment]
`BitsInteger(len_(this.xxx)) ` can be used.

**Comment by arekbulski** [comment]
How about `BitsInteger(lambda ctx: len(data)*8-?)` where data is bytes.

**Comment by movermeyer** [comment]
My original example was actually missing some complexity. Sorry. There are also optional fields that prevent me from knowing the length of `field2` a priori. I've updated the original question to capture this complexity.

**Comment by movermeyer** [comment]
In the mean time, I've come up with a hack that works, but is ugly:

```python
MY_MESSAGE = BitStruct(
    "field_1_exists" / Flag,
    If(lambda ctx: ctx.field_1_exists, BitsInteger(3)),
    "field2" / Bit[lambda ctx: ctx._['total_bit_length'] - (ctx._['fixed_mandatory_fields_len'] + (3 if ctx.field_1_exists else 0)
    "field3" / BitsInteger(3),
)

context = {'total_bit_length': len(data)*8, 'fixed_mandatory_fields_len': 1+3} #1+3 is 1 bit for `field_1_exists`, and 3 bits for `field3`
MY_MESSAGE.parse(data, context=context)
```

Which works, but is much messier than I was hoping for, especially when I have to duplicate the lengths of the fields.

Is there a cleaner way to do this?

**Comment by arekbulski** [comment]
Two hints for you. (1) Use `this` expressions, more readable than lambdas. See documentation. (2) Add some `Tell` fields and maybe use those to measure offsets, which is what you need.

**Comment by movermeyer** [comment]
Thank you for your patience and help.

Here is what I ended up with:

```python
TRAILER_LENGTH = 3 # length of `field3`, and would include length of other trailer fields if you have them. 
MY_MESSAGE = BitStruct(
    "field_1_exists" / Flag,
    "field1" / If(this.field_1_exists, BitsInteger(3)),
    "bits_so_far" / Tell,
    "field2" / Bit[this._.total_bit_length - (TRAILER_LENGTH + this.bits_so_far)],
    "field3" / BitsInteger(3)
)

context = {'total_bit_length': len(data)*8}
MY_MESSAGE.parse(data, context=context)
```

It's kind of a shame I can't use `Pointer`s within `BitStruct`s, but I understand that it's complicated. If I could, I would be able to remove the 'total_bit_length' as well (something like `'total_bit_length' / Pointer(-1, Tell),`).

P.S.: `this` expressions seems to work fine with the `If` conditional.

**Comment by arekbulski** [comment]
You can put into the context using **kw syntax.
```py
MY_MESSAGE.parse(data, total_bit_length=len(data)*8)
```
Look at  https://github.com/construct/construct/blob/master/construct/core.py#L175

**Comment by hardkrash** [comment]
You can make the length and data a bit cleaned up by making a SubConstruct sub-class.

Here is just the _parse function that looks at the data passed in and computes length for you.

```python
data = b'\xFF' * 2

class MySubConstruct(Subconstruct):
     def _parse(self, stream, context, path):
         context.total_bit_length = len(stream.getvalue()) * 8
         ret = self.subcon._parse(stream, context, path)
         del ret.bits_so_far
         return ret

print(MySubConstruct(MY_MESSAGE).parse(data))
```
Yields
```
Container: 
    field_1_exists = True
    field1 = 7
    field2 = ListContainer: 
        1
        1
        1
        1
        1
        1
        1
        1
        1
    field3 = 7
```
