### ISSUE TITLE
BitStruct Tell increments between calls to `parse`

### ISSUE THREAD

**Issue by movermeyer** [construct/construct#362]
The result of multiple calls to `parse` differs between `Struct` and `BitStruct`.
For `Struct`, the result of `Tell` is unchanged. For `BitStruct`, the result of `Tell` increments with each parse.

**Example code:**
```python
from construct import Struct, this, Byte, BitStruct, Bit, Tell

FORMAT = Struct(
    "my_tell" / Tell,
    "my_byte" / Byte
)

BIT_FORMAT = BitStruct(
    "my_tell" / Tell,
    "my_bits" / Bit[8]
)

for i in range(5):
    byte_result = FORMAT.parse(b'\x00')
print(byte_result.my_tell) # Outputs: "0"
    
for i in range(5):
    bit_result = BIT_FORMAT.parse(b'\x00')
print(bit_result.my_tell) # Outputs: "32"
```

I would have expected the value of my `my_tell` field after a `BitStruct.parse` to always be 0, as it is when using `Struct.parse`.

This affects users when they try to parse multiple objects using the same BitStruct, see #359 for an example of a BitStuct that relies on Tell.

**Comment by arekbulski** [comment]
That is indeed a defect.

**Comment by arekbulski** [comment]
I dont understand why this happens. Tell does only `stream.tell()` and the stream is recreated every time using a new `BytesIO`. I added a unit test, but still didnt figure out how this bug happens.

**Comment by movermeyer** [comment]
> ["also disabling my_byte my_bits makes it pass"](https://github.com/construct/construct/blob/83dfcef3b204fd7fab8b8bc288944f23d8923e47/tests/test_all.py#L1454)

This makes sense since you need something to increment the `tell`, otherwise it will always remain at the default of 0.

**Comment by movermeyer** [comment]
Will there be a new (minor) release sometime to formally release this fix?
Or are there other issues that need to be closed before then?

**Comment by arekbulski** [comment]
Yeah but reality is I got little time to spend on Github lately. I will wait a week or two and let PRs accumulate, and then work it all in one go. Then make a release.
