### ISSUE TITLE
LazyStruct and LazySequence don't use kwargs

### ISSUE THREAD

**Issue by movermeyer** [construct/construct#365]
When using the Python 3.6+ keyword argument syntax to build constructs, building lazy constructs fails.

Example Code:

```python
from construct import Struct, LazyStruct, Byte

MY_STRUCT_NON_KW = Struct(
    "a" / Byte,
    "b" / Byte,
    "c" / Byte,
    "d" / Byte,
)

MY_LAZY_STRUCT_NON_KW = LazyStruct(
    "a" / Byte,
    "b" / Byte,
    "c" / Byte,
    "d" / Byte,
)

MY_STRUCT = Struct(a=Byte, b=Byte, c=Byte, d=Byte)
MY_LAZY_STRUCT = LazyStruct(a=Byte, b=Byte, c=Byte, d=Byte)

print("MY_STRUCT_NON_KW:", MY_STRUCT_NON_KW.parse(b'\x00\x00\x00\x00'))
print("MY_LAZY_STRUCT_NON_KW:", MY_LAZY_STRUCT_NON_KW.parse(b'\x00\x00\x00\x00'))
print("MY_STRUCT:", MY_STRUCT.parse(b'\x00\x00\x00\x00'))
print("MY_LAZY_STRUCT:", MY_LAZY_STRUCT.parse(b'\x00\x00\x00\x00'))
```

gives:

```
MY_STRUCT_NON_KW: Container:
    a = 0
    b = 0
    c = 0
    d = 0
MY_LAZY_STRUCT_NON_KW: <LazyContainer: 4 possible items, 0 cached>
MY_STRUCT: Container:
    a = 0
    b = 0
    c = 0
    d = 0
MY_LAZY_STRUCT: <LazyContainer: 0 possible items, 0 cached>
```

I would have expected the lazy versions to produce the same values as the non-lazy versions.
Especially since [the docs say](https://construct.readthedocs.io/en/latest/api/lazy.html#construct.LazyStruct) they are equivalent and take in kwargs:
> construct.LazyStruct(*subcons, **kw): 
> Equivalent to Struct construct

This is a result of [`LazyStruct`](https://github.com/construct/construct/blob/500e9b5896e48a61747b6ae4202aef21785bfb97/construct/core.py#L2339) and [`LazySequence`](https://github.com/construct/construct/blob/500e9b5896e48a61747b6ae4202aef21785bfb97/construct/core.py#L2489) not using their `kw` parameters at all.

Credits: Discovered with help from [pylint](https://www.pylint.org/)

**Comment by arekbulski** [comment]
Good find! Do you feel up to the challange to fix it? I trust your code.

**Comment by arekbulski** [comment]
I assume you found this in connection to previous topic #359

**Comment by movermeyer** [comment]
No, actually.

As part of my editor ([Atom](https://atom.io/) or [VSCode](https://code.visualstudio.com/)), I run several static analysis tool/linters ([pylint](https://www.pylint.org/), [flake8](https://pypi.python.org/pypi/flake8), [autopep8](https://pypi.python.org/pypi/autopep8)) as plugins.

When I opened the construct code in my editor, the linters raised some interesting warnings, including this one: "Unused argument kw". I then investigated and found that it was actually a bug and reported it.

Most of the credit belongs to pylint.

**Comment by movermeyer** [comment]
As for this bug, I'll give it a shot.

**Comment by movermeyer** [comment]
I've fixed `LazyStruct` (very easy, see #368), but `LazySequence` is a more in-depth change.

Can I leave that to you?

**Comment by arekbulski** [comment]
Of course, thank you for all effort so far.

**Comment by arekbulski** [comment]
Fixed.
