### ISSUE TITLE
Suitable for binary editing without complete knowledge of format?

### ISSUE THREAD

**Issue by rrooij** [construct/construct#371]
Hello,

I'm making a game save editor for one of my favorite SNES games.

https://github.com/rrooij/sd3save_editor

The more attributes to edit I add, the more read and write functions I get since that is the way I constructed the program now. See save.py in my application. I've been looking for a binary editing library to prevent me from reinventing the wheel and found Construct. 

It seems like it will suit my needs. But when I look at the examples, there are mostly formats used that are completely known. Construct seems perfect for formats which are known, but my game save binary contains mostly bytes which purpose are unknown. I only know certain offsets and which value they represent.

However. I found the Pointer and Seek class which will maybe suit my needs. Would you recommend Construct for my purpose or should I rather build something simple for this specific case?

**Comment by arekbulski** [comment]
Sure, you can just Pointers and Bytes/GreedyBytes. I dont see a problem.

**Comment by rrooij** [comment]
Thanks, it works fine with Bytes. I didn't even need to use pointers.
