### ISSUE TITLE
Is there a way to use Greedy* on non last subconst ?

### ISSUE THREAD

**Issue by potens1** [construct/construct#374]
The question is, is there a way to use any of the Greedy* when the Greedy-thing is not the last element of the Struct.
An over simplified example could be:

```python
Struct(
    "start" / Const(b"\x01"),
    "message" / GreedyString(encoding="utf8"),
    "level" / Byte
    "end" / Const(b"\xff")
)
```
This is a simple example, do not pay attention to the fact b'\xff' could be in message or level, let's say it can not, for the example.
Since Greedy* parse until EOF, even if we can know that we must have 3 bytes after it, there is no way to pass the information to say, "be greedy, but stop at seek(-3, os.SEEK_END)"
I've taken GreedyString, but it can be any of the Greedy*.

Is writing a Subconstruct that can limit the stream to be parsed (a la "Prefixed") the way to go ?

**Comment by arekbulski** [comment]
You can write your own classes. What is it exactly that you want?

**Comment by potens1** [comment]
My problem is with some kind of things like this (many different case, GreedyString, GreedyBytes and GreedyRange):
 
```python
baz = Struct(                                 
     "data" / Byte,
     "bar" / GreedyString(encoding="utf8"),
     Const(b"\x01")
)
baz.build({"data":1, "bar": "foo"})
>>> b'\x01foo\x01'
baz.parse(baz.build({"data":1, "bar": "foo"}))
>>> FieldError: could not read enough bytes, expected 1, found 0
```

What I have is mind is to be able to do things like:
```python
baz = Struct(                                 
     "data" / Byte,
     "bar" / GreedyString(encoding="utf8", remainder=1),
     Const(b"\x01")
)
```
Same with the other classes (I know that GreedyString is a function, not a class). It could be event better is the *remainder* could be deduced, but expect it to be a lot of computation if it is even possible.

So in fewer words, the aim is to limit (in size) the stream parsed

**Comment by arekbulski** [comment]
Remainder cannot be a parameter of Greedy or String classes. You would have to add a class analog to Prefixed that reads until `EOF - specified bytes`.

**Comment by potens1** [comment]
Yes, that was what I had in mind. Thank you.
I will comment here what I will be able to get.

**Comment by arekbulski** [comment]
If you ever implement this class, please reopen the thread.
