### ISSUE TITLE
this, in and If -> not expected behaviour 

### ISSUE THREAD

**Issue by potens1** [construct/construct#375]
Hi,

Either the warning in the doc about "Known deficiencies" of the context is not complete, either there is a little bug but it seems *in* keyword is always returning True with *this*.

A PR is ~~coming~~ there #376 for the test case

If you think doc update is enough, I can do that.

**Comment by arekbulski** [comment]
The `this expression` does not support properly the `in` operator. Could you update main docs with a red warning? I also improved the PR.

**Comment by potens1** [comment]
I amended the previously existing warning in doc and made the modifications you asked.

**Comment by arekbulski** [comment]
Fixed.
