### ISSUE TITLE
Terminated tries to parse a bit from BitStruct

### ISSUE THREAD

**Issue by movermeyer** [construct/construct#378]
**Python 2.7 example code:**
```python
from construct import BitStruct, Struct, Terminated

BYTE_FORMAT = Struct(
    Terminated
)

BYTE_FORMAT.parse(b'')

BIT_FORMAT = BitStruct(
    Terminated
)

BIT_FORMAT.parse(b'')
```

**Results:**
```
$ env/bin/python test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    BIT_FORMAT.parse(b'')
  File "env/lib/python2.7/site-packages/construct/core.py", line 165, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "env/lib/python2.7/site-packages/construct/core.py", line 178, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "env/lib/python2.7/site-packages/construct/core.py", line 1785, in _parse
    obj = self.subcon._parse(stream2, context, path)
  File "env/lib/python2.7/site-packages/construct/core.py", line 848, in _parse
    subobj = sc._parse(stream, context, path)
  File "env/lib/python2.7/site-packages/construct/core.py", line 1972, in _parse
    if stream.read(1):
  File "env/lib/python2.7/site-packages/construct/lib/bitstream.py", line 27, in read
    raise IOError("Restreamed cannot satisfy read request of %d %s" % (count, self.decoderunitname))
IOError: Restreamed cannot satisfy read request of 1 bits
```

I expected the behaviour to be the same between `BitStruct` and `Struct`, and that neither should have raise an exception.

If there are no more bits to parse in the stream, `Terminated` should be OK, not raise an exception.

**Comment by arekbulski** [comment]
Holy cow, you seem to have a gift for digging out bugs. On the other hand, come on! does anybody care?! (makes excuses, waves hands...) :rofl:

**Comment by movermeyer** [comment]
It's a gift and a curse 😛 

I care in this case. 

I was trying to make a BitStruct that parsed exactly the right number of bits and no more.

Do you want to tackle this one or should I? My first thoughts are to just wrap the exception.

**Comment by arekbulski** [comment]
God no, you dont fix code by thwarting exceptions. I think you should inspect how RestreamedBytesIO class works, especially how it provides tell() for purposes of Terminated class.

**Comment by movermeyer** [comment]
In this case, it's a difference between the type signatures of `read` between `RestreamedBytesIO` and [`BytesIO`](https://docs.python.org/2.7/library/io.html#io.BufferedIOBase.read).

**Comment by arekbulski** [comment]
I am too busy/bored to fix this project anymore, well, unless its really really important. I would welcome a fix  if you would be willing to provide one.

**Comment by movermeyer** [comment]
No worries. I've gone ahead and made the change. The only usage of `read()` that cared about the number of bits/bytes returned was `_read_stream`, which already throws an Exception if the number of bits/bytes returned is less than it expected.

So this changes the type of Exception returned (`IOError` -> `FieldError`) but besides that, no one will be affected by this change.

**Comment by arekbulski** [comment]
You broken Restreamed instead of fixing Terminated. Long story short.
I understood the problem thanks to you and fixed it by changing Terminated.
Now Terminated classes uses both returned bytes len AND IOError to determine outcome.
