### ISSUE TITLE
TunnelAdapter: zlib

### ISSUE THREAD

**Issue by matwey** [construct/construct#38]
Hi, I am following the example from docs:
```
TunnelAdapter(
    PascalString("data", encoding = "zlib"),
    GreedyRange(UBInt16("elements"))
)
```

In python 3.3, I am getting at parse:
```LookupError: unknown encoding: zlib```

**Comment by arekbulski** [comment]
Compression class has been added, making TunnelAdapter useless.

Regression test was added but fails on PY3. 
https://github.com/construct/construct/commits/issue38

**Comment by harvimt** [comment]
I'm sure someone can think of other uses for TunnelAdapter besides compression. Maybe encryption?

**Comment by arekbulski** [comment]
Sure, but that is just speculation. We should add a class that is good at transforming byte strings between the stream and the subcon. Using other constructs for that is not a good way to go about it.

**Comment by arekbulski** [comment]
I would like to discard TunnelAdapter as it is because it is not an adapter. Adapter is something that transforms objects after they came out of subcon. This works on a different layer, where transformation is done between the stream and subcon. Should be named differently.

**Comment by arekbulski** [comment]
Now there are two abstract classes: Tunnel transforms between stream and subcon, and Adapter transforms between subcon and user.
