### ISSUE TITLE
Python 2.7: ConstructErrors should not be subclassed under Exception

### ISSUE THREAD

**Issue by twooster** [construct/construct#380]
Hi there,

To properly support Python 2.7, the `ConstructError` class should not be subclassed under the `Exception` class, since the convention under Python 2.7 is for "normal" runtime errors to live under `StandardError`. Should be fairly easy fix, and I'm happy to submit a pull-request if you like the fix:

```python
try:
    _BaseExceptionClass = StandardError
except NameError:
    _BaseExceptionClass = Exception

class ConstructError(_BaseExceptionClass):
    pass
```

Thoughts?

**Comment by movermeyer** [comment]
**Disclaimer: I'm not a maintainer**

I've never heard of that. All the docs I've seen seems to indicate that inheriting from `Exception` directly is an OK practice. Do you have any references?

[Docs: Built-in Exceptions](https://docs.python.org/2/library/exceptions.html#module-exceptions)
> The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new exceptions from the `Exception` class or one of its subclasses, and not from `BaseException`.

[Docs: User-defined Exceptions](https://docs.python.org/2/tutorial/errors.html#user-defined-exceptions):
 > Exceptions should typically be derived from the `Exception` class, either directly or indirectly.

**Comment by arekbulski** [comment]
Disclaimer: I am the maintainer.

I never heard of it, and @movermeyer quoted reference that states otherwise.Above that I would have declined it anyway because it adds more code than solves problems.

**Comment by twooster** [comment]
Oh wow. This looks like a holdover from my knowledge of pre-Python 2.5 days and a practice that had never bitten me until now, since it would previously catch `KeyboardInterrupt`s and the like. My apologies. Thanks.
