### ISSUE TITLE
SizeofError for an array with variable length field

### ISSUE THREAD

**Issue by dansheme** [construct/construct#382]
Construct Version: 2.8.12

### The Code
```python
AttributeHandleValuePair = "attribute_handle_value_pair" / Struct(
    "handle" / Int16ul,
    "value" / Bytes(this._._.length - 2)
)

AttReadByTypeResponse = "read_by_type_response" / Struct(
    "length" / Int8ul,  # The size in bytes of each handle/value pair
    "attribute_data_list" / Array(2, AttributeHandleValuePair)
)
```

### The Problem
The following command:

```python
AttReadByTypeResponse.sizeof(Container(length=4)(attribute_data_list=[Container(handle=1)(value=2), Container(handle=1)(value=2)]))
```

Returns the following error:

```
construct.core.SizeofError: cannot calculate size, key not found in context sizeof -> read_by_type_response -> attribute_data_list -> attribute_handle_value_pair -> value
```

### What I Found Out
Running the following code which is not using an array, works just fine. I think the issue is caused only when using an array:

```python
AttributeHandleValuePair = "attribute_handle_value_pair" / Struct(
    "handle" / Int16ul,
    "value" / Bytes(this._.length - 2)
)

AttReadByTypeResponse = "read_by_type_response" / Struct(
    "length" / Int8ul,  # The size in bytes of each handle/value pair
    "attribute_data_list" / AttributeHandleValuePair
)

AttReadByTypeResponse.sizeof(Container(length=4)(attribute_data_list=Container(handle=1)(value=2)))
```

**Comment by arekbulski** [comment]
Its simple, array size is calculated as (subcon size x amount), subcon that is struct size is calculated as (sum of subcons sizes), and 2nd subcon the Bytes(this) is not fixed size, therefore may not be calculable. In some scenarios those do get calculated from context, in some scenarios its just return unknown.

**Comment by arekbulski** [comment]
Also I believe `Bytes(this._.length - 2)` is the correct code here, and double-up is wrong.

**Comment by dansheme** [comment]
Thanks @arekbulski . Any idea for a workaround here?

**Comment by arekbulski** [comment]
If you have the values, use build and just measure the output.

**Comment by dansheme** [comment]
I would agree but in my case I need the `AttReadByTypeResponse.sizeof()` method to work. The `AttReadByTypeResponse` Struct is actually a sub-struct of another struct which uses the .sizeof to compute its own size and storing it in its `length` field.

**Comment by arekbulski** [comment]
You could use RawCopy to obrain byte length of a built struct?

**Comment by dansheme** [comment]
Thanks! Closing the issue.
