### ISSUE TITLE
Array produces wrong order

### ISSUE THREAD

**Issue by winterheart** [construct/construct#383]
Hello.

I have following code on construct 2.8.12:

```python
offset_entry = "offset_entry" / BitStruct(
    "actual_offset" / BitsInteger(24),
    "unknown" / Octet
)

data_dat = "data_dat" / Struct(
    "entries_count" / Int32ul,
    "entries_offset" / Array(this.entries_count, offset_entry),
)
```

If I parse with it my binary, `entries_offset` array will be parsed with wrong order. But, if I change `data_dat` to

```python
data_dat = "data_dat" / Struct(
    "entries_count" / Int32ul,
    "entries_offset" / Int32ul,
)
```
then list will be ordered properly. How can I make Array in that order what it's present in file?

**Comment by arekbulski** [comment]
Just use Struct, BytesInteger(3) and Byte for offset entry?

**Comment by winterheart** [comment]
My bad, didn't read carefully documentation. In my case I need to declare `actual_offset` as little endian.

```python
offset_entry = "offset_entry" / BitStruct(
    "actual_offset" / BitsInteger(24, False, True),
    "unknown" / Octet
)
```

Thank you for reply, anyway!
