### ISSUE TITLE
Importing construct.examples.formats always prints a warning

### ISSUE THREAD

**Issue by catlee** [construct/construct#385]
```
>>> import construct.examples.formats
WARNING: header is skipped not parsed, datetime can be wrong
https://wiki.wireshark.org/Development/LibpcapFileFormat
```

This is from https://github.com/construct/construct/blob/master/construct/examples/formats/__init__.py#L5 importing https://github.com/construct/construct/blob/master/construct/examples/formats/data/cap.py#L32

**Comment by arekbulski** [comment]
I totally dont know this format, so I dont know how to fix it. It was broken for a long long time after 2.8 transition. Dont ask me what is wrong with it, I dont know.

**Comment by catlee** [comment]
I see a few options. We could modify that format to not print a warning on
import, or change the formats module to not import any of the sub-modules.

On Tue, Jul 11, 2017 at 10:56 PM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
Formats module exports those, dont change that. You could change print to a comment, but then you create a risk that someone will not notice the problem and use the code willy nilly.

**Comment by catlee** [comment]
The problem is that importing unrelated examples also produces this warning
output, which is confusing. e.g.

```
from construct.examples.formats.executable import pe32
```

On Tue, Jul 11, 2017 at 11:05 PM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
Ah yeah, good point. Go ahead and turn it into a CAPITAL comment then? I will accept it.
