### ISSUE TITLE
Using compression on bitstructs

### ISSUE THREAD

**Issue by tomSh3p** [construct/construct#387]
Could the documentation be improved to state that compression can't be used within a bitstruct? From several hours of debugging I realise this isn't possible with the current architecture of construct.

The error it raises isn't too helpful either.

_parse in the Tunnel class calls stream.read(), however the stream at this point is a RestreamedBytesIO object which overrides read with a requirement for an additional argument. This causes an incorrect number of arguments errors to be raised.

It makes sense that this doesn't work as Compressed consumes the rest of the entire stream which at the time might not be byte aligned causing issues for the compression library/codec. I'm assuming nearly all compression/codec libraries assume they'll be working on streams of entire bytes. I guess potentially putting a length field (which must be byte aligned) on Compressed could solve this.

Thank you for creating/supporting a great library.

**Comment by arekbulski** [comment]
I am not sure what you mean by comprehension? What is it? Could you also show me some code, if convenient?

**Comment by arekbulski** [comment]
Why would anybody use any tunnels with bitstruct? Bitstruct works in very gimmicky kind of way, most classes you find in Construct wont work there. I would not use bitstructs with anything more than integers.

**Comment by arekbulski** [comment]
Warning added, although not in red:
https://construct.readthedocs.io/en/latest/bitwise.html#important-notes

**Comment by tomSh3p** [comment]
Thanks for the fast response.

It's not actually compressed, it's encrypted, so I wrote my own codec that did the encryption/decryption which works on bytes not bits. It's a tightly packet stream and is pretty much all ints/enums. Unfortunately the padding to 'fix' the byte alignment is done at the end after the encryption.

Potentially a new construct to do encryption could be the solution.

**Comment by arekbulski** [comment]
Oh I was going to add Encryption and Authentication classes to Construct, but ultimately I have too much paid work to do atm. But I might implement it some day.

**Comment by arekbulski** [comment]
You should check out Bytewise.
