### ISSUE TITLE
building failed for BitField with dynamic length

### ISSUE THREAD

**Issue by tdsparrow** [construct/construct#39]
With construct 2.5.1
>>> s = Struct('test',UBInt8('len'), EmbeddedBitStruct(BitField('data', lambda ctx: ctx.len)))
>>> s.build(Container(len=8, data=1))
....
....
    114         if number < 0:
    115             number += 1 << width
--> 116         i = width - 1
    117         bits = ["\x00"] * width
    118         while number and i >= 0:
TypeError: unsupported operand type(s) for -: 'function' and 'int'

**Comment by arekbulski** [comment]
This seems to have been patched a long time ago. Added regression test in a4eb0530bdad1b998e05762d45f9da7a1cdd30db.
