### ISSUE TITLE
FocusedSeq appears to alter previous values

### ISSUE THREAD

**Issue by Jaguar83** [construct/construct#397]
In writing my program with construct, I've come upon an interesting bug. I'm not sure if the bug was created by my code, or if the bug exists in construct.

What appears to happen is that, as the parsing proceeds through the sub-constructs, the parent construct is modified instead of the current one.

The error seems to occur at core.py:2064
```
        for i,sc in enumerate(self.subcons):
            parseret = sc._parse(stream, context, path)
            context[i] = parseret
            if sc.name is not None:
                context[sc.name] = parseret
            if i == index:
                finalobj = parseret
```
At this point, context appears to reference the parent context rather than a new sub-context and therefore context[i] is the first item of the parent, not the current.

I have attached the program that is experiencing the issue. If you set a breakpoint on nbt2.py:104 ("isType0") and inspect the context at each step, you will see the first item in the context ("type") changing with each call.

I've updated to 2.8.14 and the issue is still present.

[test1.zip](https://github.com/construct/construct/files/1269258/test1.zip)

**Comment by arekbulski** [comment]
I would not know how to manually debug this. I need you to submit a PR with a proper automated unit test. And I suspect that the issue might be with Struct/Sequence nesting context (which is buggy like fuck) rather than FocusedSeq itself which is simple like a bone.

**Comment by arekbulski** [comment]
I assume this thread was abandoned. Please reopen otherwise.
