### ISSUE TITLE
Indexing with names instead of numbers

### ISSUE THREAD

**Issue by marnunez** [construct/construct#400]
Basically, I'm putting an Array on a Struct like this:

```python
header = Struct(
	"headerInfo" / header_info,
	"blocks" / Array(this.headerInfo.nEntries,jump_table_entry)
	)
```
meaning after doing `f = header.parse(myStringHere)` I can access the blocks as `f.blocks[i]`

However, each jump_table_entry has a field called 'label'. Is there a way for me to access the blocks as `f.blocks.thisLabel`, `f.blocks.thisOtherLabel`, etc instead of as  `f.blocks[i]`? Which Container should I use?

**Comment by arekbulski** [comment]
You should show more code because I have no idea what tableentry is made of.

**Comment by marnunez** [comment]
Sure! Something like this:
````python
jump_table_entry = "jump_table_entry" / Struct(
	"type" / Enum(Int32ul,
		option0 = 0,
		option1 = 1,
		option2 = 2,
		option3	= 3,
		option4	= 4,
		),
	"offset" / Int32sl,
	"size" / Int32sl,
	"creationDate" / DateAdapter(Int32ul),
	"lastModificationDate" / DateAdapter(Int32ul),
	"lastAccessDate" / DateAdapter(Int32ul),
	"reserved0" / Padding(Int32ul.sizeof()),
	"comment" / String(256),
	"entry" / Pointer(this.offset,
		Embedded(Switch(this.type,
		{
			'option0': option0Block,
			'option1': option1Block,
			'option2': option2Block,
			'option3': option3Block,
			'option4': option4Block,
		},default=escapeDataBlock)))
	)

header_info = Struct(
	"version" / Int32ul,
	"nEntries" / Rebuild(Int32sl,len_(this._.blocks)),
	)

header = Struct(
	"headerInfo" / header_info,
	"anotherField" / String(10),
	"yetAnotherField" / String(10),
	"blocks" / Array(this.headerInfo.nEntries,jump_table_entry)
	)
````

The idea is the following: when I do `f = header.parse(miFile)` I get, as expected, a header structure with some fields and a list of blocks (each a jump_table_entry). To access each corresponding block, I have to do `f.blocks[index]`. Yet each block has a "type" field, with it's name on it ('Option1', 'Option2', etc). How could I access each block by doing this?:

f.blocks.Option1

**Note**: there's never two blocks of the same type. That's why I'd like to access them by name, like in a dictionary, instead of a list.

**Comment by arekbulski** [comment]
Maybe use Computed to create aliases?
eg. `"option1" / Computed(this.options[1])` or something like that

I would suggest using Int for "type" without playing around with Enums, simpler is better.
Also a warning, Embedded and Switch can be safely combined but many problems had issues with this combination and I would advise to avoid it. 
Also noticed that you are mixing signed and unsigned fields, maybe just use Int short?

**Comment by marnunez** [comment]
Computed aliases could do, I'll give it a try! I don't think adapters would work either. Regarding Embedding a Switch, I'll be on the look, but it seems to work fine for the time being. The 'type' Enum has bogus options, in the real case, 0 is not "option0". The signed and unsigned fields are actually a byproduct of the same cleanup I made for posting the example.
