### ISSUE TITLE
byte order with bitmaps

### ISSUE THREAD

**Issue by dberansky** [construct/construct#402]
I have a structure that's defined like the following:

    "misc" / BitStruct(
        "charging_status" / BitsInteger(3),
        "battery_level" / BitsInteger(7),
        "brightness" / BitsInteger(6)
    ),

These two bytes of data are written by a C program running on little-endian architecture.  In the code, uint16 is declared and individual bits are set and then written out as is.  Now, when I parse this data using construct, I get garbled data.  I believe that's because construct reads BitStruct in network order.  Is there a way I can specify that the underlying 16 bits are actually in little-endian format?

**Comment by marnunez** [comment]
I believe you can do that by using swapped=True inside BitInteger

**Comment by dberansky** [comment]
that's what I thought too, but when I tried that I got an error: data length must be multiple of linesize.  I believe swap can only be used when the bit field aligns on a byte boundary.

**Comment by arekbulski** [comment]
Depends on how the little endianess is done, perhaps ByteSwapped?

**Comment by dberansky** [comment]
Ah, yes!  ByteSwapped was it.  Thanks!  I didn't see it in the docs.
