### ISSUE TITLE
Is there a way to compute the crc of a binary message?

### ISSUE THREAD

**Issue by mgiaco** [construct/construct#403]
Hi,

Let say I do have this construct definition:

``` python

message_format = "message_format" / Struct(
    "receiver_addr" / Int8ul,
    "source_addr" / Int8ul,
    "datalen" / Int8ul,
    "flag" / Enum(Byte,
                  ACK=(1 << 0),
                  READY=(1 << 1),
                  REJECT=(1 << 2),
                  OVER_CURRENT=(1 << 3),
                  ACK_REQUEST=(1 << 4),
                  OVER_TEMPERATURE=(1 << 5),
                  RELAY_ON=(1 << 6),
                  ERROR=(1 << 7)),
    "command" / Int8ul,
    "payload" / If(this.datalen > 2, Array(this.datalen - 2, Byte)),
    "crc" / how to compute ??)

```

So I would like to compute the crc byte wise from reciever_addr to the last byte of the payload. I try to use compute but for me it is not clear how to compute bite wise. So I am not sure if this is possible.

By the way is there any better mechanism for the payload? I do have payload or no payload depends on the length. If the datalen is 2 i do have flag and command but no payload if the datalen is 3 or more i do have a payload with 1 or more.

many thanks

**Comment by arekbulski** [comment]
You can use Checksum and RawCopy classes. And some suggestions:
Int8==Byte 
Array can be made with syntax Byte[this.datalen-2].

**Comment by mgiaco** [comment]
@arekbulski  can I found any example for checksum and raw copy class. 
thx

**Comment by arekbulski** [comment]
In main documentation (readthedocs) and also in classes docstrings.

**Comment by mgiaco** [comment]
many thanks
