### ISSUE TITLE
got "KeyError: None" after upgrade to 2.8

### ISSUE THREAD

**Issue by timercrack** [construct/construct#405]
hi,
    Thanks for your awesome library, this saves me a lot of work in implementing complex protocols!
I managed to upgrade to 2.8 and rewrite my code use the new syntax through document. After rewrite & debug for three days there is still one problem I can't resolve, could you please help me!

### protocol
```python
iec_104 = "iec104" / Struct(
  Const(b"\x68"),
  "length" / Rebuild(Byte, lambda ctx: 4+int(len(ctx.ASDU) if 'ASDU' in ctx else 0)),
  "APCI1" / ExprAdapter(
      Default(Int16ul, None),
      encoder=lambda obj, ctx: obj if isinstance(obj, UFrame) else 1 if obj == "S" else obj << 1,
      decoder=lambda obj, ctx: obj >> 1 if obj & 1 == 0 else "S" if obj & 3 == 1 else UFrame(obj),
  ),
  "APCI2" / ExprAdapter(
      Default(Int16ul, None),
      encoder=lambda obj, ctx: 0 if obj is None else obj << 1,
      decoder=lambda obj, ctx: obj >> 1,
  ),
  # THE PROBLEM CODE
  If(lambda ctx: not isinstance(ctx.APCI1, UFrame) and ctx.APCI1 != 'S', ASDU_Part) 
)
```
full source code attached and online version [here](https://github.com/timercrack/pydatacoll/blob/construct2.8-update/pydatacoll/protocols/iec104/frame.py) 
the protocol is [IEC 60870-5-104](https://en.wikipedia.org/wiki/IEC_60870-5#IEC_60870-5-104)

### test code

```python
frame = Container(APCI1=1, APCI2=2, Cause=Cause.introgen, ASDU=Container())
frame.ASDU.data = [Container()]
frame.ASDU.TYP = TYP.M_SP_NA_1
frame.ASDU.StartAddress = 10
frame.ASDU.data[0].address = 5
frame.ASDU.data[0].value = 1
build = iec_104.build(frame)
```

### output
```Cython
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/jeffchen/Documents/gitdir/pydatacoll/test/test_iec104_frame.py", line 30, in test_M_SP_NA_1
    build = iec_104.build(frame)
  File "/Users/jeffchen/virtualenvs/pdc/lib/python3.6/site-packages/construct/core.py", line 191, in build
    self.build_stream(obj, stream, context, **kw)
  File "/Users/jeffchen/virtualenvs/pdc/lib/python3.6/site-packages/construct/core.py", line 205, in build_stream
    self._build(obj, stream, context2, "(building)")
  File "/Users/jeffchen/virtualenvs/pdc/lib/python3.6/site-packages/construct/core.py", line 2713, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/Users/jeffchen/virtualenvs/pdc/lib/python3.6/site-packages/construct/core.py", line 866, in _build
    subobj = obj[sc.name]
KeyError: None
```

[full protocol source file](https://github.com/construct/construct/files/1346326/protocol.py.zip)

**Comment by arekbulski** [comment]
I dont understand your code, but one thing is strange. `None` is not a valid value for `Int*` so:
```py
Default(Int16ul, None)
```

**Comment by timercrack** [comment]
I use a ExprAdapter around Default(Int16ul, None), so it will first run the encoder code and can't return None.
You can reproduced the error with the simplified code as fellow: 
```python
extra_part = "extra" / Struct(
    "data" / Byte,
)
test_struct = "test_struct" / Struct(
    "head" / Int16ul,
    If(lambda ctx: ctx.head != 0, extra_part)  #  <-- got the same error as original code
)
frame = Container(head=1, extra=Container())
frame.extra.data = 1
build = test_struct.build(frame)
```

**Comment by arekbulski** [comment]
The If member still needs to be named ("extra"). 
```py
"extra" / If(lambda ctx: ctx.head != 0, extra_part)
```
You can also simply building:
```py
test_struct.build(Container(head=1, extra=Container(data=1)))
```

**Comment by arekbulski** [comment]
Some explanation, KeyError None is because a Struct checks if the 2nd subcon has a flagbuildnon (which it does not) in which case it looks up the dict usings subcons name as index (which is None in this case). The dict obviously doesnt have such a key.

**Comment by arekbulski** [comment]
You can also use Embedded(If(...)) if that makes whatever easier for you. Just FYI.

**Comment by timercrack** [comment]
The protocol I implemented has three types of frame: S-frame, U-frame and I-frame, where only I-frame has extra part(the ASDU_PART), S and U don't. So I left the "If" unnamed in order to build S and U frame without need to specify the ASDU part. This works fine on old construct library. So I don't think the upgrade can change my code's behavior.
Thank you for your reply! I will use the Embedded(If(...)) method as you suggested, but it means when I build I-frame I need to pass the extra param to main dict directly, not as an extra dict. I have to do some reconstructions on my project to fit this.
