### ISSUE TITLE
How to limit GreedyBytes/to check if its length equals to an expected value received via an other I/O transfer

### ISSUE THREAD

**Issue by malinoff** [construct/construct#407]
Hello. First of all, thank you for your awesome library. Bytes crunching truly made fun ;)

I'm working on AMQP client implementation. If you aren't aware, AMQP is based on frames, and has two interesting frame types: `ContentHeaders` and `ContentBody`. Below are a not-so-accurate structs for these frames:
```python
BasicProperties = [
    'content_type' / PascalString(Int8ub, encoding='utf-8'),
    ...  # skipped the rest for brevity
]
ContentHeaderPayload = Struct(
    'class_id' / Int16ub,
    'weight' / Const(Int16ub, value=0),
    'body_size' / Int64ub,
    'property_flags' / BitStruct(*(
        subcon.name / Flag for subcon in BasicProperties
    )),
    'property_list' / Struct(*(
        subcon.name / If(this[subcon.name], subcon)
        for subcon in BasicProperties
    )),
)
ContentBodyPayload = Struct(
    'content' / GreedyBytes,
)
Frame = Struct(
    'frame_type' / Enum(
        Int8ub, method=1, header=2, body=3, heartbeat=8,
    ),
    'channel_id' / Int16ub,
    'payload_size' / Int32ub,
    'payload' / Switch(
        this.frame_type, cases={
            1: MethodPayload,
            2: ContentHeaderPayload,
            3: ContentBodyPayload,
            8: HeartbeatPayload,
        }
    ),
    'frame_end' / Const(Int8ub, FRAME_END),
}
```
`ContentHeader` is received first, then 0 or more `ContentBody` frames.
As you can see, `ContentHeaderPayload` has `body_size` field, which is used to determine how much "content" bytes should be read when `ContentBody` frame is received.
So my question is: is there a way to provide a length to `GreedyBytes` in run time to validate the content length?

**Comment by arekbulski** [comment]
Seems like obvious case for `Prefixed`.

**Comment by malinoff** [comment]
@arekbulski I don't follow how `Prefixed` helps in this case. Content itself is sent as is, without prefixed length. Even more, `body_size` can be much larger than the max frame size. In that case there will be multiple`ContentBody` frames, and we should chunk `body_size` by the max frame size.
Could you provide an example?

**Comment by arekbulski** [comment]
Then maybe `GreedyRange(...)` that parses until EOF?

**Comment by malinoff** [comment]
It would work, of course. But how can I validate that the parser parsed exactly `body_size` bytes? I don't need to know `body_size` to parse the content, it exists mainly for two reasons:
a) buffer allocations in a low-level language like C, and
b) run time validation that the content is fully received (i.e. combined from multiple chunks received asynchronously over time)

**Comment by arekbulski** [comment]
Ah actually I was thinking of `Bytes(this.somefield)` not `Prefixed`.

**Comment by malinoff** [comment]
I don't actually have `somefield` :) I've received it some time ago, via an other network transmission, and now I only receive chunks of "raw" bytes of `somefield` length, combined.

**Comment by malinoff** [comment]
@arekbulski why have you silently closed this ticket without any further discussion?

**Comment by arekbulski** [comment]
Its 3 weeks old and I dont see any reasons to keep it open. You can reopen it if you want to. But is there a reason to have it open?

**Comment by malinoff** [comment]
> I dont see any reasons to keep it open
How about answering the question? Or maybe discussing possible solutions to the problem?

Even a simple "I neither have time nor interest in resolving this issue" kind of a comment would look nicer than a silent close.

**Comment by malinoff** [comment]
I respect everyone else's time, especially open-source maintainers/contributors time, that's why I usually do not push issues I create. I'm usually okay to wait a couple of days, even weeks or months (otherwise the issue really hurts me and I'd rather fix it by myself and make a pull request), but I would expect to get an answer if I leave a message.

**Comment by arekbulski** [comment]
Sorry, people so often paste their entire codes (which are long and elaborate) and then ask very general questions which do not have simple clear answers and those threads then just hang for months... I just assumed this one was an instance of that.

Please restate your question, in short?

**Comment by arekbulski** [comment]
And geez please do not at/mention me, I always get notifications.

**Comment by foobarna** [comment]
If I may: what @malinoff needs is a `ContentBodyPayload` with a variable `content` in the sense that it modifies after each `Frame` of `type 2`. So, having some `Bytes(<len>)` would be the first thing to try, but it needs to be lazy evaluated, so that for each `Frame` of  `type 2` you save the `body_length` so you can take it for the next `Frame` of `type 3`.
Maybe this is what you are looking for http://construct.readthedocs.io/en/latest/lazy.html

**Comment by malinoff** [comment]
Yes, it looks like some sort of parametrized lazy field would work.

**Comment by arekbulski** [comment]
I assume this was just solved and thread is hanging.
