### ISSUE TITLE
Modifying Constructs after construction

### ISSUE THREAD

**Issue by catern** [construct/construct#408]
I have some large nested Structs. I would like to modify one of the fields to be parsed/built in a slightly different way. (Maybe change the Construct it's parsed/built with, maybe wrap it with an adapter, maybe something else).

Is there any easy way to do this? Is it OK to just mutate the subcons/subcon fields directly? I didn't see this in the documentation, but maybe I missed it.

These Structs are automatically generated from some JSON descriptions of binary files, but those JSON descriptions are fairly primitive and not much better than C headers, so for e.g. variable length fields or fixed fields I would like to modify them after the fact to add that extra information in Python.

**Comment by arekbulski** [comment]
Yes, Struct.subcons field can be mutated pretty much any way you want. It just must contain Construct instances but you can mutate the list yourself.

**Comment by arekbulski** [comment]
You can also take subcons from one Struct instance and use them to create another Struct instance. Member subcons are made immutable so they can be shared. Like
```py
st2 = Struct(*st.subcons)
```
