### ISSUE TITLE
What exceptions can construct throw?

### ISSUE THREAD

**Issue by fake-name** [construct/construct#411]
Basically, I assume construct has a set of structured exceptions, but I can't find anything about it in the documentation.

Looking in `core.py`, I found what I needed, but it'd probably be a decent idea to have the exception tree in the documentation *somewhere*.

Ideally, the "Raises: nnnn" section for each function should have "nnnn" link to the relevant exception. right now, the exceptions are not links.

The search function for "exception" is less then helpful as well: https://readthedocs.org/projects/construct/search/?q=exception

**Comment by arekbulski** [comment]
Well, the excepion hierarchy is in core, and you can read each class code for what it can throw. For this level of detail, I would not write elaborate docs. Also some docstrings have "raises" which produces some documentation hints.

**Comment by fake-name** [comment]
My point is mostly that I'd expect to not have to go digging in the source to figure out what the root exception class is.

**Comment by arekbulski** [comment]
I never seen those as too important as far as documentation is conserned.

**Comment by arekbulski** [comment]
@fake-name I feel like I should appologise for being too dismissive about your post, and probably for being rude as well. I am working on extending documentation and revisiting your complaint. I may add a page about exception types, among other things. See #438

**Comment by fake-name** [comment]
It's not a big deal, I assumed you just have to triage a lot of reports.

**Comment by arekbulski** [comment]
Actually that is not the case. Usually there is ~0 open tickets at any given time (not counting my own, those are just TODO). And I admit, that is no reason to be rude either.

**Comment by arekbulski** [comment]
The docs site was overhauled, errors are listed in Core API pages.
