### ISSUE TITLE
Array requires stream to be tellable

### ISSUE THREAD

**Issue by yannayl** [construct/construct#413]
Array requires a `tell`able stream, even though it is usually not an issue.

For example:
```python
f = open("/dev/urandom", "rb")
print Byte[10].parse_stream(f)
```
Raises a RangeError:
`RangeError: expected 10 to 10, found 1`

This is because the underlying [implementation](/construct/construct/blob/a83f5988b122a759fe66fe0b65193999f4b1c228/construct/core.py#L1125) of a fixed arrays is `Range` which [tries to `seek` the stream](/construct/construct/blob/a83f5988b122a759fe66fe0b65193999f4b1c228/construct/core.py#L1047)  back to a saved location in case of exception. To do so, it tries to save the last good position using [`tell`](/construct/construct/blob/a83f5988b122a759fe66fe0b65193999f4b1c228/construct/core.py#L1037). This attempt throws an exception if the stream does not support `tell` (even if nothing is wrong with the incoming data).

I think this behavior can be improved, just let the user take care of error if the stream can't be reset.

**Comment by arekbulski** [comment]
You see, its not a bug. Range parse does not have a fixed number of elements, but a bracket. When is the last element, is determined either by EOF or being unable to parse next element. In which case, since it had to consume some bytes to even attempt reading next element, it needs to seek back. Thats just how it was designed.

**Comment by arekbulski** [comment]
I eat my own words. Array will be reimplemented soon, this is a valid issue...

**Comment by arekbulski** [comment]
Array was reimplemented and does not use stream.tell().

**Comment by yannayl** [comment]
Cool :+1:

FTR: I don't think it was a bad idea to try and seek back (maybe support optional subcon?). I Just think in case the stream is not tellable or seekable, throw the exception only if it actually failed and let the user handle it. But I see it complicates the implementation so NVM.

**Comment by arekbulski** [comment]
It will be included in next release, I am working so hard on this project atm that I make daily releases.

**Comment by arekbulski** [comment]
BTW, I could use some input int #527  but its unrelated.

**Comment by yannayl** [comment]
Great work! I really appreciate it. Currently I'm not using construct (left the project I was involved in). But I still really really love the project! I will try to take a find some time to look at it (it's 2am on this end).
