### ISSUE TITLE
Clarify that 2.8 is incompatible with 2.5.

### ISSUE THREAD

**Issue by mrolle45** [construct/construct#414]
Your documentation does make it clear that 2.8 has many differences with 2.5.  However, I made the mistake of assuming that 2.8 would be forward compatible.  So perhaps you might say right at the start that 2.5 is not forward compatible with 2.8.
When I first posted this issue, I had problems with another package (pdbparse from PyPI) that uses construct 2.5, but I had installed construct 2.8.  I thought it was just a matter of a few names from 2.5 (such as ULInt32) being missing in 2.8.  I also didn't realize that pdbparse was in fact built on construct 2.5.  I tried installing construct_legacy 2.5 from PyPI, but this didn't work since I couldn't figure out how to import construct_legacy and pretend that it was called construct.
Then I discovered that construct 2.5 is still downloadable, so I downloaded and installed 2.5 and now everything is working fine.

Now I do wonder what happens if a project is using two external packages with the same name but different and incompatible versions.  For example, if my new project wants to use construct 2.8, but it also uses pdbparse, which uses construct 2.5, how is this problem managed?  In fact, now that I have discovered the power of construct, I may indeed be doing this in the future.  This is a general Python question, not for the construct package to be concerned about.  Anyone have some tips about this situation?

Does anyone know how to set up my Python environment so that when I say `import construct`, it imports `construct_legacy` _and_ stores the module under the `construct` name as well?

**Comment by arekbulski** [comment]
It says on both wiki and readme, in BOLD FUCKIN RED that "2.5 is legacy" and that "most classes changed interface and implementation". On the wiki, there is a Transition page that is long and only a summary at that. Relevant screenshot. 
![zrzut ekranu z 2017-12-06 20-18-47](https://user-images.githubusercontent.com/5385838/33677896-921f7ae6-daba-11e7-9052-8d62aab3b1bc.png)

Regarding how to import both versions from same script, that is a good question. I suppose you could have to differently named folders and import them both?
```py
import construct 
import construct_legacy as construct_legacy
```
