### ISSUE TITLE
Regression from enum rework

### ISSUE THREAD

**Issue by rytilahti** [construct/construct#416]
Hi,

looks like the newest release breaks something which used to work in 2.8.16:

* https://github.com/rytilahti/python-miio/pull/140
* https://github.com/home-assistant/home-assistant/issues/11048 (experiences)

I was able to bisect the breakage to this commit: https://github.com/construct/construct/commit/3c6714d22a55656e265a8d4cd43e6aaeab4c7641 .

Any ideas what is the best approach to fix it? The corresponding code is in https://github.com/rytilahti/python-miio/blob/master/miio/protocol.py#L193 . 

As that information is not really used in my code, I could just remove the enum and leave it to be a non-capture 16b value, however I thought it's worth reporting as it may break also code of others.

**Comment by rytilahti** [comment]
I agree with that notion, I think i could've left out the links (although it gives a reference for those who at some point may stumble upon a similar problem).

Printing out the container contents reveals the following:
```
        value = Container: 
            length = 32
            unknown = 0
            devtype = default (total 7)
```
vs. with 2.8.16:
```
        value = Container: 
            length = 64
            unknown = 0
            devtype = 742

```

which I assume is the cause. I will create a minimal working example for testing later.

**Comment by arekbulski** [comment]
Yes, it used to put value into context dict, now it puts labels. That is exactly what was changed in Enum behavior. :) Its a bugfix, not a bug.

**Comment by rytilahti** [comment]
Yup, here's a minimal working example:
```
from construct import Enum, Default, Pass, Int16ub

x = Enum(Default(Int16ub, 0x02f2), default=Pass, test=0x02f2)
existing = x.build(0x02f2)
print(existing)
parsed = x.parse(existing)
print(parsed)
non_existing = x.build(0x02f3)
print(non_existing)
```

and outputs;
2.8.16:
```
$ python test.py
b'\x02\xf2'
test
b'\x02\xf3'
```
and 2.8.17:
```
$ python test.py
b'\x02\xf2'
test
b''
```

But as you said it's an expected behavior, so I'm closing this bug.

Thanks for your input and your work on this awesome library!

**Comment by arekbulski** [comment]
You should use `assert parse(...) == expected` instead of prints.

**Comment by rytilahti** [comment]
Indeed, I just prepared it very quickly to see what are the outputs. Do you want that I prepare a proper unit test for this?

**Comment by arekbulski** [comment]
No, this is not a bug so no need.

**Comment by fanthos** [comment]
I think changes like this(might break things) should only happened in bigger version change, like 2.9.0, but not 2.8.17.
