### ISSUE TITLE
LazyStruct does not support values with types computed using other fields

### ISSUE THREAD

**Issue by yannayl** [construct/construct#417]
```python
import construct as cs
assert cs.Struct(
    "len"/cs.Int8ul,
    "val"/cs.Int8ul[cs.this.len],
).parse(b"\x01a").val[0]  == ord('a')
## works
assert cs.LazyStruct(
    "len"/cs.Int8ul,
    "val"/cs.Int8ul[cs.this.len],
).parse(b"\x01a").val[0]  == ord('a')
## throws an exception
```

The LazyStruct is using a regular (non-lazy) container for the context when parsing. Therefore, if a field within the LazyStruct requires another field deriving it's type (e.g. array length) an exception is thrown when parsing.

**Comment by arekbulski** [comment]
Yeah, that is a shortcoming of Lazy classes. I dont think I can do much about it other than put a warning in Lazy docstrings that its so.

**Comment by yannayl** [comment]
Yeah, I tried to solve it but it wasn't so trivial so I thought maybe brainstorming can help.

Can't it be solved by putting LazyContainer as context when parsing? (and if it recurses to Infiniti, so be it)

**Comment by arekbulski** [comment]
Its impossible for LazyStruct (or even Struct) to detect if a particular member depends on context like "val" or is context-indepenedent like "len". Only way to make it work is parse all members non-lazily.
