### ISSUE TITLE
"nvalid command name" when run build.sh

### ISSUE THREAD

**Issue by damaswangsa** [construct/construct#421]
after i run preinstall.sh and got message like this
```
damaswangsa@damaswangsa-Lenovo-ideapad-500S-14ISK:~/construct-2.8.17$ ./preinstall.sh 
The directory '/home/damaswangsa/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/damaswangsa/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages
```
and i move to build.sh and got this
```
damaswangsa@damaswangsa-Lenovo-ideapad-500S-14ISK:~/construct-2.8.17$ ./build.sh 
'nvalid command name 'register
'nvalid command name 'upload
'nvalid command name 'upload
'nvalid command name '
```
what's wrong with it?, i try to look in issues but didnt find any suggest
anyone can explain me? how to fixed it?

**Comment by arekbulski** [comment]
Those are old script files that belong to previous developer, I was going to remove them. You dont need to build the project anywya, just pip install it. If you want to have a HEAD copy instead, probably git cloning the repo is fine too.

**Comment by damaswangsa** [comment]
in [gr-satellites](https://github.com/daniestevez/gr-satellites) mention that construct is one of the required dependencies before use [gr-satellites](https://github.com/daniestevez/gr-satellites). so i just doing git clone without build the project?
before i run **build.sh** i have installed : 
`sudo apt-get install python-pip`
and
`pip install pip`
is my step right? or any suggest?

**Comment by arekbulski** [comment]
I admit that there is no explicit instructions in the readme but yes, you just pip install it. I think you meant `pip install construct`. If that project is on pypi, it can change its manifest to add prerequisits so pip installs both.

**Comment by damaswangsa** [comment]
ok, i'll try it, thank you for help

**Comment by arekbulski** [comment]
I removed those build files, so topic is closed.
