### ISSUE TITLE
utf-16-le string decoding crashes on python 3.5

### ISSUE THREAD

**Issue by kak-bo-che** [construct/construct#424]
I may be missing something here but it appears that 'utf-16-le' decoding fails on a simple example.
```python
>>> String(10, encoding='utf-16-le').parse(b"h\x00e\x00l\x00l\x00o\x00")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venv/lib/python3.5/site-packages/construct/core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/home/user/venv/lib/python3.5/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/user/venv/lib/python3.5/site-packages/construct/core.py", line 311, in _parse
    return self._decode(self.subcon._parse(stream, context, path), context)
  File "/home/user/venv/lib/python3.5/site-packages/construct/core.py", line 3343, in _decode
    obj = obj.decode(encoding)
  File "/home/user/venv/lib/python3.5/encodings/utf_16_be.py", line 16, in decode
    return codecs.utf_16_be_decode(input, errors, True)
```
Whereas if I swap the order and decode 'utf-16-be'
```python
>>> String(10, encoding='utf-16-be').parse(b"\x00h\x00e\x00l\x00l\x00o")
'hello'
```

**Comment by arekbulski** [comment]
If you had looked at the documentation, there is a warning to not use >1 byte encodings like UTF16. It mentions CString explicitly but the problem is with string classes in general.
https://construct.readthedocs.io/en/latest/advanced.html#strings
I will edit the warning in docs.

**Comment by kak-bo-che** [comment]
I see you updated the documentation for String to be similar to CString. After your update I would not expect this to work.

**Comment by arekbulski** [comment]
I am revising this issue, after  next release which will be few days from today, CString will be supporting UTF16 UTF32. But not sure if String could do that, its erm tricky to implement.

**Comment by arekbulski** [comment]
UTF16 UTF32 support was added to all String classes, available in next release.
