### ISSUE TITLE
Importing C/C++ headers structs

### ISSUE THREAD

**Issue by Scony** [construct/construct#427]
Hi, I am wondering if construct provides some mechanism to transform raw headers from C/C++ into construct code in python?

**Comment by arekbulski** [comment]
Nope, not even remotely possible. You need CFFI or Cython to interface with C code.

**Comment by harvimt** [comment]
You could interface with pycparser to parse the header files, then turn
them into construct parsers.

It would probably be faster to do it by hand, and there would be a lot of
edge cases.

**Comment by arekbulski** [comment]
...and it would compeletly miss the point of this library scope.

**Comment by arekbulski** [comment]
There was a discussion on Kaitai forum about adding Construct<->Kaitai import/export tool.
