### ISSUE TITLE
deprecation period instead of sudden API changes

### ISSUE THREAD

**Issue by rytilahti** [construct/construct#428]
Hi,

it would be nice to have some sort of grace period before doing heavy API changes. This would allow downstream users of the library to update (and especially ship fixed versions to users!) without having to resort to adhoc patching 
https://community.home-assistant.io/t/61-1-seems-to-have-broken-xiaomi-miio/39796

This is the second API breaking change, the last one being the enum-breaking #416 , so it would be really nice to have some time to prepare for these things instead of suddenly reading about everything breaking suddenly :-)

**Comment by arekbulski** [comment]
Few reasons. 
- I dont mean to be mean (condescending) but seen too many people complaining about this and that, breakage, backward and forward compatibility, yada yad. Bottom line is, I roll out the changes that I deem worthy changing, people complain and cry, then wipe their tears, fix their code, and everything is peachy and better than it was before. Other projects often do the opposite, analyse paralyze and debate to death in a comittee over changes that I would do outright without asking anyone. Then they make milestones open for a year until the big day "release date". They either keep few changes hanging for year until the release, or accumulate a lot of changes and have users to handle a lot at once. This library was entirely redesigned and reimplemented within few weeks, a month or so (to about 90% of current state, 100% of goals back then). Other projects existed for few years now and are still somewhere in the 50% state of their current goals. 
- Construct or rather me personally, dont believe in backwards compatibility. I dont quite belive in semantic versioning either. 
- I dont believe in changelogs either. Versions usually span no more than first page of commit history.

For your discretion
- What would you do with an advanced warning? If you change your code to new semantics, it will be broken until the library gets said changes added and pushed out. And you would not be able to test it before said push out.
- Immediate solution: change requirements.txt to use a specific Construct version until you fix your code.

Please dont get me wrong. I am trying to explain myself or rather make a case for the decisions that I make for other people (this library has some users...). 
I do, and I really do mean it, appreciate letting me know that you use Construct and what was broken. Are you aware of what other projects use Construct? mitmproxy was but no longer.
If you would like to have something added or changed, you are welcomed to open an Issue and make your case. I can help you with a recipe or advise at least, and add something to library at most.

**Comment by arekbulski** [comment]
It just occured to me, well, there is one way for you to know about API changes before a release. I open tickets for things I am working on, and for that matter, you can inspect the commit history as well. Not the same as depreciation warning in test suite, just mentioning.

**Comment by rytilahti** [comment]
Thanks for your reply, if nothing else it is great to have this in written if someone comes around and wonders the same thing!

> I dont mean to be mean (condescending) but seen too many people complaining about this and that, breakage, backward and forward compatibility, yada yad. Bottom line is, I roll out the changes that I deem worthy changing, people complain and cry, then wipe their tears, fix their code, and everything is peachy and better than it was before. Other projects often do the opposite, analyse paralyze and debate to death in a comittee over changes that I would do outright without asking anyone.

I agree with the notion that (open-source) projects should not be dictated by a committee nor one should not need to jump through too many hurdles to keep the development ongoing. On the other hand I still think that one should not simply break a long-standing API just suddenly if it can easily be avoided by a simple check and emiting a warning for some releases onwards.

> Construct or rather me personally, dont believe in backwards compatibility. I dont quite belive in semantic versioning either.
> I dont believe in changelogs either. Versions usually span no more than first page of commit history.

This kind of sad to hear, both of these can be very useful for those people who try to debug and try to understand how and why something has been done like it is. For an outsider it is sometimes, frankly speaking, quite a bit effort to decipher the commit logs to see what parts are relevant, especially when talking about something as low-level as protocol parsing.

> What would you do with an advanced warning? If you change your code to new semantics, it will be broken until the library gets said changes added and pushed out. And you would not be able to test it before said push out.

An advanced warning would help a bit, but having a simple deprecated warning over a couple of releases (depending on the release frequency) would likely be better assuming that someone spots it in their logs and reports about it.

With regards to a warning before a new release would allow adapting by using conditionals for those parts to be changed, but it would make the code considerably more complex than doing that on the library's end.

>  Immediate solution: change requirements.txt to use a specific Construct version until you fix your code.

The version pinning will not really work in python (or at least in this case) as long as there is no support for installing multiple versions of the same library inside the same environment, see my description of my case below.

> Please dont get me wrong. I am trying to explain myself or rather make a case for the decisions that I make for other people (this library has some users...).

I understand your position completely, and it is fair enough. I also do not want to sound ungrateful or anything of sorts. I'm also trying to explain how the situation looks from a user's perspective (when one has long dependency chains).

> I do, and I really do mean it, appreciate letting me know that you use Construct and what was broken. Are you aware of what other projects use Construct? mitmproxy was but no longer.

Alas no, I have been using it in a few projects after converting from suitcase (I liked their use of class members for defining structs, tbh) as it deemed to be a dead project in the long run. So you have been doing a great job! Speaking on the topic of library usage, it would be really nice if github could have it (as it seems to have for ruby and javascript projects, see insights -> dependency graph)!

In my case there are three libraries used within homeassistant (python-miio, python-yeelightbt, and python-eq3bt), all of which would have required being pinned to different versions. This combined with homeassistant's biweekly release cycle (as they do pin 1st level dependencies), sometimes a change hits before there's been enough time to make the changes to the library and push a new release out, it makes it quite hard to keep up with the pace and users' setups unbroken (although it remained so for a long period before the recent weeks), to be honest.

That being said I must apologize for getting back to you so late, I have been encumbered with other activities lately. And thanks again for your response, support and fast response times! Unfortunately I was not fast enough to see your reference on kaitai's issue tracker, which could have been interesting as that lib is something I have been wanting to try out at some point, but have not yet as I haven't recently being involved doing protocol parsing.

**Comment by arekbulski** [comment]
PS. I opened a poll (https://github.com/construct/construct/issues/527) asking people what they would like to be added to Construct, as in feature requests. Take a look at it. If there is something that I could do for miio, just ask.
