### ISSUE TITLE
Embedded constructs are not properly inserted into Structs

### ISSUE THREAD

**Issue by ceridwen** [construct/construct#44]
Here's a fairly minimal example in Python3.

```python
from construct import *
b = b'\x02\x04\x04\x04\x04'
m = MetaArray(lambda ctx: ctx.bytes, Struct('foo', Byte('bar'), Byte('baz')))
Minimal = Debugger(Struct(None, Byte('bytes'), Embed(m)))
print(Minimal.parse(b))
```

This should probably output something like:

```
Container:
    bytes = 2
    bar = [
        4
        4
    ]
    baz =
        4
        4
    ]
```

Instead, it outputs:

```
Container:
    bytes = 2
    bar = 4
    baz = 4
```

The problems are in lines 666-676 of core.py.

```python
            if sc.conflags & self.FLAG_EMBED:
                context["<obj>"] = obj
                sc._parse(stream, context)
            else:
                subobj = sc._parse(stream, context)
                if sc.name is not None:
                    if sc.name in obj and not self.allow_overwrite:
                        raise OverwriteError("%r would be overwritten but allow_overwrite is False" % (sc.name,))
                    obj[sc.name] = subobj
                    context[sc.name] = subobj
        return obj
```

First, line 668 calls sc._parse but doesn't do anything with the return value.  Second, because everything after line 669 is enclosed in the else clause corresponding to the if clause `sc.conflags & self.FLAG_EMBED`, if self.FLAG_EMBED is set, obj is never changed before it's returned.  If called directly on a Struct, the inner Struct's _parse method gets called and lines 658-660 set the object.  In this case, it seems like the values in the outer Struct get written twice, the second overwriting the first.

**Comment by arekbulski** [comment]
The problem is that Embed was made for Struct not lists. So this
`MetaArray(lambda ctx: ctx.bytes, Struct('s', Byte('a'), Byte('b')))`
would produce `[Container(a=4,b=4),Container(a=4,b=4)]` which is a list of structs, not a struct of lists. I will adde a regression test that makes sure Embed works only with Struct.

**Comment by arekbulski** [comment]
Oh tests show that Sequences can also be embedded in other Sequences. This doesnt make your example valid.
