### ISSUE TITLE
Anchors cause an AttributeError when building.

### ISSUE THREAD

**Issue by hardkrash** [construct/construct#45]
If an Anchor is in a construct, it must be in the Container used for building the stream.
I would prefer to not have to insert a useless value into the Container while building.
i.e. Following the behavior of Padding, when building.

There is a workaround is to set the Anchor's required container value to None while building.

**Comment by arekbulski** [comment]
Just fixed it. 5908eb61d6aa1acaf34e0648ac50336b96b7ee30
