### ISSUE TITLE
Backward-incompatible exceptions change in 2.8.22 release

### ISSUE THREAD

**Issue by pshchelo** [construct/construct#453]
the commit https://github.com/construct/construct/commit/812753a79ad8590a563c9881c5ffd8c2125e04e2 introduced a breaking change in Python API wrt to available exceptions, which is unexpected for such minor release.

Now any code that consumes construct library and tries something like

try:
    ...
except core.FieldError:
   ...

(which was valid for construct<2.8.22) is failing with

AttributeError: 'module' object has no attribute 'FieldError'

**Comment by arekbulski** [comment]
I am sorry, this was kind of supposed to fall into 2.9 release (together with huge other changes) but I somehow screwed it up. Would removing 2.8.22 release from pypi solve it?

**Comment by arekbulski** [comment]
Oh and just for my defense: I dont subscribe to semantic versioning, so these kind of changes are not unexpected for 2.8.(x+1) releases. But it would be good idea to "move" this change into 2.9 transition page.
https://construct.readthedocs.io/en/latest/transition29.html

**Comment by pshchelo** [comment]
Yes, this would solve the issue, thank you.

**Comment by arekbulski** [comment]
Hmm, after some thinking I changed my mind, and I feel like I need to clarify. I wont pull 2.8.22 from pypi (unless it would meltdown some reactors...). In general, I dont believe in semantic versioning. The 2.5<2.8 is only to signify the introduction of nameless fields and 2.8<2.9 is to signify adding compiler functionality. You can expect any kind of neck breaking changes on any release. Thats just how it is. For library to become better, something must be changed (or broken, same thing). It doesnt particularly matter what number gets attached to it. Either change your requirements.txt to use a particular version (if you want to freeze Construct for that purpose) or change your code to use newer/better/broken library. 

I am sorry for neglecting to update the docs about said changes. Docs updated atm.
