### ISSUE TITLE
Support for Python's enum module

### ISSUE THREAD

**Issue by hetsch** [construct/construct#456]
Hi,

first I want to thank you for this nice module. Very handy!
I'm having troubles making python's enum package playing nicely with construct. This is the code that I have right now:

```python
import enum
import construct as cs

def enum_to_obj(enum_cls):
    return {str(v.value): v.value for k, v in enum_cls.__members__.items()}

class FooType(enum.IntEnum):
    BAR = 0
    BAZ = 1

struct = cs.Struct(
    'type' / cs.Enum(
        cs.Int8ul,
        **enum_to_obj(FooType)
    )
)

# Good
assert b'\x01' == struct.build(dict(
    type=FooType.BAZ
))

# Bad
obj = struct.parse(b'\x01')
assert obj.type == FooType.BAZ
```

The `enum_to_obj` function is the problem here. I had to cast `str(v.value)` because the `**mapping` kwargs of the constructor method of `construct.Enum` require the argument keys to be strings and not integer (and so does Python as far as I know). Anyhow, this seems to be a messy solution and I wanted to ask you if could think of another solution or - if you think this might be of value for construct - to support Python's Enum/IntEnum module?

**Comment by arekbulski** [comment]
Good idea, I would gladly add support for Enum module (there is probably more people that would benefit from it). Would this syntax be fine? 
```py3
class FooType(enum.IntEnum):
    BAR = 0
    BAZ = 1

construct.Enum(FooType)
```

**Comment by hetsch** [comment]
Oh yeah, for me - perfect! Thank's for considering this ...

**Comment by arekbulski** [comment]
FYI, it will take me up to a week to implement this. Normally I would just add it off the bat but am currently hard working on getting major version change ready to ship. Please just bear with me.

**Comment by hetsch** [comment]
No problem at all. I totally understand this. Thx

**Comment by arekbulski** [comment]
Implemented. You can see examples in docs, it will be included in next release (in a day or two).
https://construct.readthedocs.io/en/latest/advanced.html#mappings
