### ISSUE TITLE
ULInt24 throws a field error when building

### ISSUE THREAD

**Issue by Lambdanaut** [construct/construct#46]
ULInt24 is a weird case in that it has the same format as all of the other multi-byte parsers, but it acts very differently. 

It does seem to work when parsing a binary, but the struct library will throw a Field Error when building a binary. 

    >>> parser = Struct('foo', ULInt24('my_24bit_thing'))
    >>> parser.build(Container(my_24bit_thing=123))
    FieldError(error('pack expected 2 items for packing (got 1)',)

Any hints on getting this to work or is it just broken? I'm replacing all ULInt24 parsers in my code with BitFields for now.

**Comment by fl0v0** [comment]
I can confirm that.

**Comment by arekbulski** [comment]
This was recently fixed.
