### ISSUE TITLE
Over broad exception catching (except Exception)

### ISSUE THREAD

**Issue by joneskoo** [construct/construct#48]
I have an issue where I'm running pyelftools and need to interrupt processing. I'm calling pyelftools from a Celery task. Celery cancels tasks by raising an celery.exceptions.Terminated exception. I have traced the offending except Exception to construct library where it needs to be fixed.

Due to the problem, I can't reliably cancel my task as sometimes construct except Exception will eat my celery exception and as far as I know there's no way to work around it.

As a fix, all occurences of except Exception should be changed to catch more specific exceptions, such as IOError, ValueError etc.

Example of an offending exception:
https://github.com/construct/construct/blob/master/construct/core.py#L364

```

$ git grep --line-number "except Exception"
construct/core.py:246:        except Exception:
construct/core.py:364:        except Exception:
construct/core.py:369:        except Exception:
construct/core.py:928:                except Exception:
construct/core.py:1398:        except Exception:
construct/core.py:1405:        except Exception:
construct/debug.py:110:        except Exception:
construct/debug.py:121:        except Exception:
```

This is follow-up from https://github.com/eliben/pyelftools/issues/59 where they told me construct is upstream so here I am.

**Comment by arekbulski** [comment]
I noticed these broad exception catches. You can submit a patch to either and any of them, go ahead.

**Comment by arekbulski** [comment]
Some are broad by design I think. Debuggers should use broad.
