### ISSUE TITLE
Example for string build function not working for python3

### ISSUE THREAD

**Issue by red-hood** [construct/construct#54]
Hi,

the example in https://github.com/construct/construct/blob/208df16e51f8fc35f5c924a5cabc623eb425bc4e/construct/macros.py#L522 won't work for python3, as long as there is no encoding set for the String macro. Guess there should be a hint in the documentation.

When  I do

    String('foo', 3).build('abc')
    
I get the error

    TypeError: 'str' does not support the buffer interface

**Comment by arekbulski** [comment]
On PY2 str is a bytes object while PY3 has unicode strings. I make a guess that encoding to ASCII/UTF8/other is missing. 

Could you add a test case for this and submit a pull request?

**Comment by arekbulski** [comment]
Fixed in commit b65413e5d1d0aea01fe8ca1a6dec0ca45245da95. Documentation and tests updated.
