### ISSUE TITLE
Numpy Arrays building and parsing

### ISSUE THREAD

**Issue by scls19fr** [construct/construct#55]
Hello,

I wonder if `construct` can deal with Numpy Arrays and the use of `memmap`.
http://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html

I didn't see anything about this in the doc but it might be efficient because
I have a binary file format with 1863 bytes of headers (including an array length at offset 1859), an array of 9 unsigned floats (little endian) and 104 bytes at the end.

Kind regards

**Comment by arekbulski** [comment]
Sequences of integers are already supported, and numpy arrays are exactly that. And you can put a list of ints into a numpy array constructor. Wont be blazing fast but will work. I think what you are suggesting is some sort of numpy dump that includes the data format, dimensions, etc. I will add a new field for that.

**Comment by arekbulski** [comment]
Here it is. Want to implement it?
http://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html

**Comment by arekbulski** [comment]
Implemented.

**Comment by arekbulski** [comment]
Implemented and tested (although not all Travis profiles suppoer numpy). Done.
