### ISSUE TITLE
PascalString and max length

### ISSUE THREAD

**Issue by scls19fr** [construct/construct#56]
Hello,

I'm reading a binary file.
This file seems to use a sort of PascalString

See this hex:

    09 53 65 62 61 73 74 69 65 6E 00 00 00 00 00 00 00 06 43 65 6C 6C 65 73 00 00 00 00 00 00 00 00 00 00 06 46 72 61 6E 63 65 00 00 00 00 00 00 00 00 00 00 06 46 2D 43 47 4E 4A 00 03 46 31 39

I should get

    Sebastien (FirstName) -> 53 65 62 61 73 74 69 65 6E
    Celles (ForeName) -> 43 65 6C 6C 65 73
    France (Country) -> 46 72 61 6E 63 65
    F-CGNJ (RN) -> 46 2D 43 47 4E 4A
    F19 (CN) -> 46 31 39

09 is len("Sebastien")
06 is len("Celles")
06 is len("France")
06 is len("F-CGNJ")
03 is len("F19")

Unfortunately if I'm using a PascalString I can't define a max length for my strings.

In my case I'd like to be able to define

    PascalString("FirstName", length_field=UBInt8('length'), max_length=16)

because

    09 53 65 62 61 73 74 69 65 6E 00 00 00 00 00 00 00 

is 17 bytes long.

It will be nice to have a max_length parameter add.

Kind regards

**Comment by tomerfiliba** [comment]
Hi

Construct is much like lego bricks. The library comes with some useful,
preconfigured bricks, but it's up to you to build meaningful things with
them.
And if a brick doesn't fit your needs, you can always just "disassemble" it
and build it to your own liking.
For instance, have a look at how PascalString is defined and add the
missing parts.

Hope this helps,
-tomer


-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by scls19fr** [comment]
Thanks. It's a nice lego bricks package ;-)

**Comment by arekbulski** [comment]
I will make this one of my priority tasks, even tho it is a year old. PascalString class will be more handy than separate field for length and context lambda.

**Comment by arekbulski** [comment]
Architectural question: should maxlength be checked against the field and throw when the field is more than the maximum specified, or something else?

I think what you meant was having some sort of variable length padding field that swallows remaining bytes when parsed. Meaning the parsed blob can be longer then the struct representation.

**Comment by arekbulski** [comment]
Architectural question: should maxlength be checked against the field and throw when the field is more than the maximum specified, or something else?

I think what you meant was having some sort of variable length padding field that swallows remaining bytes when parsed. Meaning the parsed blob can be longer then the struct representation.

**Comment by arekbulski** [comment]
Only now I figured it out. You are asking for a field similar to `Padding` that consumes zero bytes during parsing. Such a class could be added easily, question remains should this class also add zero bytes when building and how many? And I think this can be already done using `RepeatUntil` although a more convenient version would be nice.

**Comment by scls19fr** [comment]
There is a long time since I wrote this feature request!

Unfortunately I don't have a Windows computer here to test

Here is the code I wrote last year

https://github.com/scls19fr/pycondor/blob/ee87854504e8f4023feda860d8a9ddbecc7a70da/pycondor/read_ftr.py#L40

but I've done a quick Python example to test it:


```python
import binascii

from construct import Struct, Bytes, CString, String, PascalString


hex_string="09 53 65 62 61 73 74 69 65 6E 00 00 00 00 00 00 00 06 43 65 6C 6C 65 73 00 00 00 00 00 00 00 00 00 00 06 46 72 61 6E 63 65 00 00 00 00 00 00 00 00 00 00 06 46 2D 43 47 4E 4A 00 03 46 31 39"
hex_string = hex_string.replace(" ", "")
bin_string = binascii.unhexlify(hex_string)


ftr_struct = Struct("ftr_header",
    String("FirstName", 17),
    String("FamilyName", 17),
    String("Country", 17),
    String("RN", 8),
    String("CN", 4),
)

dat = ftr_struct.parse(bin_string)
```

The number of zero bytes which need to be add is the max len - number of bytes that are really use.

**Comment by arekbulski** [comment]
I think this could be done: `Aligned(PascalString("firstname"), modulus=16)`

**Comment by arekbulski** [comment]
If Aligned works, could you still write a proper test case and submit a pull request?

**Comment by scls19fr** [comment]
I've just try

```python
ftr_struct = Struct("ftr_header",
	Aligned(PascalString("FirstName"), modulus=16),
	Aligned(PascalString("FamilyName"), modulus=16),
	Aligned(PascalString("Country"), modulus=16),
	Aligned(PascalString("RN"), modulus=7),
	Aligned(PascalString("CN"), modulus=3)
)

dat = ftr_struct.parse(bin_string)
```

but it raises `KeyError: 'length'`

**Comment by arekbulski** [comment]
I suspect, from reading some code examples and not personal experience which right now is zero, that construct is built on assumption that fields have unique names. Each PascalString is a macro that creates a subcon named "length" and that creates a conflict. Needs some internal understading of the code.

**Comment by arekbulski** [comment]
Does `Struct(PascalString("first"),PascalString("last"))` cause same problem?

**Comment by scls19fr** [comment]
No it doens't cause any problem... but doesn't solve anything

```python
import binascii

from construct import Struct, Bytes, CString, String, PascalString

hex_string="09 53 65 62 61 73 74 69 65 6E 00 00 00 00 00 00 00 06 43 65 6C 6C 65 73 00 00 00 00 00 00 00 00 00 00 06 46 72 61 6E 63 65 00 00 00 00 00 00 00 00 00 00 06 46 2D 43 47 4E 4A 00 03 46 31 39"
hex_string = hex_string.replace(" ", "")
bin_string = binascii.unhexlify(hex_string)


ftr_struct = Struct("ftr_header",
    PascalString("FirstName"),
    PascalString("FamilyName"),
    PascalString("Country"),
    PascalString("RN"),
    PascalString("CN"),
)

dat = ftr_struct.parse(bin_string)

## -- End pasted text --

In [26]: dat
Out[26]: Container({'Country': b'', 'CN': b'', 'FamilyName': b'', 'RN': b'', 'FirstName': b'Sebastien'})
```

**Comment by arekbulski** [comment]
I know but it disproves my hypothesis about nonunique fields. Then it could be an issue of Aligned not handling variable length subcons. Lets see if this fails `Aligned(Cstring(), modulus=8).parser("test\0\0\0\0")`

**Comment by arekbulski** [comment]
This goes belly up. As I suspected, Aligned does not work with variable size subcons.
```
Aligned(CString('name'), modulus=8).parse(b'1234\0pad')
```

**Comment by arekbulski** [comment]
Aligned should be rewritten to use tell from byte stream, not sizeof from subcon.

**Comment by arekbulski** [comment]
You should know that Aligned now uses stream tell, not sizeof. So this works OK:
`Aligned(CString('name'), modulus=8).parse(b'1234\0pad')`

**Comment by arekbulski** [comment]
Solution existed before you asked. String class takes a number of bytes regardless of zeros and trims using a chosen zero byte. Here you go:
```py
arkadiusz@pc:~/Dokumenty/GitHub/construct$ cat t1.py 
import binascii
from construct import *

hex_string="09 53 65 62 61 73 74 69 65 6E 00 00 00 00 00 00 00 06 43 65 6C 6C 65 73 00 00 00 00 00 00 00 00 00 00 06 46 72 61 6E 63 65 00 00 00 00 00 00 00 00 00 00 06 46 2D 43 47 4E 4A 00 03 46 31 39"
hex_string = hex_string.replace(" ", "")
bin_string = binascii.unhexlify(hex_string)

ftr_struct = Struct("ftr_header",
    Byte(None),
    String("FirstName",16),
    Byte(None),
    String("FamilyName",16),
    Byte(None),
    String("Country",16),
    Byte(None),
    String("RN",7),
    Byte(None),
    String("CN",3),
)

dat = ftr_struct.parse(bin_string)
print(dat)

arkadiusz@pc:~/Dokumenty/GitHub/construct$ ipython3 t1.py 
Container: 
    FirstName = b'Sebastien'
    FamilyName = b'Celles'
    Country = b'France'
    RN = b'F-CGNJ'
    CN = b'F19'
```

**Comment by scls19fr** [comment]
Thanks for your nice answer!

**Comment by arekbulski** [comment]
I could use some help with processing issues and features. There are some things that do not work yet and I dont know why. Need assistance.
https://github.com/construct/construct/branches
