### ISSUE TITLE
Parent field cannot be accessed if embedded struct is present

### ISSUE THREAD

**Issue by rabbitsaviola** [construct/construct#566]
Hi,

  I'm having trouble accessing parent field if embedded struct is present in the sub-structure. "KeyError: c1" would be issued if `test_outer.build()` is called. The same structure works fine with `test_outer.parse('\x01\x02\x80\x03\x04')`.  

  If I change embedded struct to nested, then no error occurs. I'm new to construct. Perhaps I misunderstand the usage. Could you tell me what's wrong with my code? Thanks.

Following is the structure definition I use: (edited by mod)
```python
test_inner = Struct(
    "f1" / Int8ul,
    Embedded(Struct(
        'a' / Int8ul,
    )),
    "f2" / If(this._.c1 > 0, Int8ul),
    "f3" / Int8ul,
)

test_outer = Struct(
    "c1" / Int8ul,
    "c2" / test_inner,
)

```

Error message and traceback:
```
>>> test={'c1': 1, 'c2': {'a': 1, 'f1': 2, 'f2': 3, 'f3': 4, 't': {'a': 1}}}
>>> test_outer.build(test)

KeyError: 'c1'
```

**Comment by arekbulski** [comment]
Few hints for you, aside of the embedding issue:
- Byte is alias for Int8.
- Name only fields inside Struct, dont name embedded structs, dont name struct.
- I recommend using, build(dict(c1=1, ...)) syntax
- No stack traces, those arent useful here
- Read documentation (Basics chapters) if you havent

Could you update your post with these? I will get back to you in a while.

**Comment by arekbulski** [comment]
Please update your post with these, if you could, then show me what parsing returns.

**Comment by arekbulski** [comment]
Explanation is simple, here is what parsing results. What you need to build from should be in same format. Can you see the difference?
```py
In [4]: test_outer.parse(b'\x01\x02\x80\x03\x04')
Out[4]: Container(c1=1)(c2=Container(f1=2)(a=128)(f2=3)(f3=4))
```
There is "t" entry, because embedded struct builds from a parent dictionary (its keys).

**Comment by arekbulski** [comment]
Added your code to test suite, its a BUG.
```py
def test_struct_issue_566(self):
    inner = Struct(
        Embedded(Struct(
            "b" / Byte,
        )),
        "c" / If(this._.a > 0, Byte),
    )
    outer = Struct(
        "a" / Byte,
        "inner" / inner,
    )
    outer.parse(b'\x01\x02\x03') == Container(a=1)(inner=Container(b=2)(c=3))
    outer.build(Container(a=1)(inner=Container(b=2)(c=3))) == b'\x01\x02\x80\x03\x04'
```

**Comment by arekbulski** [comment]
This ticket gets postponed until #568 because that one might possibly solve this one.

**Comment by arekbulski** [comment]
Bug was fixed, please wait for incoming realease for the bugfix. 

You can read about the new embedding semantics on:
https://construct.readthedocs.io/en/latest/meta.html#nesting-and-embedding

**Comment by arekbulski** [comment]
New release just shipped out, fixing your issues as well. You should use pip to upgrade your installed version.
