### ISSUE TITLE
Switch(includekey=True) is anyone use this?

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#576]
@yannayl 
Could you help me out with checking something? Is this one being used by anyone?
```
Switch(includekey=True)
```

**Comment by yannayl** [comment]
Couldn't find anything on GitHub. I'm definitely not using it, I couldn't even figure out from the documentation what it is supposed to do.

**Comment by arekbulski** [comment]
Lol. Then its useles. I will remove it right away. Thanks for your help, much appreciate it.
