### ISSUE TITLE
Building a Struct and automatically updating some fields (like a length field)

### ISSUE THREAD

**Issue by yoelk** [construct/construct#58]
Hi,
I'm sorry if this was covered in the documentation, I tried finding it but did not succeed.
Let's say I want to use the IP Struct to generate an IP message.
Is it possible to make the build() function calculate the length and put it in the right place in the Struct?

Meaning, can I have a field in a struct that is calculated according to the other fields?

Toda,
Joel

**Comment by rainx86** [comment]
Hi,

This is not covered in the documentation and ```Struct.build()``` is not able to do this on its own.
I found two ways to acheive this:
- The first one is to calculate the length by hand, but it is cumbersome and can be error-prone if your structure has a lot of fields.
- The second one is to initially set the length to 0 and build the structure a second time, using an anchor to get the length. This method is described more in-depth in [this article](http://forums.4fips.com/viewtopic.php?f=3&t=1205).

Here's an example:
```py
from construct import *

ipv4_header = Struct('ip_header',
    # …
    UBInt16('length'),
    # …
    Anchor('_end'),
)

container = Container(
    # …
    length = 0,
    # …
    _end = 0,
)

my_header = ipv4_header.build(container)

# Build the header a second time, using the anchor to get its length
container = ipv4_header.parse(my_header)
container.length = container._end
my_header = ipv4_header.build(container)

# …
```

**Comment by yoelk** [comment]
Works like a charm! Thanks a lot! :)

**Comment by arekbulski** [comment]
Look at my comment. Is this what you are looking for?
https://github.com/construct/construct/issues/68#issuecomment-240563438

**Comment by yoelk** [comment]
Thanks Arkadiusz!
I don't know,it's been a while since I last touched that code.
For now, Rain's comment solved the issue for me but I'll look into it if I
decide to change the code.

Thanks again,
Joel

**Comment by arekbulski** [comment]
Good for you. If you have it solved, please close the issue.

**Comment by yoelk** [comment]
Oh, sorry about that.
I'll close it now.

On Thu, Aug 18, 2016 at 11:10 PM, Arkadiusz Bulski <notifications@github.com

**Comment by arekbulski** [comment]
Dont get me wrong, if you can suggest something that will be of use to others then reopen. But please make it specific.

**Comment by arekbulski** [comment]
Should have mentioned: Anchor puts current stream position from stream.tell() both during parsing and building. There are some examples in docstrings and test suite.

**Comment by yoelk** [comment]
Thanks!
