### ISSUE TITLE
Kaitai Struct (.ksy) importer and exporter

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#583]
Importer would allow using their examples to promote Construct. It would also allow them to compile builders (KS is only a parser). 

Analog thread on Kaitai side: https://github.com/kaitai-io/kaitai_struct/issues/377

**Comment by edobez** [comment]
This is what is meant by "collaboration with Kaitai Struct" in the project's homepage?

**Comment by Znunu** [comment]
How did this go?

**Comment by KOLANICH** [comment]
Stalled, Arkadiusz is no longer active in KS repo. There is a target in KSC to generate python scripts using Construct, but I don't remember if Construct can generate `ksy`s. If you want to implement it, you may want to look at sources of synalysis2kaitai, there is some classes of kind of AST, but in fact it needs deep refactoring: we need to untie the ast nodes from YAML library and implement multiple passes.

**Comment by arekbulski** [comment]
Construct can generate KSY YAML files, its called a KSY exporter tool. There is no importer on Construct side, but the KSY compiler does support a Construct target.

**Comment by KOLANICH** [comment]
https://github.com/construct/construct/blob/master/construct/core.py#L653

**Comment by arekbulski** [comment]
As @KOLANICH pointed out, every parsing class (that derives from Construct abstract class) has a "export_ksy" method, just as every one of them has a "parse" and "build" method.
