### ISSUE TITLE
Enums to be referred by value or field (not only name string)

### ISSUE THREAD

**Issue by yannayl** [construct/construct#597]
Currently, referring to Enums and other mappings during parsing must be done with the field's name string, e.g.:
```python
e = Enum(Byte, one=1, two=2)
Struct('type'/e, Switch(this.type, {'one': Int8ul, 'two':Int16ul})).parse('\x01\xff')
```
I wish to be able to refer to it also by value, e.g.:
```python
Struct('type'/e, Switch(this.type, {1: Int8ul, 2:Int16ul})).parse('\x01\xff')
```
And even better, to be able to specify it as an attribute of the `Enum` object, e.g.:
```python
Struct('type'/e, Switch(this.type, {e.one: Int8ul, e.two:Int16ul})).parse('\x01\xff')
```

I think these semantics will make it much more clear and less error prone than strings.

I think reference by value will break the current implementation. However, reference as an attribute should be pretty easy.

**Comment by yannayl** [comment]
I think reference by value will break the current implementation. However, reference as an attribute should be pretty easy.

**Comment by arekbulski** [comment]
Just for completeness, you can use this syntax:
```py
Struct('type'/e, Switch(this.type, dict(one=Int8ul, two=Int16ul ))).parse('\x01\xff')
```

**Comment by yannayl** [comment]
The benefit of specifying `{e.two:Int16ul}` is that a typing error, e.g. `{e.twoo:Int16ul}` will throw an exception in runtime whereas `dict(twoo=Int16ul)` won't necessarily.

**Comment by arekbulski** [comment]
Yes, that would fail at runtime but you would need to have a testsuite to test your code for that.

**Comment by yannayl** [comment]
It will throw an exception when interpreting the code, event if you don't use it. It's the closest thing you can get to compile-time in python :)

**Comment by arekbulski** [comment]
Implemented. Review the docs:
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum

**Comment by yannayl** [comment]
I would add a use example of building/parsing in both. e.g.: `d.build(d.one)` which yields `\x01` 

p.s. The documentation of Mapping and SymmetricMapping is `???`. I assume you are aware of that.

**Comment by arekbulski** [comment]
Good catch. Updated docs. Review?

Mapping and SymmetricMapping are deprecated, I was even going to delete them, but decided to just leave them in the core in case someone was stupid/brave enough to use those.

Enum had recently another upgrade, someone asked that Enum could suck labels and values from enum.IntEnum. You can see that on the API page. I wonder if we could add some more features into Enum. Also I droped the "default" parameter, due to implementation issues.

**Comment by yannayl** [comment]
Reviewed. Looks good! (I like the fact it's the first example when building, as it is the least error-prone way to do it).

Wow, dropping features like a boss :+1: , hope it doesn't break anything.

**Comment by arekbulski** [comment]
> dropping features like a boss

Yeah, I had made a rant recently about it. Feel free to read it and laugh. #428

**Comment by arekbulski** [comment]
> dropping features like a boss

Yeah, I had made a rant recently about it. Feel free to read it and laugh. #428 

Truth is, some features are simply not as useful as I anticipated, and some existed before I took over the project and I didnt even think of it. Range was dropped recently. Lazy* were dropped, and you know exactly why. Mapping should be dropped, but meh. OnDemand should be dropped, you know that one. HexString was dropped, I dont think anyone used it in the first place. EmbeddedBitStruct was removed but due to implementation issue.

**Comment by yannayl** [comment]
I used something similar actually.

Adapter I re-implemented so many time - HexNum:
```python
class HexNum(int):
    def __str__(self):
        return hex(int(self))

class HexNumAdaptr(Adapter):
    def _decode(self, obj, context):
        return HexNum(obj)
    def _encode(self, obj, context):
        print(type(obj), obj)
        return int(obj)
```

I think I also used HexString, though not sure when. At least for printing purposes it's convenient.

But I agree it can be implemented individually by the users. It's not hard to implement and not a core feature of the library.

**Comment by arekbulski** [comment]
Actually, I would be willing to add HexNum into the core. How about you open an Issue for it?

**Comment by arekbulski** [comment]
Actually, I would be willing to add HexNum into the core. How about you open an Issue for it? HexString is dead, long live HexString!

I added another ticket for upgrading FlagsEnum up to standard. #600

**Comment by yannayl** [comment]
#see 601

**Comment by arekbulski** [comment]
Moved to #601 .

**Comment by yannayl** [comment]
They are not referred by value. I think the right thing to do, if you don't give a shit about backwards compatibility is to change the value of `e.one` to 1 instead of `"one"`. And when parsing change the `__str__` method to show the name, but the value stays the the number (or whatever is enumerated).

**Comment by arekbulski** [comment]
The thing is, Enum in principle exposes string labels to end user, and integer values are hidden, or rather used internally when processing the data. Why should the constant expose an integer?

**Comment by yannayl** [comment]
Hmm because it's not really a string nor an integer. I strongly believe it should be an object on it's own. So `e.one != "one" and e.one != 1` is the best approach. `e.one == e.one`. but I want to be able to build it from both, the label and the value, but compare it only within the scope of the enum.

**Comment by yannayl** [comment]
Imagine two different enums sharing some tables although with different values. It's obvious that comparing then is no sense and should yield false (or better, throw an exception). Yet if we treat them as labels the interpreter happily does the comparison. And you can imagine an equally wrong scenario with values.

**Comment by arekbulski** [comment]
Now you are suggesting changing semantics for parsing results. Breaking compatibility is fine, as long as it serves a greater good. But returning objects is not acceptable: often Enum is followed by Switch in same Struct. Switch could not be keyed by integer or string in that case, and it could not be keyed by objects because those are not accessible when Enum is inlined. Example:
```py
Struct(
  "x"/Enum(Byte, one=1),
  "y"/Switch(this.x, { ??? : Byte}),
)
```

**Comment by yannayl** [comment]
You have a point there. So maybe for eq operator both the label and value should yield true.
However `FlagsEnum(Byte, one=1, two=2).parse ('\x01') | 2` seems quite natural. (or any other operator should probably operate on the value and not on the label.)
Another example is when you have one enum where values are logically separated into two categories and the parsing depends on the category but not on a specific value. In this case, in C, I would add an unused label as a separator and check if the value is greater than the separator. Obviously the __ge__ operator should only apply to the value.

**Comment by arekbulski** [comment]
By definition, enums are not integers, they are "distinct objects". Therefore < and > comparisons between enum objects is not idiomatic, its trickery.

**Comment by yannayl** [comment]
I agree. It's tricky and I don't have any good arguments left. I vaguely remember a project from my previous work where I excessively used the internal dictionary to convert mappings from labels to values, but don't remember the details. Probably I was just doing something wrong.
Anyway I think we can close this one for now. If I have a more convincing argument I'll re open it. At this point I think it's not really productive.

**Comment by arekbulski** [comment]
Finished. Docs for review:
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum

**Comment by yannayl** [comment]
1. The documentation should mention that pipe sign '|' is used implicitly as a delimiter and thus must not be used.
2. "Size is same as subcon, unless it raises SizeofError" - English is not my mother tongue, but this doesn't seem right to me. My suggestion: "Size is same as subcon; if it's not - an SizeofError is raised".
3. Mapping and SymmeticMapping examples is ???
4. You didn't mention SymmetricMapping as deprecated

**Comment by arekbulski** [comment]
I dont feel like there is a need for explicit warning. The example shows clearly that pipe is used as separator. And you cant have attributes with pipe either. Overcautious.

Mapping* added notes for deprected.

Thanks for your review.
