### ISSUE TITLE
Auto calculated size

### ISSUE THREAD

**Issue by WoLfulus** [construct/construct#60]
Is there any way to automatically calculate the whole struct size?

For example, I have a struct like this:

    int8 type; // header 
    intX size; // header
    int8[] data;

"type" can be anything from 0 to 2, in which

0 makes size be an int8
1 makes size be an int16
2 makes size be an int32

"size" will be calculated based on header length + data length

I can parse this without problems with a switch do switch between int8/16/32 types of "size" and an anchor to retrieve the current header length... data will be Bytes() using context to calculate **header.size - header.length** - not sure if this is the right way to do it

the problem comes when I try to build an object using this method

is there any way to make size calculate the whole struct size based on the whole struct size?

The current code I came up with to parse things:

    Header = Struct("header",
        UBInt8("type"),
        Switch("size", lambda ctx: ctx.type,
        {
            0: UBInt8("size"),
            1: UBInt16("size"),
            2: UBInt32("size")
        }),
        Anchor("length")
    )
    
    HeaderData = Struct("header",
        Embed(Header),
        Bytes("data", lambda ctx: ctx.size - ctx.length)
    )

Building HeaderData will result in an invalid buffer(header)

**Comment by arekbulski** [comment]
Is the format fixed in stone? You could use varint encoding, would be much better here. I will implement wihin a day or two.

**Comment by arekbulski** [comment]
Short answer is NO. Currently sizeof works only for fixed size constructs so Switches and such do not compute sizeof. I am going to refactor sizeof but that is something for later.

More immediate solution would be to use two Anchors, then a Computed (renamed from Value) to calculate the difference between the two anchors. Or just use `len(HeaderData.build(...))`.

If you can change the format, use the new VarInt construct that I just added.

**Comment by arekbulski** [comment]
Here is a test I just added (and it passes).
```py
Header = Struct("header",
    UBInt8("type"),
    Switch("size", lambda ctx: ctx.type,
    {
        0: UBInt8("size"),
        1: UBInt16("size"),
        2: UBInt32("size")
    }),
    Anchor("length"),
)
self.assertEqual(Header.parse(b"\x00\x05"), Container({'length': 2, 'type': 0, 'size': 5}))
self.assertEqual(Header.parse(b"\x01\x00\x05"), Container({'length': 3, 'type': 1, 'size': 5}))
self.assertEqual(Header.parse(b"\x02\x00\x00\x00\x05"), Container({'length': 5, 'type': 2, 'size': 5}))
```

**Comment by arekbulski** [comment]
If I didnt solve the problem for you, please reopen. Good luck.

**Comment by arekbulski** [comment]
Updated the test. I think you got the lambda wrong, and the anchor is not needed anyway. Test PASSES.
```py
Header = Struct("header",
    UBInt8("type"),
    Switch("size", lambda ctx: ctx.type,
    {
        0: UBInt8("size"),
        1: UBInt16("size"),
        2: UBInt32("size")
    }),
    Anchor("length"),
)
self.assertEqual(Header.parse(b"\x00\x05"), Container(type=0)(size=5)(length=2))
self.assertEqual(Header.parse(b"\x01\x00\x05"), Container(type=1)(size=5)(length=3))
self.assertEqual(Header.parse(b"\x02\x00\x00\x00\x05"), Container(type=2)(size=5)(length=5))

self.assertEqual(Header.build(dict(type=0, size=5)), b"\x00\x05")
self.assertEqual(Header.build(dict(type=1, size=5)), b"\x01\x00\x05")
self.assertEqual(Header.build(dict(type=2, size=5)), b"\x02\x00\x00\x00\x05")

HeaderData = Struct("header",
    Embed(Header),
    Bytes("data", lambda ctx: ctx.size),
)
self.assertEqual(HeaderData.build(dict(type=0, size=5, data=b"12345")), b"\x00\x0512345")
self.assertEqual(HeaderData.build(dict(type=1, size=5, data=b"12345")), b"\x01\x00\x0512345")
self.assertEqual(HeaderData.build(dict(type=2, size=5, data=b"12345")), b"\x02\x00\x00\x00\x0512345")
```

**Comment by StohanzlMart** [comment]
Any updates on this?

How can I do an invisible but referenceable `Tell()` (modern Anchor) at a desired position?

**Comment by arekbulski** [comment]
No. This has been closed in 2016 and will not be reopened. 

What does that even mean, invisible but referencable? Look at the Struct class implementation. Either the subcon is named or it is not inserted into parsed dictionary.

**Comment by StohanzlMart** [comment]
> What does that even mean, invisible but referable?

Invisible: Not inserted into parsed dictionary
Referenceable: Able to use `Tell`-position in prior `Rebuild`-field.

But I think I'll play for 10 more hours with the solution proposed in another issue (which I cannot find atm) with building Header and Payload in two stages to be able to calculate the length.

**Comment by arekbulski** [comment]
If the subcon is not named then it wont be inserted into the context dictionary, period. It seems like you are using two differently sounding terms for the exact same thing. Or do I get that wrong?
