### ISSUE TITLE
Enum and FlagsEnum to build from integer values

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#600]
Enum can build from both integer and label, so FlagsEnum could do that too.

**Comment by yannayl** [comment]
Yeah, I was thinking about it, but couldn't come up with satisfying syntax...

**Comment by arekbulski** [comment]
I added it to both Enum and FlagsEnum. @yannayl Would you review the docs?
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum

**Comment by yannayl** [comment]
"semantics??? Size is same as subcon, unless it raises SizeofError." Remove the word semantics and quotation marks. I think this sentence is grammatically incorrect. Should be something like "if a specified value exceeds the maximal value that can be specified by the Subcon, a SizeofError is thrown".

Need and example for the merge parameter cause I have no idea how to use it (also maybe improve it's doc or completely drop it, I don't know what it does so..).

I don't understand the semantics of multiple flags in FlagsEnum. If my suggestion of the field value as the value of the mapping (a number, not a string) is accepted, one can use `fe.build(fe.eight | fe.two)`. If not, perhaps passing and iterable of flags names.

**Comment by arekbulski** [comment]
Ah sorry sorry, let me update those docs tomorrow and resubmit for review.

**Comment by arekbulski** [comment]
Building FlagsEnum from iterable like `build([1,"two"])` is fine. I will implement it.

**Comment by arekbulski** [comment]
Building FlagsEnum from iterable like `build([1,"two"])` is fine. I will implement it. Also it would be possible for FlagsEnum.eight be string-alike that is coercible to integer, which would allow bit-or on labels like `build(d.one | d.two)` even tho `d.one=="one"`.

**Comment by arekbulski** [comment]
There is an alternative implementation possible as well. I am leaning towards the second:
- string-alike coercible to integer, `d.one | d.two == 3` but `d.one == "one"`
- string-alike with bitwise-or, so `d.one | d.two == "one|two"` that build would recognize

**Comment by yannayl** [comment]
I'm also leaning towards the second though it implicitly makes the pipe char "|" a delimiter and thus can't be used in a label. Document it and everything is fine I think

**Comment by arekbulski** [comment]
Finished. Docs for review:
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.FlagsEnum
