### ISSUE TITLE
Add HexIntAdapter

### ISSUE THREAD

**Issue by yannayl** [construct/construct#601]
`HexIntAdapter` displays numbers in hex form by default.
Example:
```python
>>> Int8ul.parse('\xff')
255
>>> print HexIntAdapter(Int8ul).parse('\xff')
0xff
```

Implementation:
```python
class HexInt(int):
    def __str__(self):
        return hex(int(self))

class HexIntAdapter(Adapter):
    def _decode(self, obj, context):
        return HexInt(obj)
    def _encode(self, obj, context):
        return int(obj)
```

Note: I think conceptually `HexInt` belongs to python core, it's not specific to _construct_ and can be useful in various other cases. However, my only use-case is in parsing, so _construct_ it is.

**Comment by arekbulski** [comment]
Number is a term that includes floats and complex numbers, and rationals. I would call it `HexInt`. Also I made a convention that core classes do not have `-Adapter` in their name, like Hex, HexDump. But those are just details. 

What is that last sentence? (you can edit top post)

**Comment by arekbulski** [comment]
It just occured to me, we could change Hex class so it works with both integers and byte strings. Make it a universal adapter. Mayber there are even other types that it could support?

**Comment by arekbulski** [comment]
It just occured to me, we could change Hex class so it works with both integers and byte strings. Make it a universal adapter. Mayber there are even other types that it could support?

Also it could support RawCopy, so pretty much any subcon wrapped as in Hex(RawCopy(...)), would be displayed in hexadecimal form instead. Pretty neat huh?

**Comment by yannayl** [comment]
It feels wrong. Representation of bytes is Vietnam War of parsing, you know where you start, but not where it ends. I don't think it should be mixed with Ints where it's very well defined. (i.e. 0xff and 255 are treated the same by the language )

**Comment by arekbulski** [comment]
Let me put Vietnam War issue aside for a moment.

Would it be better if integer was displayed with leading zeroes, depending on subcon used?
```
Int16 --> 0x12ff
Int32 --> 0x000012ff
```

**Comment by yannayl** [comment]
IMHO yes. Definitely yes. Usually I use it for memory addresses and in 64 and leading zeros will be very useful

**Comment by arekbulski** [comment]
I dont know what is that Vientam War of parsing, I assume its some sort of historical reference to something like pascal/cstring or unicode/codepages thing?

Its just so that there is not a different class for different subcon. Consider parsing: Each outputs about same type as original, but with changed `__str__`. 
- Hex(Int8) -> int-alike
- Hex(Bytes) -> bytes-alike
- Hex(RawCopy) -> dict-alike

**Comment by yannayl** [comment]
Okay, one Hex to rule them all. If it gets complicated I assume we can always drop it and restrict ourselves to Ints in the future.

**Comment by arekbulski** [comment]
Finished. Docs for review:
https://construct.readthedocs.io/en/latest/misc.html#hex-and-hexdump
https://construct.readthedocs.io/en/latest/api/misc.html#construct.Hex

**Comment by yannayl** [comment]
Looks good.
Future: when lazy parsing is implemented, if it's implemented in a way that every field is aware of it's offset in the stream, the HexDump offset can have the absolute offset in the stream.

**Comment by arekbulski** [comment]
That would not be advisable, it complicates the code more than it solves, but thats devs optinion. End user needs might justify that. I will keep that in mind.
