### ISSUE TITLE
push a release

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#609]
Quite some changes accumulated since last release, about 3 days ago?

**Comment by yannayl** [comment]
Lol, well

**Comment by arekbulski** [comment]
Yeah. :grin:  During heavy development when I work 10hr/day on it, I make releases about daily, then it turns into ironing it out and bugfixes and weekly releases, and then well, stagnation. Or stability region, depending how you see it. 

There are good reasons to release daily: docs are updated at same time as feats are implemented, so people see in the docs features that do not exist in the (released) code yet. Also sometimes people are able to pinpoint exact version that broke their project (less commits between tags to check).
