### ISSUE TITLE
constructs are not picklable

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#616]
.

**Comment by arekbulski** [comment]
@domenzain @schamper
Guys, could you help me out with this one? domenzain fixed pickling containers, maybe he would have better undersanding of this area. There is xfailed test case in core for it, at the bottom of test_core.

**Comment by domenzain** [comment]
Hi, thanks for all the recent work.

I must admit I have not looked through the re-implementation of `Container`.
During the week I will try to see what's going on.

In general, objects which use `__slots__` need a method to serialize and de-serialize them explicitly.

**Comment by arekbulski** [comment]
Thanks, I really appreciate it. Please notice that I am talking about pickling Constructs, not Containers. The latter was also reimplemented, and broken, and then patched using your PRs from years ago. Containers code is "patchy" but works.

**Comment by arekbulski** [comment]
On the gitter chat, someone hinted that sizeof() causes exact same error as I encountered in pickling. I will link to exact code when I receive it. Its possible that some/all problems with pickling are due to some other unknown issue.

**Comment by arekbulski** [comment]
Oh also I think I should mention, in case you get some hands-on. The tox config was unmaintainable and dropped, but you can use "make test" to run the test suite. Check makefile.

**Comment by arekbulski** [comment]
In dd3717b9e76b3e572b10538ddfced5f7f109bef0 slots were removed from almost all classes. Objects without slots are pickled differently.

**Comment by arekbulski** [comment]
It seems to me that constructs do not serialize properly due to a handful of different reasons, so I am closing this one. There is an xfailed testcase for it.
