### ISSUE TITLE
add Timestamp class

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#617]
Inspired by https://hachoir3.readthedocs.io/developer.html#list-of-field-types.

Adds soft dependency on https://pypi.python.org/pypi/arrow

Explain in https://stackoverflow.com/questions/11895382/net-datetime-to-dos-date-32-bit-conversion

Usable in
- https://github.com/Flameeyes/glucometerutils/blob/67a70d1a544c76b5352f1dcf297c93599ab307a5/glucometerutils/support/lifescan_binary_protocol.py#L59
- https://github.com/rytilahti/python-yeelightbt/blob/60dffced37c37b4f9565bfec6a04e739ac2b6370/yeelightbt/structures.py#L55

**Comment by arekbulski** [comment]
- https://github.com/Flameeyes/glucometerutils/blob/67a70d1a544c76b5352f1dcf297c93599ab307a5/glucometerutils/support/lifescan_binary_protocol.py#L59
- https://github.com/rytilahti/python-yeelightbt/blob/60dffced37c37b4f9565bfec6a04e739ac2b6370/yeelightbt/structures.py#L55

**Comment by yannayl** [comment]
Lol

**Comment by arekbulski** [comment]
Finished. Docs at
https://construct.readthedocs.io/en/latest/api/misc.html#construct.Timestamp
