### ISSUE TITLE
Unions should build as Selects

### ISSUE THREAD

**Issue by kevhill** [construct/construct#62]
I'm trying to build a tool that goes from some fairly human readable data representation such as json into tightly packed byte arrays. Unions are great 1:many mappings of bytes -> structured data, but the implementation in Construct isn't very useful for many:1 mappings of structured data -> bytes. Take the below code for example:

```
from construct import *

class QuickObj(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

test_union = Union("test_union",
    Embed(Struct("foo",
        ULInt8("a"),
        ULInt8("b")
    )),
    Embed(Struct("bar",ULInt16("c")))
)

test_ok = QuickObj(a=1,b=2)
test_union.build(test_ok)
test_fail = QuickObj(c=513)
test_union.build(test_fail)
```

Because test_fail doesn't follow the "foo" struct, the `.build()` fails, which isn't expected behavior because test_fail is a valid form of the many possible structured data representations. This basically forces you to reproduce the union twice; once with construct's `Union`, and once in your python-side object or an adapter.

I think this could be solved by having `Union().build` behave somewhat like `Select().build`. Try each subcon in order until one works.

**Comment by kevhill** [comment]
After a bit of hacking, here's the extension I came up with. I would suggest that this replace the existing `Union` Construct

```python
class MPU(Union):
    '''More Perfect Union'''

    def __init__(self, name, master, *subcons, **kw):
        Construct.__init__(self, name)
        args = [Peek(sc) for sc in subcons]
        args.append(MetaField(None, lambda ctx: master._sizeof(ctx)))
        self.parser = Struct(name, Peek(master, perform_build = True), *args)

        # above is standard __init__ from Union, but we will need self.subcons and self.include_name self.build
        self.subcons = (master,) + subcons

    def _build(self, obj, stream, context):
        '''build taken from Select, but modified to deal with non-embeded subcons'''

        for sc in self.subcons:
            # with modifications, we need a temporary obj as well
            obj2 = copy.deepcopy(obj)

            stream2 = BytesIO()
            context2 = context.__copy__()

            try:
                # modification to Select's .build taken from Struct. needed for non-embeded subcons
                if sc.conflags & self.FLAG_EMBED:
                    context2["<unnested>"] = True
                else:
                    obj2 = getattr(obj2, sc.name)
                    context2[sc.name] = obj2

                sc._build(obj2, stream2, context2)
            except Exception:
                pass
            else:
                context.__update__(context2)
                temp_str = stream2.getvalue()
                padding = '\x00' * (self._sizeof(context) - len(temp_str))
                stream.write(temp_str + padding)
                return
        raise SelectError("no subconstruct matched", obj)

    def _sizeof(self, context):
        return max([sc.sizeof(context) for sc in self.subcons])
```

**Comment by arekbulski** [comment]
You should submit this code as a Pull Request and add unit tests.

**Comment by arekbulski** [comment]
Thing is, Union was meant to always build from the **first subcon**, not any of them. Quote from documentation. What you propose is a feature request, no bug there. Still, it is worth considering.

> a set of overlapping fields (like unions in C). when parsing,
> all fields read the same data; when building, only the first subcon
> (called "master") is used.
>

**Comment by arekbulski** [comment]
I propose that we add a keyword argument that defaults to None, in which case the first subcon building without exception is allowed to put into the stream, otherwise the subcon is selected by int or name.

**Comment by kevhill** [comment]
Unfortunately the project I was working on moved to protocol buffers to manage passing data, so I'm not using construct any more. You are welcome to claim the PR for yourself if you would like to do so.

**Comment by arekbulski** [comment]
I incorporated your code into the Union class and added appropriate tests. :cake:
