### ISSUE TITLE
remove StringsAsBytes and set global encoding

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#638]
String* classes would then only work with encodings, and result in unicode objects.
I am going to drop set global encoding while at it.

**Comment by arekbulski** [comment]
@yannayl @Schamper
Guys, I could use some input on this one. Anyone?

**Comment by yannayl** [comment]
No idea, really.

**Comment by Schamper** [comment]
What would be the recommended way of getting a (optionally prefixed or null terminated) byte string at that point? I use this heavily.

**Comment by arekbulski** [comment]
PascalString~Prefixed
CString~???

Have you considered just using ascii or utf8 there?

@Schamper  Could you show me your project where you use it? I would like to see how its being used. I will do my best to recommend some useful alternatives before removing features.

I dont quite understand why would anyone use bytestrings for using text, like names titles addresses. Unicode has been around for DECADES people. If you are still catching up to that fact...

**Comment by Schamper** [comment]
It's not my protocol to define.. ;) unfortunately it's not public at this time, but will be soon'ish. Imagine a UUID field which is represented in bytes, not characters. Or just other binary fields that are better represented using a byte string instead of an array. E.g. An embedded X509 DER certificate.

**Comment by arekbulski** [comment]
UUID is fixed-length, you can just use Bytes(16) for that.

**Comment by Schamper** [comment]
Right. Take my second example in that case. Another thing in this protocol is a protocol specific identifier which is length prefixed, and can be represented in both string and bytes.

**Comment by arekbulski** [comment]
In second, use Prefixed(GreedyBytes) hm?

**Comment by arekbulski** [comment]
String classes do not accept either unicode or bytes, they accept only one (as specified). String(StringsAsBytes) wont accept a unicode literal, and vice versa. 

Perhaps you were using String classes for what should have been Bytes?

**Comment by Schamper** [comment]
I know, I just meant in the protocol. E.g. I have a message that takes it one way and another message that takes it the other way. Just giving examples of where I need byte strings.

**Comment by arekbulski** [comment]
I would advise having an Adapter that "coerces" data, so its unicode/bytes on input, always bytes on output, or so. I have a feeling that the problem is in your project not doing strings right, not the Construct. But its hard to talk about something you havent even specs of. If you cant publish the code in question, feel free to email me a private copy, GPG encrypted if needed, for private discussion.

**Comment by arekbulski** [comment]
Finished.
