### ISSUE TITLE
remove LazyField and LazyBound

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#640]
This removes all lazy classe from the core.

**Comment by yannayl** [comment]
Is it *that* useless?

**Comment by arekbulski** [comment]
Yeah, after second and tertiary thoughts, it is. OnDemand is a lousy (no pun) implementation, a half measure that doesnt really do anything useful. What you need is the new lazy semantics, everything that is currently in the library is shit. Out with it. Time to shove it out the barn.

**Comment by yannayl** [comment]
Do you intend on implementing the new lazy semantics in the foreseeable future?

**Comment by arekbulski** [comment]
Yes, probably within a month. 

For regular parsing, whatever you read with OnDemand, you can just as well read it directly. And for CTF kind of job, you need something with way more bang, or sophistication, than that.

**Comment by yannayl** [comment]
Yup

**Comment by arekbulski** [comment]
I am having a funny feeling here, a dejavu. You might be thinking this guy is dropping features like a  boss, but if you look at 2.8 changelog, I am barely doing housekeeping.
https://construct.readthedocs.io/en/latest/transition28.html

**Comment by yannayl** [comment]
Yes, it was a major change. I remember how surprised I was. I think it justified a major version change as well. The API was entirely incompatible.

**Comment by yannayl** [comment]
The convention I am used to for x.y.z version (X- Major, Y - Minor, Z - secondary minor):
Major version change - everything is different
Minor version change - features added
Secondary Minor - bug fixes

**Comment by arekbulski** [comment]
Thanks but you dont need to explain semantic versioning to me. Its just that Construct3 is a different (abandoned) project so (years ago) I simply decided to use a different versining system. First is gonna be always 2, second signifies major changes like 2.8 you know, 2.9 compiler, 2.10 maybe lazy parsing, third is each release. Thats also why 2.8.20->2.9.21. 
There are huge projects like Kaitai that go from 0.7 to 0.8 while doubling their features. The number doesnt mean how much was added, nor how much was broken in this case. Its just a formal system.

**Comment by yannayl** [comment]
Sorry, I didn't mean to sound condescending, just to explain my surprise. I understand the constraints

**Comment by arekbulski** [comment]
No worry, I just vented myself. You dont think you are the first person that came here to explain to me how versioning should be done, the *proper way*, do you?...

**Comment by yannayl** [comment]
No, of course not. Actually, I wasn't even complaining. I am very grateful to you for maintaining and improving the project and screw  formal versioning. It's an interpreted language and the project uses git.
Just whenever there is a chance of misunderstanding I assume the other side is ignorant of everything. Not because I think so, because it's practically better than assuming the other side is omniscient. I also expect to be treated the same way. From my experience it's an effective way to reduce misunderstandings. Especially that we have never met and I don't know your background.
And here is somewhat related xkcd, just because I like it :) https://xkcd.com/1053/

**Comment by arekbulski** [comment]
Interesting, someone came to the chat and asked about something that could be parsed using LazyBound. I am not sure if it should be dropped after all. 

> What would be a good way to represent a recursive structure of blocks that look like`<block> := <length> <ID> <content | block>`? I am having trouble structuring my declarations because the form and size of the content depends on the ID that precedes it. As an additional complication, I don't know all the possible IDs or what they mean.

**Comment by yannayl** [comment]
Right! That's how it used to be. I knew I used it once but didn't remember when.

**Comment by arekbulski** [comment]
LazyField removed.

**Comment by arekbulski** [comment]
LazyBound updated, especially docs:
https://construct.readthedocs.io/en/latest/lazy.html

**Comment by yannayl** [comment]
Yes. They are much better :)

However, I think you can drop the note and example about how to evaluate it with a loop. The purpose of using construct is to avoid hand written parser (as much as possible) and the loop solution does the exact opposite. It's also not declarative and one must write different code for building and parsing. All in all it's a cumbersome hack to overcome a limitation that doesn't exist. So I don't think it should be part of the docs.


I think we should make a distinction between "Lazy Definition" - definition of data which is resolved only when parsing supported by the LazyBound construct. And "Lazy Parsing" which is what I called "truly lazy parsing" in #549. Just to keep the semantics in the project and issues consistent.

**Comment by arekbulski** [comment]
Semantics means behavior, I think the word you meant is terminology (or phraseology).  :)

**Comment by yannayl** [comment]
Yes! Thanks for making it clear :)

**Comment by arekbulski** [comment]
Of course, differentiating between those 2 words would also be terminology. :grin: Just felt like pointing out.
