### ISSUE TITLE
Struct upgrade: insert subcons into context

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#659]
There was an (invalid) example on the chat that gave me an idea. Suppose you have a struct where 2nd field wants to use 1st field sizeof() within parameter. This aint possible because constructs (subcons) arent in the context dict, only parsed values are. Its also not possible to refer to 1st field at all, since its inlined. Example:
```py
Struct(
    "count"/Byte,
    "b"/Bytes(10-this.count.sizeof()),
    # this.count is an integer, not Construct instance
)
```
With proposed chanes, this would be a valid example:
```py
Struct(
    "count"/Byte,
    "b"/Bytes(10-this._subcons.count.sizeof()),
)
```
Thanks to @Kylotan .

**Comment by arekbulski** [comment]
Finished adding it, but fails tests.
```py3
_____________________________________ test_struct_exposing_members ______________________________________

    def test_struct_exposing_members():
        d = Struct(
            "count" / Byte,
>           "data" / Bytes(this.count - this._subcons.count.sizeof()),
        )
E       TypeError: __call__() missing 1 required positional argument: 'obj'


tests/test_core.py:398: TypeError
```

**Comment by arekbulski** [comment]
Finished, docs at
https://construct.readthedocs.io/en/latest/meta.html#refering-to-inlined-constructs
https://construct.readthedocs.io/en/latest/api/structs.html#construct.Struct

**Comment by arekbulski** [comment]
For the record, this feature cannot be superseded by #669 because without lazy-bounding subcons, you cannot reference another inlined field, since entire Struct doesnt exist in namespace yet.

**Comment by yannayl** [comment]
Docs look good. I would stylized the word _this_ in the when saying "*this* expression is not supported" to clarify it means the context object and not the literal English word.

**Comment by arekbulski** [comment]
Right, thanks for catching that. Been to sleepy to write straight. Fixed that.

**Comment by Kylotan** [comment]
Is this pushed to pip? I just updated to 2.9.34 but get errors like `TypeError: __call__() missing 1 required positional argument: 'obj'` when I add an expression like `"UnparsedLeafData" / Bytes(this.Length - this._subcons.BlockID.sizeof())`.

**Comment by arekbulski** [comment]
Yes, it was shipped to pypi. If you look at the example, you need to "lambdafy it".
`Bytes(lambda this: this.Length - this._subcons.BlockID.sizeof())`
https://construct.readthedocs.io/en/latest/api/structs.html#construct.Struct
