### ISSUE TITLE
Enum semantics: return int-convertible string, integer if no mapping

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#663]
This solves the problem of removed default parameter. If no mapping is found, it returns an integer because it can build from integers as well. Equality of integer with a string label (like enum1.label1) is also valid and results False (no exception raised).

**Comment by yannayl** [comment]
Isn't that a continuation of #597?

**Comment by arekbulski** [comment]
Well yeah it is. (nods) Its related, not same feature exactly. You would be able to use **both** below, and **regardless** if parses into BitwisableString (if mapping found) or integer (otherwise): 

- `parsedvalue == "aaaaa"` 
- `int(parsedvalue) == 1` 

This is an effort to remedy the missing default parameter, which I believe was both necessary and had wrong semantics (thats why it was removed).

**Comment by arekbulski** [comment]
Finished. Could you review docs?
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum

**Comment by yannayl** [comment]
Docs look good.

I still feel that string-convertible int would be a little better (as the default value is int as well). But I don't think it matters that much.

English is not my forte, but the style of this sentence bothers me:
"This class supports exposing member labels as attributes, as integer-convertible strings." Putting "as" twice in the same sentence feels wrong. I would write "as attributes which are..." (in EnumFlag also).

p.s. typo in "processing files": "which cannot be parsed or build" should be "built"

**Comment by arekbulski** [comment]
What do you mean by string-convertible int would be a little better?

Ah yeah, build and built are just some spelling niuance. Like color and colour. British american australian differences and whatnot. Twice "as" is not wrong in a technical languague, because its two separate meanings.

**Comment by arekbulski** [comment]
Ah string-integer as opposed to integer-string? That would break current semantics and therefore every project using Enum. I guess that never stopped me before but... strings are better than integers when used as enum objects-alike. Notice that entire Python runtime uses strings as constants (eg. seek whence) not integers.
