### ISSUE TITLE
redesign Switch, remove/replace default parameter

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#667]
I have some mixed feelings about Switch. I dont like the default parameter the way it is, Enum class had similar api and I removed that one with success. I would like to remove default and either 
- do Pass implicitly when no mapping found or 
- add strict=False boolean parameter that would make it either Pass or raise error if no mapping found

Additional details
- Note that neither Enum or Switch was designed (intentionally) to be a strict check against a limited set of values. Its purpose is to allow branching, not checking. Thats why implicit pass would be acceptable. This library purpose is generating parsers, not apps. Its implied that if checks are reaaally necessary, then the app will go to much greater lenghts to verify data than that.
- Also neither was designed (intentionally) to map wildcards to values, like Enum returning "default" string or Switch returning default subcon. Those were historical design decisions of previous developer, not mine. 
- EmbeddedSwitch has no default, it implies Pass.

@yannayl @schamper @mcscope
Have you encountered any usecases where non-Pass default was actually needed?

Docs at
https://construct.readthedocs.io/en/latest/api/conditional.html#construct.Switch
https://construct.readthedocs.io/en/latest/api/conditional.html#construct.EmbeddedSwitch
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum

**Comment by Schamper** [comment]
I have no code where a non-Pass default is needed.

**Comment by yannayl** [comment]
Ditto. Though it doesn't mean too much

**Comment by arekbulski** [comment]
Ha ha, @yannayl  was right on the money. Yes, I fully implemented the changes, even updated the test cases. Then I run tests and find out that several examples use non-pass default... so I left the default parameter in place, but changed it to Pass by default. So its a partial.

Thank you guys for input.

**Comment by arekbulski** [comment]
Finished, docs at
https://construct.readthedocs.io/en/latest/api/conditional.html#construct.Switch
