### ISSUE TITLE
need logo designer

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#668]
I sketched a logo, but I could use someone who does graphics professionally. @greycat Could you refer me to your designer? Would he be willing to draw one for me too?

Logo sketch:
![sketch-edited](https://user-images.githubusercontent.com/5385838/36469219-bbc308fa-16e6-11e8-9250-5eced5beb7e7.png)

**Comment by GreyCat** [comment]
@arekbulski You can ask him yourself — https://twitter.com/vervalkon. Sorry, no, I won't be referring you.
