### ISSUE TITLE
Struct exposing subcons as attributes

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#669]
Currently, for example to use Enum exposing labels as attributes feature, the Enum must be declared outside (not inlined) like so:
```py3
enum = Enum(Byte, giraffe=789)
st = Struct("animal"/enum)
st.build(dict(animal=enum.giraffe))
```
If Struct would expose subcons as attributes:
```py3
st = Struct("animal"/Enum(Byte, giraffe=789))
st.build(dict(animal=st.animal.giraffe))
```
Notes:
- does not supersede #597 or #659 
- Thanks to @yannayl for inventing the Enum attributes feature

**Comment by arekbulski** [comment]
Finished. Docs at
https://construct.readthedocs.io/en/latest/meta.html#refering-to-inlined-constructs

**Comment by yannayl** [comment]
Cool idea. Just saying it wasn't a genuine invention, just what I'm used to from other OO languages with namespaces (namely Java/C# enums and C++ scoped enumeration).
