### ISSUE TITLE
problem with Optional construct

### ISSUE THREAD

**Issue by rand0musr** [construct/construct#67]
Hello,

according to the docs the Optional construct allows a default value, however i could not get that to work, was it removed ? any other way of doing this ? that would allow me to make an empty structure with default values, then parse it to fill in the checksum and other fields.

http://construct.readthedocs.org/en/latest/misc.html

**Comment by arekbulski** [comment]
Give us some code that fails or submit a unit test directly. Then we can do something about it.

**Comment by arekbulski** [comment]
I think you misunderstood how Optional works. When building, either the subcon builds OK or it puts nothing on the stream. Whan you are trying to do seems to be `Select`.
