### ISSUE TITLE
Deserialize to numpy array 

### ISSUE THREAD

**Issue by pzoltowski** [construct/construct#671]
What is the easiest way to deserialize to numpy.array instead of construct.Array? The following format worked for me but I would prefer to deserialise instead to numpy.array with numpy element type e.g. numpy.uint8:

`Struct("rows" / Int32ub, "cols" / Int32ub, "pixels" / Array(this.rows * this.cols, Byte),)`

**Comment by arekbulski** [comment]
[Numpy](https://construct.readthedocs.io/en/latest/api/misc.html#construct.Numpy) would let you serialize shape and dtype, but the data format is not simple. Its doesnt produce smallest blobs (but within reason) and you can forget about any portability, like parsing it with non-python code. [Pickled](https://construct.readthedocs.io/en/latest/api/misc.html#construct.Pickled) is more general version, you could serialize a list, or list of lists. That takes care of shape but not dtype, and its not compact either.

[Computed](https://construct.readthedocs.io/en/latest/api/misc.html#construct.Computed) could be added after pixels to transform the list into ndarray, but it would only do for parsing. 
`Computed(lambda this: numpy.array(this.pixels, numpy.uint8).reshape((this.cols,this.rows))`
[Rebuild](https://construct.readthedocs.io/en/latest/api/misc.html#construct.Rebuild) could do what previous doesnt, turn ndarray into pixels-input.
`Rebuild(pixels, lambda this: numpy.tolist(this.pixels.flatten())`

You could write a proper adapter for doing those 2 things. 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html

**Comment by arekbulski** [comment]
Actually an adapter would not work because it would have access only to the object but not context (the rows cols fields). But [ExprAdapter](https://construct.readthedocs.io/en/latest/api/adapters.html#construct.ExprAdapter) would work fine, you already have the lambdas.
