### ISSUE TITLE
swap bits order in BitsInteger

### ISSUE THREAD

**Issue by nikeix** [construct/construct#672]
Why `swapped` is available only for multiples of 8bits? I needed to swap each `BitStruct` field bit order,  and i couldn't unless i removed `length & 7` check. Please consider finding a solution for bit-order reversing.

**Comment by arekbulski** [comment]
Can you give me a minimalistic code (use case) that uses this feature? Smaller the better.

**Comment by arekbulski** [comment]
People have already asked similiar questions like this one. Particularly #315 #415 . The short summary is, what you are asking is gibberish. Little endianness by definition means swapping octects. What you are asking is swapping octects in non-octets data. If you are actually serious about it, then you need to provide a clear code example that would use it, and define the semantics of swapping octets in non-octets data. 

Check if [ByteSwapped](https://construct.readthedocs.io/en/latest/api/tunneling.html#construct.ByteSwapped) works for you.

**Comment by yannayl** [comment]
I'm not very familiar with details here, but how hard it is to parse middle endian encoded integers for example
https://en.m.wikipedia.org/wiki/Endianness#Middle-endian

**Comment by arekbulski** [comment]
If you read the first sentence, you realise that middle-endian is a generic term for many encodings, and neither is modern or popular nowadays. More importantly, middle-endian is still octect-aligned.

**Comment by yannayl** [comment]
I vaguely remember from GSM something we called "middle endian" and it was nibble aligned for some reason. I missed that the wiki page was byte aligned. It was shit, btw, and there is no real need to support it generically in the project.
Maybe it's the SMS timestamp which is nibble reversed binary coded decimal. Really, I have no idea why they have to re invent the wheel every time (I do know the justification for big/little endian though).
I also worked on a protocol where we had 17 bits timestamp and nothing was aligned to anything and it was a nightmare.
Just very unsatisfying examples I have for when such a thing can be useful.

Anywho, the project is extensible enough imho and if I ever find myself in such a nightmare again I think I will manage.

**Comment by arekbulski** [comment]
For BCD you would need to write your own construct, and for nibble reversal you can use Restreamed. Also 17-bit timestamps of whatever fields would not be a problem within Bitwise, aligned or not. So what is exactly the reason behind little-endianness?

**Comment by yannayl** [comment]
No idea. Everything was horrible in that format. I think I'm repressing it ever happened.
