### ISSUE TITLE
Parse stream until its end

### ISSUE THREAD

**Issue by HL94DXU** [construct/construct#673]
![Image of BAD C0FFEE](https://i.imgur.com/E5p5MaK.png)

Suppose we have a binary file format which is made up of structs with the following form:
`my_struct = Struct(
    "block_length" / Byte,
    "block" / Bytes(this.block_length)
  )`
(This is a popular pattern with many binary file formats, although usually the header includes not just the length.)

It would be great if _construct_, and specifically the _parse_stream_ function, would include a Pythonic/idiomatic way to read such files block by block.
(Currently there's not support for this, because there's no support for knowing when we reach the EOF.)
__________________________________________________________________________________________

The current methods to read such files, which I'm aware of, are quite cumbersome:

1. Read the block length/header separately.
2. Use _parse_stream_, and catch the exception which, as far as I've tested, changes between _construct_ versions.
(For example, in _construct_ 2.9.34 it is "construct.core.StreamError: could not read enough bytes, expected 1, found 0".
Even if you'd want to catch it, catching StreamError alone would be unwise, and catching StreamError with the explicit exception message would be repulsive.)
3. Avoid using _parse_stream_ altogether.

Possible solutions:

1. Throw an EOF exception (to be mentioned explicitly in _parse_stream_'s documentation).
I tend to go for this solution.
2. Return _False_ or _''_. This will be similar to how Python's built-in _read_ function works:
```
    while True:
        file_byte = f.read(1)
        if not file_byte:
            break
```

These are just examples. I think that any solution would be great, and I'd love to hear your opinion on the subject.

Thank you.

**Comment by arekbulski** [comment]
From the terminology you are using, I have an impression that you have absolutely no idea how this library works (or how to use it). You keep talking about `parse_stream` specifically, there is nothing important about it, `parse` uses same exact code when parsing. Both are just thin wrappers to same code. If you want to be proficient with construct, then I suggest reading the entire tutorial:
https://construct.readthedocs.io/en/latest/#user-guide

The solutions you mention dont tell me squat what exactly you want to be done. If the struct you pasted is what you consider the `block`, and you have an array of blocks of unknown count (concatenated blocks), then [GreedyRange](https://construct.readthedocs.io/en/latest/api/repeaters.html#construct.GreedyRange) is what you need. 

Just on side note, if lenght field is directly before data, you can use [Prefixed](https://construct.readthedocs.io/en/latest/api/tunneling.html#construct.Prefixed).

**Comment by HL94DXU** [comment]
Thank you for your response.

> The solutions you mention dont tell me squat what exactly you want to be done.

The goal is to read a file block by block (where a block is the second field in the struct I've pasted), and to be able to process each individual block immediately after reading it.

> If the struct you pasted is what you consider the block, and you have an array of blocks of unknown count (concatenated blocks), then GreedyRange is what you need.

As far as I understand, by using GreedyRange (or similar constructs, for that matter) one is coerced to read the entire file, and only then process the blocks one by one.  
This is useful for some scenarios, but undesirable for others (for example, one might want to be able to terminate the program at any given moment, or to start receiving results immediately).
I specifically mentioned_parse_stream_ since it does almost exactly what's needed, but the problem is that it does not handle EOF in a well-defined manner.

**Comment by arekbulski** [comment]
The [parse_stream docstring](https://construct.readthedocs.io/en/latest/api/abstract.html#construct.Construct.parse_stream) doesnt mention anything about EOF exception. The current (and probably way forward) way of catching EOF is StreamError. 

You noticed that the exceptions have changed recently, but you make it sound like it was changing from version to version. StreamError is the intended way of finding EOF, [among 4 causes](https://construct.readthedocs.io/en/latest/api/bytes.html#construct.Bytes). "StreamError – requested reading negative amount, could not read enough bytes, requested writing different amount than actual data, or could not write all bytes". First might be triggered by corrupted data, second is EOF, third and fourth do not apply to parsing.

Yes, GreedyRange does parsell all data before returning it. Currently the only way to parse and process interchangably would be parse_stream. It might be a good idea to consider adding a hook system of sorts, callbacks that are attached to constructs, that are triggered on each successful parsing. This would let you use GreedyRange and process each block before further parsing. 

![zrzut ekranu z 2018-03-03 19-45-50](https://user-images.githubusercontent.com/5385838/36937983-7ee5b120-1f1b-11e8-8988-8dfc55109ffa.png)

**Comment by arekbulski** [comment]
The [parse_stream docstring](https://construct.readthedocs.io/en/latest/api/abstract.html#construct.Construct.parse_stream) doesnt mention anything about EOF exception. The current (and way forward) intended way of catching EOF is StreamError. 

You noticed that the exceptions have changed recently, but you make it sound like it was changing from version to version. StreamError is the intended way of finding EOF, [among 4 causes](https://construct.readthedocs.io/en/latest/api/bytes.html#construct.Bytes). "StreamError – requested reading negative amount, could not read enough bytes, requested writing different amount than actual data, or could not write all bytes". First might be triggered by corrupted data, second is EOF, third and fourth do not apply to parsing. See [example](https://user-images.githubusercontent.com/5385838/36937983-7ee5b120-1f1b-11e8-8988-8dfc55109ffa.png).

Yes, GreedyRange does parse all data before returning it. Currently the only way to parse and process interchangably would be parse_stream. It might be a good idea to consider adding a hook system of sorts, callbacks that are attached to constructs, that are triggered on each successful parsing. This would let you use GreedyRange and process each block before further parsing. 

I added #678 feature request for hooks.

**Comment by arekbulski** [comment]
The parsed hook and GreedyRange discard option were added. Check docs:
https://construct.readthedocs.io/en/latest/basics.html#processing-on-the-fly
