### ISSUE TITLE
BitStruct with default fields doesn't fill context with default values

### ISSUE THREAD

**Issue by Schamper** [construct/construct#676]
Take the following struct as example:
```
a = Struct(
     'a' / Struct(
         'b' / Default(BitsInteger(8), 0)
     ),
     Probe(),
     'c' / Default(Array(this.a.b, Int32ub), [])
)

a.build({})
```

Prints the following on probe:
```--------------------------------------------------
Probe, path is (building), into is None
Container: 
    a = Container: 
        b = 0
--------------------------------------------------
```

Which shows the correct default value has been added to the context.

However, when using a `BitStruct`, this doesn't happen:
```
a = Struct(
     'a' / BitStruct(
         'b' / Default(BitsInteger(8), 0)
     ),
     Probe(),
     'c' / Default(Array(this.a.b, Int32ub), [])
)

a.build({})
```

Probe prints the following and an exception is thrown, because `a` is `None`:
```--------------------------------------------------
Probe, path is (building), into is None
Container: 
    a = None
--------------------------------------------------
```

I believe the error to be on the following line, but I'm not sure if that line is intended for some reason or not: https://github.com/construct/construct/blob/47980b03dafc6df3b9c8547748fbdaa866cc44de/construct/core.py#L4381
Shouldn't that return `buildret`?

**Comment by arekbulski** [comment]
Confirmed and fixed, see 636efac835ac9a460cee8b201e84f965827f0a62. Test case has 2 fields, because bitwise actually uses 2 different classes depending if subcon is fixed-size or variable-size, it uses either TranformData or Restreamed. Both are checked.

**Comment by arekbulski** [comment]
Fixed.

**Comment by Schamper** [comment]
Thanks! That fixed it.
