### ISSUE TITLE
Compiled enum throws KeyError while parsing if no mapping exists

### ISSUE THREAD

**Issue by ius** [construct/construct#677]
Parsing an enum using a compiled instance fails if no mapping exists:

```python
#!/usr/bin/env python3
from construct import *

print(Enum(Byte).parse(b'\xff'))
print(Enum(Byte).compile().parse(b'\xff'))
```

```cmd
$ python testcase.py 
255
Traceback (most recent call last):
  File "testcase.py", line 5, in <module>
    print(Enum(Byte).compile().parse(b'\xff'))
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 244, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 261, in parse_stream
    return self._parse(stream, context, "(parsing)")
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 607, in _parse
    return self.parsefunc(stream, context)
  File "/home/user/construct_compile_target_8ba6da622212019d.py", line 28, in parseall
KeyError: 255
```

(I'm on v2.9.35, though git master is only a few commits ahead)

**Comment by arekbulski** [comment]
Bug confirmed, added a test case. You actually also found a second bug, which is that compiled Enum doesnt return IntegerString instances. Thank you for reporting it.

**Comment by arekbulski** [comment]
Both fixed in 6b8e4120a1875abb9a8dcedd177aa0d3e6d41f18.

**Comment by ius** [comment]
Thanks! Unfortunately it seems to trigger another bug:

```python
print(Struct(a=Enum(Byte,b=0xff)).parse(b'\xff'))
````
````
Container: 
    a = ntegerString.new(255, 'b' (total 1)
````
The root cause appears to be in `Container`
https://github.com/construct/construct/blob/e386936a4f7c39f7f7319d461c3ec5f1293946cb/construct/lib/containers.py#L198-L208

Because `IntegerString` subclasses `str`, `repr` is called instead of `str`. My local fix is:
```python
if isinstance(v, stringtypes) and not issubclass(type(v), stringtypes)
```

... but I'm not sure whether that's the best solution

**Comment by arekbulski** [comment]
I would not consider this a bug. The output is correct, although the "total 1" could be omitted. I could make it show something more readable like `(enum) b =255` , what do you think?

**Comment by arekbulski** [comment]
Fixed in 52f2e4506d0ada7534a1f163f3b5882d81d78bf3.

**Comment by arekbulski** [comment]
Fixed. Notice that unmapped integer is also displayed as (enum).

**Comment by ius** [comment]
Works fine - and its actually similar to what it used to be, which was what I was trying to point out. v2.9.35 just prints the enum string if it exists, or the integer if there's no mapping instead of the `repr` I was seeing.

Do note that there was some small other issue my example showcased (but I didn't mention it explicitly) - the `repr` output of `IntegerString` had it's first and last character stripped off by `reprbytes` - you kindly edited my post to fix it, but it was the actual output I got. Anyway, I believe that's no longer an issue either now.

Thanks again!

**Comment by arekbulski** [comment]
Yes, people make typos when typing and pasting code (and so do I...) so obviously I assumed that was it. Just to give you a hint, you could explicitly point out that its "(sic)" which is latin short for "original spelling", or better yet, explicitly point out how its wrong.
