### ISSUE TITLE
How can I handle large files efficiently?

### ISSUE THREAD

**Issue by fake-name** [construct/construct#68]
I'm trying to use construct to parse *large* binary files, often in the range of 500 MBytes.

It works, but it's *extremely* slow and uses enormous quantities of RAM. A 42.4 MByte file takes ~1 minute to load, and consumes about 2.5 **gigabytes** of ram once the file is fully loaded.

How does one handle large files effectively with construct?

My parser is as follows

import construct as c

```
COMBO_PARSER = c.GreedyRange(
	c.Struct("sweep",
		c.SNInt32("segment_sz"),

		c.Struct("header",
			c.SNInt32("frame"),
			c.SNInt32("combo"),
			c.NFloat64("time"),
			c.SNInt32("tx"),
			c.SNInt32("rx"),
			c.SNInt32("tx_p"),
			c.SNInt32("rx_p"),
			c.SNInt32("gain"),
		),

		c.Struct("serial",
				c.UNInt8("serial_present"),
				c.If(
					lambda ctx:ctx['serial_present'] > 0,
					c.Array(CONST__BYTESPerTelemetry, c.SNInt8("serial_data"))
				)
			),

		c.Struct("telemetry",
				c.NFloat64("comboDelay"),
				c.NFloat64("x"),
				c.NFloat64("y"),
				c.NFloat64("distance"),


				c.NFloat32("theta"),
				c.NFloat32("velocity"),
				c.NFloat32("turnRate"),
				c.Padding(4),

				c.NFloat64("timeStamp"),

				c.UNInt32("LSE"),
				c.UNInt32("RSE"),
				c.UNInt32("flipperSE"),

				c.UNInt16("sonar"),
				c.UNInt8("temperature"),

				c.Padding(1)
			),
		c.Struct("stitch_points",
				c.SNInt32("stitch_count"),
				c.Array(lambda ctx: ctx.stitch_count,
					c.Struct("stitch_point",
							c.SNInt32("I"),
							c.NFloat32("Q"),
							c.NFloat32("is_stitch"),

						)
					)
			),
		c.UNInt32("data_point_cnt"),

		c.Array(lambda ctx:ctx.data_point_cnt,
			c.Struct("data_point_arr",
					c.NFloat32("I"),
					c.NFloat32("Q"),
				)
			),
		c.Anchor("data_end"),
	)
)
```

**Comment by harvimt** [comment]
I started using construct, but ended up using David Beazley's trick in Python Cookbook to parse files lazily (similar in spirit to construct in many ways) with memory mapped files.

It's quite fast because it's lazy, I made a [youtube stream](https://www.youtube.com/user/infinull), but never released the source code. (I remember oblivion.esm being ~ 50M which I suppose is still an order or magnitude smaller than 500M)

Also those videos probably need to be watched on time lapse mode. :-)

depending on what you want to do with the data, that might be a good approach.

**Comment by fake-name** [comment]
@harvimt - Is there a resource for what your describing that *doesn't* involve watching a video? That sounds interesting.

**Comment by harvimt** [comment]
This is the code I used as a reference: http://chimera.labs.oreilly.com/books/1230000000393/ch06.html#_solution_105

But I made some improvements to it (using memory mapped files & `memoryview`)

I really should publish that code somewhere.

**Comment by harvimt** [comment]
Actually, now that I'm looking at it again the only improvements I made were being able to parse ascii encoded string data. (the strings in .esp/.esm files are pascal strings), using a memory mapped file instead of loading the entire file into a buffer, and some stuff to handle the funkiness Bethesda put into their formats.

**Comment by arekbulski** [comment]
I think what we need is substructures having both `fixedsize() -> int or None` and `size() -> int`. If all fields in a struct are fixed size then entire struct is fixed size, therefore range classes can be made lazy. Only when you access at particular index the appropriate bytes are parsed. This behavior can be by default or by option. If a field is variable length then everything built on top of it will be variable length. I will implement it.

**Comment by fake-name** [comment]
Well, I've moved on after writing some C extension stuff to get the performance I need, so I'm not really in a position to do tests any more.

Feel free to close the issue when you feel it's appropriate to do so.

**Comment by arekbulski** [comment]
I would write a parser in Cython. But the issue is still relevant, other people might stumble upon the same thing. 

Could you provide some in memory generated data blob so we could write a manual test for performance testing? `combo.parse(bytes(50mb)` or something.

**Comment by arekbulski** [comment]
After current API changes are finished, code will be turned into Cython. That should speed things up. Untill then, one could write a lazy version of Struct or Range. Anyone feel free to write it.

**Comment by arekbulski** [comment]
Actually LazyStruct was just implemented. There should be LazyRange later on.
