### ISSUE TITLE
Repeat Struct parsing

### ISSUE THREAD

**Issue by xamix** [construct/construct#682]
Hello,

For information I'm a beginner with Python and Construct,
I want to test the Construct library on a protocol which provide 3 type of frame which have a common header (HEAD declared as a Struct).
I'm a bit confused for one of my frame which repeat a Struct layout in the frame (i.e Frame3):
```
Frame1 
+------+------------+
| Head |  StructF1  |
+------+------------+

Frame2
+------+------------+
| Head |   StructF2 |
+------+------------+

Frame3
+------+-------------+------------+------------+------------+--------------+
| Head |       StructCount        | StructF3_1 | StructF3_2 | StructF3_... |
+------+-------------+------------+------------+------------+--------------+
```
As seen here, the StructF3 is repeated StructCount time across a full frame.
How can I declare that for parsing this type of frame?

**Comment by arekbulski** [comment]
Please dont take it the wrong way, but maybe you should have at least familiarized yourself with the documentation first. It covers all basics. I dont mind that you need help with some basics and reach out, but on this kind of technical forum its expected of people to be technical (as in show some level of professionalism), and by that I mean its expected that you browse the documentation throughly before getting someone to hold your hand. The "RTFM" acronym is so cliche that if it didnt make you look stupid, it would look funny. 

Array class is what you need. I realise that the examples dont show it, but after reading the documentation you should already know that most parameters can be context lambdas. Something like `Array(this.header.countfield, StructF3)`. The second link should help you with context lambdas.

https://construct.readthedocs.io/en/latest/basics.html#repeaters
https://construct.readthedocs.io/en/latest/meta.html

Feel free to ask anything, but please dont ask things that would be obvious after just glancing over the docs.

**Comment by xamix** [comment]
Hello,

Thank you for your answer,
I understand your point of view and I assure to you that I already make a pass over the documentation  and example. It's fairly big but well documented library, maybe with a lot of concept which must be learn.
What I was looking for is more an answer to the question "is it possible to do that" with the library before starting deep learing with this library and integrating it to my project. 

After a first pass to the documentation It was not obvious to me that it will be possible because I was lost under all the other concept of the library which seem to be also possibilities to do what I want.

As you pointed out, no example seem to be presented for use context lambda inside an Array.

Anyway  your answer "Array(this.header.countfield, StructF3)" put me on the right track and I really thank you for that. 

I promize that I will investigate more to make it work since I now know it's possible.
If in any case I'm in trouble I will copy here part of my code in order to get int from someone.

Thank you for your time.

**Comment by arekbulski** [comment]
If you look at this chapter:
https://construct.readthedocs.io/en/latest/meta.html#using-this-expression
"When creating an Array (“items” field), rather than specifying a constant count, you can use a previous field value as count."

**Comment by xamix** [comment]
Thank you,
I've successfully finished to parse all the frame by using "this", and "Switch" statement.

Many thanks for your help
