### ISSUE TITLE
array of Pointers

### ISSUE THREAD

**Issue by boringhexi** [construct/construct#683]
Is there an official or recommended way to read an array of pointers? I was able to do it by passing Pointer a context function that uses a global variable, but I'd like to know if there's a better way.

For example, something like:
```Pointer(Int32ul, CString)[4]```
to read the next 4 Int32uls as offsets to CStrings.

Or something fancier, like:
```Pointer(Int32ul, CString, this.chunk_offset)[this.num_strings]```
 to read the next `num_strings` Int32uls as relative offsets to CStrings, i.e. each string offset is `this.chunk_offset` + the read Int32ul offset.

**Comment by arekbulski** [comment]
Pointer offset parameter can only be a constant or a context lambda. The solution is obvious:
```py
Array(this.count, Struct(
  'offset' / Int32ul,
  'data' / Pointer(this.offset, CString('utf8')),
))
```
The recommended way of passing data from one field into another is in fact, using context lambdas.
