### ISSUE TITLE
On Windows: os.sync() not available

### ISSUE THREAD

**Issue by tuxuser** [construct/construct#687]
**Construct lib**: 2.9.37
**Python version**: 3.6.3
**OS**: Windows x86
**When does it happen:** Running **.compile()** on a struct
**Where does it work:** It is fine on linux and osx

Following error:
```
construct\core.py:412: in compile
    os.sync()
E   AttributeError: module 'os' has no attribute 'sync'
```

Line of code: [core.py line 412](https://github.com/construct/construct/blob/master/construct/core.py#L412)

**Comment by arekbulski** [comment]
Oh wow, you even filled an entire proper bug report form. The title itself would be enough. Thanks, I will fix it asap. Just on side note: its not only a matter of Windows or POSIX. Python 2 doesnt have os.sync either.

**Comment by arekbulski** [comment]
Fixed. To be shipped ASAP.

**Comment by arekbulski** [comment]
I recommend pulling bd87622572293c82abb5c5d066d7695e4adab4df, it has important fixes related to this issue.

**Comment by arekbulski** [comment]
You can pull newest from pypi. If you removed os.stat and that caused some random `__import__` errors, that bug was fixed already as well. If you need additional support, just open a new issue.
