### ISSUE TITLE
Dumping construct parser as python code

### ISSUE THREAD

**Issue by KOLANICH** [construct/construct#691]
This can be done using `ast` and `astor`.
The archeticture: every construct class must have a method dumping it into ast.
In the end the final ast is serialized into source as done in https://github.com/KOLANICH/pyxgboost/blob/master/pyxgboost/compiler.py

**Comment by arekbulski** [comment]
Sorry but I dont know why you are telling me this... Is this a suggestion for the CS->KS export tool? I dont know anything about AST or how to use it for this purpose.

**Comment by KOLANICH** [comment]
>Is this a suggestion for the CS->KS export tool?

No, it is suggestion of construct->construct exporting. Construct code is python code, right? So we can create structures dynamically, for example looping over xml.  After it we may want to export the generated construct code into python file for hand-tuning. 

> I dont know anything about AST or how to use it for this purpose.

AST is a very basic thing. It's an object representation of source code.

try
```python
import ast
with open("comparison_1_construct.py", "rt", encoding="utf-8") as f:
  print(ast.dump(ast.parse(f.read())))
```

to catch the sense.

All that you need is to dump the pieces of source code calling creation of functions and then replacing in that code some pieces with the ones extracted from your objects. And some architecture around this, of course.
