### ISSUE TITLE
Automatically switch endianness based on context?

### ISSUE THREAD

**Issue by kratsg** [construct/construct#698]
First off, thanks for all the work on this (amazing) library. I initially wrote a bulk of this code about 2-3 years ago (constructs ~2.5) and have admittedly not updated to the latest version yet, but I plan to do so soon!

Below is a packet header description that I'm trying to decode correctly.

<img width="657" alt="screenshot 2018-03-22 21 45 20" src="https://user-images.githubusercontent.com/761483/37808804-5514263e-2e1a-11e8-83ae-25721ccc1cd0.png">

What i've done in the past is [here](https://github.com/kratsg/ironman/blob/master/ironman/constructs/ipbus.py) . Specifically, I have the following short code

```python
PacketHeaderStruct = BitStruct("header",
                        OneOf(BitField("protocol_version", 4), [IPBUS_VERSION]),
                        OneOf(BitField("reserved", 4), [0x0]),
                        BitField("id", 16),
                        OneOf(BitField("byteorder", 4), [0xf]),
                        Enum(BitField("type_id", 4),
                            CONTROL = 0x0,
                            STATUS = 0x1,
                            RESEND = 0x2
                        )
)
```

and simply did some checks to make sure that I passed in a big-endian 4-byte word into this struct first:

```python
class IPBusPacket(object):
    implements(IIPBusPacket)

    def __init__(self, blob):
        self.request = None
        self.response = None
        self._raw = blob
        # if little-endian, we need to swap when reading and writing
        self.littleendian = bool((ord(self._raw[0])&0xf0)>>4 == 0xf)
        # do some flipping
        raw = self.raw
        if self.littleendian: raw = byteswap(raw)
        self.request = IPBusConstruct.parse(raw)
        self.response = IPBusConstruct.parse(raw)
```

So I decide enough is enough! I want the construct to be smart enough to handle big-endian and little-endian, and I can simply ask it for which endianness was used for input, and build the corresponding version (e.g. setting/copying the packet header over into a response packet).

Looking in the [construct docs](http://construct.readthedocs.io/en/latest/tunneling.html#endianness), I suspect I can use context to switch all the following 32b words after the packet header... but the packet header might be interpreted incorrectly... How might I do this correctly in construct, or should I wrap this entirely in logic that passes a boolean to `swapped=<bool>` in order to flip things?

**Comment by kratsg** [comment]
@arekbulski - so that's the thing, when I wrote this back in construct 2.5, there wasn't an easier way to do it then... it might be easier or more possible now -- specifically, if you just look at the screenshot, the 32b words are 4 bytes... so really, there are two 4b fields surrounding a 2 byte field, which really means that I could treat this byte-wise:

```
PacketHeaderStruct = ByteStruct(Byte, Byte(2), Byte)
```

but I would still need to be able to have the 4b/4b granularity of the bytes on the end, so that I can do something like

```python
foo = PacketHeaderStruct.parse('...')
print foo.type_id
```

The rest of the code (I linked in the issue as well) is here: https://github.com/kratsg/ironman/blob/master/ironman/constructs/ipbus.py.

**Comment by kratsg** [comment]
To also aid this, here is an example of big-endian and little-endian packet headers that should work:

```python
'big-endian': '\x20\x00\x00\xf0'
'little-endian': '\xf0\x00\x00\x20'
```

**Comment by arekbulski** [comment]
It seems like a perfect usecase for ByteSwapped.

**Comment by kratsg** [comment]
How so? Reading the docs, I managed to convert my above 2.5.X code to 2.9.39 code:

```python
PacketHeaderStruct = "header" / BitStruct(
                                  "protocol_version" / OneOf(Nibble, [IPBUS_VERSION]),
                                  "reserved" / OneOf(Nibble, [0x0]),
                                  "id" / Bytewise(Int16ub),
                                  "byteorder" / OneOf(Nibble, [0xf]),
                                  "type_id" / Enum(Nibble,
                                    CONTROL = 0x0,
                                    STATUS = 0x1,
                                    RESEND = 0x2)
)
```

and running

```python
>>> print PacketHeaderStruct.parse(b'\x20\x00\x00\xf0')
Container: 
    protocol_version = 2
    reserved = 0
    id = 0
    byteorder = 15
    type_id = (enum) CONTROL 0
>>> print ByteSwapped(PacketHeaderStruct).parse(b'\xf0\x00\x00\x20')
Container: 
    protocol_version = 2
    reserved = 0
    id = 0
    byteorder = 15
    type_id = (enum) CONTROL 0
```

but how do I get `PacketHeaderStruct` to automatically switch for me?

**Comment by arekbulski** [comment]
`IfThenElse(this.littleendian, ByteSwapped(PacketHeaderStruct), PacketHeaderStruct)`

**Comment by kratsg** [comment]
Hi, I'm still struggling in converting my code. So first, I'll address my problem with the solution:

> `IfThenElse(this.littleendian, ByteSwapped(PacketHeaderStruct), PacketHeaderStruct)`

I need to byteswap the entire packet, not just the header. But the byteswapping is determined in the header itself, so how does `this.littleendian == this.header.byteorder == 0xf` get defined if the packet header hasn't been parsed yet? The other problem is that as soon as I byteswap (including the packet header), then it looks big-endian and I've lost information about whether it was littleendian in the first place using `this.header.byteorder == 0xf`.

However, what I've been struggling with right now is adapting the `Embed(Switch)` from 2.5.X days to 2.9.X days:

```python
ReadStruct = Struct("read",
                Switch("data", lambda ctx: ctx.info_code,
                    {
                        "REQUEST": Pass,
                        "SUCCESS": Array(lambda ctx: ctx.words, UBInt32("data"))
                    },
                    default = Pass
                )
)

ControlStruct = Struct("ControlTransaction",
                    Embed(ControlHeaderStruct),
                    UBInt32("address"),
                    Embed(Switch("data", lambda ctx: ctx.type_id,
                        {
                            "READ": ReadStruct,
                            "WRITE": WriteStruct,
                        }
                    ))
)
```

has become

```python
ReadStruct = Struct(
                "data" / If(this._.header.info_code == "SUCCESS", Array(this._.header.words, Int32ub))
)

ControlStruct = "ControlTransaction" / Struct(
                    "header" / ControlHeaderStruct,
                    "address" / Int32ub,
                    "data" / If(this.header.type_id == "READ", ReadStruct),
                    StopIf(this.header.type_id == "READ"),
                    "data" / If(this.header.type_id == "WRITE", WriteStruct),
)
```

And the problem is that `ByteSwapped(ControlStruct)` gives an error: 

```
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    ByteSwapped(ControlStruct)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 4202, in ByteSwapped
    size = subcon.sizeof()
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 342, in sizeof
    return self._sizeof(context, "(sizeof)")
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 2384, in _sizeof
    return self.subcon._sizeof(context, path)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 1928, in _sizeof
    raise SizeofError("cannot calculate size, key not found in context")
construct.core.SizeofError: cannot calculate size, key not found in context
```

which seems to be related to the fact that `Array(....)` has variable byte size. The second problem with this solution is that I have a non-embedded ReadStruct, when really, I would like `ReadStruct` to be embedded, so I tried

```python
ControlStruct = "ControlTransaction" / Struct(
                    "header" / ControlHeaderStruct,
                    "address" / Int32ub,
                    Embedded(IfThenElse(this.header.type_id == "READ", ReadStruct, Struct()),
                    StopIf(this.header.type_id == "READ"),
                    Embedded(IfThenElse(this.header.type_id == "WRITE", WriteStruct, Struct()),
)
```

as done in #296 but this raises an error about

```
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct
```

so I'm not sure how this is wrong.... A MWE that breaks is

```
Struct(Embedded(IfThenElse(True, Struct(), Struct())))
```

but so does the example in the issue.

**Comment by kratsg** [comment]
Anyway, given all of these issues, I've settled upon this current structuring:

```
ControlStruct = "ControlTransaction" / Struct(
                    "header" / IfThenElse(this._.bigendian, ControlHeaderStruct, ByteSwapped(ControlHeaderStruct)),
                    "address" / IfThenElse(this._.bigendian, Int32ub, Int32ul),
                    "data" / Switch(lambda ctx: (ctx.header.type_id, ctx.header.info_code), {
                      ("READ","SUCCESS"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("NOINCREAD","SUCCESS"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("RCONFIG","SUCCESS"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("WRITE","REQUEST"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("NOINCWRITE","REQUEST"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("WCONFIG","REQUEST"): Array(this.header.words, IfThenElse(this._.bigendian, Int32ub, Int32ul)),
                      ("RMWBITS", "REQUEST"): ["and" / IfThenElse(this._.bigendian, Int32ub, Int32ul), "or" / IfThenElse(this._.bigendian, Int32ub, Int32ul)],
                      ("RMWBITS", "SUCCESS"): IfThenElse(this._.bigendian, Int32ub, Int32ul),
                      ("RMWSUM", "REQUEST"): IfThenElse(this._.bigendian, Int32sb, Int32sl),  # note: signed 32-bit for subtraction!
                      ("RMWSUM", "SUCCESS"): IfThenElse(this._.bigendian, Int32ub, Int32ul)
                    }, default=Check(lambda ctx: getattr(ctx, 'data', None) == None))
)

IPBusConstruct = "IPBusPacket" / Struct(
                    "pointer" / Pointer(3, Int8ub),
                    "bigendian" / Computed(this.pointer == 0xf0),
                    "header" / IfThenElse(this.bigendian, PacketHeaderStruct, ByteSwapped(PacketHeaderStruct)),  # defined as 'header' in context

                    "transactions" / If(lambda ctx: ctx.header.type_id == "CONTROL", GreedyRange(ControlStruct)),
                    "status" / If(lambda ctx: ctx.header.type_id == "STATUS", StatusRequestStruct),
                    "resend" / If(lambda ctx: ctx.header.type_id == "RESEND", ResendStruct),
                    Terminated
)
```

as `ByteSwapped` does not like my `Array(this.header.words, Int32ub)` portions at all. It's a little bit of copy/pasting involved, but it seems to be the only way to make it work.

**Comment by arekbulski** [comment]
What version of Construct are you using? Array is not Switch-able since long time ago. I dont understand how this code could possibly work.

Some sugar:
```py
lambda ctx: ctx.header.type_id == "CONTROL"
this.header.type_id == "CONTROL"
```
For your use:
https://construct.readthedocs.io/en/latest/api/core.html#construct.core.EmbeddedSwitch

**Comment by kratsg** [comment]
> What version of Construct are you using? Array is not Switch-able since long time ago. I dont understand how this code could possibly work.

2.9.39

**Comment by arekbulski** [comment]
Ah sorry. I am just sleepy and not very clear minded. Yes, the Switch is fine. I was still thinking of Embedded(Switch) which is a can of worms that everyone seems to be opening like it was a jar of cookies or something. Your code looks fine.

Well almost, this line isnt a Construct insance (class object) so its not valid:
`("RMWBITS", "REQUEST"): ["and" / IfThenElse(this._.bigendian, Int32ub, Int32ul), "or" / IfThenElse(this._.bigendian, Int32ub, Int32ul)],`

Also, consider:
`Switch(..., default=Error)`

**Comment by arekbulski** [comment]
You lost me entirely on this. Look, if you ask a simple question, then I will gladly give you a clear answer. But please dont make me do research into exactly how this few-thousand lines of code project of yours really works. I have a backlog of features to implement. I dont feel like dropping that on the floor so I can work on your project as well. I appreciate the links, the images, the specs, the whole nine yards, but come on, man. 

If you care much about peformance, and network protocol apps usually do, then I sugges few things: 
- use BitsInteger instead of Bytewise(Int*)
- post me the entire code for review, when its done (or some parts of it) but code, not descriptions
- look at [compilation feature ](https://construct.readthedocs.io/en/latest/compilation.html)and using pypy

**Comment by kratsg** [comment]
> I dont feel like dropping that on the floor so I can work on your project as well. I appreciate the links, the images, the specs, the whole nine yards, but come on, man.

No problem. Thanks for all the help so far.

> use BitsInteger instead of Bytewise(Int*)

I got this from here: http://construct.readthedocs.io/en/latest/bitwise.html#fields-that-work-with-bytes . Is it just a matter of using only "bit"-fields inside BitStructs and "byte"-fields inside Structs?

> post me the entire code for review, when its done (or some parts of it) but code, not descriptions

Sure. I'll come back to this issue/question later when i finish the tests.

> look at compilation feature and using pypy

Oh, this is new. Definitely will want to look at this.

**Comment by arekbulski** [comment]
> Is it just a matter of using only "bit"-fields inside BitStructs and "byte"-fields inside Structs?

You can use `Bytewise(Int32ub)` and `BitsInteger(32)` interchangably, but the 2nd form has better performance. Just for your consideration. 

> Sure. I'll come back to this issue/question later when i finish the tests.

This issue (as far as the title suggests) is about little endiannes. Please create a new issue if you post a code for review, even if its the same project. The titles should reflect the topic.

> Oh, this is new. Definitely will want to look at this.

You should check the [Transition page. ](https://construct.readthedocs.io/en/latest/transition29.html) It also mentions compilation feature.

**Comment by igiloh** [comment]
@kratsg I know this was almost a year ago - but I wonder if you ended up having a working solution that you care to share?

I'm struggling with a similar issue, and will be glad to see a working example.

**Comment by kratsg** [comment]
@igiloh : i used a variable to keep track and manually switch everywhere where needed: https://github.com/kratsg/ironman/blob/master/ironman/constructs/ipbus.py#L88-L97

**Comment by kratsg** [comment]
@igiloh - I will point out that for my given solution with `Computed`, while it wasn't readily obvious to me at first, in order to change the duck-typed object to switch the endianness -- you have to change the `duck.pointer = 0x0` in my case, rather than the `duck.bigendian = False` -- in order to switch it. The latter is a Computed variable that's computed at build-time/parse-time [in case you run into this niche case].
