### ISSUE TITLE
parsing to enum.Enum compatible enums?

### ISSUE THREAD

**Issue by girtsf** [construct/construct#699]
When I saw that documentation for `Enum` said "This class supports enum34 module.", I kind of expected that things would "just work" with the `enum` module in 3.6. E.g., I expected that the parsed values would compare to the enum class with something like this:

```
$ cat demo.py
#!/usr/bin/env python3

import enum

import construct

class Foo(enum.Enum):
    A = 1
    B = 2

E = construct.Enum(construct.Byte, Foo)

e = E.parse(b'\x01')
print('e repr: %r' % e)
print('e is Foo.A? ', e is Foo.A)

$ ./demo.py
e repr: EnumIntegerString.new(1, 'A')
e is Foo.A?  False
```

It would be nice if `construct.Enum.parse` could return "real" enum values if an enum class was passed in.

Though, since this might be a backwards-incompatible change, perhaps that could be an optional flag? Thoughts?

**Comment by arekbulski** [comment]
I have no problem with adding this feature. Parsing Enum would still result in a string, and still convertable to integer, but there is no reason why it cant be equatable to Enum objects. It would either be `==` or `is` depending on implementation details.

**Comment by arekbulski** [comment]
I should point out that this feature is somewhat superfluous. Enum (the construct) exposes values as attributes. You can easily use:
```py
e == E.A
```
Foo.A is an enum object and E.A is a string, but it does compare and is valid code.

**Comment by arekbulski** [comment]
```
$ cat demo.py 
import enum
import construct

class Foo(enum.Enum):
    A = 1
    B = 2
E = construct.Enum(construct.Byte, Foo)

e = E.parse(b'\x01')
print(e == E.A)  #valid and proper
print(e == Foo.A)  #to be implemented
print(e is Foo.A) #invalid

$ python3 demo.py 
True
False
False
```

**Comment by arekbulski** [comment]
Frankly, after giving this some thought, I am rejecting this feature. Enum34 support does not mean that using it is encouraged or endorsed or recommended in any way. If you are using Construct the way its recommended, you dont need enum34 module.
```py
animal = Enum(Byte, giraffe=1)
animal.parse(bytes(1)) == animal.giraffe
```

**Comment by larsch** [comment]
Just hit this. It surprised me that support for enum didn't mean actually being compatible with enum.Enum. Having mapping support, but not actually mapping to the underlying enum.Enum type is kind of pointless, when that type is used by the rest of the code base. Then you still need to do explicit mapping, which I really what I hoped to avoid.
