### ISSUE TITLE
More natural handling of little-endian BitStructs

### ISSUE THREAD

**Issue by Lekensteyn** [construct/construct#70]
Goal: parse a protocol with little-endian fields. Consider this hypothetical specification for 24-bit data:

| bits  | description   |
| ----- | ------------- |
| 0    | Flag 1        |
| 1    | Flag 2        |
| 03:02 | Reserved      |
| 19:04 | Number (16-bit) |
| 23:20 | Reserved 2    |

As far as I can see there is currently no way to construct a structure for this (where the number overlaps multiple fields). Perhaps this code example demonstrates the problem better:
```py
from construct import *

# Cool, very readable (big endian)!
example_struct = BitStruct("Example",
    Padding(4),                     # bits 23:20
    BitField("number", 16),         # bits 19:04
    Padding(2),                     # bits 03:02
    Bit("flag2"),                   # bit 1
    Bit("flag1")                    # bit 0
)

# WTF?
example_struct_little_endian = BitStruct("Example",
    BitField("number_lo", 4),       # bits 07:04
    Padding(2),                     # bits 03:02
    Bit("flag2"),                   # bit 1
    Bit("flag1"),                   # bit 0

    BitField("number_mi", 8),       # bits 15:08

    Padding(4),                     # bits 23:20
    BitField("number_hi", 4)        # bits 19:16
)


# Tests
data_be = b'\x0a\xbc\xd1'
data_le = b'\xd1\xbc\x0a'

# Data in network order (big endian).
testdata = Container(flag1=1, flag2=0, number=0xabcd)
data = example_struct.build(testdata)
print(data)
assert(data == data_be)

c = example_struct.parse(data)
print(c)
assert(c.flag1 == testdata.flag1)
assert(c.flag2 == testdata.flag2)
assert(c.number == testdata.number)


# Data in little endian.
testdata = Container(number_hi=0xa, flag2=0, flag1=1,
                     number_mi=0xbc, number_lo=0xd)
data = example_struct_little_endian.build(testdata)
print(data)
print(data_le)
assert(data == data_le)

c = example_struct_little_endian.parse(data)
print(c)
assert(c.flag1 == testdata.flag1)
assert(c.flag2 == testdata.flag2)
# It would be nice if this manual computation was unnecessary, so we can use
# number = c.number
number = (c.number_hi << 12) | (c.number_mi << 4) | c.number_lo
assert(number == 0xabcd)
```

It would be great if we could write a structure like:
```py
LittleEndian24BitStruct("Example",
    Bit("flag1"),                   # bit 0
    Bit("flag2"),                   # bit 1
    Padding(2),                     # bits 03:02
    BitField("number", 16),         # bits 19:04
    Padding(4)                      # bits 23:20
)
```
so it can also work where fields are overloaded to be 32-bit or 64-bit (depending on the lower bits).

The above is a toy example, in reality I somehow have to parse a larger structure containing sequences of multiple structures of varying size (16-bit, 32-bit, 64-bit).

Adapter cannot be used here as the transformation needs to be done after reading the bytes, but before converting it to an object. Maybe a (sub)construct can be used here though.

**Comment by Lekensteyn** [comment]
An adapter for the stream seems to work, it is admittedly a bit hacky:
```py
from contextlib import contextmanager

# (put definitions from first post here)

class StreamAdapter(object):
    """Perform in-place byte swaps while accessing the stream."""
    def __init__(self, stream, size):
        self.stream = stream
        self.size = size
    def write(self, data):
        with self._adjust_pos(len(data)):
            self.stream.write(data[::-1])
    def read(self, size):
        with self._adjust_pos(size):
            return self.stream.read(size)[::-1]
    @contextmanager
    def _adjust_pos(self, size):
        real_offset, next_offset = self._calc_offsets(size)
        try:
            self.stream.seek(real_offset)
            yield
        finally:
            self.stream.seek(next_offset)
    def _calc_offsets(self, size):
        assert 0 <= size <= self.size
        pos = self.stream.tell()
        skip_begin = pos % self.size
        # Calculate begin of aligned buffer, go to the end and step back "size".
        real_offset = (pos - skip_begin) + (self.size - 1) - size
        # Next position to end up after reading
        next_offset = pos + size
        return real_offset, next_offset

class ByteSwapped(Subconstruct):
    """Swap the byte order within aligned boundaries of given size.."""
    def __init__(self, subcon, size):
        Subconstruct.__init__(self, subcon)
        self.size = size
    def _parse(self, stream, context):
        stream = self._wrapped_stream(stream)
        return self.subcon._parse(stream, context)
    def _build(self, obj, stream, context):
        stream = self._wrapped_stream(stream)
        return self.subcon._build(obj, stream, context)
    def _wrapped_stream(self, stream):
        return StreamAdapter(stream, self.size)

example_struct_adapted = ByteSwapped(example_struct, 4)
testdata = Container(flag1=1, flag2=0, number=0xabcd)

c = example_struct_adapted.parse(data_le)
print(c)
assert(c.flag1 == testdata.flag1)
assert(c.flag2 == testdata.flag2)
assert(c.number == testdata.number)

data = example_struct_adapted.build(testdata)
print(data)
print(data_le)
assert(data == data_le)
```

**Comment by arekbulski** [comment]
`IfThenElse` can be used to make fields depend on a predicate. It would be more handy if we added two new classes so one would define a predicate once and other would take two subcons and figure the switch from the parent. 

I do not understant your post completely. You are talking of both overlapping fields, reordering fields in a struct, and making switches. Which is it? 

Could you add a readable test case to the suite and submit a pull request?

**Comment by Lekensteyn** [comment]
IfThenElse would only help if two alternatives are needed. In the given example, there only one case (byte order swapping).

The stated problem is that current types are only suitable to models structures in big-endian encoding (network byte order). If little-endian encoding is involved, then you have to do ugly field re-ordering (and still fail to describe fields spanning part of multiple bytes).

The suggested "solution" felt fragile, but it is what I use in https://github.com/Lekensteyn/acpi-stuff/blob/master/mxm/parse_mxm.py. However I am not comfortable submitting it as it seems to work only in a narrow case. Any better suggestions to handle the problem of **little endian encodings**?

**Comment by arekbulski** [comment]
Are to talking abount little-endian integers? Because so far I had an impression that you are talking about little-endian structures which to me seems nothing else than reordering fields. We already have `UBInt8` and `ULInt8`. Aint that what you describe? Sources are here:
https://github.com/construct/construct/blob/0a83e3134cc9acf9d1ffcd2fb7cc964512e27d2d/construct/macros.py#L129

**Comment by arekbulski** [comment]
Could you write a unit test and submit a pull request? And I mean a unit test, a proper class deriving from unittest, etc. Not a snippet.

**Comment by Lekensteyn** [comment]
Not just normal integers, but bitfields. What is not clear from the example in the first post? A big-endian integer with bitfields can easily be described, this is however not the case for a little-endian integer with bitfields.

Since there is no implementation for such bitfields, I cannot write a proper testcase for it either... the snippet just demonstrates the issue with a possible half-baked workaround. Have I defined the problem well enough or is there still some uncertainty?

**Comment by arekbulski** [comment]
I finally understand it, thanks you. Just so you know, I learned of this module yesterday and became a maintainer the same day so please forgive me for not catching up too fast. =}

I will get on top of this as soon as possible.

**Comment by arekbulski** [comment]
Are you talking about swapping bytes before the bytes are divided by Bitwise? Because little endian integers like ULInt32 work just fine within a Bitwise.

**Comment by Lekensteyn** [comment]
Yes, it is specifically about swapping before dividing into further fields. (Interpretation of a 32-bit LE word as a bitfield)

**Comment by arekbulski** [comment]
This was just added in 5dddf88ab448021f99c47f95e4ca82c383e960f9.

**Comment by Lekensteyn** [comment]
Thanks, I can verify that it is a drop-in replacement for the previous code.
