### ISSUE TITLE
EmbeddedSwitch could use StopIfs to allow subcons with same name

### ISSUE THREAD

**Issue by kratsg** [construct/construct#700]
Plagiarizing from http://construct.readthedocs.io/en/latest/api/conditional.html#construct.EmbeddedSwitch -- you can use `StopIf` with `If(...)` to effectively reproduce the EmbeddedSwitch without a significant amount of hacking... and in fact, would replicate standard switch/case/break statements.

```python
d = EmbeddedSwitch(
    Struct(
        "type" / Byte,
    ),
    this.type,
    {
        0: Struct("name" / PascalString(Byte, "utf8")),
        1: Struct("name" / Byte),
    }
)

# generates essentially following
d = Struct(
    "type" / Byte,
    "name" / If(this.type == 0, PascalString(Byte, "utf8")),
    StopIf(this.type == 0),
    "name" / If(this.type == 1, Byte),
    StopIf(this.type == 1)
)

# both parse like following
>>> d.parse(b"\x00\x00")
Container(type=0)(name=u'')
>>> d.parse(b"\x01\x00")
Container(type=1)(name=0)
```

**Comment by arekbulski** [comment]
Interesting. The problem however is that, the result dict will contain some garbage Nones due to unselected switch cases. If you use StopIfs, then it would have some garbage fields and some not. It makes the result kind of incomplete, even if what makes it complete is effectively garbage. 

That said, I think this feature should be merged. Thanks for the improvement.

**Comment by kratsg** [comment]
> Interesting. The problem however is that, the result dict will contain some garbage Nones due to unselected switch cases. If you use StopIfs, then it would have some garbage fields and some not. It makes the result kind of incomplete, even if what makes it complete is effectively garbage.

But the Ifs() all refer to the same field, so the None of a previous gets overridden with the success of another.

**Comment by arekbulski** [comment]
It does solve the issue of duplicated names yes, but it also creates another issue.
```py3
>>> d = EmbeddedSwitch(
...     Struct(
...         "type" / Byte,
...     ),
...     this.type,
...     {
...         1: Struct("name" / Byte),
...         2: Struct("garbage" / Byte),
...         3: Struct("name" / Byte),
...     }
... )
>>> 
>>> d = Struct(
...     "type" / Byte,
...     "name" / If(this.type == 1, Byte),
...     StopIf(this.type == 1),
...     "garbage" / If(this.type == 2, Byte),
...     StopIf(this.type == 2),
...     "name" / If(this.type == 3, Byte),
...     StopIf(this.type == 3),
... )
>>> 
>>> print(d.parse(b'\x01\xff'))
Container: 
    type = 1
    name = 255
>>> print(d.parse(b'\x02\xff'))
Container: 
    type = 2
    name = None
    garbage = 255
>>> print(d.parse(b'\x03\xff'))
Container: 
    type = 3
    name = 255
    garbage = None
```

**Comment by arekbulski** [comment]
Actually I could simply add a construct like `ContextPurge` that would remove all entries from the context after each failed switch case. 
```py
>>> d = Struct(
...     "type" / Byte,
...     "name" / If(this.type == 1, Byte),
...     StopIf(this.type == 1),
...     ContextPurge,
...     "garbage" / If(this.type == 2, Byte),
...     StopIf(this.type == 2),
...     ContextPurge,
...     "name" / If(this.type == 3, Byte),
...     StopIf(this.type == 3),
...     ContextPurge,
... )
```

**Comment by arekbulski** [comment]
Actually its not the context entries that should be purged but the resulting dictionary. Those two are similar but not the same object. Just making a note, for someone reading previous and wondering.

**Comment by wtc-peg** [comment]
Hello all,
Experience some problems to port from 2.8 to 2.9 for conditional embedded fields.
I tried the previous proposition in "my" project as "MyEmbeddedSwitch" (See below).
And it works. Except for the RemoveEntry that i don't know  how to do implement. 
Any proposition ?

`def MyEmbeddedSwitch(merged, selector, mapping):
	merged2 = list(merged.subcons)
	for key,st in mapping.items():
		for sc in st.subcons:
			merged2.append(sc.name / If(selector == key, sc))
		merged2.append(StopIf(selector == key))
		#merged2.append(RemoveEntry(sc.name))
	return Struct(*merged2)`

**Comment by wtc-peg** [comment]
Hello all,
Here is an implementation of the solution suggested by "arkbulski". 
Unfortunately it seems Ok when probing ... but KO in result:
- Keys that should have been deleted are still there (None)
- Orderred container has kept the order of first encoutered keys (For my futur use case, I need possibility to order some fields according to previous selector)


```
$ py EmbededSwitchTest.py
LAST PROBE OK:
--------------------------------------------------
Probe, path is (parsing) -> None, into is None
Container:
    SELECTOR = 1
    TESTA = 1
    TESTB = 1
    TESTC = 1
    TESTD = 1
--------------------------------------------------
RESULT swapped !:
Container:
    SELECTOR = 1
    UNUSED1 = None
    TESTD = 1
    TESTC = 1
    TESTB = 1
    TESTA = 1
    UNUSED2 = None
```
 


```
from construct import *
from binascii import hexlify,unhexlify

class RemoveEntry(Construct):
	def __init__(self, scName):
		super(RemoveEntry, self).__init__()
		self.flagbuildnone = True
		self.scName = scName

	def _parse(self, stream, context, path):
		#print (context.__keys_order__)
		result = context.pop(self.scName)
		#print (context.__keys_order__)

	# def _build(self, obj, stream, context, path):

def MyEmbeddedSwitch(merged, selector, mapping):
	merged2 = list(merged.subcons)
	for key,st in mapping.items():
		for sc in st.subcons:
			merged2.append(sc.name / If(selector == key, sc))
		merged2.append(StopIf(selector == key))
		for sc in st.subcons:
			merged2.append(RemoveEntry(sc.name))
	#print ("--- EmbeddedSwitch Merge -------")
	#print(merged2)
	#print ("--------------------------------")
	return Struct(*merged2)

	
TESTEmbededSwitch = MyEmbeddedSwitch(
	Struct(
		"SELECTOR"      / Int8ub
	),
	this.SELECTOR,
	{
		0: Struct(
			"UNUSED1" / Computed(0),
			"TESTD" / Computed(0),
			"TESTC" / Computed(0),
			"TESTB" / Computed(0),
			"TESTA" / Computed(0),
			"UNUSED2" / Computed(0),
		),
		
		1: Struct (
			"TESTA" / Computed(1),
			"TESTB" / Computed(1),
			"TESTC" / Computed(1),
			"TESTD" / Computed(1),
			Probe()
		)
	}
)
print("LAST PROBE OK:")
result = TESTEmbededSwitch.parse(unhexlify("01"))
print("RESULT swapped !:")
print(result)
```

**Comment by arekbulski** [comment]
Unfortunately I am not maintaining this project anymore but this ticket seems to be still alive somehow so... tell me if this thing is still hot (otherwise I will close it promptly). Then we can talk about merging anything.

**Comment by wtc-peg** [comment]
Hello Arekbulski,
First really thanks for the work you've already done on construct. 
It's very sad you stop maintaining this project. We discovered it more than one year ago and found it so nice !! We decided to make an open source bidirectional implementation of ours sensors codec and it works quite very well.
And tell all of us what good be a good motivation for you to continue working on it ?

So, about current post, 
Last month I came back to it seing the new 2.9 wishing to try compiled solution... unfortunately it has cost me quite a lot of time to re-write our solution as somme elements like "embedded" were really not working the same way than before... but finally I've got again a quite working solution except that it would works definitely beter if the embedded switch was working fine...

Then I decided to spend a while to try to implement your suggestion(StopIf and RemoveEntry in my previous post), but I must still be wrong because it does ot let things in the correct order ... If you've got any suggestion ...

And again many thanks for your work !

**Comment by arekbulski** [comment]
Thank you for some kind words. Its nice to see someone out there actually appreciates what I done.

Regarding maintanance: I am currently low on money so I have to work on paid projects. But even if you would setup some sort of Construct-fund, I am still hesitant to work on it. The library has, as far as I think about it, everything it needs.

Embedded is the prime biggest fuckup this library has, it should have never existed in the first place. If I resume maintanance, then my first action will be removing it entirely. I know this will break every project out there, but you need to realize that Embedded was a broken idea in the first place. Implementing it requires hacking code, its not clean like the rest of library. And then people started embedding Switches which is even less sane. 

My advice: refactor your code and stop embedding at all.

**Comment by wtc-peg** [comment]
About embedding ... that's so I did when I start rewriting using 2.9 ;O)
So, you gave the answer to your original question ... the ticket should be closed.

I still hope that some early users will show their enthusiasm on your work ...

**Comment by arekbulski** [comment]
And so I am going to do it, man! I am going to remove Embedded and EmbeddedSwitch.

**Comment by arekbulski** [comment]
It happened. Embed is gone. This closes this ticket.
