### ISSUE TITLE
Can Switch be stricter about keys with the wrong values?

### ISSUE THREAD

**Issue by kratsg** [construct/construct#702]
MWE:

```python
from construct import Switch, Struct, Int8ub, Probe, this

p = Struct(
  "type" / Int8ub,
  "data" / Switch(this.type, {
    0: Int8ub
  }), 
  Probe()
)

p.parse(b'\x00\xAB')
p.build({'type': 0, 'data': 171})
```

gives output like

```
--------------------------------------------------
Probe, path is (parsing), into is None
Container: 
    type = 0
    data = 171
--------------------------------------------------
--------------------------------------------------
Probe, path is (building), into is None
Container: 
    data = 171
    type = 0
--------------------------------------------------
```

which is fine. It works as expected... however,  it still parses (and ignores other bytes/values) for

```
p.parse(b'\x01\xAB')
p.build({'type': 1, 'data': 171})
```

Is there a way to force strictness in both directions? One way I've thought about doing it right now is to add a default case to `Switch` in this example, so that it `Check` makes building stricter and `Terminated` makes parsing stricter:

```python
p = Struct(
  "type" / Int8ub,
  "data" / Switch(this.type, {
    0: Int8ub
  }, default=Check(lambda ctx: getattr(ctx, 'data', None) == None)), 
  Terminated,
  Probe()
)
```

and these now cause validation errors correctly, also making `Switch` a bit stricter. Is this the correct way to do it or am I thinking about it wrong?

**Comment by arekbulski** [comment]
Switch docs clearly say that default can be Error. Is that what you are asking?
https://construct.readthedocs.io/en/latest/api/conditional.html#construct.Switch
https://construct.readthedocs.io/en/latest/api/misc.html#construct.Error

**Comment by kratsg** [comment]
> Switch docs clearly say that default can be Error. Is that what you are asking?
> https://construct.readthedocs.io/en/latest/api/conditional.html#construct.Switch
> https://construct.readthedocs.io/en/latest/api/misc.html#construct.Error

This will fix things more for parsing, rather than building won't it? E.G. I want it to be able to allow all other values except `0` to be accepted as long as `data = None`... so maybe `Error` isn't perfect for this case.

**Comment by arekbulski** [comment]
`If(this.type == 0, Pass, Error)`

**Comment by arekbulski** [comment]
You can write it 2 ways:
```py
IfThenElse(this.type == 0, Pass, Error)
If(this.type != 0, Error)
```
