### ISSUE TITLE
VarInt._build return wrong

### ISSUE THREAD

**Issue by yaozong-zhu** [construct/construct#705]
```py3
from construct import *

x = Container(namelen = 400, name = b'1'*400)
Struct('namelen' / VarInt, 'name' / Bytes(this.namelen)).build(x)

construct.core.StreamError: bytes object of wrong length, expected 3, found 400
```

**Comment by arekbulski** [comment]
Sorry, your code was unreadable so I took the liberty of changing it. Please take effort to post as readable code as humanly possible, otherwise it might be looked upon as garbages/spaghetti.

The could looks valid, I will investigate and get back to you.

**Comment by arekbulski** [comment]
The bug was recently introduced when fixing Rebuild implementation. Fixed and to be shipped ASAP.

**Comment by yaozong-zhu** [comment]
Great. Close issue.
