### ISSUE TITLE
Add EnumIntegerString __eq__

### ISSUE THREAD

**Issue by Schamper** [construct/construct#707]
Take the following example:
```
e = Enum(Byte, a=1)
r = e.parse(b'\x01')

assert r == 'a'  # True
assert r == 1   # Fails
```

I suggest something like this in EnumIntegerString:
```
def __eq__(self, other):
    return str(self) == other or int(self) == other
```

Thoughts?

**Comment by arekbulski** [comment]
Sure, I will add it at earliest convenience, unless you need it right away.

**Comment by arekbulski** [comment]
With current implementation, you can use `assert int(r) == 1` but I will add your feature.

**Comment by Schamper** [comment]
No rush. I actually ended up with a different method altogether, but I think this might still be useful.

In case you're curious, in our project we have a custom enum type. E.g.:
```
class Example(Enum):
    a = 1
    b = 2

assert Example.a == 1
assert Example[1] == 'a'
assert Example['a'] == 1
```

Why? Don't remember, was the best option at the time. However, due to this, we are incompatible with Construct `Enum`. Even if this patch was added, things like `Switch` still won't work.

The only thing we really wanted was the visual feedback in structure dumps. So I ended up writing a custom adapter instead. Basically boils down to:
```
class XEnumInt(int):
    def __new__(cls, *args, **kwargs):
        enum = kwargs.pop('enum')
        res = int.__new__(cls, *args, **kwargs)
        res.enum = enum
        return res

    def __repr__(self):
        return '<{} {}=0x{:x}>'.format(self.enum.__name__, self.enum[self], self)


class XEnum(Adapter):
    def __init__(self, subcon, enum):
        super(XEnum, self).__init__(subcon)
        self.enum = enum

    def _encode(self, obj, context, path):
        return obj

    def _decode(self, obj, context, path):
        return XEnumInt(obj, enum=self.enum)
```

This now allows us to do:
```
class Example(Enum):
    a = 1
    b = 2

x = XStruct(
    'a' / XEnum(Byte, Example)
)

res = x.parse(b'\x01')
print(res)
# <XStructWrap: None>(Container:
#     a = <Example a=0x1>)
print(res.build())
# b'\x01'
```

**Comment by arekbulski** [comment]
Instead of an adapter, you could simply fork (copy and modify) the Enum class implementation. So you import other classes from Construct but override Enum with your own (modified) class. Get it?

**Comment by arekbulski** [comment]
I am too busy/lazy to implement this in a forseeable future. Would you be willing to implement this one for me and PR it?

**Comment by arekbulski** [comment]
I am not maintaining it anymore. And also I am totally through with the enum module at this point. I dont like it, and I dont know why people want so much to integrate it. Just use string values like it was meant to use it, eh.
