### ISSUE TITLE
Values need to be provided to `Anchor` types when Structs are built.

### ISSUE THREAD

**Issue by zblach** [construct/construct#71]
Consider the following definition:

```python
from hashlib import sha512
from construct import Struct, PascalString, Bytes, Terminator, UBInt16, Validator, Container, Anchor, Pass, ValidationError


class ChecksumValidator(Validator):
    def _validate(self, obj, ctx):
        return obj == sha512(ctx.string).hexdigest()

class ChecksumLengthValidator(Validator):
    def _validate(self, obj, ctx):
        return ctx.checksum_end - ctx.checksum_start == 128

SumString = Struct(
    "checksum_string",
    PascalString('string', length_field=UBInt16('length')),
    Anchor('checksum_start'),
    ChecksumValidator(Bytes('checksum', 128)),
    Anchor('checksum_end'),
    ChecksumLengthValidator(Pass),
    Terminator
)

def make_string(string):
    checksum = sha512(string).hexdigest()
    return SumString.build(Container(string=string, checksum=checksum))

```

Calls to `make_string` will fail, as `checksum_start` and `checksum_end` values aren't provided to the `Container` in `SumString.build`. The actual values passed are irrelevant, as they're properly populated when deserializing.

Also, calling `ChecksumLengthValidator` on `Pass` is kinda hacky.

**Comment by harvimt** [comment]
This example makes no sense to me. I don't think this is how Anchors were intended to be used at all. `Bytes` will always be 128 because it's defined to be 128. On the other hand I don't see why it shouldn't work.

Also is the checksum encoded as a hex string in ascii? That's... strange, and if it is, you should use a fixed string with an ascii encoding and note bytes to make it more clear that's what's going on.

**Comment by zblach** [comment]
It's a contrived example. In practice, I've got a field that speaks about a payload length, and I'd like to validate that this field is populated correctly.

**Comment by zblach** [comment]
Here's a less contrived example:

```python
class ValidatePayloadLength(Validator):
    def _validate(self, obj, ctx):
        return ctx.payload_end - ctx.payload_start == ctx.payload_len == len(ctx.raw_payload)

LessContrivedExample = Struct(
    "less_contrived_example",
    UBInt16('struct_type'),
    UBInt16('payload_len'),
    Anchor('payload_start'),
    Peek(String('raw_payload', length=lambda ctx: ctx.payload_len)),
    PascalString("name"),
    PascalString("occupation"),
    Anchor('payload_end'),
    UBInt16('serial'),
    ValidatePayloadLength(Pass),
    Terminator,
)

def make_structure(name, occupation, serial):
    payload_len = len(name) + len(occupation) + 2  # 2 = PascalString overhead for both fields
    return LessContrivedExample.build(Container(name=name, occupation=occupation, payload_len=payload_len, serial=serial, struct_type=9001, raw_payload=None, payload_start=None, payload_end=None))
```

`raw_payload` is the raw version of the structure we care to validate. `payload_len` is the expected length of this data. Yes, it's redundant to measure the length of `raw_payload` in the validator, but I'll actually be using that field to calculate a checksum later.

**Comment by arekbulski** [comment]
Anchors within Structs no longer need values when building. This was fixed within last few days. I just added a test showing your example code works fine without the container containing None for anchors.
Look at commit dc7c08cc33c0a3e99ab06ffd13f12cf7824fba5a.

However, checksum building and verification could be added to the framework. But you should create a new issue for that.

**Comment by arekbulski** [comment]
Code in question should be rewritten using newest fields like AnchorRange and Checksum.
