### ISSUE TITLE
Why does Struct.build with an optional field needs key=None in parameter dict

### ISSUE THREAD

**Issue by hetsch** [construct/construct#710]
I think that my problem is more a question of the right usage and you accept such question in the issue tracker .

I use Python 3.6.4 and construct 2.9.45 and have the following simplified code:

```
import enum
import construct as cs

@enum.unique
class Commands(enum.IntEnum):
    CMD_1 = 0
    CMD_2 = 1

@enum.unique
class State(enum.IntEnum):
    NONE = 0
    SUCCESS = 1
    ERROR = 2

cmd = cs.Struct(
    'type' / cs.Enum(cs.Byte, Commands),
    'state' / cs.Enum(cs.Byte, State)
)

result = cs.Struct(
    'foo' / cs.Byte,
    'bar' / cs.Byte,
    'baz' / cs.Byte
)

s = cs.Padded(64, cs.Struct(
    cs.Embedded(cmd),
    'result' / cs.Optional(result)
))

# Working both
print(s.parse(b'\x01\x00\x02\x03\x04' + (b'\x00' * 59)))

print(s.build(dict(
    type=Commands.CMD_2,
    state=State.NONE,
    result=None
)))
```

Both calls, `build` and `parse`, work perfectly fine above but removing the **optional** `result` key from the `build` function's parameter dict raises the following exception:

```
print(s.build(dict(
    type=Commands.CMD_2,
    state=State.NONE
)))

# Traceback (most recent call last):
#   File "test_nested_optional_struct.py", line 49, in <module>
#     state=State.NONE
#   File "/Volumes/Data/Users/xxx/.pyenv/versions/xxx/lib/python3.6/site-packages/construct/core.py", line 352, in build
#     self.build_stream(obj, stream, **contextkw)
#   File "/Volumes/Data/Users/xxx/.pyenv/versions/xxx/lib/python3.6/site-packages/construct/core.py", line 364, in build_stream
#     self._build(obj, stream, context, "(building)")
#   File "/Volumes/Data/Users/xxx/.pyenv/versions/xxx/lib/python3.6/site-packages/construct/core.py", line 3889, in _build
#     buildret = self.subcon._build(obj, stream, context, path)
#   File "/Volumes/Data/Users/xxx/.pyenv/versions/xxx/lib/python3.6/site-packages/construct/core.py", line 1998, in _build
#     subobj = obj[sc.name] # raises KeyError
# KeyError: 'result'
```

The exception message is clear - it does not find the `result` key in the parameter dict. From my point of view it would be convenient if one must not define a dict key and set it's value to `None` if the field is optional. So I wanted to ask you if this is intended behavior or if there is another way you can think of how to achieve this? Million thanks! (I  tried to use `Default` and friends but no luck so far ...)

P.S.: The reason I'm asking is that I sometimes have more optional fields, if it simply would be the one, I would be perfectly fine for me to declare the optional key.

**Comment by arekbulski** [comment]
It seems to me that you just looked at the word "optional" and imagined the rest of it, an RTFM fail. The Optional wrapper has clear semantics, and not requiring a build value is not one of these. The docs says that it attemps to build from a given value and fails gracefully if any error is encountered. For example, Optional(Int) build(None) would raise FormatFieldError, parsing less than needed amount of bytes would raise StreamError. These are the scenarios in which Optional "attempts" to build. It still needs a value to build from. If Optional is inside a Struct, that means there needs to be a key for it.

What you seem to be asking for is Default like following. If all fields in the struct are Defaults then entire struct is Default-alike, meaning it doesnt need a key in build value dictionary.
```py
result = Struct('x' / Default(0, Byte))
outer = Struct('r' / result)
outer.build({})
outer.build(dict(r=dict(x=1)))
```

**Comment by hetsch** [comment]
Thank you @arekbulski, clear answer, thank's. Sorry, interpreted Optional the wrong way - my fault!
