### ISSUE TITLE
PaddedString() should possibly ignore garbage

### ISSUE THREAD

**Issue by papperlapapp** [construct/construct#711]
Python 3.6.4, construct 2.9.45

Recently I had to parse some legacy data, which I thought would be a perfect match for ``PaddedString``: a (guaranteed) zero-terminated ascii string within a bigger fixed len field. Unfortunatly, on parsing ``PaddedString`` stumbled upon the garbage after the trailing zero:
```
>>> print(PaddedString(3, "ascii").parse(b"x\x00\xff"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 2: ordinal not in range(128)
```
Apart from supporting more encodings (in my case ``latin1`` would have been perfect), how about adding another keyword argument, e.g. ``padding=`` with

value  | meaning
------ | -----------
strict   | raise if garbage found
ignore | ignore any garbage after the pad unit

**Comment by arekbulski** [comment]
You seem to be using it wrong. PaddedString chops null \0 bytes from the end (right side). \xff is not such a byte so trimming ends there. What you described seems to be:
```py
FixedSized(3, CString("ascii"))
```

**Comment by papperlapapp** [comment]
Oh, I see. Thanks. What's the reason for restricting the encodings to a subset of what Python supports?

**Comment by arekbulski** [comment]
CString implementation: it needs to find the terminating null bytes (2 or 4 of them in case of UTF16 and UTF32). It needs to know how many nulls are considered as terminating for the selected encoding. You cannot ask Python runtime that, so it only works for encodings that I manually give values for.

**Comment by papperlapapp** [comment]
> Do you need me to add some additional support like latin-1?

Not really. I'm o.k. with setting
```
construct.possiblestringencodings["latin1"]=1
```
in my script but I'd rather not fiddling with library internals.
