### ISSUE TITLE
Enum() parsing should return enums, not strings

### ISSUE THREAD

**Issue by papperlapapp** [construct/construct#712]
Python 3.6.4, construct 2.9.45

How about ``Enum()`` parsing returns a real Python enum instead of strings when defined with an enum? I find the current behavior a bit non-intuitive. E.g. an ``enum.IntEnum`` can directly be used as integer, whereas I have to explicitly use ``int()`` on the parsed ``construct.Enum()``.

**Comment by arekbulski** [comment]
Fair point. Honestly, thats just how it always was. Enum always returned a string, although if there is no mapping then it returns an integer instead of just failing. If you want to use integers, then use Int instead of Enum, or use int(parsedvalue).

**Comment by papperlapapp** [comment]
O.k., it's not a big issue for me. I'm currently using adapters  for conversion. ``construct.Enum`` just seemed to be the right fit for ``enum.Enum`` ;-)
