### ISSUE TITLE
Equivalent of Embedded(Switch()) in construct > 2.9

### ISSUE THREAD

**Issue by hetsch** [construct/construct#713]
Hi, I'm updating a codebase to construct >2.9. Reading the docs and some entries on the gitter chat, it seems that the `Embedded(Switch(...))` functionality was drop recently. The code I've inherited heavily relies on this functionality. As far as I can read from the docs, `EmbeddedSwitch` seems to be the successor and *"behave the same way as you would expect from embedded Switch"*. In the code below, I tried to recreate the behavior.

```py
    # See: https://github.com/construct/construct/issues/631
    # See: http://doc.kaitai.io/user_guide.html#tlv
    # See: http://doc.kaitai.io/user_guide.html#switch-advanced
    
    head = cs.Struct(
        # Some header data ...
    )
    
    foo = cs.Struct(
        'foo_1' / cs.Default(cs.Byte, 0),
        'foo_2' / cs.Default(cs.Byte, 0)
    )
    
    bar = cs.Struct(
        'bar_1' / cs.Default(cs.Byte, 0),
        'bar_2' / cs.Default(cs.Byte, 0)
    )
    
    ###########################################################################
    # 2.8 Version of construct
    # pip install --upgrade https://github.com/construct/construct/tarball/v2.8.22#egg=construct
    ###########################################################################
    
    body = cs.Struct(
        'component' / cs.Default(cs.Enum(cs.Int8ul,
                 foo=0,
                 bar=1
            ), 0),
        ),
        cs.Embedded(cs.Switch(
            cs.this.component,
            {
                'foo': foo,
                'bar': bar
            },
            cs.Pass
        ))
    )
    
    packet = cs.Struct(
        cs.Embedded(head),
        cs.Embedded(body)
    )
    
    print(packet.parse(b'\x00\x01\x01'))
    # Container:
    #     component = foo (total 3)
    #     foo_1 = 1
    #     foo_2 = 1
    
    
    ###########################################################################
    # 2.9.45 Version of construct
    # pip install --upgrade https://github.com/construct/construct/tarball/2.9.45#egg=construct
    ###########################################################################
    
    body = cs.EmbeddedSwitch(
        cs.Struct(
            'component' / cs.Default(cs.Enum(cs.Int8ul,
                 foo=0,
                 bar=1
            ), 0),
        ),
        cs.this.component,
        {
            'foo': foo,
            'bar': bar
        }
    )
    
    packet = cs.Struct(
        cs.Embedded(head),
        cs.Embedded(body)
    )
    
    print(packet.parse(b'\x00\x01\x01'))
    # Container:
    #     component = (enum) foo 0
    #     foo_1 = 1
    #     foo_2 = 1
    #     bar_1 = None <-- Additional entry compared to Embedded(Switch()) in < 2.9
    #     bar_2 = None <-- Additional entry compared to Embedded(Switch()) in < 2.9
```
If I'm using `EmbeddedSwitch` as intendend, there are two additional keys (bar_1 and bar_2) compared to the `Embedded(Switch())` construct. Any ideas how to get rid of these additional entries?

**Comment by arekbulski** [comment]
Yes, the issue is already known to me. If you look at #700 the solution there would remove those "dead entries". But the library is not under active development atm so I would not be implementing this unless you need it right away?

**Comment by arekbulski** [comment]
Okies, I will treat this ticket as first priority. I started implementing it but the test suite fails in some bizarre way so it needs some more work than I expected. I will get back to you when and if I get this resolved.

**Comment by hetsch** [comment]
@arekbulski Don't want to be rude but did you have some time to work on this issue? I stumbled again over this problem and just wanted to ask you ...

**Comment by arekbulski** [comment]
Sorry but I wont be able to work on Construct for forseeable future. I am accepting PRs but not writing updates myself anymore.

**Comment by hetsch** [comment]
OK. Thanks so far! Will try to dive into the source ...

**Comment by hardkrash** [comment]
If I take time to fix this issue again will a PR be accepted?

**Comment by arekbulski** [comment]
If you are asking about this ticket, probably yes, if you are asking about the old issue of dynamic buildfromnone flag that was related to Embedded Switch, probably no since I already rejected the proposed solution a long time ago. It depends on what exactly you are proposing.
