### ISSUE TITLE
how to read C++ bit structure

### ISSUE THREAD

**Issue by gupie** [construct/construct#714]
I have the following C++ structure:

struct S {
    int a : 5;
    int b : 7;
};

Setting a to 0 and b to 0xFF results in the following bit pattern, 0xe0ef:

          `11100000 00001111`
          `bbbaaaaa  ----bbbb`

The first 3 bits of the first byte are for field b, next 5 bits are for field. The remaining 4 bits of b are at the end of the second byte.

How would I read this in using Construct? I have tried the following:

Test = BitStruct(
    'a' / BitsInteger(5),
    'b' / BitsInteger(7),
    Padding(4),
)

But Construct expect:

          `aaaaabbb  bbbb----`

**Comment by arekbulski** [comment]
Frankly I am suprised that C/CPP compilers do this kind of thing. This layout is, as far as I see it, weird insane and just plain wrong. You could write your own Construct-derived class that would read 2 bytes, convert it using lib module to bits, rotate the bits, convert those back to bytes, then feed it to the BitStruct that you have. Its parse method could be made, more or less, a one-liner.

**Comment by gupie** [comment]
Thank you for your reply. Note I am using Visual Studio 2010 with default packing and alignment. I don't know how reliable the following link is but it says "Little endian machines pack bitfields from least significant byte to most." The compiler seems to be doing this.

http://mjfrazer.org/mjfrazer/bitfields/

**Comment by arekbulski** [comment]
The page doesnt explain how fields are split into separate bytes (non continous bits). Anyhow, if you can map the bits yourself by hand, I think you could use a trick: have Bitwise fetch bytes and convert to bits, then use Pointers to read individual fields:
```py
FixedSized(2, BitStruct(
'f1' / Pointer(..., BitsInteger(5)),
'f2' / Pointer(..., BitsInteger(7)),
Padding(4),
))
```
I havent tested this code, its just overall idea. Also then there is the issue of glueing bits from 2 bitstrings, not sure how to do that. It would be possible to add a class that joins bitstrings.

**Comment by gupie** [comment]
Thanks. I am only exploring how Construct works at the moment. Starting with what I expected to be a straightforward case. I am looking to ultimately generate GPS navigation data which contains a lot of bit fields of various types. Construct looks like it will be very useful for this. I should not need to address the complication of C++ bit field issues for this task.
