### ISSUE TITLE
Embedding BitStructs

### ISSUE THREAD

**Issue by reox** [construct/construct#716]
Embedding BitStructs is not possible at the moment. But it might be useful. I try to parse a fileformat which stores sizes and type in a single byte. In this case it would be nice to do something like this:
```
from construct import *

fmt = Struct(
        Embedded(BitStruct(
            "size" / BitsInteger(3),
            "type" / BitsInteger(5),
            )),
        "value" / Array(this.size, Int8ul),
        )
fmt.parse(b"\x40\x23\x42")
```

Instead of
```
from construct import *

fmt = Struct(
        "s" / BitStruct(
            "size" / BitsInteger(3),
            "type" / BitsInteger(5),
            ),
        "value" / Array(this.s.size, Int8ul),
        )
print(fmt.parse(b"\x40\x23\x42"))
```

Is there any reason why embedding is not possible in this case?

**Comment by arekbulski** [comment]
Yes, if you search Issues then you will find several issues where people already discussed this topic. Embedding semantics were (recently) changed, and under these Bitwise is simply impossible to embed. I know it would be "handy", its just technically not possible.
