### ISSUE TITLE
Create additional Array Elements / Skip elements

### ISSUE THREAD

**Issue by reox** [construct/construct#719]
Java Class files use a very bad format for parsing, as the number of elements in the constant_pool might not be the actual number of elements, as Long and Double fields are counted twice: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4.5

That means that you need to insert an empty element into the Array or skip the index.

I figured out that you can decrement the size inside an hook from a GreedyRange, so at least the correct number of elements is parsed, but then the Indices are off and need to be calculated again in some wrapper class.

Here is an example:
```
from construct import *

foo = Struct(
    "bla" / Enum(Int8ul,
        FOO=0x23,
        BLA=0x42,
        AHH=0x99,
    ),
)

def hook(obj, ctx):
    if ctx._index >= ctx.size:
        raise CancelParsing
    if obj.bla == "BLA":
        ctx.size -= 1

    print("ctx:", ctx._index, ctx.size, obj.bla == "BLA")

x = Struct(
    "size" / Int8ul,
    "items" / GreedyRange(foo * hook)
)

print(x.parse(b"\x04\x23\x42\x99\xFF\xFF\xFF"))
```

In this case, all `foo` structs which are of type `BLA` need to be counted twice.

**Comment by arekbulski** [comment]
It seems to me like you need a custom adapter or class. There is nothing in the core library matching your description. Oh and... nice someone found a use for parsing hooks!

**Comment by reox** [comment]
btw: regarding the hook: EIther the documentation or the code is wrong with the `_index`. The documentation says it is `ctx._._index` but it is `ctx._index`.

Other than that, it works quite nicely! I wrote a wrapper around the Struct which returns the correct element from the constant_pool.

**Comment by arekbulski** [comment]
You found stale information in the docs: the Struct class was updated so it copies _index into from its parent (up-level context) for your convenience. Could you please point me where exactly you found that? Better yet, submit a PR.
