### ISSUE TITLE
Please release 2.5.3

### ISSUE THREAD

**Issue by hardkrash** [construct/construct#72]
Last version on pypi is over 2 years old.

Please consider updating pypi.

**Comment by tomerfiliba** [comment]
i'm looking for someone to take over the project. do you want to do so?

**Comment by arekbulski** [comment]
I would be willing to take over. Would you consider that? At least to solve all the issues and pull requests.

**Comment by tomerfiliba** [comment]
glad to hear :) made you a collaborator. send my your pypi username and i'll add it to pypi's maintainers so you could make releases

**Comment by arekbulski** [comment]
I am under a tent right now so how about I start with coding varint and cython and dealing with open issues. Will register at pypi later on.

**Comment by arekbulski** [comment]
I will start working on selected issues and update pypi after the weekend.

**Comment by arekbulski** [comment]
My pypi account is _arekbulski_. Could someone explain to me how to build this and upload to pypi? I am very new to this process.

**Comment by tomerfiliba** [comment]
added you. see http://peterdowns.com/posts/first-time-with-pypi.html

you basically need to set up your `.pypirc` file and run `build.sh` -- see https://github.com/construct/construct/blob/master/build.sh

**Comment by arekbulski** [comment]
I had pip install six and wheel. `bash build.sh` throws errors:
```bash
arkadiusz@pc:~/Pobrane/GitHub/construct$ bash build.sh 
'nvalid command name 'register
'nvalid command name 'upload
'nvalid command name 'upload
build.sh: linia 5: $'\r': nie znaleziono polecenia
'nvalid command name '
```

**Comment by arekbulski** [comment]
Should I be using Windows for building? :confused:

**Comment by arekbulski** [comment]
Tag created. But I still need some guidance on how to build this, both on Ubuntu and Windows.
https://github.com/construct/construct/releases/tag/v2.5.3

**Comment by arekbulski** [comment]
Since six is no longer used, the readthedocs needs to be rebuilt with new readme.

**Comment by arekbulski** [comment]
Release 2.5.3 is available through both PYPI and GitHub, at least as a source. Still cannot figure out how to build it.

**Comment by zappeee** [comment]
Seems like pypi, https://pypi.python.org/pypi/construct, was updated with beta 2.6.2 which breaks a few applications.
Anyway you can revert to a stable release on pypi?

**Comment by arekbulski** [comment]
Pypi now shows 2.5.3 and I will try to release 2.5.4 post facto that had six removed.

**Comment by arekbulski** [comment]
2.5.4 is now the latest of pypi. Its where six was removed.
