### ISSUE TITLE
how best to handle data that isn't a multiple of bytes

### ISSUE THREAD

**Issue by gupie** [construct/construct#722]
I want to generate a stream of binary messages that are not multiples of bytes. Each message is 300 bits long. I have been trying to work out how to do this using Construct but I cannot figure out how to get past the requirement the BitStructs have to be multiples of bytes. What would be the recommended way to proceed?

**Comment by arekbulski** [comment]
You could use a BitStruct with some padding, then put build output into lib/bytes2bits function and then just slice off (truncate) few bits.

**Comment by arekbulski** [comment]
I think you could embed a normal Struct within a BitStruct, that would have that 1 const field.

**Comment by gupie** [comment]
Could you explain this a little more please? How this be 12 bits?
