### ISSUE TITLE
Equivalent of Prefixed when the length doesn't lead the subcon

### ISSUE THREAD

**Issue by smurfix** [construct/construct#723]
The title says it all: I need to parse/build a struct where the length field (counting bytes) is not directly in front of the affected subcon. This is documented for a length counting items (replacing `PrefixedArray`: use `Rebuild()` with `len_`).

Please add an example that details how to do replace `Prefixed` accordingly.

**Comment by arekbulski** [comment]
Simple, parse the count field, then parse `Prefixed(Computed(this.count), ...)`.
