### ISSUE TITLE
Access Array Entries by type

### ISSUE THREAD

**Issue by reox** [construct/construct#724]
Yet another question...

I have some format which has a table of different types, which are coded by an Enum.
I like to get a certain array entry based on the this type.
What I came up with, is to create a dict and store the types plus the item:
```
from construct import *

list_item = Struct(
    "type" / Enum(Int8ul,
                  SOME_TYPE=0x01,
                  OTHER_TYPE=0x02,
                  YET_OTHER_TYPE=0x03,
                  FOURTH_TYPE=0x04,
                  ),
    "value" / Int8ul,
)

fmt = Struct(
    "size" / Int8ul,
    "item" / Array(this.size, list_item),
)

data = fmt.parse(b"\x04\x03\x23\x01\x42\x02\x13\x04\x37")

# create a dict with the types
type_list = {}
for i in data.item:
    type_list[i.type] = i

print(type_list["OTHER_TYPE"])
```

In my opinion this works fine, but maybe there is a better solution?

**Comment by arekbulski** [comment]
You could use PrefixedArray, but that is a small detail. You seem to be grouping items by TYPE category. If there is more than 1 per type, it would be overriden. You should use a defaultdict where default value is an empty set.
