### ISSUE TITLE
Parsing dynamically sized little-endian bytes

### ISSUE THREAD

**Issue by Evidlo** [construct/construct#725]
I'm trying to parse [KeePass database headers](https://gist.github.com/msmuenchen/9318327#file-gistfile1-txt-L7-L28).

I've got the following Struct which should do the job,
``` python
header = Struct(
    "magic" / Bytes(4),
    "magic2" / Bytes(4),
    "minor_version" / ByteSwapped(Int16ub),
    "major_version" / ByteSwapped(Int16ub),
    "dynamic_header" / RepeatUntil(lambda item,a,b: item.id == 0x00,
        Struct("id" / Byte, "len" / ByteSwapped(Int32ub), "data" / ByteSwapped(Bytes(this.len)))
    ),
    "rest" / GreedyBytes
)
```
but after getting an error and seeing that ByteSwapped needs a fixed length subcon, I'm not sure how to proceed.  

How do you parse little endian ordered bytes of dynamic size?

Also, is there a more idiomatic way to write my `RepeatUntil` expression, perhaps using a repeater and `StopIf`?

**Comment by arekbulski** [comment]
ByteSwapped is same as Int*ul. You could write  a custom class that is similar to ByteSwapped that reads tilll EOF, swaps bytes, then feeds entire data to subcon. But I have never seen a format where little-endianness is applied to anything but fixed-size integers. Of course, you could use GreedyRange+StopIf but that would probably cause the final (garbage) struct to be included in the results.

**Comment by Evidlo** [comment]
You're right, the dynamic sized part isn't byteswapped.  I just saw that the fixed sized fields were little endian and just assumed the dynamic part had to be byteswapped, too.
