### ISSUE TITLE
Debugging advice

### ISSUE THREAD

**Issue by reox** [construct/construct#728]
I have created a rather complex parser by now but it seems it fails on some object and reads over the file bounds (looks like its an Array with a size reading over the end of the file).
I tried the `Probe` and also the `Debugger` but both does not give me a hint where this error happens.

I get this error: `construct.core.StreamError: stream read less then specified amount, expected 1, found 0`
In the debugger I see these variables:
```
(Pdb) dir()
['data', 'length', 'stream']
```
I can see that the current position is the end of file:
```
(Pdb) stream.tell()
8364356
(Pdb) stream.getbuffer().nbytes
8364356
```

I like to know inside the Debugger what was the last item which was successfully processed and where in the hierarchy I'm in. Is this possible? It would certainly help me finding the bug much faster.
From the stacktrace I have no idea where I'm...

**Comment by arekbulski** [comment]
You should post the code in question. Error itself isnt sufficient.

**Comment by reox** [comment]
I constructed a short example here:
```
from construct import *

arrayitem = Struct(
        "type" / Enum(Byte,
            A_TYPE=0x00,
            B_TYPE=0x01,
            C_TYPE=0x02,
            ),
        "value" / Switch(this.type, {
            "A_TYPE": Struct("len" / Int8ul, "bytes" / Bytes(this.len)),
            "B_TYPE": Struct("attr1" / Int32ul, "attr2" / Int32ul),
            "C_TYPE": Struct("offset" / Pointer(Byte, CString("utf8"))),
            }),
        ) * "arrayitem"

fmt = Struct(
        "size" / Int32ul,
        "arrayitems" / Array(this.size, arrayitem),
        ) * "outer struct"


b = b"\x04\x00\x00\x00\x00\x06\x11\x22\x33\x44\x55\x66\x00\x02\x23\x23\x01\x42\x42\x42\x42\xff\xff\xff\xff"

print(Debugger(fmt).parse(b))
```

It's quite obvious whats wrong here: the size says 4 but there are only three items.

So I drop into the pdb, but what can I investigate now?
For example: `list` is not very helpful:
```
(Pdb) list
 81  	    try:
 82  	        data = stream.read(length)
 83  	    except Exception:
 84  	        raise StreamError("stream.read() failed, requested %s bytes" % (length,))
 85  	    if len(data) != length:
 86  ->	        raise StreamError("stream read less then specified amount, expected %d, found %d" % (length, len(data)))
 87  	    return data
 88  	
 89  	
 90  	def stream_read_entire(stream):
 91  	    try:
```
I already found out, that documenting fields can help here, as the debugger prints the struct in which this error happens:
```
Debugging exception of <Renamed +docs <Struct>>
```
But as I renamed two structs, this information is also useless :/

My goal would be to know exactly in which part of the parser I'm currently - in this example this would be `"outer struct" --> "arrayitems"` and what was the last offset that worked i.e. the last correctly parsed item. Is this possible with the debugger?

I mean you can add many Probes on places you think there is an error and hope for the best...

**Comment by arekbulski** [comment]
Since a recent version, all exceptions include the "path" information.
