### ISSUE TITLE
Const & FlagsEnum

### ISSUE THREAD

**Issue by riggs** [construct/construct#73]
`FlagsEnum.parse` returns a dict-like object, FlagsContainer, which means that, when using Const to verify its value, one musts supply a dict-like object. However, `FlagsEnum.build` (like the rest of construct) examines the passed-in object's attributes for the flag values. Thus, passing a dictionary to `build` will cause it to not set any flags. However, passing in an object rather than a dictionary will cause Const to fail its test.

To wit:
```
In [20]: Const(FlagsEnum(Byte("types"), feature=4, output=2, input=1), {'feature': True, 'output': False, 'input': False}).parse('\x04')
Out[20]: FlagsContainer({'output': False, 'feature': True, 'input': False})

In [21]: Const(FlagsEnum(Byte("types"), feature=4, output=2, input=1), {'feature': True, 'output': False, 'input': False}).build({'feature': True, 'output': False, 'input': False})
Out[21]: '\x00'    ## ERROR ##

In [22]: FlagsEnum(Byte("types"), feature=4, output=2, input=1).build(types_obj)
Out[22]: '\x04'

In [23]: Const(FlagsEnum(Byte("types"), feature=4, output=2, input=1), {'feature': True, 'output': False, 'input': False}).build(types_obj)
---------------------------------------------------------------------------
ConstError                                Traceback (most recent call last)
<snip>
ConstError: expected {'output': False, 'feature': True, 'input': False}, found <types_obj>
```
I'm guessing the more consistent solution is to refactor FlagsContainer to not be a dict-like object.

**Comment by arekbulski** [comment]
I think the way to go about this is to make Const accept more usable values like a string "feature" or int 4, and interpret it according to subcon. What do you think?

**Comment by arekbulski** [comment]
Reminds me of this: http://construct.readthedocs.io/en/latest/adapters.html#enums

```py
>>> c = Enum(Byte("protocol"),
...     TCP = 6,
...     UDP = 17,
... )
>>> c.build("TCP")
'\x06'
>>> c.build("UDP")
'\x11'
```

**Comment by riggs** [comment]
`types_obj` is just an object with three attributes, feature, output, input, since that's what FlagsEnum requires.

The fundamental discrepancy is that FlagsEnum uses getattr & setattr to encode and decode, but the object it creates to decode, FlagsContainer, is a subclass of a the dict-like Container object that overloads get/setattr. Thus, when Const makes its comparison, it's either between the constant value and a dict-like object returned by its decode method, or between the constant value and an object with attributes provided to the encode. So, unless the user-provided object to be encoded is also a dict-like object with overloaded get/setattr methods, there will never be parity between the encoded and decoded objects, so no single constant value can be equal to both objects.

I see a few different possible resolutions:

1. (Flags)Container could have __eq__ defined such that it will return true when given an object with attributes & values that match its contents.

1. FlagsContainer could not derive from Container, and also test equality by comparing attributes of itself and the other object.

1. FlagsEnum could switch from using getattr/setattr to getitem/setitem to take a dict-like object.

I think the third option is the cleanest, but it's an API change. I think #2 is the best option without changing the API, but it's the most work and could run into a lot of corner cases. I think the first option is the easiest to implement, but smells like a crude hack that could cause problems later.

**Comment by arekbulski** [comment]
I just made the `Container` use keys instead of attributes. 310d78241f68d2e00eb2f623370a80cf7222e4c I dont see how it breaks the API, the containers already support **both** by key and by attribute access.

**Comment by riggs** [comment]
Forgive my ignorance, but I don't see what that commit has to do with this bug.

I just pulled the latest and the bug is still there:
```
In [35]: types = namedtuple('Types', 'feature output input')(True, False, False)

# Builds correctly
In [36]: Const(FlagsEnum(Byte("types"), feature=4, output=1, input=1), types).build(types)
Out[36]: '\x04'

# Fails to parse
In [37]: Const(FlagsEnum(Byte("types"), feature=4, output=1, input=1), types).parse('\x04')
---------------------------------------------------------------------------
ConstError                                Traceback (most recent call last)
<snip>
ConstError: expected Types(feature=True, output=False, input=False), found FlagsContainer({'output': False, 'feature': True, 'input': False})

# Parses with dictionary as value instead of 'types'
In [38]: Const(FlagsEnum(Byte("types"), feature=4, output=1, input=1), {'feature': True, 'output': False, 'input': False}).parse('\x04')
Out[38]: FlagsContainer({'output': False, 'feature': True, 'input': False})

# But fails to build
In [39]: Const(FlagsEnum(Byte("types"), feature=4, output=1, input=1), {'feature': True, 'output': False, 'input': False}).build(types)
---------------------------------------------------------------------------
ConstError                                Traceback (most recent call last)
<snip>
ConstError: expected {'output': False, 'feature': True, 'input': False}, found Types(feature=True, output=False, input=False)

# No ConstError when dictionary passed in with dict as constant value, but builds into the wrong output
In [40]: Const(FlagsEnum(Byte("types"), feature=4, output=1, input=1), {'feature': True, 'output': False, 'input': False}).build({'feature': True, 'output': False, 'input': False})
Out[40]: '\x00'  # Should be \x04
```

**Comment by arekbulski** [comment]
I didnt say that I fixed it. I am saying that your solution no 3 does not break any API because `Container` already support accessing by keys. No reason why other containers could not do same.

**Comment by riggs** [comment]
My suggestion no 3 is to change FlagsAdapter from using getattr & setattr to dictionary access.

This would then make
```FlagsEnum(Byte("types"), feature=4, output=1, input=1).build(types_dict)```
return `'\x04'` whereas it currently returns `'\x00'`.

It would also make most current FlagsEnum.build uses throw a `TypeError` because whatever object is currently being passed into it is likely not iterable.

It's a straightforward (2 line) change and I'd be happy to submit a PR, but it's definitely an API change.

**Comment by arekbulski** [comment]
Go ahead and submit a code proposal, preferrably with some unit tests. I am going to refactor Adapters functionality into Construct/Subconstruct so API will change a bit anyway. For now, lets just make something that works.

**Comment by riggs** [comment]
PR submitted and passing.

**Comment by arekbulski** [comment]
I could use some help with processing issues and features. There are some things that do not work yet. You can find what I am working on in the non-master branches.
https://github.com/construct/construct/branches

**Comment by arekbulski** [comment]
Just updated: Container now compares order as well and there is a new creation syntax for preserving order, see docs. However, FlagsContainer preserves order on insertion but doesnt check it on equality testing.
