### ISSUE TITLE
Non-modular alignment / put aligned data at end / absolute alignment

### ISSUE THREAD

**Issue by matejcik** [construct/construct#730]
I'm parsing a structure which must be sized to a multiple of 512 bytes -- and the *last* 65 bytes are flag + signature. I find this difficult to express with existing Construct constructs.

something like:
```python
VendorHeader = c.Struct(
    "magic" / c.Const(b"TRZV"),
    "header_len" / c.Rebuild(c.Int32ul, c.len_(c.this)),
    "expiry" / c.Int32ul,
    "dynamic_data" / c.Prefixed(c.Int32ul, c.GreedyBytes),
# ...
    StrangeAlignment(512, 65),
    "signature" / c.Bytes(65),
)
```

I tried making a substructure, without the signature, and wrapping it:
```python
SignedVendorHeader = c.Struct(
    "header" / VendorHeader,
    c.Padding(-(c.len_(c.this.header) + 65) % 512),
    "signature" / c.Bytes(65),
)
```
The expression for `c.Padding` seems to go wrong, but maybe that's my bug, I haven't looked too deeply into that. A drawback of this solution is that the `VendorHeader` container doesn't see the full length of the `SignedVendorHeader` structure. That could possibly be solved by using `len_(this._)` instead of `len_(this)`?
A second drawback is that the "header" field is nested, while I would like it embedded. But it seems impossible to name an embedded struct and then refer to its length?

It occurs to me that I could put a `Padding` in place of `StrangeAlignment` in the original example, and calculate its length based on `header_len`, but that looks like it would fail when building, unless I prespecified the header len.

I copy-pasted `Aligned` subconstruct into `AlignedWithSubtraction` that can do what I want, i.e. "align as if the inner length was bigger". This still has the drawback that all of the fields apart from the signature must be thus aligned, so I'd again need a substructure.

I'm thinking of writing `AbsoluteAlignmentWithSubtraction` instead, which would use absolute stream position instead of subconstruct length. This would work for my usecase, but I suppose it would fail if used in a substructure?

I've come up with several things, possibly conflicting, that would help here:
* a way to express "length so far", so that I wouldn't have to nest the preceding fields
* a way to left-pad a fixed size subconstruct
* alignment with subtraction

Is there a good way to express my usecase within the existing framework, in accordance with "you probably don't need to write your own subconstruct"? Is there a feature somewhere in this that would make a good addition to Construct?

**Comment by arekbulski** [comment]
It seems to me that you overcomplicated this. You could use Aligned instead of Padding, and you could also use Tell to find offsets when building. Check those 2 classes.

**Comment by arekbulski** [comment]
https://construct.readthedocs.io/en/latest/api/streaming.html#construct.Tell

**Comment by matejcik** [comment]
thanks for the pointers. `Tell` indeed solves this
