### ISSUE TITLE
Differentiate checksum exceptions

### ISSUE THREAD

**Issue by Evidlo** [construct/construct#731]
I have a complicated Struct with multiple Checksums throughout and no way to differentiate between them if they fail.  It would be nice to be able to tell these apart programmatically, either by adding an `exception` kwarg to `Checksum` or by adding the `path` string as an attribute to `ChecksumError`.

A more general solution would be to include the path for *all* exceptions, which would also be useful for quickly zeroing in problems while debugging.

(also, why is `path` a string and not something more easily parsed, like a list?)

**Comment by arekbulski** [comment]
Why its a string not a list? Well, there wasnt much decision making put into that. Anyway, I am not sure exactly what is it that you are asking. If you would want to provide a PR, I would look at it.

**Comment by Evidlo** [comment]
https://github.com/construct/construct/pull/732

**Comment by Evidlo** [comment]
Did you look at my proposal in #732 ?

**Comment by arekbulski** [comment]
I am not going to merge it, truth be told, I simply dont like it. If you want to use it, you can copy (git clone) the Construct into a local folder, and there add your own commits as you like.

**Comment by Evidlo** [comment]
Ouch.

This would've taken care of two deficiencies in construct:

1.  No ability to distinguish checksum errors and provide helpful information to the end user.

2. Exceptions in complicated/large projects (especially stream errors) are not useful because you can't tell where they occur.  I'm forced to insert a Probe in different places and rerun the code multiple times to determine where the error happens.

Aren't these issues worth tackling?
