### ISSUE TITLE
Validating/Enumerating valid entries for an Enum within Struct

### ISSUE THREAD

**Issue by mungewell** [construct/construct#733]
I'm using Construct to define/parse/build a propitiatory file format, which is config file for a device I own. I am attempting to write an editor for this config file.

Is there a way I can get a list of valid entries for a previously defined Enum? Ideally I only want it defined in one place...

For example, some way of getting '[cat, dog, fish]':
```
>>> from construct import *
>>> a = Struct("pet" / Enum(Byte, cat=1, dog=2, fish=3))
>>> a
<Struct>
>>> a.pet
<Renamed pet <Enum <FormatField>>>
>>> a.pet.cat
EnumIntegerString.new(1, 'cat')
>>> type(a.pet)
<class 'construct.core.Renamed'>
>>> type(a)
<class 'construct.core.Struct'>
```

**Comment by arekbulski** [comment]
If I am not mistaken: https://github.com/construct/construct/blob/master/construct/core.py#L1651
```py
>>> str(a.pet.cat)
'cat' which is a unicode string
```
Also: https://github.com/construct/construct/blob/master/construct/core.py#L1716-L1717
```py
>>> a.pet.subcon.encmapping.keys()
list of EnumIntegerString, convert to str as above
```

**Comment by mungewell** [comment]
Wow, I'd would have never found that.... 

For my code I used 'ksymapping' as follows to quickly build an interactive menu.
```
    menu = qprompt.Menu()
    for x,y in Header.swing.subcon.ksymapping.items():
        menu.add(str(x),y)
    config[0]['swing'] = int(menu.show())
```

Thanks,
Simon.
