### ISSUE TITLE
FeatureReq: 'PadChar' for PaddedString()

### ISSUE THREAD

**Issue by mungewell** [construct/construct#735]
In my little project I noticed that the device "freaks out" if a padded string has 'Nulls', instead of the 'Spaces' it expects. I can pre-pad the string but that defeats the rational of Construct.

Previously it looks like the concept of 'padchar' was used:
https://github.com/MostAwesomeDude/construct/blob/dad8ecaf5ce75c7a66cd995bfc137d1ad368e290/construct/adapters.py#L153

But that does not exist now...
https://github.com/construct/construct/blob/abd48c4892ceddc60c11d25f4a955573e2c61111/construct/core.py#L1503

Any chance of having it re-instated?

**Comment by arekbulski** [comment]
No. It would probably be possible to implement (since underlying NullStripped class can take other pad chars as parameter) but I am not actively developing it anymore.

**Comment by arekbulski** [comment]
However, if you would be willing to effectuate it and send a PR, then yes.
