### ISSUE TITLE
Check for Mapping type instead of dict

### ISSUE THREAD

**Issue by SF-300** [construct/construct#738]
Hi,

It seems that custom dict-like classes (i.e. inherited from collections.abc.Mapping or collections.abc.MutableMapping) are not handled correctly in Container.update() function (there is an explicit check for isinstance(seqordict, dict)). Is this an intended behaviour?

**Comment by arekbulski** [comment]
It wasnt designed or tested beyond the dict. If you would expand the test suite with some code that shows this, and submit a PR, then we could do something about it.
