### ISSUE TITLE
StopIf - 'not in' expression doesn't work

### ISSUE THREAD

**Issue by 0x6a61** [construct/construct#739]
Example:

```
EthTypeHeader = Struct(
    "etherType" / EtherType,
    StopIf(this.etherType not in [EtherType.VLAN, EtherType.VLAN_DOUBLE]),
    "vlan" / VlanHeader
)
```

`Not in` always returns false and `in` always true. It's even worse that no error is thrown.

The easy solution is to use `lambda`. But maybe you can fix this with ease, or at least throw an error.

**Comment by arekbulski** [comment]
Already explained in the docs:
https://construct.readthedocs.io/en/latest/meta.html#known-deficiencies
