### ISSUE TITLE
UnicodeDecodeError breaks Select

### ISSUE THREAD

**Issue by leromarinvit** [construct/construct#743]
Hi,

I'm trying to parse a field that can either be a string or a binary array, without knowing in advance which it's going to be (this depends on application state outside the parsing context - which I could pass in, but I'd prefer not having to worry about this). I'm trying to use a Select() for this:

```
Select(
    PaddedString(LEN, "ascii"),
    Bytes(LEN),
)
```

However, when the parser encounters a character which isn't valid ASCII, the resulting UnicodeDecodeError isn't caught by Select and breaks decoding:

```
Debugging exception of <Select>
path is (parsing) -> msg -> szPass
  File "/home/mao/.local/lib/python3.6/site-packages/construct/debug.py", line 122, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/mao/.local/lib/python3.6/site-packages/construct/core.py", line 3480, in _parse
    obj = sc._parsereport(stream, context, path)
  File "/home/mao/.local/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/mao/.local/lib/python3.6/site-packages/construct/core.py", line 715, in _parse
    return self._decode(obj, context, path)
  File "/home/mao/.local/lib/python3.6/site-packages/construct/core.py", line 1490, in _decode
    return obj.decode(self.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc7 in position 0: ordinal not in range(128)
```

On a somewhat related note, is there a specific reason PaddedString and CString don't support non-ASCII 8-bit encodings?

**Comment by arekbulski** [comment]
I dont understand how you could parse a string, Construct parses only bytes (perhaps bytearrays also, that wasnt ever tested). Please submit PR with a testcase that shows how and what fails. The simpler the testcase, the better.

What are those non-ASCII 8-bit encodings? I wasnt aware there is such a thing.

**Comment by leromarinvit** [comment]
I just created https://github.com/construct/construct/pull/744, I hope it's clear what I mean now.

**Comment by arekbulski** [comment]
There is a global variable named something like possibleencodings. Its mutable. You can add any encoding you want to it.

**Comment by leromarinvit** [comment]
Thanks, that solves my immediate problem - I can just use a Union instead of Select and present both views to the application.

However, I still think not catching the UnicodeDecodeError in Select is a bug, though possibly only in the documentation:

> Parses and builds by literally trying each subcon in sequence until one of them parses or builds without exception.

There might be situations where you want to parse something that can either be a string with a given encoding, or something else. It's admittedly a somewhat contrived example, and a data format that didn't indicate which interpretation to use before such a field would be stupid - but stupid formats exist...

**Comment by sides** [comment]
I see this is closed, but for the record, I have a similar use-case, where the application that outputs the data I'm parsing sometimes cuts its strings short at the byte-level (I'm using `PaddedString`) meaning it fails to be decoded due to various issues. I would like to use `Optional` (or `Select`) here to just output `None` as a fallback if it fails to be decoded without failing the entire parse.
