### ISSUE TITLE
Using Union with embedded struct

### ISSUE THREAD

**Issue by chnd** [construct/construct#745]
Hi, I tried Union with embedded struct as follows:
```
test = Union(
    None,
    "x" / Int16ub,
    Embedded(Struct("y1" / Int8ub, "y2" / Int8ub)),
    "z" / Struct("z1" / Int8ub, "z2" / Int8ub)
)
print(test.parse(b'\x01\x02'))
```
I expect that y1=1 and y2=2, but I got:
```
Container: 
    x = 258
    y1 = 1
    y2 = 1
    z = Container: 
        z1 = 1
        z2 = 2
```
I am not sure how to use the _parsefrom_ parameter, so I just use "None". I would appreciate any suggestions. Thanks.

**Comment by arekbulski** [comment]
Embedded Struct does not work inside a Union due to embedding semantics. There should be no embedded members inside a Union. And I would not embed a Union anywhere either.
