### ISSUE TITLE
Using the Optional struct at the end of a BitStruct raises StreamError

### ISSUE THREAD

**Issue by matan1008** [construct/construct#747]
Hi,
I am trying to make an optional field at the end of a bitwise protocol (a type-length-value field that might exist and might not). I tried doing the following (simplified):

```
protocol_tail = BitStruct("field" / Optional(Octet))
protocol_tail.parse(b"")
```

And I get the following exception:
`construct.core.StreamError: stream.seek() failed, offset 0, whence 0`
I read in the manuals that `Select` is not supported under a bitwise context so I also tried:

```
protocol_tail = BitStruct(
    "struct" / Bytewise(Struct(
        "field" / Optional(Byte)
    ))
)
```
But I got the same error.

Note that doing the following:

```
protocol_tail = Struct("field" / Optional(Byte))
protocol_tail.parse(b"")
```

Returns `Container(field=None)`

Thanks for dedicating time!

**Comment by arekbulski** [comment]
Bitwise(BitStruct) and Bytewise are almost identical and are affected by same issues. I would not expect anything to be solved by using both if either alone causes problems.
There could be a workaround, but I wasnt working on this project for a long time so I am reaching. I leave investigating this to you: Bitwise/Bytewise use 2 classes depending on subcon. If they opt for Restreamed then thats is the problem, its not seekable. If they would opt for Transformed, that might be seekable. You could use some trick to make the outer subcon fixed sized and therefore causing Transformed code path. Look into FixedSized wrapper.
If you manage to solve it, I would appreciate a PR with a test case showing how. Not an example on this page but a runnable testcase. Maybe even a documentation patch too.

**Comment by matan1008** [comment]
Is there a reason for `RestreamedBytesIO` not to be seekable?

**Comment by matan1008** [comment]
#749
