### ISSUE TITLE
Escaping in byte stream

### ISSUE THREAD

**Issue by aegonzalez** [construct/construct#748]
In this protocol, a message starts with 0x01 and embedded 0x01 bytes found after the start  must be encoded as 0x1b 0x31
Any advice on how to handle in Construct? Is an Adapter the mechanism to use?
Thanks.

**Comment by arekbulski** [comment]
Its not a clear question. What is "embedded 1 bytes"? How is 1 byte encoded as 2 bytes?

**Comment by aegonzalez** [comment]
#---  Start of Example
from construct import *
msg=Struct(
    'som'       / Const(b'\x01'),
    'm2'        / Byte,
    'm3'        / Byte,
    'm4'        / Byte,
)

#----- Case 1 - m2-m4 are not equal to 0x01 -- Success
c=msg.parse(b'\x01\x02\x03\x04')
print(c)
'''
Container:
    som = b'\x01' (total 1)
    m2 = 2
    m3 = 3
    m4 = 4
'''

#----- Case 2 - m2 equals 1, m1 and m3 are not equal to 0x01 -- Not Ok
#Since m2 equals 1 it will be received on the wire as 0x1b31:
c=msg.parse(b'\x01\x02\x1b\x31\x04')
print(c)
'''
Container:
    som = b'\x01' (total 1)
    m2 = 2
    m3 = 27
    m4 = 49
'''
#--- End of Example

Messages are received on the wire with any byte with value 0x01 encoded as two bytes 
with value  0x1b31.

**Comment by arekbulski** [comment]
I think you are asking too much of Construct. Its a library for binary parsing, not for elaborate algorythmic processing of data. I would suggest that you read those bytes, aside of that Const, as a list and not separate individual fields. Maybe `Array(3,Byte)` or `GreedyRange(Byte)`. Then either process it outside of Construct, or use some custom adapter to process the list.

**Comment by aegonzalez** [comment]
Ok. I appreciate your help. Thanks.
