### ISSUE TITLE
BFloat32 -> Float32b, String -> StringEncoded?: Where do I find changes between versions of construct?

### ISSUE THREAD

**Issue by bwagner** [construct/construct#751]
I've found an example of someone porting a piece of code using an earlier (unknown) version of construct to version 2.8.11. Between these two versions, apparently BFloat32 has been renamed to Float32b.

As it seems, there used to be a "String" in version 2.8.11 which has migrated to something else in version 2.9.45 of construct, possibly StringEncoded.

Where do I find changes between versions of construct?
Is there information around how to port code to newer versions of construct?

**Comment by bwagner** [comment]
OK, these seem to answer my question:
https://construct.readthedocs.io/en/latest/transition28.html
https://construct.readthedocs.io/en/latest/transition29.html

**Comment by I4HJrl0** [comment]
Note that on Python 2.7, porting `String` to `PaddedString` may require more than renaming:
https://github.com/construct/construct/issues/740
