### ISSUE TITLE
Range with 2.9.*

### ISSUE THREAD

**Issue by domenzain** [construct/construct#754]
Hi,

`Range` was removed with the transition to 2.9.*
Is there a recommended way to obtain the same result?

For example `Range(2, 5, Int16ub)` would parse no less than 2 and no more than 5 half-words. And when building, it would require a list of no less than 2 and up to 5 values.

Thank you,

**Comment by arekbulski** [comment]
GreedyRange or pin older version of Construct. Or copy-paste that one class into your source code.

**Comment by I4HJrl0** [comment]
One idea:
```
class Range2To5Validator(Validator):
    def _validate(self, obj, context, path): 
        return 2 <= len(obj) <= 5

Range2To5Validator(GreedyRange(Int16ub))
```

A more elegant idea might be to use `Check`.

(Personally I find both solutions not very elegant, compared to `Range`.)

**Comment by arekbulski** [comment]
Yeah, and I found Range to be utterly useless, but it seems people have very and I really mean very strange applications for this library. My best suggestion would be to simply copy paste the Range class into your own source code. Its not much different than writing a custom adapter except in this case, the code is already written  (in archived commits).

**Comment by domenzain** [comment]
Thanks for your answers.

To copy-paste the original class is a hacky solution and likely to break with future updates. Is there a core subset of the API expected to be stable through construct 2.9?
`Validator` and `GreedyRange` are expected to stay?

For protocols like PTP, `Range` matched the binary specification exactly, so not quite "utterly useless" or "very strange". Given that all large camera manufacturers implement it, it is an industrial standard.

**Comment by arekbulski** [comment]
`Array` is a commonly used class, but `Range` is not. I never seen one specification that used it.

The library is no longer maintained, so "its stable".

**Comment by domenzain** [comment]
Understood.
Are you looking for a maintainer?

**Comment by arekbulski** [comment]
No.
