### ISSUE TITLE
Array Don't works in BitStruct (invalid)

### ISSUE THREAD

**Issue by latot** [construct/construct#756]
Hi, if we use Array inside a bitstruct we don't get any data:

```
>>> BitStruct("a" / Flag, "b" / Flag, "c" / Flag, "d" / Flag, "e" / Flag, "f" / Flag, "g" / Flag, "h" / Flag).parse(b"1")
Container(a=False, b=False, c=True, d=True, e=False, f=False, g=False, h=True)
>>> BitStruct(Array(8, "a" / Flag)).parse(b"1")
Container()
```

Bye.

**Comment by arekbulski** [comment]
No. You named the array subcon which has no purpose and you did not name the struct member which has an implication. If its not named then its result cannot be inserted into resulting dict.

`>>> BitStruct("array" / Array(8, Flag)).parse(b"1")`

**Comment by latot** [comment]
mm, maybe an error with this cases?, i think is betteran than return an empty container.

**Comment by arekbulski** [comment]
No. There are usecases like Padding where the results would be useless and should not be included in the resulting dict. You used it incorrectly, simple as that.
