### ISSUE TITLE
Remove deprecated "requires" from setup.py

### ISSUE THREAD

**Issue by zvezdan** [construct/construct#757]
The presence of `requires` in setup.py together with `install_requires` breaks builds with the most recent releases of _wheel_ when used with _distlib_. The `requires` entry in setup.py produces `Requires` in metadata file, and `install_requires` produces `Requires-Dist`. The change has been done in [PEP 345](https://www.python.org/dev/peps/pep-0345/) over 13 years ago. Presence of both fields in the metadata file is not accepted by _distlib_ any more.

Namely, _wheel_ >= 0.31.0 uses metadata format 2.1 and _distlib_ has adapted to that change. Notice also that wheel-0.31.1 is required by the most recent releases of virtualenv (16.0.0) and pip (18.0). Among them, _distlib_ is the most strict in what it considers as correct metadata. See the recent issue and _distlib_ author's reply: https://bitbucket.org/pypa/distlib/issues/106/support-21-metadata
This led to other issues similar to the one I'm opening here:
* https://github.com/dateutil/dateutil/issues/720
* https://github.com/pypa/setuptools/issues/1396

Fortunately, the current version of _construct_'s setup.py has both of these entries empty: https://github.com/construct/construct/blob/master/setup.py#L28
Thus, neither of these fields is recorded into metadata.
The older versions, though, had both entries populated: https://github.com/construct/construct/blob/v2.5.2/setup.py#L36
This did leak into metadata and caused exceptions with _distlib_ (debug logging turned on):
```
DEBUG:distlib.metadata:Removed 1.0 due to Requires-Dist
DEBUG:distlib.metadata:Removed 1.1 due to Requires-Dist
DEBUG:distlib.metadata:Removed 1.2 due to Provides
DEBUG:distlib.metadata:Removed 1.3 due to Provides
DEBUG:distlib.metadata:Removed 2.1 due to Provides
DEBUG:distlib.metadata:Removed 2.0 due to Provides
DEBUG:distlib.metadata:Out of options - unknown metadata set: {'Metadata-Version': '2.1', 'Author': 'Tomer Filiba, Corbin Simpson', 'Version': '2.5.2', 'Requires-Dist': ['six'], 'Platform': ['POSIX', 'Windows'], 'Provides': ['construct'], 'Requires': ['six'], 'Classifier': ['Development Status :: 5 - Production/Stable', 'License :: OSI Approved :: MIT License', 'Programming Language :: Python :: 2.5', 'Programming Language :: Python :: 2.6', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.0', 'Programming Language :: Python :: 3.1', 'Programming Language :: Python :: 3.2', 'Programming Language :: Python :: 3.3'], 'Author-email': 'tomerfiliba@gmail.com, MostAwesomeDude@gmail.com', 'License': 'MIT', 'Summary': 'A powerful declarative parser/builder for binary data', 'Keywords': ['construct', 'declarative', 'data structure', 'binary', 'parser', 'builder', 'pack', 'unpack'], 'Home-page': 'http://construct.readthedocs.org', 'Name': 'construct'}
```
The presence of both `Requires` and `Requires-Dist` is the same as the issues referenced above.

Can `requires` be removed from setup.py to ensure this does not happen in the future?

**Comment by zvezdan** [comment]
Just tested with 2.5.2 and `provides` also needs to be removed because it was dropped in PEP 345 together with `requires`. So, can we have both removed please?

**Comment by arekbulski** [comment]
I wont even pretend to understand the issue you are describing. My understanding of the whole pip ecosystem is essentially zero. Please, submit a PR with whatever should be changed and I will simply merge it. As for 2.5 that version wasnt supported for years. Would removing the branch solve that?

**Comment by zvezdan** [comment]
@arekbulski Thank you for looking into it.

I'll make a small PR that removes those two deprecated fields.

The removal of 2.5 branch is not needed or necessary. I asked the team that was using that version to upgrade to newer releases of _construct_.

**Comment by arekbulski** [comment]
Thank you for contributing this. I will close the ticket but merge the PR.
