### ISSUE TITLE
Issues parsing Const with subcon type that is itself a Struct

### ISSUE THREAD

**Issue by tehampson** [construct/construct#761]
Using version: 2.9.45 of construct in python2.7

The last line trying to parse VersionStruct results in the following error:
`Error saying construct.core.ConstError: parsing expected Container(major=9, minor=4) but parsed Container(major=9, minor=4)`
```from construct import Struct, Nibble, Const, BitStruct, Container

VersionStruct = "version" / Const (
    subcon=BitStruct(
        "major" / Const(subcon=Nibble, value=9),
        "minor" / Const(subcon=Nibble, value=4),
    ), value=Container(major=9) (minor=4))

foobar = VersionStruct.build(None)
version = VersionStruct.parse(foobar)
```

For what it's worth version 2.8.17 of contruct this did work

**Comment by arekbulski** [comment]
I think the whole nesting of Const is wrong. Try using only those inner or the outter but not both. And there is a real possibility that this is a bug... Container equality operator is buggy. We would need a test case PR.

**Comment by tehampson** [comment]
The issue is still present if the const is on the outer level. I think you are right about the Container equality operator being buggy. I'll issue a PR containing a test case sometime in the next few days.

**Comment by arekbulski** [comment]
I already encountered the Container equality bug before, but since I am not working on the project anymore, I did not fix it. Its surprising that if this bug really exists, no one has reported it before. I would welcome a test case, and if you would be willing to fix the bug as well, of course that too. But no pressure.
