### ISSUE TITLE
Shift-jis in Strings formats

### ISSUE THREAD

**Issue by latot** [construct/construct#765]
Hi, before we was able to use shift-jis format, but now is not available in strings, can be added again?

The olcode was ```String(64, encoding="shift-jis")```

Ty

**Comment by arekbulski** [comment]
It was already answered in a recent ticket although I cant find it atm. In short, you can add encodings to a global variable.

**Comment by latot** [comment]
Hi, reading the docs, there is construct.core.possiblestringencodings, all the values have a string and a number, how i should add to it?, i mean, i know the name would be "shift-jis", but the numeric value i don't know, in the docs show several names with the same value, what should i use in this case?

```
construct.core.possiblestringencodings['shift-jis'] = something
````

Bye.

**Comment by latot** [comment]
Is there some way to get the number of bytes of old encodes?

**Comment by arekbulski** [comment]
If you mean those already supported by Construct, its in the source:
https://github.com/construct/construct/blob/master/construct/core.py#L1464
If you mean ancient encodings supported by Python runtime, dont know.

**Comment by latot** [comment]
Okis, if you can update the docs to specify how include a new encoding (['encoding'] = bytes), i think this issue will be ready, actually only is missed explain the number of bytes of the encoding.

https://construct.readthedocs.io/en/latest/api/strings.html#construct.core.possiblestringencodings

**Comment by arekbulski** [comment]
I am not maintaining this project anymore... you can PR an update to the docs if you want.
