### ISSUE TITLE
SizeofError for Struct and Sequence

### ISSUE THREAD

**Issue by jpsnyder** [construct/construct#771]
(I'm using construct 2.9.45)

When I try to use sizeof() for a dynamic Struct that requires a context it produces a SizeofError that it cannot find the key. (This also happens for Sequence and FocusedSeq)

```python
from construct import *


spec = Struct(
    'count' / Int32ul,
    'entries' / Byte[this.count]
)

print(spec.sizeof(count=3))
```

```
Traceback (most recent call last):
   ...
construct.core.SizeofError: cannot calculate size, key not found in context
```

It seem that removing lines 2011 and 2012 (https://github.com/construct/construct/blob/master/construct/core.py#L2011) seems to fix the issue, but only if the Struct is at the first level. Doing something like this will still fail:

```python
spec = Struct(
    'a' / Int32ul,
    'b' / Struct(
        'count' / Int32ul,
        'entries' / Byte[this.count]
    )
)

print(spec.sizeof(**{'b': {'count': 3}}))
```

I believe this may be due to it not setting up a context container that is relative to the current Construct being evaluated like it was in 2.8.

**Comment by arekbulski** [comment]
You are interpretting how passing the keywords works wrong. For your sizeof() to work the code would need to use I think `Byte[this._.count]`. You are passing so called global parameters, not a value for b field.

**Comment by jpsnyder** [comment]
I'm simply trying to pass back what I would receive in a parse() into sizeof(). This symmetry was something I could do in 2.8 and it made a lot of sense. 
e.g.

```python
spec = Struct(
    'a' / Int32ul,
    'b' / Struct(
        'count' / Int32ul,
        'entries' / Byte[this.count]
    )
)

data = b'\x01\x00\x00\x00\x02\x00\x00\x00\x0a\x0b'

info = spec.parse(data)
assert spec.build(info) == data
assert spec.sizeof(info) == 10  # Succeeds in 2.8 but fails in 2.9 
```

It seems like this no longer works because the `this.count` isn't relative to the Struct it is in anymore?

I can contribute a fix if you would like. Are you looking for a maintainer?

**Comment by arekbulski** [comment]
I am looking for patches, no.

**Comment by arekbulski** [comment]
I am reviving this ticken and am planning to merge it, eventually. Are there any developments in this area?

**Comment by arekbulski** [comment]
Altough its true that I am not really looking for a another maintainer, I would need your explanation as to how this patch works. I am not going to merge a piece of code that goes beyond my understanding.

**Comment by jpsnyder** [comment]
No new developments that I can remember. Looking back at my code, I was attempting the following:

- Make the context it's own class (inherited from a Container)
- This `Context` class helps to enforce certain fields to be present (like `_io` and `_index`) as well as make it easy to create and retrieve nested contexts (child).
  - This help to remove the building of the context outside each individual Construct. (Removes repeated code and prevents typos)
- Fixed the `sizeof()` in the `Array` construct to make it go through the motions of setting up the context appropriately for each item. This fixes issues with the wrong value being displayed for constructs that use the `_index` field.
- Changed the `sizeof()` in the Sequence and Struct type constructs to pass the nested context for each field instead of the root when calculating the `sizeof()` for each subconstruct.
- Added a test based on the example above.


I'm glad to see you are getting back into this. I have plenty more suggestions and improvements that I would love to get your opinion on if you are interested.

**Comment by jpsnyder** [comment]
While it is possible to not have the Context class, I believe this makes it the code more organized and will better scale over time.

**Comment by arekbulski** [comment]
Please look at the commit comments I left. We should split this issue 2-3 issues.
Please do tell what else you think of it. Feel free to open new tickets for those.

**Comment by arekbulski** [comment]
I should point out that the parse-sizeof combo that you are using was never meant to work with one another. This goes far beyond the original feature.

**Comment by arekbulski** [comment]
> I have plenty more suggestions and improvements that I would love to get your opinion on if you are interested.

Could you please elaborate on that?

**Comment by arekbulski** [comment]
Okay, after 2 years of thinking about it here is my conclusion:

What you are complaining about is that you use an unsupported feature, namely passing parse output into sizeof directly. This feature was never supported by me. Maybe it worked that way before, I dont know anything about that. Struct was reimplemented several times during my reign and its possible that I broke it unintentionally. 

The way I see it, you are the only person on this forum for whom "context doesnt work". Context seems to work correctly for pretty much anyone else. Therefore I am closing this issue.

Thank you for the PR too. Even tho you seem to have fixed something that wasnt entirely broken, I do appreciate some input. If you keep having problems with the context, feel free to open another issue. I will try my best to help you.

**Comment by girtsf** [comment]
I'm running into this as well. My use case involves a `Switch` based on a `version` field. While it works for parsing, it does not work for `sizeof` even if I pass in `version=N`.

**Comment by jpsnyder** [comment]
:shrug: 
The guess the developer didn't seem to think this issue was important enough.
IMHO the QoL features of construct over the years have dwindled or have been removed entirely (e.g. I miss `[:]` being used for GreedyRange)
I may fork construct (under a new name) in the future to better match my domain and re-add these QoL features.
