### ISSUE TITLE
Implement `Container`diffing

### ISSUE THREAD

**Issue by yannayl** [construct/construct#773]
I quite often find myself parsing similar structures, then print to files and diff the two.
It would be nice if there were a "diff" method for containers which would visually print the diff between two containers.

```Python
>>> a = "fdsafsd"
>>> b = "dsafsd"
>>> st = Struct(...)
>>> print st.parse(a).diff(st.parse(b))
```

**Comment by arekbulski** [comment]
Nice but I am not working on the project. I dont think you would implement the whole thing yourself hm? Please reply.

**Comment by yannayl** [comment]
Hi! unfortunately no. I try to share every feature I do implement to my satisfaction but this definitely isn't the top priority right now :/ I don't know when and if it will ever be.

**Comment by arekbulski** [comment]
I see it same way. Closing it then.
