### ISSUE TITLE
Not clear how to apply RawCopy with Checksum

### ISSUE THREAD

**Issue by ralienpp** [construct/construct#774]
I have the following code naive code that deals with a data structure that has a checksum field:

```py
from construct import *
from binascii import crc_hqx

def crc1(ctx):
    raw_tag = ctx.tag.to_bytes(length=2, byteorder='big')
    raw_length = ctx.length.to_bytes(length=4, byteorder='big')
    crc = crc_hqx(raw_tag + raw_length, 0)
    return crc.to_bytes(length=2, byteorder='big')

TlvEx = Struct(
    'tag' / Int16ub,
    'length' / Int32ub,
    'value' / Array(this.length, Byte),
    'crc' / Checksum(Bytes(2),  # checksum of the first two fields
        lambda data: crc1(data),
        this
        )
    )

```

Having consulted the manual and questions asked by others, I know that I should leverage `RawCopy`  to get it done. However, I cannot grasp how it works, even after reading the doc. I would like to make sure I understand this concept, so I can apply it in the future, with more complex scenarios.

The manual provides 2 examples, here's one of them:

```py
import hashlib
d = Struct(
    "fields" / RawCopy(Struct(
        Padding(1000),
    )),
    "checksum" / Checksum(Bytes(64),
        lambda data: hashlib.sha512(data).digest(),
        this.fields.data),
)
d.build(dict(fields=dict(value={})))
```

However, it refers to a single field, so I cannot transpose this to my case. The other example also uses a single field. I cannot wrap my head around the part where we transition from considering a single field in the checksum, to using multiple fields in the calculation.

Can you please bridge this gap with an example?

**Comment by arekbulski** [comment]
Too complicated example. I wont do your work for you, sorry.

**Comment by ralienpp** [comment]
I am sorry that I made the impression that I expected you to do someone else's work for them. I will happily contribute to the documentation, adding some remarks that will make it more comprehensible to beginners (at least from my perspective). But for that, I have to understand it myself first.

The complicated example is from the current documentation. If you refer to the data structure that I described - in what way can I simplify it, to make the question more specific?

My question boils down to "_How to rewrite the function `def crc1(ctx)`, such that it leverages the library correctly?_". 

After reading the doc multiple times - I couldn't figure it out. I have studied the example in the gallery and the ones from the deprecated gallery, I didn't find any examples that would match this scenario. This issue has been open for a month, throughout this time I had several attempts to approach this matter, but with no luck. I am thinking that I am missing some really obvious detail, and I was hoping someone could provide advice on how to address it, not necessarily the solution itself.

**Comment by DanseMacabre** [comment]
This issue is highlighting a gap in the documentation, it is a common use case to perform checksumming upon multiple, but not all, fields within a data structure.

This issue should be re-opened and an example provided in the documentation for this use case of the Checksum subcon.

**Comment by arekbulski** [comment]
Then use multiple RawCopy and then Checksum(..., this.fields1.data+this.fields2.data).

**Comment by StohanzlMart** [comment]
Read this for a comprehensible example if it's not already added to the docs:
https://github.com/construct/construct/issues/971
