### ISSUE TITLE
Construct Structure to Numpy Datatype

### ISSUE THREAD

**Issue by DPastl** [construct/construct#775]
Hello,

 I'm trying to adapt a library containing data structures written with construct our own data storage format, for which I need to use numpy custom datatypes.  Is there a built in or easy way to go from construct to numpy dtypes?

Thanks,

**Comment by DPastl** [comment]
I was looking through the source code (sbp_lib) and it looks like they did something a bit more custom so I don't think any of the built in methods of construct will work.

**Comment by arekbulski** [comment]
Check the Numpy as well as Pickled classes. RTFM.
