### ISSUE TITLE
Deduplicating fields read from same offset

### ISSUE THREAD

**Issue by RenaKunisaki** [construct/construct#779]
I have a complex struct describing a binary file format which contains several strings. These strings are all contained in a pool, but are referenced by their offsets by other substructs in the file.

When parsing the file, I read the string pool (which is itself a struct; a header followed by an array of strings) as well as other structs which reference those strings. As a result, the strings are read multiple times.

This isn't a problem for reading the file and writing it back, unless I want to modify a string. Changing one instance doesn't affect the others. When writing, depending on the order the structs are written, the modified string might be overwritten; or it will overwrite the original, rendering pointers to it incorrect.

Is there some way to fold multiple references to the same object/string, so that the various structs refer to the same instance?

**Comment by arekbulski** [comment]
I wasnt able to imagine what exactly you are trying to achieve at all. Its way too complicated to be a case for Construct, sorry. I am closing this because I dont think anyone else is going to well, do your (hard) work for you. Best of luck.
