### ISSUE TITLE
Referencing offset of fields later in struct

### ISSUE THREAD

**Issue by RenaKunisaki** [construct/construct#780]
How can I write the pointer of a field that hasn't yet been written? eg:

```python
>>> s = construct.Struct(
    "p_foo" / construct.Int32ul,
    "foo" / construct.Pointer(construct.this.p_foo,
        construct.PascalString(construct.Int8ul, 'utf-8')))
>>> s.parse(b'\x04\0\0\0\x05Hello')
Container(p_foo=4, foo=u'Hello')
>>> s.build({'foo':"hello"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 352, in build
    self.build_stream(obj, stream, **contextkw)
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 364, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/usr/lib/python3.7/site-packages/construct/core.py", line 1998, in _build
    subobj = obj[sc.name] # raises KeyError
KeyError: 'p_foo'
```

I imagine there's something I can do with Rebuild and LazyBound and maybe RawCopy or Tell to get the offset of `foo` and seek back to fill it in, but I haven't been able to figure it out. (Just using `Tell + 4` won't work because in real cases `foo` might be arbitrarily far away from `p_foo`.)

**Comment by jpsnyder** [comment]
You must provide the `p_foo` value when building, otherwise it has no idea where to place the `foo` object.

When you use `Seek` or `Pointer` while building it should back fill the data with null bytes.

**Comment by RenaKunisaki** [comment]
OK, so is there any way to go back and fill in the offsets after writing `foo`? Or do I have to do that manually?

**Comment by RenaKunisaki** [comment]
Well I've managed to put together some classes that achieve this, but I'm unusre if I'm going about it properly. It's proving quite awkward, especially with arrays.

The gist of it is:

- Offset: Wraps a field (which should be an integer) for later reference by AutoPtr
- AutoPtr: Works like a Pointer, but also seeks back to theTh location of an Offset and writes the stream position there; writes the referenced object at the *current* stream position
- DeferredAutoPtr: Like AutoPtr, but doesn't write the referenced object; that's done later by WriteAutoPtr
- WriteAutoPtr: does nothing when parsed; when building, writes the referenced object of a previous DeferredAutoPtr
- CheckAutoPtrs: issues warnings if any DeferredAutoPtrs weren't written

The classes reference fields by name, which is buggy. Hopefully you can help with this?
[AutoPtr.py.txt](https://github.com/construct/construct/files/2911918/AutoPtr.py.txt)

**Comment by arekbulski** [comment]
This seems like a too difficult thing to do using Construct... It was never meant to do such complicated things, this library.

**Comment by arekbulski** [comment]
You need to PR a proper test case, but a colleague already pointed out the solution: you need to provide the integer with a value. Rewrite the code without "construct." too.
