### ISSUE TITLE
Refering to Enum in BitStruct

### ISSUE THREAD

**Issue by waszil** [construct/construct#781]
Is it possible to refer to an Enum inside a BitStruct? Now it tells me "AttributeError: 'Transformed' object has no attribute <...>"
Thanks!

**Comment by felixn** [comment]
Here's a small example of this behavior:

```
d = Struct(
    "animal" / Enum(Byte, giraffe=1),
)

x = d.parse(b"\x01")
assert x.animal == "giraffe"  # works
assert x.animal == d.animal.giraffe  # works

d = BitStruct(
    "animal" / Enum(BitsInteger(8), giraffe=1),
)

x = d.parse(b"\x01")
assert x.animal == "giraffe"  # works
assert x.animal == d.animal.giraffe  # AttributeError: 'Transformed' object has no attribute 'animal'
```

**Comment by arekbulski** [comment]
Please PR a test case first.

**Comment by arekbulski** [comment]
PR accepted at https://github.com/construct/construct/pull/788 . This is indeed a bug, because its unacceptable behavior but I am not able to fix it. Bitwise (BitStruct) hacks data in ways that make a fix too difficult. I am leaving this ticket open as a warning, with no fix.
