### ISSUE TITLE
Any automation help with translating pre-2.8 definitions to newer versions?

### ISSUE THREAD

**Issue by in90210foq** [construct/construct#782]
Has anyone tried to auto-generate translation of some newer Construct definition code from old v.2.5 definitions?  How might someone attempt this?  (Any little bit of code generation might help someone with larger amounts of old code?)  Any guidance would be appreciated.  Thanks

**Comment by arekbulski** [comment]
That is a negatory.

Its not possible. The entire API was redesigned and even so, you are expected to make use of the cutting edge classes and not translate 1-to-1. Sorry, but if you want to contribute then you need to write it by hand. Case closed.
