### ISSUE TITLE
Static Field, packer,_read_stream, _write_stream are not present in construct.core module, can someone please help, what are the new modules i have to use instead of these, i am using construct version : 2.9.5

### ISSUE THREAD

**Issue by MaruthiRathnakar** [construct/construct#783]

**Comment by arekbulski** [comment]
Putting your entire description into the title makes you seem like a child or troll. I wont even read it. Also exploring the namespace is something you should do yourself and not use other people for it. I suggest you read the (oh excellent...!) documentation (yes, I wrote it). Thats it.

**Comment by MaruthiRathnakar** [comment]
Thanks arekbulski
