### ISSUE TITLE
Extraneous value getting Struct values

### ISSUE THREAD

**Issue by dberansky** [construct/construct#785]
I'm using Construct v2.9.45 and I get a strange difference in behavior when running the code under Windows (Python 3.6) vs Linux (Python 3.5).

Here's a snippet of the construct structure:

```
    "cpu_count" / Int32ul,
    "times" / Array(this.cpu_count, Struct(
        "user" / Int32ul,
        "nice" / Int32ul,
        "system" / Int32ul,
        "idle" / Int32ul,
        "iowait" / Int32ul,
        "irq" / Int32ul,
        "soft_irq" / Int32ul,
    )).compile(),

```

elsewhere in the code I have the following two lines:

```
        print(row.times[cpu_num])
        print(list(row.times[cpu_num].values()))
```

The output I get on Windows is (as expected):

```
Container: 
    user = 766
    nice = 965
    system = 10468
    idle = 17958
    iowait = 392
    irq = 332
    soft_irq = 140
[766, 965, 10468, 17958, 392, 332, 140]

```

On linux I get the following instead:

```
Container:
    user = 766
    nice = 965
    system = 10468
    idle = 17958
    iowait = 392
    irq = 332
    soft_irq = 140
[<_io.BytesIO object at 0x7f276dbbc5c8>, 766, 965, 10468, 17958, 392, 332, 140]

```

What's that io.BytesIO object doing in the value list?  This code worked as expected in v.2.8.x.  Should I be using a different approach if I want to get the structure's values as an array?

**Comment by arekbulski** [comment]
Please PR a proper (and very simple) test case for this. Only then will I investigate it.

**Comment by dberansky** [comment]
turned out to be a version conflict in the linux environment
