### ISSUE TITLE
Parsing a list of key-value pairs to list of dictionaries (containers) 

### ISSUE THREAD

**Issue by igiloh** [construct/construct#786]
Say I have an array of simple key-value pairs:

```python
pair = Struct(
    "key" / PascalString(MyInt8u, "ascii"),
    "value" / MyDouble
)

output = Struct(
    "number_of_items" / Rebuild(MyInt32u, len_(this.pair_array)),
    "pair_array" / Array(this.number_of_items, pair)
)
```
I want the output to be something like:
```python
[ {"first_key": 1}, {"second_key":2} ]
```
And **not**:
```python
[ {"key":"first_key" , "value": 1} , {"key":"second_key" , "value": 2}]
```

I'm pretty sure I need an `Adapter` for that - but not sure about the syntax.  
Would really appreciate some help!

I can probably do it without `Adapter` in an external loop (before building and after parsing) - would that be faster or slower? I plan to compile this struct.

**Comment by arekbulski** [comment]
I wont do your work for you. You can use an adapter or simply transform the dictionary manually after the parsing.

**Comment by igiloh** [comment]
No problem - I'll make it work eventually 😄 

I was just wondering as a general rule of thumb whether an adapter be faster than a manual loop.  
I guess I'll just try both and measure.

**Comment by arekbulski** [comment]
Of course, Adapter would be a bit slower because it has its own red tape internally. But unless your code is time critical, it wont be that much difference... you are writing in Python after all...
