### ISSUE TITLE
Embedding BitStruct: another take

### ISSUE THREAD

**Issue by michallowasrzechonek-silvair** [construct/construct#787]
I've come up with a somewhat nasty macro... that works ;)

The idea is to:
 - nest the `BitStruct` as usual
 - when building, `Rebuild` it, taking field values from the parent
 - when parsing, generate `Computed` accessors in the parent

The syntax is awkward, though, as I can't think of a way to add `Computed` fields to the parent construct.

```
def EmbeddedBitStruct(name, *args):
    return (name / Rebuild(BitStruct(*args), dict), ) + \
           tuple(i.name / Computed(this[name][i.name]) for i in args)

Header = Struct(
        *EmbeddedBitStruct(
            "_bits",
            "type" / BitsInteger(4),
            "pad" / BitsInteger(4),
        ),
        "length" / Rebuild(Int8ul, len_(this.data)),
        "data" / Bytes(this.length),
    )

def test_embedded_bitfield_parse():
    frame = bytes.fromhex('32040a0b0c0d')

    header = Header.parse(frame)
    assert header.type == 3
    assert header.pad == 2
    assert header.length == 4
    assert header.data == bytes.fromhex('0a0b0c0d')

def test_embedded_bitfield_build():
    frame = Header.build(dict(
        type=3,
        pad=2,
        data=bytes.fromhex('0a0b0c0d')
    ))

    assert frame == bytes.fromhex('32040a0b0c0d')
```

**Comment by arekbulski** [comment]
Again, I totally discourage using Embedding...

**Comment by michallowasrzechonek-silvair** [comment]
OK, but if so, what's the recommended way to define reusable bit fields and mix them with bytewise structs?

The protocol I'm dealing with is Bluetooth Mesh, and it has a very nasty habit of switching endianness between layers, so it's not practical to define everything as a bitstruct, because I need to differentiate ul/ub variants.

**Comment by arekbulski** [comment]
My recommendation is dont.

**Comment by michallowasrzechonek-silvair** [comment]
:)
