### ISSUE TITLE
How to define a recursive structure

### ISSUE THREAD

**Issue by pfmoore** [construct/construct#790]
I'm struggling to work out how to define a recursive structure ([Minecraft NBT data](https://minecraft.gamepedia.com/NBT_format), for what it's worth). The structure is basically (highly simplified)

```python
tag_map = {
    1: Byte,
    9: Struct("tag" / Byte, "vals" / PrefixedArray(Byte, tag_map[this.tag]))
}

TAG = Struct(
    "id" / Byte,
    "value" / Switch(this.id, tag_map)
)
```

This doesn't work as it stands (obviously!) as `tag_map[9]` is recursive - it's an ID (byte), then a count (byte), then a number of values, whose type is determined by the ID. And it's possible for the structure to be a list of lists, for example:

```python
>>> data = b"\x09\x09\x02\x01\x01\x07\x01\x02\x06\x05"
>>> my_parser.parse(data)
[[7],[6,5]]
```

I've tried all sorts of variations using `LazyBound`, but they are all failing with error messages that I can't interpret - for example,

```
  File ".\t.py", line 5, in <lambda>
    9: Struct("tag" / Byte, "vals" / LazyBound(lambda:PrefixedArray(Byte, tag_map[this.tag])))
TypeError: unhashable type: 'Path'
```

I'm guessing that I can't use the magic `this` reference in a `LazyBound`, but I need to access the type of the list elements when I define the list structure.

Can anyone show me how I'd define a structure like this? Or at least point me to an example in the docs or elsewhere that explains things more clearly?

**Comment by jpsnyder** [comment]
It looks like LazyBound doesn't pass you the context to your lambda. You'll need to create your own version that does.

```python
class NewLazyBound(LazyBound): 
  def _parse(self, stream, context, path):
    sc = self.subconfunc(context)
    return sc._parsereport(stream, context, path)

  def _build(self, obj, stream, context, path):
    sc = self.subconfunc(context)
    return sc._build(obj, stream, context, path)


tag_map = {
  1: Byte,
  2: Int16ul,
  # ...
}

TAG = Struct(
  'tag' / Byte,
  'vals' / NewLazyBound(lambda ctx: tag_map[ctx.tag])
)

tag_map[9] = PrefixedArray(Byte, TAG)
```

**Comment by jpsnyder** [comment]
Actually, the LazyBound isn't necessary:

```python
tag_map = {
  1: Byte,
  2: Int16ul,
  # ...
}

TAG = Struct(
    'tag' / Byte,
    'vals' / Switch(this.tag, tag_map),
)

tag_map[9] = PrefixedArray(Byte, TAG)


data = b'\x09\x02\x09\x01\x01\x02\x09\x02\x01\x03\x02\x04\x00'

print TAG.parse(data)

```

```
Container: 
    tag = 9
    vals = ListContainer: 
        Container: 
            tag = 9
            vals = ListContainer: 
                Container: 
                    tag = 1
                    vals = 2
        Container: 
            tag = 9
            vals = ListContainer: 
                Container: 
                    tag = 1
                    vals = 3
                Container: 
                    tag = 2
                    vals = 4
```

**Comment by pfmoore** [comment]
First of all, thanks for the example of LazyBound. I'll remember that for the future.

**But** more importantly, thanks for pointing out my dumb mistake, you're absolutely right I don't need that machinery anyway. My problem was twofold - first, I was having trouble creating the map because I needed to use data I hadn't defined yet. I can't believe I completely missed the simple approach of updating the map after defining the extra item for so long 😞 Added to that, I'd made a mistake with my test data, which meant I was getting errors that didn't actually relate to my real issue - I'm not sure that made much difference (the errors from Construct aren't exactly easy to interpret!) but it sure didn't make it any easier...

Anyway, thanks so much for the advice, I now have my code working.
