### ISSUE TITLE
Is there a repository of recipes to start from?

### ISSUE THREAD

**Issue by danielquinn** [construct/construct#792]
I've been working on a [project](https://github.com/danielquinn/aletheia) that reads/writes header data for media files (jpg, png, mkv, pdf, etc.) and until now I've been relying on external binaries like `exiftool` and `ffmpeg` to do the work.  Now that I've discovered this project however, I'd like to remove those dependencies and make the library independent.

I'd rather not re-invent the wheel though, so if there's a repository out there of examples for the many many media file formats out there (at the moment my project supports jpg, gif, png, mp3, mkv, webm, and mp4), and the deprecated_gallery folder doesn't cover most of that.  Is there a handy repo that one can reference for standard formats, or is this more of a "figure it out and hope you got it right" situation?

I should mention that I'm mostly a web guy, so digging deep into binary file formats is brand-new to me.  The learning curve appears rather steep.

**Comment by arekbulski** [comment]
Just look into this library source, deprecated_gallery and gallery.
