### ISSUE TITLE
If(), Switch() doesn't support "and" and "or" statements for multiple expressions.

### ISSUE THREAD

**Issue by geekyprats** [construct/construct#793]
Hi Folks,

I just noticed the If() and Switch() method doesn't support "and" and "or" operators thoroughly.
As an example

==============================================
from construct import *

TestStructure = Struct(
"var1" / Int8ul,
"var2" / Int8ul,
"var3" / Int16ul,
"var4" / If(this.var1 == 0x00, Int8ul),
"var5" / If((this.var1 == 0x00 and this.var2 == 0x00), Int16ul),
)

print (TestStructure.parse(b"\x8C\x00\x00\x00"))

=====================================

Ideally since var1 value == 0x8C, var4 & var5 will be absent and the number of bytes is sufficient and the program should pass.

However, on debugging inside construct's core.py, I found that If() is only able to take right most expression, i.e. this.var2==0x00, and hence it makes the expression true. Due to which it expects more bytes and code crashes.

Can someone let me know how to use multiple expressions using and/or.

**Comment by geekyprats** [comment]
Ok I figured out. Seems lambda must be used. Changing below line works
"var5" / If( lambda this : (this.var1 == 0x00 and this.var2 == 0x00), Int16ul),

**Comment by arekbulski** [comment]
Yes, its explained in the docs.
