### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by wgaylord** [construct/construct#794]
Question why is this construct 2.9 being maintained while construct 3 has been abandoned?

**Comment by harvimt** [comment]
Construct3 was a fork by a different developer (both of the original construct and the current maintainer of 2.9)

**Comment by arekbulski** [comment]
Construct 3 was a spinoff of previous developer. He abandoned it.  Thats it.

**Comment by arekbulski** [comment]
This is why the versioning goes 2.(10).(51) and not 3.x .
