### ISSUE TITLE
Using Optional inside BitStruct doesn't work, raises Stream Error

### ISSUE THREAD

**Issue by MaruthiRathnakar** [construct/construct#795]
I have a optional field inside the Bitstruct  like below, actually i have other fields inside the Bitstruct, but i have simplified the Structure just to keep it easy to understand

codec = BitStruct("cpo" / Optional(BitsInteger(8)))

codec.parse(b"")  raised Stream Error :
construct.core.StreamError: stream read less then specified amount, expected 8, found 0
construct.core.StreamError: stream.seek() failed, offset 0, whence 0

But if i use, Struct it works..
codec = Struct("cpo" / Optional(BitsInteger(8)))
codec.parse(b"")  will give me output as Container(cpo=None) as expected

I expect it to work in BitStruct as well.

we do have this issue raised, https://github.com/construct/construct/issues/747

But , there is no solution yet, i cant make this one as Transformed also.

@arekbulski , can you please suggest me a work around for this.

Thanks a lot

**Comment by MaruthiRathnakar** [comment]
I am using construct 2.9.45 version with python 3.7

**Comment by arekbulski** [comment]
Dont use BitStruct then. Use BytesIntefer(1) instead of BitsInteger(8).

**Comment by MaruthiRathnakar** [comment]
@arekbulski without Bitstruct, I cant accomplish my task, But Optional should work always if we go by its definition i guess, I cant really avoid BitStruct

**Comment by arekbulski** [comment]
My point is that BitStruct (Bitwise) does very hackey things with data, and its not all simple to explain what happens with anything that interacts with it. I generally advise either not use it at all or only with basic and tested classes like BitsInteger. Optional was never tested in this context. Like most classes.

**Comment by MaruthiRathnakar** [comment]
Thanks I understand the point,Optional was working fine in the Previous release of construct - 2.8, As soon as i updated to 2.9.45, I found that Greedyrange and Optional not working in Bitstruct case.

Will this issue be addressed in next release?

**Comment by jpsnyder** [comment]
The reason you are getting a StreamError is because the internal `RestreamedBytesIO` object that converts the byte stream to a bit stream doesn't implement the seek() function, which is needed by `Optional` and `GreedyRange`.

As a workaround, you can convert the bytes to bits using `bytes2bits` before passing it into parse() and then use the regular `Struct`.

```python 
from construct import *
from construct.lib.binary import bytes2bits


# Use "Struct" because we already converted the stream.
codec = Struct("cpo" / Optional(BitsInteger(8)))


# Convert data to bit stream
data = bytes2bits(b"")
codec.parse(data)
```

However this will limit you, because you no longer can jump in and out of byte and bit mode within a single construct.

**Comment by arekbulski** [comment]
@jpsnyder Very accurate.

**Comment by arekbulski** [comment]
@jpsnyder  This is a very accurate assessment AFAIR.

**Comment by MaruthiRathnakar** [comment]
Thanks @jpsnyder , works like a charm

**Comment by arekbulski** [comment]
> Will this issue be addressed in next release?

This issue will never be addressed.
