### ISSUE TITLE
Architectural changes

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#80]
I want to make some changes on the API level in the forseeable future so if you have something against it, speak your mind openly:

###  List is not up to date but close.

- [ ] Nameless fields now use `"name" / Byte"` syntax, many fields turned singletons.
- [x] Container now uses a different syntax for creating eg `Container(a=1)(b=2)`
- [x] Container also created using `Container([(k,v),(k,v)])` and `Container(list of dicts)`
- [x] Container also created from one dict, ie `Container(container2)`
- [x] Container popitem now takes last, not random item out
- [x] Container equality checks order (by default) or skips it (if asked to)
- [x] FlagsContainer equality doesnt check order because its built from a dict
- [x] OpenRange/GreedyRange/OptionalGreedyRange consolidated into one class
- [x] Adapters functionality moved into Construct/Subconstruct
- [x] Tunnel and SymmetricAdapter abstract classes (adapters transform objects, tunnels transform bytes)
- [ ] LazyStruct and LazyRange, where data is parsed on demand
- [ ] RepeatWhile analog to RepeatUntil
- [x] Value renamed to Computed, make it parse only, noop on build
- [x] Const should take over adapter and Magic 
- [x] Padding and Aligned use stream tell, not subcon sizeof
- [x] Union builds more like Select, tries each subcon 
- [x] AnchorRange that measures both offsets and length, better than Anchors
- [ ] Sizeof should be more strict
- [x] String incorporates the adapter
- [x] PascalString(lengthfield=UBInt16()) should work with anonymous length field
- [x] CString and GreedyString also reimplemented 
- [x] Anchor has optional subtract argument, name of another Anchor
- [x] Checksum using AnchorRange
- [x] Numpy construct that is better than Range and manual conversion from list
- [x] LengthValue class that chops a buffer of the stream
- [x] Compression and PrefixedCompression
- [x] Slicing and Indexing changed
- [x] GreedyBytes added
- [x] Drop support for PY 3.2, due to unicode literals 
- [x] Drop support for PY 2.5, due to not being on Travis
- [ ] Make it dependent on Cython, this is far far away

Of lesser importance:
- [x] Remove six completely
- [x] py3compat overhaul
- [x] Move prettystr into `__str__` 
- [x] Unlimited lines, PEP8 is good but word wrap is better
- [x] Arguments being renamed, so `length_field` becomes `lengthfield`

Ping @tomerfiliba

**Comment by joachimmetz** [comment]
> Unlimited lines, PEP8 is good but word wrap is better

Regarding this action item, have a look at [yapf](https://github.com/google/yapf) if not already

**Comment by arekbulski** [comment]
Nice tool, thank you! :smiley:  Unfortunately it uses a style that I am getting away from.

**Comment by joachimmetz** [comment]
Just FYI, it supports multiple styles, also quite configurable. Might not be a 100% match but could help you on your way.

**Comment by arekbulski** [comment]
This thread is no longer maintained. **Please move to #86 and subscribe to it.****
