### ISSUE TITLE
Checksum Warning

### ISSUE THREAD

**Issue by DanseMacabre** [construct/construct#803]
Is there an existing way for a checksum failure to emit a warning (and possibly set some hidden variable flags?), rather than raising an error?

The use case for this would be reading data from a link that may have multiple sub-messages/blocks that are individually checksummed within a larger message block.

Obviously a quick-n-dirty fix would be to modify the exception into a warning, or add a warning ad a config parameter, however it would be good if this could be achieved using the standard version.

**Comment by arekbulski** [comment]
Nothing like this will me implemented in the mainstream version.

**Comment by DanseMacabre** [comment]
Understood.

I can implement this behaviour with an Adapter instead I think.
