### ISSUE TITLE
ValidationError caught by GreedyRange. Add message.

### ISSUE THREAD

**Issue by JohannesNE** [construct/construct#804]
I'm parsing a file with a repeated structure using GreedyRange. I want to validate some of the values (e.g. using OneOf), but GreedyRange catches the ValidationError.

Is there a better way to parse and validate a file with a repeated structure of unknown length? Otherwise, I suggest adding a message, notifying the user if an exception is caught.

**Comment by DanseMacabre** [comment]
I'd suggest that this was intended behaviour, as the documentation is written. If something fails validation, then it is logical to assume that the GreedyRange should stop as it no longer fits the specified format.

**Comment by JohannesNE** [comment]
Ahh, I see.
It could be useful with the option in 'validate functions' to raise exceptions that are not caught by GreedyRange, but it might complicate things too much.

Is there an alternative way, that allows me to repeat a structure till the end of the stream and also validate values?

**Comment by DanseMacabre** [comment]
You should be able to use RepeatUntil for that purpose, with a context lambda looking either at the remaining stream size by returning false when remaining bytes = to the the size of the struct you're attempting to read into.

**Comment by JohannesNE** [comment]
Thanks for the clarification about GreedyRange. I ended up solving the problem using a loop until StreamError:

```python
body = ListContainer()
completed = False
while not completed:
    try:
        body.append(body_str.parse_stream(f))
    except StreamError:
        print("End of stream reached")
        completed = True
```
