### ISSUE TITLE
Building variable length field with preceding offset and length fields

### ISSUE THREAD

**Issue by catern** [construct/construct#805]
Hi,

I'm running into some issues with building a protocol with messages with variable-length parts. Parsing the messages is fine and easy, it's only building that is tricky.

Suppose I have a binary message, with a header like this C struct:
```
struct header {
  ...some fields...
  size_t data1_offset;
  size_t data1_length;
  ...some fields...
  size_t data2_offset;
  size_t data2_length;
  ...some fields...
}
```

Building just this header is fine with Construct, that part is easy.

But then after this header, I put two variable-length arbitrary bytestrings "data1" and "data2", one after another.

Then I want data1_offset to point to the start of data1 (which in this case will be the end of the header, but can be tricky if the header contains more variable-size things, such as a Switch), and data1_length to contain the length of data1. And I want data2_offset to point to the start of data2 (which in this case will be data1_offset, plus data1_length), and data2_length to contain the length of data2.

I can't see a way to do this in Construct.

To build the data1_offset and data2_offset fields, I need to know the offsets of the variable-length parts. But I don't know those offsets until I actually reach that point in the building, which is after data1_offset and data2_offset have already been built.

Any thoughts?

**Comment by DanseMacabre** [comment]
This is possible with the Rebuild Subcon.
For length:
`Rebuild( Int16ul, lambda ctx: data1.sizeof())`
Where data1 is the context reference to your data1 data.

For offset, use the same, but instead of returning the data sizeof, either write a function to calculate the offset of something in a stream, or using Tell or .tell'ing the underlying objects.

**Comment by catern** [comment]
Yes, I'm familiar with the Rebuild subcon. I've already been using it for a constrained form of this problem.

The issue is with determining the value for the offsets. It's not clear either how to write a function to calculate the offset, or to use Tell. Using Tell, for example, doesn't seem to help, because while inserting a Tell just before the data1 data will give me the offset at that point, I can't get that offset back to when data1_offset needs it, which is before that Tell gets computed.

**Comment by DanseMacabre** [comment]
I had a little bit of a play, and I think I understand your issue more now, and yes, that is awkward!

The only way to do it would be to .sizeof() and sum all constructs prior to the data with enough context to calculate sizeof, however in your particular case that is v. difficult.

Don't think I can help, but I'll think on the problem and see if a solution occurs to me.

**Comment by arekbulski** [comment]
I dont understand most of this issue, so I will just link to Tell class:
https://construct.readthedocs.io/en/latest/streaming.html#pure-side-effects
https://construct.readthedocs.io/en/latest/api/streaming.html#construct.Tell

**Comment by catern** [comment]
Thanks for the link! Sadly, as I said above, Tell doesn't work here because I need to know the offset of a position *before* reaching that position.

**Comment by arekbulski** [comment]
Then insert Tell before it?

**Comment by DanseMacabre** [comment]
@catern I know this isn't helpful for you yet, however with some more work, I think something could be done with the below code. It's a bit unclear and possibly an abuse of the behaviour of the API, for sure, and it currently only works for parsing, building outputs the default 0 parameter. I can only look a bit further into this in a few hours.

`from construct import *

demo_construct = Struct(
    "data1_len" / Int8ul,
    "data1_offs" / Default(Int8ul, 0),
    "data2_len" / Int8ul,
    "data2_offs" / Default(Int8ul, 0),
    "data1_offs" / Tell,
    "data1" / RepeatUntil(lambda x, lst, ctx: len(lst) >= ctx.data1_len / Int8ul.sizeof(), Int8ul),
    "data2_offs" / Tell,
    "data2" / RepeatUntil(lambda x, lst, ctx: len(lst) >= ctx.data2_len / Int8ul.sizeof(), Int8ul),
    Probe()
)

if __name__ == "__main__":
    data1_list = [0xDE, 0xAD]
    data2_list = [0xBE, 0xEF]
    to_build = dict(
        data1_len=len(data1_list),
        data2_len=len(data2_list),
        data1=data1_list,
        data2=data2_list
    )
    built = demo_construct.build(to_build)
    print(built)
    parsed = demo_construct.parse(built)
    print(parsed)`

**Comment by DanseMacabre** [comment]
@catern This is _gloriously_ hacky, but it works for build and parse. Might be a way to work out how to do what you need to do:

```
from construct import *

demo_construct = Struct(
    "data1_len" / Int8ul,
    "_data1_offs_ptr" / Tell,
    "data1_offs" / Default(Int8ul, 0),
    "data2_len" / Int8ul,
    "_data2_offs_ptr" / Tell,
    "data2_offs" / Default(Int8ul, 0),
    "_data1_offs" / Tell,
    "data1_offs" / Pointer(this._data1_offs_ptr, Rebuild(Int8ul, this._data1_offs)),
    "data1" / RepeatUntil(lambda x, lst, ctx: len(lst) >= ctx.data1_len / Int8ul.sizeof(), Int8ul),
    "_data2_offs" / Tell,
    "data2_offs" / Pointer(this._data2_offs_ptr, Rebuild(Int8ul, this._data2_offs)),
    "data2" / RepeatUntil(lambda x, lst, ctx: len(lst) >= ctx.data2_len / Int8ul.sizeof(), Int8ul),
    Probe()
)


if __name__ == "__main__":
    data1_list = [0xDE, 0xAD]
    data2_list = [0xBE, 0xEF]
    to_build = dict(
        data1_len=len(data1_list),
        data2_len=len(data2_list),
        data1=data1_list,
        data2=data2_list
    )
    built = demo_construct.build(to_build)
    print(built)
    parsed = demo_construct.parse(built)
    print(parsed)
```
