### ISSUE TITLE
ListContainer, indentation is new line but how to use comma

### ISSUE THREAD

**Issue by sbasharati** [construct/construct#806]
I am using a nested structure and some of them are a long bytearray (256 size) and when I print it each item of the ListContainer is printed on a new line but I really want comma separated rather than new line. 
Maybe one way is to make indentation = "\n    " as argument with different options.

**Comment by DanseMacabre** [comment]
Write your own prettyprinter. All the data you need to print is right there, the methods provided by Construct to output data are a mere convenience, if you need anything above and beyond that, you should implement that yourself. If you *must* use construct's printing system, I'm sure you could write and Adapter to do that job quite happily. An example of an Adapter on an Array is provided in the documentation: https://construct.readthedocs.io/en/latest/adapters.html#adapting

**Comment by sbasharati** [comment]
Thanks for the tip of using Adaptor but now when I print I get another truncated problem, is there another way

data = b'1795020100000000'... (truncated, total 32)

**Comment by DanseMacabre** [comment]
https://construct.readthedocs.io/en/latest/api/bytes.html#construct.setGlobalPrintFullStrings
