### ISSUE TITLE
Error in check.data.partitions.covmats(args)

### ISSUE THREAD

**Issue by rpercino** [construct/construct#807]
Hi, 

I try to run the cross validation analysis the following error pop up:
Error in check.data.partitions.covmats(args) : 
you have specified an invalid data partition "data" element is not positive definite. 

these the code:
my.xvals <- x.validation(train.prop = 0.9, n.reps = 10, K = 1:5,
                         freqs = freqs, 
                         data.partitions = NULL,
                         geoDist = geoDist, coords = coords, 
                         prefix = "Crau_K1_5", n.iter = 1000, 
                         make.figs = FALSE, save.files = TRUE, 
                         parallel = FALSE, n.nodes = 1)

Please, can you help what is going on error? thank you in advance,

r

**Comment by DanseMacabre** [comment]
You've posted this in the wrong repository.

**Comment by rpercino** [comment]
Sorry, I didn't realize, I apology
