### ISSUE TITLE
BitStruct little endian

### ISSUE THREAD

**Issue by gek47** [construct/construct#809]
How to tell BitStruct data is little endian?
I have the following little endian data:
b'\x01\x00\x00\x00'

BitStruct('flag00'  / Flag,
              'flag01'  / Flag,
              ...
              'flag31 /  Flag
             )

parsing assigns flag07 the value True and the rest False
what I need is for flag31 to be True and the rest False

Thanks

**Comment by gek47** [comment]
Thanks for the help, would you provide an example? I have been playing around for a few days and can't get it right.  I very new to construct.

**Comment by arekbulski** [comment]
Check the documentation.

**Comment by gek47** [comment]
I did not understand arekbulski's solution but found another
ByteSwapped(BitStruct( flags for little endian 32 bit int))
