### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by khssnv** [construct/construct#810]
Python3.8 deprecates `imp` module

```python
$ python3.8                                                                                                                                                                                        
Python 3.8.0b4 (default, Sep 14 2019, 21:10:22)
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import construct
/home/user/test/venv-py38/lib/python3.8/site-packages/construct/core.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
>>>
```

**Comment by paravoid** [comment]
It's actually deprecated since 3.4, and emits DeprecationWarnings since 3.7.

**Comment by arekbulski** [comment]
I know it is deprecated. But its necessary for the compilation feature. Thats it.

**Comment by paravoid** [comment]
I see you're only using `imp` as `module = imp.new_module(modulename)` in `core.py.

Not an expert in importlib, but following the pointers from the documentation it sounds like this could be replaced with:
```python
module_spec = importlib.machinery.ModuleSpec(modulename, None)
module = importlib.util.module_from_spec(module_spec)
```
This requires 3.5+, so it could need some duck-typing, catching the missing method and falling back to `imp` if you want to retain compatibility.

Alternatively, from the docs it sounds like for something as simple as this you could simply use:
```python
module = types.ModuleType(modulename)
```
...which seem to be older (but not deprecated).

**Comment by arekbulski** [comment]
I am simply not interested in fixing this. Case dismissed.

**Comment by mgoral** [comment]
May I ask you to reconsider? Deprecation means that `imp` will be finally removed from Python and PEP594 schedules the removal to Python 3.10 (https://www.python.org/dev/peps/pep-0594/#imp). It means that most probably since 2021 construct will not work anymore with new Python versions.

Python already 3.9 removed a lot of deprecated features which caused massive problems e.g. in Fedora because there are many libs and programs which ignore these warnings (https://mail.python.org/archives/list/python-dev@python.org/thread/EYLXCGGJOUMZSE5X35ILW3UNTJM3MCRE) and I'm worried about the future of this library and software which uses it if it continues to ignore deprecation warning.

**Comment by arekbulski** [comment]
I would prefer to postpone this issue indefinitely. If something breaks, then I will disable compilation feature and publish a "fixed" version asap. So dont worry.

**Comment by arekbulski** [comment]
@paravoid and @mgoral 
I welcome you both fix this and PR it. I dont know nothing about how impotlib works, nada.

**Comment by paravoid** [comment]
I've posted two alternatives above (one two-liner, and one one-liner). Either one should work and be a drop-in replacement for the `module = imp.new_module(modulename)` line.

**Comment by arekbulski** [comment]
Can you PR it?

**Comment by arekbulski** [comment]
Alright, I will check it out.

**Comment by mgoral** [comment]
I sent PR with implementation suggested by @paravoid.

**Comment by arekbulski** [comment]
It looks good, builds and tests ok. Thank you all guys.

**Comment by gormux** [comment]
Hello, could you also make a release so that projects using construct do not get the deprecation warning when using from pypi ?

**Comment by mahao18cm** [comment]
ignore_types = [ imp.C_EXTENSION, imp.C_BUILTIN ]
init_names = [ '__init__%s' % x[0] for x in imp.get_suffixes() if
               x[0] and x[2] not in ignore_types ] how to replace this
