### ISSUE TITLE
Hidden fields in Container aren't very hidden

### ISSUE THREAD

**Issue by iabervon** [construct/construct#811]
In 2.8, I was using lines like "obj = MyClass(**fmt.parse(data))", which extracted all of the fields of the Struct into same-named arguments of my class constructor without any fuss. In 2.9, this also sends hidden fields as keyword arguments. Would it be possible for Container to omit hidden fields from the responses to methods like keys() or items() and only return them to code that knows what field to look for or specifically asks for internal details?

**Comment by arekbulski** [comment]
In short, no. You can copy `Struct` class source into your code, and remove the offending lines if you likes. There is no switch  to be pulled like `SetGlobal*` alikes.
