### ISSUE TITLE
 What are used instead of EmbeddedBitStruct and BitField in py construct 2.9?

### ISSUE THREAD

**Issue by mnergis** [construct/construct#812]
I use py construct 2.5.2 version. I want to update to 2.9. For example:

```py
xid = Struct("xid",
               EmbeddedBitStruct(
                                BitField("versionNum",3),
                                BitField("type",1), ),) 
```

What can I use instead of this code?

**Comment by arekbulski** [comment]
RTFM: https://construct.readthedocs.io/en/latest/transition28.html

**Comment by mnergis** [comment]
> RTFM: https://construct.readthedocs.io/en/latest/transition28.html

There is no info about EmbeddedBitStruct.

**Comment by arekbulski** [comment]
There is: https://construct.readthedocs.io/en/latest/transition29.html

**Comment by arekbulski** [comment]
You can also just use `Embedded(Bitwise(Struct( )))`. Thats what the macro did in the first place.

**Comment by arekbulski** [comment]
I forgot to add: since the embedding semantics have changed, its no longer possible to embed Bitwise context. You need to forgo embedding it.

**Comment by ilteberkarapinar** [comment]
Hi, I have tried this:


```
xid = Struct(Bitwise("xid" /
               BitStruct(
                      "versionNum" / BitsInteger(3),
                      "type" / BitsInteger(1) )))
```

But It didn't work.

**Comment by arekbulski** [comment]
BitStruct is already a Bitwise. You bitwised it twice. Duh.

**Comment by arekbulski** [comment]
Simple.
```py3
xid = Struct("xid" / BitStruct(
                      "versionNum" / BitsInteger(3),
                      "type" / BitsInteger(1) ))
```
