### ISSUE TITLE
How to use Checksum with embedded fields?

### ISSUE THREAD

**Issue by rotu** [construct/construct#813]
I can't quite figure out how to checksum fields without nesting them. The below code creates `field1` and `field2` keys nested beneath a `fields` key (trying to use `Embedded` to un-nest this, either outside or inside the `RawCopy` constructor, gives me a `ConstructError`).

Is there some way to un-nest the subconstructs of `RawCopy`? Is `RawCopy` the wrong thing to be using here? Is there some reason why what I'm trying to do can't work?

```
d = Struct(
    fields=RawCopy(Struct(
        field1=Float32l,
        field2=PaddedString(8, 'utf-8')
    )),
    checksum=Checksum(Int16ul,
        lambda data: 0, # Insert actual checksum function here :-)
        this.fields.data),
)
```

**Comment by rotu** [comment]
This seems similar to #774 which was closed without an answer. @ralienpp, @DanseMacabre, did you ever figure this out?

**Comment by arekbulski** [comment]
Check #774 I added an answer there. As for checksumming, using RawCopy is the only reasonable way to do it. Embedding is probably not compatible with checksumming.
https://construct.readthedocs.io/en/latest/tunneling.html#compression-and-checksuming

**Comment by arekbulski** [comment]
I updated the docs site but it doesnt rebuild for some reason, here is an excerpt:

> Can only be used between Struct Sequence FocusedSeq Union LazyStruct, for example Struct can embed fields from a Sequence or vice versa. There is also :class:`~construct.core.EmbeddedSwitch` macro that pseudo-embeds a Switch, it is NOT a Embedded(Switch(...). Its not possible to embed IfThenElse Switch RawCopy or otherwise.

**Comment by rotu** [comment]
Thank you, @arekbulski
