### ISSUE TITLE
Is there an elegant way to combine Enum and OneOf?

### ISSUE THREAD

**Issue by hofstee** [construct/construct#816]
I have a file format that has two choices for a repeated field. One of them is delimited by `0xFE` and `0xFF`, but the other is unlikely to fail to parse since an `Enum(Byte)` is basically just a `Byte` while parsing. This results in something roughly like the following:

```python3
Var = Struct(
    "type" / VarType,
    "direction" / VarDirection,
    "name" / CString("ascii"),
    "length" / VarInt,
    "handle" / VarInt,
)

Scope = Struct(
    "_begin" / Const(b"\xFE"),
    "type" / ScopeType,
    "name" / CString("ascii"),
    "comp" / CString("ascii"),
    "members" / GreedyRange(Select(LazyBound(lambda: Scope), Var)),
    "_end" / Const(b"\xFF"),
)
```

The problem arises when the outermost `Scope` needs to terminate. the `0xFF` gets consumed by a valid match to `Var`, which breaks things horribly later on. Changing the Enum (VarType) to a OneOf containing all of the values works to avoid this issue, but is pretty annoying to write everywhere.

As I can see it currently, there are two solutions that would be nice:

- The ability to peek a byte, and terminate the GreedyRange based on that (I tried a few approaches but wasn't able to get anything working)
- The ability to have strict Enums that fail, like `OneOf`

Are either of these currently possible?

**Comment by arekbulski** [comment]
In this order:

- Have you explored using GreedyRange with a parse hook and raising CancalParsing?
- Strict enum solution: you can build a custom adapter that checks if the value parse is EnumIntegerString or EnumInteger (in which case it fails strict enum)

Please let me know if this issue is not stale (should I close it)?
