### ISSUE TITLE
Container equality doesn't check equality

### ISSUE THREAD

**Issue by yuo123** [construct/construct#818]
The Container `__eq__` implementation doesn't actually check equality, it only checks that the container is a subset of `other` (in addition to other, intended, special-cases). Consider the following example:
```python
a = Container(a=1)(b=2)
b = Container(a=1)(b=2)(c=3)

print(a == b)  # prints 'True'
print(b == a)  # prints 'False'
```
There is actually a test for this, but it's based on the wrong assumption that `(a != b) == (not a == b)`, but the above expression is actually false (try it!). This reveals another bug, where `__eq__` is overridden but `__ne__` is inherited from `dict`, so the custom comparison isn't considered if you use `!=`. Here's a reproduction of just this bug:
```python
c = Struct('a' / Int8ul).parse(b'\x01')  # c contains internal '_io' field, which shouldn't be considered in the comparison
d = {'a': 1}

print(c == d)  # prints 'True'
print(c != d)  # prints 'True'
```

**Comment by arekbulski** [comment]
Here is the culprit piece of code:
https://github.com/construct/construct/blob/master/construct/lib/containers.py#L203-L220

**Comment by arekbulski** [comment]
Fixed. Big thanks for pointing this one out.
