### ISSUE TITLE
Seek

### ISSUE THREAD

**Issue by gek47** [construct/construct#819]
I have an buffer of approx 128kb bytes there are 150  locations each the size of a byte or multiple bytes, that I need to operate on.  If I use Seek to move around in the buffer, parsing works as expected however when building the bytes between Seek  locations are back filled with 0x00.  I need to preserve the data between Seek  locations.  What is the recommend method?  As a work around I have been using Bytes(n) instead of Seek(n).

Thanks

**Comment by arekbulski** [comment]
Then use a different construct for building...
