### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str at construct/adapters.py

### ISSUE THREAD

**Issue by aliyamuc** [construct/construct#820]
I am moving my codes from python 2.7 to python 3.7. My construct version is 2.5. 
Function of "build" fails. In python 2.7 it works. But in 3.7:

TypeError: can only concatenate str (not "bytes") to str.

How can I solve this issue?

**Comment by arekbulski** [comment]
Construct 2.5 is ancient and unsupported any longer.

**Comment by arekbulski** [comment]
You may share with us the code, if its not that long...
