### ISSUE TITLE
build doesn't work in python 3

### ISSUE THREAD

**Issue by mnergis** [construct/construct#821]
I am moving my codes from python 2.7 to python 3.7. My construct version is 2.5. (Construct version isn' updated because embeddedbitStruct is used and I could't updated 2.9. )
Function of "build" fails. In python 2.7 it works. But in 3.7:

TypeError: a bytes-like object is required, not 'str' (stream.write(data))
Code:

```
ActivateReq = Struct("ActivateReq", CString("requestSequenceId"),)
xx = Struct("xx", Embed(ActivateReq)

xx.build(Container(requestSequenceId = "SYSTEM_OFF"))

```

How can I solve this issue?

**Comment by arekbulski** [comment]
You are the second person reporting this (or similar) problem. See #820 .
Version 2.5 is not supported anymore. Period.
Embedding is defacto not supported either.

**Comment by arekbulski** [comment]
On second look, its obvious:
```py
xx.build(Container(requestSequenceId = b"SYSTEM_OFF"))
```
