### ISSUE TITLE
FormatField with value range

### ISSUE THREAD

**Issue by bjourne** [construct/construct#828]
It would be useful to be able to specify the range of allowed values when parsing scalars. E.g 

`'length' / Byte(0, 32)`

maybe you can do it already when the `Check` class, but it is not very elegant.

**Comment by arekbulski** [comment]
I thinks its a too rare functionality to warrant such a drastic change to api. I could also suggest something like `Within(Byte, 0, 32)` class. Where do you  need this?

**Comment by arekbulski** [comment]
Week has almost passed and no reply. I treat this ticket as abandoned.

**Comment by bjourne** [comment]
I'm working on a parser where I have use for this functionality. I'll come back to this bug when I have an example to show.

**Comment by arekbulski** [comment]
Its s feature request, not a bug.
