### ISSUE TITLE
Dynamically identify length for use by Array()

### ISSUE THREAD

**Issue by kuanb** [construct/construct#829]
[Question] Looking for help on how to determine the full length of byte array from within the `Struct` definition.

I have a structure I would like to define where the number of items `'foo'` to be created is a function of the total length of the byte array. I've made a structure below that shows what this might look like.

```
s = Struct(
    "count" / GreedyRange(Padding(1)),  # look ahead and get total number of bytes
    "foo" / Array(this.count / 3, Struct( ... )),
)
```

In the above situation, there are `n` items `'foo'` where `n` is determined by looking through the whole byte array and dividing that length by 3 (since each item `'foo'` is 3 bytes long).

_Apologies if this is not the appropriate location to ask this question._

**Comment by arekbulski** [comment]
This is the right place to ask questions. I dont follow Gitter.

I dont see why you just dont simply do
`GreedyRange(Struct(...))`
or
`Array(len(data)/3, Struct(...)).parse(data)`

**Comment by kuanb** [comment]
Thanks @arekbulski I ended up using that pattern (checking length prior). I was wondering if there was a way to expressed that from within the structure, but perhaps that's unnecessary.

Thanks for the quick response.
