### ISSUE TITLE
Shorthand for reaching the "top" of a Struct's kwargs

### ISSUE THREAD

**Issue by kuanb** [construct/construct#830]
Given a structure with a series of nested components, such as the below, it can be "tedious" or prone to error to use the `this._` pattern to chain underscores to reach the "top" level and access a keyword argument passed to the structure. Is it (or, rather, would it be) reasonable to create a shortcut (eg a `this._kwargs`) that would allow you to access the top level arguments passed to the structure?

```py3
foo = Struct(
    ...
    'baz' / Array(
        this._.n,
        BytesInteger(2),
    )
    ...
)

# where n is passed in as a keyword argument
foo(..., n=4)
```

Note in the above the pattern becomes more difficult to maintain as the array structure becomes more deeply nested or should it need to be moved from one subset of the parent structure to another.

**Comment by arekbulski** [comment]
Did you check `_root`?
https://construct.readthedocs.io/en/latest/basics.html#hidden-context-entries

**Comment by arekbulski** [comment]
Ah wait, it was the `_params` instead. My mistake.

**Comment by kuanb** [comment]
Oh, I failed to see that - awesome! This is very useful; thanks for your help again.
