### ISSUE TITLE
Use on PDFs?

### ISSUE THREAD

**Issue by Prismacolor** [construct/construct#836]
This is just a general question, has anyone tried to use this tool on PDFs? I suppose I would need to convert said PDF to an object/data stream first?

**Comment by arekbulski** [comment]
No, you can check the deprecated gallery, there is only images, filesystems, network packets, etc. There is noothing like PDFs. I would welcome a PR tho.

**Comment by arekbulski** [comment]
See for yourself: https://github.com/construct/construct/tree/master/deprecated_gallery

**Comment by arekbulski** [comment]
Here is the PDF spec that I just found by googling it. Its well... formidable.
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

**Comment by Prismacolor** [comment]
Whew, good heavens! Thank you for looking!
