### ISSUE TITLE
Sizeof alternate for variable length fields

### ISSUE THREAD

**Issue by dbdante** [construct/construct#839]
I would like to reference the solution to the issue here
https://github.com/construct/construct/issues/768

I would like to modify the soln a bit and add a variable length CString as shown below:
```py
import construct
from construct import *
_body = Switch(this.message_type, {
    0x0000: Struct(
        'body_val1' / Int8ub,
        'body_val2' / Int16ub,
        'body_val3' / Int8ub,
        'string_ex' / CString('utf8')
    ),
    0x0001: Struct(
        'body_val2' / Int16ub,
    ),
    0x0002: Struct(
        'body_val2' / Int16ub,
        'body_val4' / Int8ub,
    ),
})


Example = Struct(
    'magic' / Const(b'01234567'),
    'message_type' / Int16ub,
    'message_len' / Rebuild(Int16ub, lambda ctx: 12 + _body.sizeof(message_type=ctx.message_type)),
    'body' / _body,
)


data = Example.build({'message_type': 0, 'body': {'body_val2': 2,'string_ex':"hello"}})
print(data)
print(Example.parse(data))

```
This doesnt work as sizeof doesnt like variable length fields. How can I approach this?

**Comment by DanseMacabre** [comment]
I would say this is probably a feature that might need adding as at build-time, the data is known.

I have code like this, however as I never need to _build_ a packet like this, I have no issues.  I only parse using this sort of construct (RepeatUntil as the offender to SizeOf rather than CString).

It would be good if you were able to explicitly pass the size, or if the length/size parameter could be deferred until completion of the build (assuming a constant size of the length/size parameter itself).

**Comment by arekbulski** [comment]
Why not use Prefixed instead?
```py
Example = Struct(
    'magic' / Const(b'01234567'),
    'message_type' / Int16ub,
    'messageLenPlusData' / Prefixed(Int16ub, _body),
```

**Comment by arekbulski** [comment]
Another suggestion: build the body separately, then you can reference its lenght.

**Comment by dbdante** [comment]
Thank you for the suggestions. The below worked but it seemed like I am building the packets twice. 
```
import construct
from construct import *
_body = Switch(this.message_type, {
    0x0000: Struct(
        'body_val1' / Int8ub,
        'string_ex' / CString('utf8')
    ),
    0x0001: Struct(
        'body_val2' / Int16ub,
    ),
    0x0002: Struct(
        'body_val2' / Int16ub,
        'body_val4' / Int8ub,
    ),
})


Example = Struct(
    'magic' / Const(b'01234567'),Probe(),
    'message_type' / Int16ub,
    'message_len' / Rebuild(Int16ub,this.body_size+12),Probe(),
    'body' / _body,
)


bodybuilt = _body.build({'body_val1':1,'string_ex':'hello'},message_type=0)
data = Example.build({'message_type': 0, 'body_size': 7, 'body':{'body_val1':1,'string_ex':'hello'}},message_type=0)

print(data)
print(Example.parse(data))
```
 I tried modifying this to 'body' / _body to below, but that didnt work as well
`'body' / Rebuild(_body, this.bodybuilt)`

Any insight into passing raw bytes to a rebuild?

**Comment by arekbulski** [comment]
Why not use modified Prefixed?

**Comment by dbdante** [comment]
Unfortunately I am not able to use prefixed - the actual protocol fields looks like 
length1
length2
String of size length1
String of size length2

Let me look into RawCopy

**Comment by dbdante** [comment]
The below code worked. Thank you.
```
import construct
from construct import *
_body = Switch(this.message_type, {
    0x0000: Struct(
        'body_val1' / Int8ub,
        'string_ex' / CString('utf8')
    ),
    0x0001: Struct(
        'body_val2' / Int16ub,
    ),
    0x0002: Struct(
        'body_val2' / Int16ub,
        'body_val4' / Int8ub,
    ),
})


Example = Struct(
    'magic' / Const(b'01234567'),
    'message_type' / Int16ub,
    'message_len' / Rebuild(Int16ub,this.body_size+12),
    'body' / RawCopy(_body),
)


bodybuilt = _body.build({'body_val1':1,'string_ex':u'hello'},message_type=0)
data = Example.build({'message_type': 0, 'body_size': 7, 'body':dict(data=bodybuilt)})

print(data)
print(Example.parse(data))
```

**Comment by DanseMacabre** [comment]
Surely a user *should* be able to do this without separately building the body? Seems a bit unnecessary, IMO.

**Comment by arekbulski** [comment]
Implementing Sizeof was always tricky and it seems to never work the way you would like it to. This is he best of how it is going to get.
