### ISSUE TITLE
Enum dos not support default value  as written in transition28

### ISSUE THREAD

**Issue by herrfrei** [construct/construct#840]
I want to use a Struct to send a binary message to a device. Here I have entries like

`"control1" / Default(Enum(Int8ul, Local=0, Remote=1), 1),`

that works (gets a default value). But how to set it? `struct.build(dict(control1=Local))` seems to be wrong.

On the other side, I saw in some docs and older samples that this should also be possible:

`"control1" / Enum(Int8ul, Local=0, Remote=1, default=Remote),`

This results in an error. How to define a predefined Enum correctly and how to set it later to one of the named fields?

**Comment by arekbulski** [comment]
Good question as I have no clue what this is supposedly would make. Perhaps a smaller example would be better?

**Comment by herrfrei** [comment]
Okay, let's explain what I want to do: I need to control a sensor connectied via Ethernet and for this I have to send a special control message.  This starts like this:

`control_message = Struct(
    "signature" / Const(b"AF"),
    "device_id" / Default(Int8ul, 0),
    "control" / Default(Enum(Int8ul, Local=0, Remote=1), 0),
    "range" / Default(Enum(Int8ul, Range1m=1, Range2m=2, Range5m=3, Range10m=4), 2),
    ...
)
`
The default values allow to build this message without setting any field. To switch remote control on, I need to set the `control` field to Remote. It would be possible to use a Flag here, but for other fields like `range` I need  to set a default value (btw, it's not ideal to use 2 here, Range2m would be better) and later change this. How to do that?

`control_message.build(dict(range=Range10m))` 

results in an error.

**Comment by arekbulski** [comment]
My jaw dropped. No clue.

**Comment by arekbulski** [comment]
One thing I noticed, you seem to be writing dict wrong (its supposed to be a string):
```py
control_message.build(dict(range="Range10m")) or
control_message.build(dict(range=4))
```
