### ISSUE TITLE
ValueError: Data length must be a multiple of eight

### ISSUE THREAD

**Issue by rgmann** [construct/construct#845]
I don't believe this is a defect with construct, but it is not clear to me from the documentation what is wrong with my structure definition. I am attempting to pack a variable length struct (minimum of 8-bits, maximum of 104 bits) using the following snippet.

```
import construct

payload = {
    'SENT_ELEMENTS' : {'X' : True, 'Y' : False, 'Z' : False},
    'X' : 1.0,
    'Y' : 2.0,
    'Z' : 3.0
}

d = construct.BitStruct(
    'SENT_ELEMENTS' / construct.FlagsEnum(construct.BitsInteger(8,signed=False), X=1, Y=2, Z=4),
    'X' / construct.If(lambda this: this.SENT_ELEMENTS['X'], construct.Bitwise(construct.Float32l)),
    'Y' / construct.If(lambda this: this.SENT_ELEMENTS['Y'], construct.Bitwise(construct.Float32l)),
    'Z' / construct.If(lambda this: this.SENT_ELEMENTS['Z'], construct.Bitwise(construct.Float32l)))

d.build(payload)
```

The code includes the X, Y, and Z components of the dictionary if the 'SENT_ELEMENTS' flags indicate that they should be included.

However, when I run this example, I get the following error.

```
Traceback (most recent call last):
  File ".\test_construct.py", line 12, in <module>
    d.build(payload)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 336, in build
    self.build_stream(obj, stream, **contextkw)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 4829, in _build
    buildret = self.subcon._build(obj, stream2, context, path)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 2005, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 2443, in _build
    return self.subcon._build(obj, stream, context, path)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 3564, in _build
    return sc._build(obj, stream, context, path)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\core.py", line 4772, in _build
    data = self.encodefunc(data)
  File "C:\Users\rglissman\AppData\Local\Programs\Python\Python38\lib\site-packages\construct\lib\binary.py", line 115, in bits2bytes
    raise ValueError("data length must be a multiple of 8")
ValueError: data length must be a multiple of 8
```

From my calculations, the data length should be a multiple of 8 bits. The flags are packed into an 8-bit field and then you have an additional 32 bits for the X field.

What am I doing wrong here?

**Comment by arieltz23** [comment]
@rgmann I think I figured it out.
Because BitStruct converts everything underneath it to bits, you need something to do the **opposite** action, in order for this to work.
You need to treat the floats as *bytes* rather than *bits* - **Use Bytewise!**

It's stated in the documentation, in https://github.com/construct/construct/blob/master/docs/bitwise.rst#fields-that-work-with-bytes:

> Normal classes, that is those working with byte-streams, can be used on bit-streams by wrapping them with Bytewise. Its a wrapper that does the opposite of Bitwise, it transforms each 8 bits into 1 byte. The enclosing stream is a bit-stream but the subcon is provided a byte-stream.

Therefore, you need to do the following for this to work as you desire:
```
import construct

payload = {
    'SENT_ELEMENTS' : {'X' : True, 'Y' : False, 'Z' : False},
    'X' : 1.0,
    'Y' : 2.0,
    'Z' : 3.0
}

d = construct.BitStruct(
    'SENT_ELEMENTS' / construct.FlagsEnum(construct.BitsInteger(8,signed=False), X=1, Y=2, Z=4),
    'X' / construct.If(lambda this: this.SENT_ELEMENTS['X'], construct.Bytewise(construct.Float32l)),
    'Y' / construct.If(lambda this: this.SENT_ELEMENTS['Y'], construct.Bytewise(construct.Float32l)),
    'Z' / construct.If(lambda this: this.SENT_ELEMENTS['Z'], construct.Bytewise(construct.Float32l)))

d.build(payload)
```

This will print out:
```
'\x01\x00\x00\x80?'
```
Which is 5 bytes long.

**Comment by arekbulski** [comment]
Sorry for being so late, I wasnt offline for few days. You got your answer. Yes, you need to use `Bytewise` wrapper.

**Comment by rgmann** [comment]
@arieltz23 Excellent answer! That's exactly what I was trying to understand and I missed it in the docs. Thanks for the clarification.
