### ISSUE TITLE
Stopping a GreedyRange that contains padding

### ISSUE THREAD

**Issue by x1ppy** [construct/construct#848]
If I have a stream of appended structs that may contain padding, how do I stop the `GreedyRange` once it encounters that padding? For example:

```
format = GreedyRange(Struct(
    'id' / PaddedString(4, 'ascii'),
))

format.parse(b'abcdefgh\x00\x00\x00\x00\x00\x00\x00\x00')
```

I get:
```
ListContainer([Container(id=u'abcd'), Container(id=u'efgh'), Container(id=u''), Container(id=u'')])
```

But I want:
```
ListContainer([Container(id=u'abcd'), Container(id=u'efgh')])
```

I think the answer probably involves some combination of `StopIf` and `Peek`, but I can't figure it out. I thought this might work, but it gives the same result as above:
```
format = GreedyRange(Struct(
    StopIf(Peek(Int8ub) == 0),
    'id' / PaddedString(4, 'ascii'),
))
```

**Comment by x1ppy** [comment]
There's probably a better way to do this, but I was able to solve this by using `RepeatUntil` with a lookahead field:

```
format = RepeatUntil((this.next == 0 or this.next == None), Struct(
    'id' / PaddedString(4, 'ascii'),
    'next' / Peek(Int8ub),
))
```

**Comment by x1ppy** [comment]
...although I also want to be able to return `[]` if the stream is *all* padding, so this still isn't exactly what I need.

**Comment by arekbulski** [comment]
You can process the list outside of Construct. Simple enough.

**Comment by x1ppy** [comment]
Well, I guess that'd be one way to do it: I could change the format to raw `Bytes` and create an `Adapter` that processes the list separately (this list is actually embedded in another struct and prefixed with its length in bytes).

I thought there might be a way this could be done directly, but this should be good enough for me.

**Comment by arekbulski** [comment]
Ah your are right about using an Adapter. It should be a simple to write one.
