### ISSUE TITLE
build_file vs build with negative pointer

### ISSUE THREAD

**Issue by x1ppy** [construct/construct#849]
Given the following:
```
format = Struct('foo' / Pointer(-1, GreedyBytes), 'bar' / GreedyBytes)
dict = {'foo': b'a', 'bar': b'b'}
```

Can someone tell me why this fails:
```
format.build_file(dict, path)
# construct.core.StreamError: Error in path (building) -> foo
# stream.seek() failed, offset -1, whence 2
```

while this succeeds?
```
with open(path, 'wb') as f:
    f.write(format.build(dict))
```

**Comment by arekbulski** [comment]
You are telling it to seek from end of a file. I am amazed that either works at all.

**Comment by x1ppy** [comment]
Yes, I was also surprised that it worked; I didn't know if Construct had some special case magic that could handle an EOF pointer before the actual stream like this.

I was also surprised that `build` and `build_file` gave different results, so I was just curious what was going on here. But if this is just undefined behavior, I guess the answer doesn't matter.

**Comment by arekbulski** [comment]
Yes, I think this is undefined behavior indeed. Crazy town folk.
