### ISSUE TITLE
Merging build and parse structs

### ISSUE THREAD

**Issue by x1ppy** [construct/construct#850]
Let's say I have a simple construct to build MP3s, like so:
```
Mp3Format = Struct(
    'id3v2' / Optional(Id3v2Format),
    'audio' / GreedyBytes,
    'id3v2_end' / Optional(Id3v2Format),
    'id3v1' / Optional(Id3v1Format),
    Terminated,
)
```

I can't use this to parse since the stream has an optional footer after an arbitrarily-sized chunk of bytes in the middle. So I have a separate construct to parse:

```
Mp3FormatParser = Struct(
    'id3v2' / Optional(Id3v2Format),
    'offset' / Tell,
    'try_id3v1' / Pointer(-128, Optional(RawCopy(Id3v1Format))),
    'try_id3v2' / Pointer(-138 if this.try_id3v1 else -10, Optional(RawCopy(Id3v2HeaderFormat))),
    'audio' / IfThenElse(this.try_id3v2, Bytes(this.try_id3v2.offset1 - this.try_id3v2.size - 10 - this.offset),
                         IfThenElse(this.try_id3v1, Bytes(this.try_id3v1.offset1 - this.offset), GreedyBytes)),
    'id3v2_end' / Optional(Id3v2Format),
    'id3v1' / Optional(Rebuild(Id3v1Format, this.try_id3v1)),
    Terminated,
)
```

I can't use this second contruct to build since I'd run into [this issue](https://github.com/construct/construct/issues/849).

So I need one construct for building, and one for parsing. That makes things a little uglier since I now have to pass two separate structs around to deal with a single entity.

Is there any way to merge these into a single `Struct`-like object that will use the parser to parse, and the builder to build? Something like `ExprAdapter(subcon, decoder, encoder)`, for example, where `decoder` and `encoder` would be constructs rather than lambdas?

**Comment by arekbulski** [comment]
I am not sure how to approach this. Maybe use a Struct with two IFs and use those special context entries like _parsing and _building. Hm?

**Comment by x1ppy** [comment]
Thanks for the suggestions. After sleeping on it, I think an `Adapter` could work just fine after all:

```
class Mp3FormatAdapter(Adapter):
    def _decode(self, obj, context, path):
        return Struct(
            'id3v2' / Optional(Id3v2Format),
            'offset' / Tell,
            'try_id3v1' / Pointer(-128, Optional(RawCopy(Id3v1Format))),
            'try_id3v2' / Pointer(-138 if this.try_id3v1 else -10, Optional(RawCopy(Id3v2HeaderFormat))),
            'audio' / IfThenElse(this.try_id3v2, Bytes(this.try_id3v2.offset1 - this.try_id3v2.size - 10 - this.offset),
                                 IfThenElse(this.try_id3v1, Bytes(this.try_id3v1.offset1 - this.offset), GreedyBytes)),
            'id3v2_end' / Optional(Id3v2Format),
            'id3v1' / Optional(Rebuild(Id3v1Format, this.try_id3v1)),
            Terminated,
        ).parse(obj)

    def _encode(self, obj, context, path):
        return Struct(
            'id3v2' / Optional(Id3v2Format),
            'audio' / GreedyBytes,
            'id3v2_end' / Optional(Id3v2Format),
            'id3v1' / Optional(Id3v1Format),
            Terminated,
        ).build(obj)

Mp3Format = Mp3FormatAdapter(GreedyBytes)
```
I assume this will incur a performance hit since it needs an extra pass to build/parse the `GreedyBytes`, but I don't see a noticeable difference for my use case.
