### ISSUE TITLE
Parsing after adapting?

### ISSUE THREAD

**Issue by larsks** [construct/construct#851]
I'm trying to figure how to correctly make use of an adapter. I am parsing a format that includes a binary blob that needs to be decoded into another binary blob before parsing.  For example, say we have something that looks like:

```
format = Struct(
  'version' / Byte,
  'data' / GreedyBytes
)
```

Where the `data` field is actually a chunk of base64 encoded data.  Can can convert that into decoded bytes doing something like this:

```
class Base64Adapter(Adapter):
  def _decode(self, obj, ctx, path):
    return base64.b64decode(obj)
```

And then writing:

```
format = Struct(
  'version' / Byte,
  'data' / Base64Adapter(GreedyBytes)
)
```

That works fine, and means the `data` field is now a collection of bytes. But how do I apply parsing *after* adapting, so that I get something effectively like:

```
format = Struct(
  'version' / Byte,
  'data' / SomeOtherStruct(Base64Adapter(GreedyBytes))
)
```

Thanks!

**Comment by larsks** [comment]
I tried something like this:

```
class SomeOtherStructAdapter(Adapter):
  def _decode(self, obj, ctx, path):
    return SomeOtherStruct.parse(obj)
    
  def _encode(self, obj, ctx, path):
    return SomeOtherStruct.build(obj)
```

And then:

```
format = Struct(
  'version' / Byte,
  'data' / SomeOtherStructAdapter(Base64Adapter(GreedyBytes))
)
```

But that fails with:

```
TypeError: a bytes-like object is required, not 'Container'
```

**Comment by Evidlo** [comment]
Does this help?

https://github.com/construct/construct/issues/729
