### ISSUE TITLE
Stream not closed when holding reference to Container

### ISSUE THREAD

**Issue by x1ppy** [construct/construct#852]
```
from construct import *
from guppy import hpy

Test = Struct('first' / Struct(Int8ub))
b = bytearray(1024*1024)
accum = []

for i in range(1000):
    print(hpy().heap())
    obj = Test.parse(b)
    #obj._io.close()
    accum.append(obj.first)
```

This reveals a memory leak where `_io.BytesIO` objects are never freed. This caught me off guard since I expected `accum` to be a collection of `Container`s with just a single `Int8ub`, but the entire stream is held in memory. Adding `obj._io.close()` "fixes" the issue.

Should the stream not be closed immediately after parsing?

**Comment by arekbulski** [comment]
No. The stream is within the containers "_io" entry and remains there.
https://construct.readthedocs.io/en/latest/basics.html#hidden-context-entries

**Comment by x1ppy** [comment]
Would it make sense to have a `close` method on `Container` or something similar? Considering containers mostly act like regular Python dictionaries, this seems like an easy mistake to make (and less easy to notice). Perhaps stream handling could even be managed using Python `with` statement context managers?

**Comment by arekbulski** [comment]
Sorry but this functionality is just not worth doing. I am closing the topic.
