### ISSUE TITLE
Options to handle strings with decoding errors

### ISSUE THREAD

**Issue by bjourne** [construct/construct#853]
It is common in a lot of binary formats to have fields that are ostensibly strings but which can be filled with bytes that can't be decoded. Python's builtin `decode` allows you to replace or ignore such errors:

    bytes([65, 66, 190]).decode('utf-8', 'replace')

It would be great if Construct's string types worked similarly:

    CString('utf-8', 'replace').parse(bytes([65, 66, 190]))

**Comment by arekbulski** [comment]
Nothing like this isnt planned to be added.
