### ISSUE TITLE
Structs with unknown fields

### ISSUE THREAD

**Issue by eternaleclipse** [construct/construct#854]
I'd like to create a Struct representing a data structure without knowing all the fields and types.
For example, parse an existing game save file where at offset ```0x1f``` there is an ```unsigned int```, then file and read / write only these fields.

Is this possible somehow, maybe with ```Pointer``` or ```Seek```?

**Comment by arekbulski** [comment]
Honestly I dont understand what it is that you are talking about...

**Comment by eternaleclipse** [comment]
Okay, I'll try to further explain my question by using a simple example.

Let's say I have a file:
```
00000000: bba7 44b1 0100 0000 93b2 721a 7a97 4776  ..D.......r.z.Gv
00000010: 498f d05e a6d1 d752 d282 39dd a5b8 68e5  I..^...R..9...h.
00000020: 23b5 62d8 b890 ea9a 1a92 aa80 fa17 1e70  #.b............p
00000030: f83a 5547 6739 f8b5 4564 7220 86b4 1d5d  .:UGg9..Edr ...]
00000040: 4260 c353 268f 7dc8 4480 fa2a 1397 2185  B`.S&.}.D..*..!.
00000050: 9b6b 6c58 cd46 80b7 2989 4505 a1d2 1312  .klX.F..).E.....
00000060: 401d 93ad                                @...
```

I want to create a script that reads and writes certain fields in this file, without knowing the entire format. For example, I know that in offset `0x4` there is a 4 bytes, long little-endian `unsigned int` containing the amount of money the player has (currently, `1`).

This is what I would do in Python with the standard library:
```Python
import struct

money_data = struct.pack('I', 100)
money_offset = 4

with open('file.dat', 'r+b') as f:
    # Read
    f.seek(money_offset)
    cur_money_data = struct.unpack('I', f.read(money_offset))[0]
    print('The current amount of money is:', cur_money_data)

    # Write
    f.seek(money_offset)
    f.write(money_data)
```

I wanted to know if there is an elegant way to do this using Construct.

**Comment by arekbulski** [comment]
How about a Struct that has a Seek(4) and then Int32ul?
Read the docs, man? https://construct.readthedocs.io/en/latest/basics.html#structs

**Comment by arekbulski** [comment]
BTW, unsigned 32bit little-endian int is <L and not I.
https://github.com/construct/construct/blob/master/construct/core.py#L1281-L1283

**Comment by eternaleclipse** [comment]
Thanks for the hint, I got it to read properly.

```Python
format = Struct(
    Seek(4),
    'x' / Int32ul
)

# Read
print(format.parse(b'ABCD\x01\x00\x00\x00'))
```

I went over the docs again, and I still don't completely understand how `Seek` works in Structs with writing ("building"). It seems I need to declare an initial `GreedyBytes` field so that I can pass the original data to seek upon to `build`. It works with `Sequence`. Doing this with a `Struct` causes an exception:

```Python
format = Struct(
    GreedyBytes,
    Seek(4),
    'money' / Int32ul
)

data = b'ABCD\x01\x00\x00\x00'

# Write
new_money = 100
data = format.build([data, None, new_money])
print(data)
```
```
Exception has occurred: ValueError
too many values to unpack (expected 2)
  File "C:\Users\Knuckles\Desktop\a.py", line 16, in <module>
    data = format.build([data, None, new_money])
```

> BTW, unsigned 32bit little-endian int is <L and not I.
> https://github.com/construct/construct/blob/master/construct/core.py#L1281-L1283

So, reading the struct docs, `I` is `int` and `L` is `long`.
But yes, if I want it to be a machine-independent 32-bit integer I should use `L` :)

**Comment by arekbulski** [comment]
Well yeah, a Struct needs to be build from a dict and a Sequence from a list.

**Comment by eternaleclipse** [comment]
Oh, I see.
It works now, awesome. Thank you!
```Python
from construct import *

format = Struct(
    'data' / GreedyBytes,
    Seek(4),
    'money' / Int32ul
)

data = b'ABCD\x01\x00\x00\x00'

# Write
new_money = 100
data = format.build(dict(data=data, money=100))
print(data)
```
