### ISSUE TITLE
Pad with zeroes if end of file

### ISSUE THREAD

**Issue by bjourne** [construct/construct#855]
I'm writing a parser for the MOD file format using Construct. 

The last part of the file is a sequence of bytearrays whose sizes are declared earlier in the file. The declared sizes of the bytearrays may extend beyond the file size limit of the file. If so, they should be padded with trailing zeroes. 

Is this possible to do using Construct? I cannot find an easy way to get the size of the file being parsed.

**Comment by arekbulski** [comment]
You probably going to need a custom class or a custom Adapter for this.

**Comment by mungewell** [comment]
Don't know whether this is the best way, but this ensures file size is padded to given size
```
ZT2 = Padded(8502, Sequence(
    "header" / Header,
    "groups" / GreedyRange(Group),
))
```

https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2.py#L61

**Comment by arekbulski** [comment]
Perhaps Padded could be replaced with Aligned? In case the data grows over 8502 bytes.

**Comment by bjourne** [comment]
This class solved my problem:

```python
class EOFPaddedBytes(Bytes):
    def _parse(self, stream, context, path):
        length = self.length(context) if callable(self.length) \
            else self.length
        data = stream.read(length)
        n_padding = length - len(data)
        assert n_padding >= 0
        data += bytes([0] * n_padding)
        return data
```

It works exactly like `Bytes` except it pads with zero bytes.

**Comment by arekbulski** [comment]
Just so you kmow, `bytes(n_padding)` works the same.

**Comment by bjourne** [comment]
No. `Bytes(10).parse(b'AAAAA')` throws an error. But:
```python
>>> EOFPaddedBytes(10).parse(b'ABCD')
b'ABCD\x00\x00\x00\x00\x00\x00'```

**Comment by arekbulski** [comment]
This is what works exacty same way:
```python
class EOFPaddedBytes(Bytes):
    def _parse(self, stream, context, path):
        length = self.length(context) if callable(self.length) \
            else self.length
        data = stream.read(length)
        n_padding = length - len(data)
        assert n_padding >= 0
        data += bytes(n_padding)
        return data
```
