### ISSUE TITLE
How to access parent struct field ?

### ISSUE THREAD

**Issue by gllb** [construct/construct#857]
I try  to access "size" field in a parent struct like this :

```
motorun_file_meta = Struct(
    "name" / PaddedString(24, 'ascii'),
    "offset" / Int32ul,
    "size" / Int32ul,
    "file" / Pointer(this.offset,
                     Struct(
                         "signature" / Const(b'MotoRun\0'),
                         "width" / Int16ub,
                         "height" / Int16ub,
                         "pixels" / Array(this.size, Byte[5]),
                     )
    ),
)
```

But it trigger a KeyError exception.

I think what I want to do is very similar to what is done here https://github.com/construct/construct/blob/master/deprecated_gallery/bmp.py#L13 
but as it's in deprecated_gallery I wonder if it's still working like that and if is there any other alternative of doing that ?

**Comment by arekbulski** [comment]
You may try `this._.size` because of the nesting. See https://construct.readthedocs.io/en/latest/basics.html#hidden-context-entries
Also you might decouple the pointer and then you just reference it.
