### ISSUE TITLE
Output a struct as a header file

### ISSUE THREAD

**Issue by AsafFisher** [construct/construct#858]
I want to add a feature that will let you dump a Struct into a header file like `struct.generate_header()` Is it welcomed?
Also i want to add a get_endianity method to check the endianity of a field...

**Comment by arekbulski** [comment]
I am not very much into it, tbh. But feel welcomed to write more about it.

**Comment by AsafFisher** [comment]
Say you have a struct:

```
MY_STRUT = Struct(
"megic"/Int32ub,
"size"/Int32ul
)
data = b'ABCAABCA'
struct = MY_STRUCT.parse(data)

The new feature will allow me to do as such:
struct.megic.to_bytes(MY_STRUT.megic.endianity, MY_STRUT.megic.sizeof())
```

**Comment by AsafFisher** [comment]
> I am not very much into it, tbh. But feel welcomed to write more about it.

lemme know why
