### ISSUE TITLE
STICKY: Need help with solving issues and features

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#86]
I could use some help with processing issues and features. There are some things that do not work yet. You can find what I am working on in the non-master branches. **Please subscribe.**
https://github.com/construct/construct/branches

If you can help, feel free to leave a note in this thread.

**Comment by arekbulski** [comment]
I am about to make a release with what was changed so far. Please subscribe.

**Comment by arekbulski** [comment]
Release 2.5.5 is out on both GitHub and Pypi.

**Comment by arekbulski** [comment]
Release 2.5.5 is out on both GitHub and Pypi.

**Comment by gkonstantyno** [comment]
new pull request with fix for #46 
I also started some work to make code pep8 compliant

**Comment by arekbulski** [comment]
Please notice that I respect PEP8 with the exception of line length of 79. I use unlimited lines. This is more handy when you use a good code editor that has word wrap. Sometimes its more convenient to use wrap, sometimes its more convenient to just see line beginnings. Look at #80 .

**Comment by arekbulski** [comment]
Edited above. @gkonstantyno

**Comment by arekbulski** [comment]
Gah, just noticed. You should branch off master, not issue46. :confused:  Small detail.

**Comment by arekbulski** [comment]
Edited above. @gkonstantyno

**Comment by arekbulski** [comment]
Tell when you are done or at least take a break. Then I will accept your changes partially and you can re-checkout from there.

**Comment by gkonstantyno** [comment]
For now I don't have anything more - do you want me to change pull request for #46 ? 

Regarding pep8 I see things differently :) Looking at your approach I will stop for now.

**Comment by arekbulski** [comment]
I will accept it partially and get back to you in a moment. :)

**Comment by arekbulski** [comment]
@gkonstantyno I merged your changes (partially) and pushed it to the repo. Please checkout from the current master branch before you apply more changes. Big thanks for testing ULInt24. I would welcome more help with extending the test suite. :+1:

**Comment by gkonstantyno** [comment]
I want to put some thoughts regarding future of constuct.
First of all I don't like idea of cythonize it. Maybe better would be to make those changes in separated library like construct-cython.
If you want to run code faster just use pypy. There is also cffi if you want to put some c code inside.
Generally it would be the best to left possibility of running it on standard python interpreter.

Current changes are to big and probably you should think about some deprecation strategy.
Good idea would be to add something like Value = Computed for backward compatibility if functionality is exactly the same but moved to class etc.

Thanks for taking care of this project!

**Comment by arekbulski** [comment]
Cython is just an implementation detail. Aside of adding one module to requirements (after removing six) there is no difference from the perspective of the users. Cython methods are seen from outside as python methods. Only that you cannot inspect their source using reflection.

Good idea to make some aliases like Value = Computed. May help people with the transition.

**Comment by arekbulski** [comment]
If anyone has any idea what the Struct nested argument does, please explain it to me.

**Comment by arekbulski** [comment]
Could use help with #98 .

**Comment by arekbulski** [comment]
**Currently making all fields nameless using / >> [] operators essentially backporting Construct3.**

**Comment by arekbulski** [comment]
**Nameless branch has been merged into the trunk. Name arguments have been purged and / >> operators are used for naming fields.** Docs site and docstrings  are stale. Look at the source code directly.

**Comment by arekbulski** [comment]
**There is around 20 new but small issues after 2.7 beta release. Need assistance.**

**Comment by arekbulski** [comment]
**API changes are done, its stable now.** Upcoming is up-bringing docstrings and website documentation  to what the code actually does.

**Comment by arekbulski** [comment]
**New 2.8 release is out of beta!** Fields are not name-less and / >> []  operators are used. `this.x` is used instead of `lambda ctx: ctx.x`. Most classes were redesigned and reimplemented.

**Comment by arekbulski** [comment]
@gkonstantyno  Maybe you would help me with translating the formats and protocols to 2.8? Please, I need some help with the amount of work.
