### ISSUE TITLE
How to get specific number of bits in Struct?

### ISSUE THREAD

**Issue by LaNihal** [construct/construct#860]
com1 = Struct(
    "mty" / Enum(BitsInteger(4), Mty), 
    "flag" / BitsInteger(2),
    "id" / Enum(BitsInteger(4), ID),
    "not" / BitsInteger(2),
    "id2" / BitsInteger(7),
    )

1)'mty' is 4 bit field.-> Which function to use to 
  make it 4 bit a field?
   BitsInteger(4)-> Read as 4 Bytes not bits when I 
   build the packet.
   * 'Mty' is defined as enum.
2) How to use this with BitStruct.

**Comment by arekbulski** [comment]
Wrap the Struct in a Bitwise.
https://construct.readthedocs.io/en/latest/bitwise.html#bitstruct

**Comment by LaNihal** [comment]
Thanks for reply. I have tried as you suggested but it gives error. This is my code:

from construct import *
from construct.lib import *
import enum

class Mty(enum.IntEnum):
    Mty1  = 0x0,
    Mty2  = 0x1,
    Mty3 =  0x2,
    Mty4  = 0x3

class Flag(enum.IntEnum):
    Flag1 = 0x0,
    Flag2 = 0x1

class ID (enum.IntEnum):
    Id1 = 0x0,
    Id2 = 0x1,
    Id3 = 0x2,
    Id4 = 0x3
class Eid (enum.IntEnum):
    EId1 = 0x0,
    EId2 = 0x1,
    EId3 = 0x2,
    EId4 = 0x3,
    EId5 = 0x4,
    EId6 = 0x5,
    EId7 = 0x6,
    EId8 = 0x7

com1 = Bitwise(Struct(
    "mty" / Enum(BitsInteger(4), Mty),     #this should 
                                                             be a four bit field
    "flag" / Enum(BitsInteger(2), Flag),
    "id" / Enum(BitsInteger(4), ID),
    "not" / BitsInteger(2),
    "id2" / Enum(BitsInteger(8), Eid),
))

c = com1.build({'mty': 'Mty3','flag': 'Flag1', 'id': 'Id2','not':0x0,'id2': 'Eid4'})
print(c)

Error:
"BitStream.py",Line 54
in close raise ValueError("closing stream but %d unwritten bytes remain, %d is encoded unit" % (len(self.wbuffer), self.encoderunit))
ValueError: closing stream but 2 unwritten bytes remain, 8 is encoded unit

**Comment by LaNihal** [comment]
Sorry, error is:
"binary.py" ,line 115, in bits2bytes
Value Error data length must be multiple of 8.

**Comment by arekbulski** [comment]
You need to consume 24 bits instead of 20. Add `Padding(4).`

**Comment by LaNihal** [comment]
Solved, Thanks. 
How to code TLV format using Construct?

**Comment by arekbulski** [comment]
Explain what is TLV?

**Comment by arekbulski** [comment]
I suggest you open a new Issue regarding this TLV of yours.
