### ISSUE TITLE
Bitwise - Multi-Byte with LittleEndian

### ISSUE THREAD

**Issue by mungewell** [construct/construct#861]
I am trying to extract data from a config file which has a block of data (dumped as HexDump)
```
        0000   C3 01 00 90 F5 61 00 0E 04 80 00 90 ED C0 00 00   .....a.....
               ^^ ^^ ^^ ^^ config/ID
               1100,0011 1000,0000 0000,0000 0000,1001
                ^^^ ^^^^ ^^^^ ^^^^ ^^^^ ^^^^ ^^^^ ^ 0x80000e1
               ^ Enabled
```

The first (LE) bit is 'enabled' and the next is an encode of a Int32LE of "0x80000e1", how can I extract this?
```
EDTB1 = Struct(
    "dump" / Peek(HexDump(Bytes(23))),
    "control" / Bitwise(Struct(     # note only does BE
        Padding(7),
        "enabled" / Bit,
    )),
    Padding(23),
)
```

Further in the bit-stream are 12bit and 8bit ints.

**Comment by arekbulski** [comment]
Well for a start, you can replace `Bitwise(Struct(Bit))` with a simple `Flag`.
I dont understand what is the rest of what you want to do here.

**Comment by mungewell** [comment]
The values (UInt32le) I want to extract are shifted in the byte stream by a few bits. ie in the Bitwise strut above the 7 bits are the lower bits...

**Comment by arekbulski** [comment]
You can still replace the `Bit` with a `Flag` to get True/False value instead of 0/1.

**Comment by arekbulski** [comment]
BitsInteger is probably what you are missing?
https://construct.readthedocs.io/en/latest/bitwise.html

**Comment by mungewell** [comment]
The problem is that 'my' data is Little Endian, so the first bit in the steam is the lowest bit of the first byte.

The BitStruct seems to parse with BigEndian, means the highest bit of first byte is parse first.
```
>>> d = BitStruct(
...     "a" / Flag,
...     "b" / Nibble,
...     "c" / Padding(3),
... )
>>> d.parse(b"\x01")
Container(a=False, b=0, c=None)
>>> d.parse(b"\x80")
Container(a=True, b=0, c=None)
```

Is there a way to reverse the bits in each byte before they are parsed?

**Comment by arekbulski** [comment]
Of course, the swapped parameter indicates endianess. And its not that BitStruct is big endian but the BitsInteger is by defeault big endian. Nibble is BitsInteger(4).
https://github.com/construct/construct/blob/master/construct/core.py#L1170

**Comment by arekbulski** [comment]
Check https://construct.readthedocs.io/en/latest/api/numerics.html#construct.BitsInteger

**Comment by arekbulski** [comment]
> Is there a way to reverse the bits in each byte before they are parsed?

You are not asking for little endianness, its something different: BitsSwapped class
https://construct.readthedocs.io/en/latest/tunneling.html#endianness

**Comment by mungewell** [comment]
Thank you for the suggests, but I'm still having issues... my data looks like
```
    EDTB = Container:
        length = 120
        effect1 = Container:
            dump = hexundump("""
            0000   81 00 00 C6 03 C8 40 0D F0 00 00 00 00 00 00 00   ......@.........
            0010   00 00 00 00 00 00 00 00                           ........
            """)

            reversed = hexundump("""
            0000   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 F0   ................
            0010   0D 40 C8 03 C6 00 00 81                           .@......
            """)

            control = Container:
                enabled = True
```

The 'enable' flag should be read from the '1' in 0x81 (and not the '8' - which is how BitStruct expect to parse the stream).

Also I made a mistake in saying the ID was 32bit, it's actually only 28 (don't ask my why.... I'm reverse engineering something). This puts it in the same category as the 12bit values, which don't accept the "swapped=True" parameter to BitsInteger.

I did, however, confirm that if I (manually) take the byte-reversed bit stream and reverse the order of my definition I can make it parse correctly. So perhaps it is possible to do this automatically in the construct definition.
```
$ python3 reverse_test.py
Container: 
    control = Container: 
        param8 = 0
        param7 = 0
        param6 = 0
        param5 = 0
        param4 = 60
        param3 = 53
        param2 = 50
        param1 = 15
        id = 50331712 (which is 0x3000040)
        enabled = True
```
[reverse_test.py.zip](https://github.com/construct/construct/files/4685531/reverse_test.py.zip)
![bank1_0_crop](https://user-images.githubusercontent.com/236907/82960378-918bbc00-9f77-11ea-895f-0b25bee69d31.png)

**Comment by mungewell** [comment]
Found a parsing  work around with "RestreamData", but I understand that this won't allow for the rebuilding of the data.

```
AUTO = Struct(
    "autorev" / ByteSwapped(Bytes(24)),
    "reversed" / RestreamData(this.autorev, REV),
)
```
[auto_test.py.zip](https://github.com/construct/construct/files/4686005/auto_test.py.zip)
