### ISSUE TITLE
usage of imp is deprecated

### ISSUE THREAD

**Issue by jugmac00** [construct/construct#862]
```
.tox/coverage/lib/python3.8/site-packages/construct/core.py:3
  /home/jugmac00/Projects/hibpcli/.tox/coverage/lib/python3.8/site-packages/construct/core.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
```

I get this when I run the test suite for  `hibpcli` which uses `pykeepass` which uses `construct`.
```
git clone https://github.com/jugmac00/hibpcli
tox -e py38
```

**Comment by arekbulski** [comment]
The library was replaced a while ago. I dunno, perhaps I didnt publish the changes to pypi yet. I will investigate.

**Comment by jugmac00** [comment]
Thanks for getting back to me.

`construct` 2.10.56 was released Jan 28, 2020 and `imp` was dropped Feb 7, 2020, so this is fixed already, but not yet published to PyPi.

Sorry, I should have looked more closely.

So, all ok as soon as you make a new release - no hurry!

**Comment by arekbulski** [comment]
I just noticed. The title is wrong. Its the use of `imp` not `importlib` is deprecated. Nevermind.

**Comment by jugmac00** [comment]
I am sorry. Just updated the title.
