### ISSUE TITLE
Container _io attribute present in keys during iteration

### ISSUE THREAD

**Issue by gmassman** [construct/construct#867]
Not sure if this is the intended behavior, but the attribute `_io` shows whenever a Container is used as an iterable. For example:
```python
In [1]: from construct import Struct, Int8ub
   ...:

In [2]: file_version = Struct(
   ...:     'major' / Int8ub,
   ...:     'minor' / Int8ub,
   ...:     'patch' / Int8ub
   ...: )
   ...:

In [3]: fv = file_version.parse(b'\x01\x02\x03')
   ...:

In [4]: [(k, v) for k, v in fv.items()]
   ...:
Out[4]:
[('_io', <_io.BytesIO at 0x10d8ef410>),
 ('major', 1),
 ('minor', 2),
 ('patch', 3)]
```

Workaround for now is to add if statements during iteration, but ideally the BytesIO key would not be present at all.

Thanks!

**Comment by arekbulski** [comment]
Str(container) is made in a way to ommit hidden entries. However, iteration does not.

**Comment by gmassman** [comment]
I see, thanks for the clarification. We'll continue to work around the `_io` key.
