### ISSUE TITLE
Can't get original construct back from parse results

### ISSUE THREAD

**Issue by butterwagon69** [construct/construct#871]
When parsing complex data structures, it can be difficult or inconvenient to get the `Construct` object back from parse results. 
Here's a trivial example:

```python
from construct import Struct, Int32ul, Int16ul, Int8ul, Switch, this
s1 = Struct("b1" / Int8ul, "b2" / Int8ul, "b3" / Int8ul, "b4" / Int8ul,)
s2 = Struct("b1" / Int8ul, "b2" / Int16ul, "b3" / Int8ul,)
s3 = Struct("b1" / Int16ul, "b2" / Int16ul,)
s = Struct("type" / Int8ul, "value" / Switch(this.type, {0: s1, 1: s2, 2: s3,},),)
res = s.parse(bytes([1, 5, 6, 7, 8]))
```

It would be very convenient if the `s2` `Construct` was accessible from `res` somehow so that the user could say, modify `b1` and then `build` a new byte stream.

**Comment by arekbulski** [comment]
Well, yes that is true. There is no pushback to implement what you are talking about. And I am not keen on implementing it anyway. So sorry but that is just the way it is.

**Comment by butterwagon69** [comment]
Here's a quick monkey-patch implementation that attaches the `Struct` definition to the `_construct` attribute:

```python
import construct


class Container(construct.Container):
    __slots__ = construct.Container.__slots__ + ["_construct"]


construct.Container = Container


def annotate_parse(cls):
    _parse = cls._parse

    def parse(self, stream, context, path):
        res = _parse(self, stream, context, path)
        res._construct = self
        return res

    cls._parse = parse


annotate_parse(construct.Struct)

s1 = construct.Struct(
    "b1" / construct.Int8ul,
    "b2" / construct.Int8ul,
    "b3" / construct.Int8ul,
    "b4" / construct.Int8ul,
)
s2 = construct.Struct(
    "b1" / construct.Int8ul, "b2" / construct.Int16ul, "b3" / construct.Int8ul,
)
s3 = construct.Struct("b1" / construct.Int16ul, "b2" / construct.Int16ul,)
s = construct.Struct(
    "type" / construct.Int8ul,
    "value" / construct.Switch(construct.this.type, {0: s1, 1: s2, 2: s3,},),
)
res = s.parse(bytes([1, 5, 6, 7, 8]))
```

I don't know what implications this would have for the rest of the module but this should be good enough for me.

**Comment by arekbulski** [comment]
Thanks for sharing the recipe but I wont be merging it.

**Comment by butterwagon69** [comment]
I was hoping you could suggest a better way if you saw exactly what I'm doing. Otherwise, monkey patching it is...
