### ISSUE TITLE
variant of FlagsEnum treating unexpected set bits as an error

### ISSUE THREAD

**Issue by inkerman** [construct/construct#872]
`FlagsEnum` silently ignores unexpected set bits:

```Python console
>>> FlagsEnum(Byte, one=1, two=2).parse(b'\x02')
Container(one=False, two=True)
>>> FlagsEnum(Byte, one=1, two=2).parse(b'\x42')
Container(one=False, two=True)
```

This is a good default, since binary formats are occasionally extended with backwards compatible flags. But sometimes unexpected set bits should be considered an error:

<sub>https://www.postgresql.org/docs/8/sql-copy.html:</sub>
> Bits 16-31 are reserved to denote critical file format issues; a reader should abort if it finds an unexpected bit set in this range.

A variant of `FlagsEnum` supporting this could be useful. Perhaps something like:

```Python
class CheckedFlagsEnum(FlagsEnum):
    def _decode(self, obj, context, path):
        result = super()._decode(obj, context, path)
        expected = 0
        for name, value in self.flags.items():
            if result[name]:
                expected |= value
        if obj != expected:
            raise Exception(f'with {result!r} flags set, parsing expected {hex(expected)} but parsed {hex(obj)}')
        return result
```
```Python console
>>> CheckedFlagsEnum(Byte, one=1, two=2).parse(b'\x02')
Container(one=False, two=True)
>>> CheckedFlagsEnum(Byte, one=1, two=2).parse(b'\x42')
Exception: with Container(one=False, two=True) flags set, parsing expected 0x2 but parsed 0x42
```

**Comment by arekbulski** [comment]
Interesting. I am not keen on integrating your version with the core library tho. Thanks for posting this recipe for everyone tho.

**Comment by inkerman** [comment]
The class depends on implementation details of the library and so it is not guaranteed to work correctly with future versions of construct.

**Comment by arekbulski** [comment]
Well, the library internals dont change that often nowadays. So use the recipe and thanks for posting it.

**Comment by inkerman** [comment]
Ok, thank you.
