### ISSUE TITLE
How to Install Construct v2.10.56

### ISSUE THREAD

**Issue by leonelce3t** [construct/construct#873]
Hi!

Hello, please can you give me information on how to install Construct v2.10.56 on Ubuntu 20.04, 
I have used the command
$ pip install construct
but I have this problem

leonel@leonel-X555LB:~$ pip install construct
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: construct in /usr/local/lib/python2.7/dist-packages (2.9.45)

Thank you in advance for your help!!!

**Comment by arekbulski** [comment]
I never seen this error before. Try  `pip3 install construct` instead?

**Comment by leonelce3t** [comment]
Thanks for your attention!
But,

![image](https://user-images.githubusercontent.com/51714908/86960243-d6814180-c124-11ea-92b3-f38f98b3a392.png)

**Comment by arekbulski** [comment]
Sorry but I cant help you. Try searching this on StackOverflow.

**Comment by leonelce3t** [comment]
Download v2.10.56 Source code(.zip)
How can install this?

**Comment by wamserma** [comment]
@leonelce3t It seems you are still using python2 and/or an outdated version of pip3. Please try to update/install python3 and python3-pip using your distributions package manager.
