### ISSUE TITLE
How to get absolute offset of the nested Length-Type-Value box in the input binary stream?

### ISSUE THREAD

**Issue by antonysigma** [construct/construct#875]
*The context:* I have an input binary stream that has nested Length-Type-Value (LTV) boxes, and I successfully parsed the stream (i.e. `LTVBox.parse(mybytes)` with the following grammar:

```python
# Generic Length-Type-Value box
LTVBox = Prefixed(
    'box_length' / Int32ub,
    Struct(
        '@start' / Tell,
        'type' / Bytes(4),
        'value' / IfThenElse(
            this.type == b'nest', 
            GreedyRange(LazyBound(lambda: LTVBox)),
            GreedyBytes,
        ),
        '@length' / Tell,
    ),
    includelength=True)
```

*The question:* I would like to tell the absolute offset (denoted `@start` above), and length (`@length`) of the inner box in the input binary stream (i.e. `mybytes` in `LTVBox.parse(mybytes)`). I think I got the `@length` field to work, but `@start` is always equal to zero.

What is the best approach to get the absolute offset?

**Comment by arekbulski** [comment]
Yes, its zero because Prefixed reads the original stream and puts the data into stream2, just so GreedyBytes/GreedyRange can read it to end. I dont know of any way to get the original offset.

**Comment by antonysigma** [comment]
I see. I don't mind rewriting the grammar in order to get absolute offset, even if it end up less elegant then the `Prefixed` method.

I am thinking about getting `@start` and `@end` in the pseudo-code below, but I don't know how to make it recursively parse the inner boxes. More importantly, I am not sure if the value of `@start` is always equal to zero eitherway.

```python
# Generic Length-Type-Value box
LTVBox = Struct(
    'box_length' / Int32ub,
    '@start' / Tell,
    'type' / Bytes(4),
    'inner_box' / GreedyRange(LazyBound(lambda: LTVBox)),
    '@length' / Tell,
    'value' / Bytes(this.box_length + this['@length'] - this['@start']),
    '@end' / Tell,
    )
```

**Comment by arekbulski** [comment]
I think what you could try is use an outer struct with a Tell, and a nested Prefixed in it. Similiar to your first post but move the Tell outside.

**Comment by antonysigma** [comment]
It works! Thank you very much!

**Comment by antonysigma** [comment]
Actually, the trick failed on the 3rd nested level. I am okay to have my question marked as "wont-fix".
