### ISSUE TITLE
Problem with custom codec and Prefixed

### ISSUE THREAD

**Issue by J-T-de** [construct/construct#876]
I encountered buggy(?) behavior when trying to parse something compressed with a custom codec. Minimum (non-) Working Example:

```python
# create Codec
import codecs

def test_decode(input, errors='strict'):
    assert errors == 'strict'
    return (input[:4], len(input))

def getregentry():
    return codecs.CodecInfo(
        name='test',
        encode=None,
        decode=test_decode
    )

# register Codec
codecs.register(lambda l: getregentry() if l=="test" else None)


from construct import *

zlib_struct = Struct(
    "data" / Prefixed(VarInt, Compressed(GreedyBytes, "zlib")),
    "remainder" / GreedyBytes
)
print(zlib_struct.parse(b'\x0cx\x9cc`\xa0=\x00\x00\x00d\x00\x01\x01\02'))

test_struct = Struct(
    "data" / Prefixed(VarInt, Compressed(GreedyBytes, "test")),
    "remainder"/ GreedyBytes
)
print(test_struct.parse(b'\x0cx\x9cc`\xa0=\x00\x00\x00d\x00\x01\x01\02'))
# test_decode input is      b'x\x9cc`\xa0=\x00\x00\x00d\x00\x01'
```

The zlib codec does exactly what I expect him to do: It takes only as much as it needs, the rest is put into the remainder.
The test-codec should (in my mind) only consume the first four bytes. However, when debugging, i see that test_decode input is b'x\x9cc`\xa0=\x00\x00\x00d\x00\x01', so the first two bytes, and the last two bytes are missing. Furthermore, the test codec fully consumes the input, and not only the first 4 bytes as I expected. Is this a bug or is this a bug in my example.

In this trivial case, I know that 4  is the compressed size, thus the workaround would be
```python
test_struct_fixed = Struct(
    "data" / FixedSized(4, Compressed(GreedyBytes, "test")),
    "something"/ GreedyBytes
)
```
However, in my actual application, I don't know the compressed size, so this workaround does not work.

**Comment by arekbulski** [comment]
Sorry for such a delay, but I was on vacation away from a computer.

What you are asking is completely out of my area of expertise. I cant help you.
