### ISSUE TITLE
sizeof() fails for Array when using _index

### ISSUE THREAD

**Issue by jpsnyder** [construct/construct#877]
The `Array` construct doesn't take into account `_index` when calculating `sizeof()`.
This can make the construct produce the wrong number if `_index` was used in the spec.

```python
import construct
from construct import this

d = construct.Bytes(this._index + 1)[3]


ret = d.parse(b'\x01\x02\x02\x03\x03\x03')
assert ret == [b'\x01', b'\x02\x02', b'\x03\x03\x03']

# sizeof() returns 3 instead of 6
assert d.sizeof() == 6
```

**Comment by arekbulski** [comment]
The correct sizeof() output is SizeOfError and not 3 nor 6.

**Comment by jpsnyder** [comment]
Sorry, yes. I think I was running that still with the changes made by #771 . 
The idea is, instead of throwing an error or producing 3, it should produce 6 by taking into account the index.
