### ISSUE TITLE
`If` function should make the key not needed when the result is `False`

### ISSUE THREAD

**Issue by OmerYe** [construct/construct#879]
Even when 

```python
Struct('x1' / Flag, 'x2' / If(this.x1, Byte )).build({'x1': False})
```
`KeyError: 'x2'` raises here. But as `x1` is` False`, `x2` is irrelevant anyway - Should it really raise an exception?

Thanks you all!

**Comment by arekbulski** [comment]
Yes, its correct. As I mentioned on the chat: If(Byte) does not flag it for build-from-none. This is how things work unfortunately.

**Comment by arekbulski** [comment]
Check something like this:
```py
Default(If(this.x1, Byte ), 0)
```
