### ISSUE TITLE
Does this library support for tagged union?

### ISSUE THREAD

**Issue by 524119574** [construct/construct#881]

**Comment by arekbulski** [comment]
You have to explain what a tagged union is. Provide an example.

**Comment by 524119574** [comment]
For example:
```
struct {
  uint8_t t;
  union ds {
    uint8_t u8[4];  // default interpretation
    int16_t s16[2]; // when t is 'h'
    uint32_t u32;   // when t is 'w'
    float f32;      // when t is 'f'
  } u;
} __attribute__((__packed__)) un;
```
where the interpretation of the union depends on the value of `t`.

**Comment by arekbulski** [comment]
Well, there is Peek. You can use it multiple times.
https://construct.readthedocs.io/en/latest/streaming.html

**Comment by arekbulski** [comment]
There is also Union. RTFM man.
https://construct.readthedocs.io/en/latest/misc.html#union

**Comment by arekbulski** [comment]
I would also suggest that you check Switch.
https://construct.readthedocs.io/en/latest/misc.html#switch
