### ISSUE TITLE
Set endianness with the context

### ISSUE THREAD

**Issue by chibacchie** [construct/construct#884]
Currently, BytesInteger and BitsInteger do not allow to set endianness (`swapped`) with the context as follows:

```
>>> from construct import BytesInteger, this
>>> d = BytesInteger(4, swapped=this.swapped)
>>> d.parse(b'\x00\x00\x00\x01', swapped=True)
16777216
>>> d.parse(b'\x00\x00\x00\x01', swapped=False)
16777216
```

It would be useful if we can set endianness with the context. It allows us to define parsers/builders that accept both little and big endian with common data structure definitions.

**Comment by arekbulski** [comment]
This feature was already requested, at least once if not more. I am keen to merge it. I looked at the PR related and it looks very high quality, with test cases and everything. Good job.

**Comment by chibacchie** [comment]
Thanks for reviewing the PR. I appreciate it if you could merge it. Thanks!

**Comment by arekbulski** [comment]
The PR is missing one thing... main docs tutorial update.

**Comment by chibacchie** [comment]
I updated docs and made additional commit (0f0bcd0afb4a2810b90e2d6fcf02e29bd75b9add) to the PR.

**Comment by arekbulski** [comment]
Yes, I read it. It looks very good. The test cases and all. Very good.

**Comment by arekbulski** [comment]
Merged. Thank you again for bringing this to my attention. 
This related PR was very high quality.
