### ISSUE TITLE
How to best parse through nested objects in a tree-like structure?

### ISSUE THREAD

**Issue by Kelebek1** [construct/construct#887]
I have some binary format which is in the form of opcodes with differing numbers of bytes. Some are 1 byte, some 2, some 3, etc, and I want to map them to some output strings. What is the best way to go about parsing that? Currently I'm trying something like this:

```python
CHARSET = {
    "𝅘𝅥𝅮" : 0x00,
    "!" : 0x01,
    '"' : 0x02,
    "#" : 0x03,
    "$" : 0x04,
    "%" : 0x05,
    StopIf(True) : 0xFD,
    Switch(Byte, 
        {
            f"[var {Byte}]" : 0x28,
            f"[center {Byte}]" : 0x29,
            f"[volume={Byte}]" : 0x2E,
            Switch(Byte,
                {
                    "[sound=bowser]\n" : 1,
                    "[sound=spirit]\n" : 2,
                    f"[sound={Byte}]\n" : 0xFF,
                },
            ) : 0x2F,
        },
    ) : 0xFF,
```

and calling the parse like:

```python
message = RepeatUntil(
    lambda obj,lst,ctx: obj == 0xFD,
    Mapping(Byte, CHARSET),
).parse(fd[offset:])
```

The StopIf seems to be fine, but the first Switch throws a `AttributeError: 'int' object has no attribute 'flagbuildnone'` error. I also assume the strings won't work either, but the idea I was going for was to follow the tree through, and consume a byte at each level of nesting, including with the string. Is that possible? Is there a better structure to do this?

For reference, I'm trying to re-write this code in construct, to hopefully speed it up: https://github.com/ethteck/papermario/blob/master/tools/splat_ext/PaperMarioMessages.py

**Comment by arekbulski** [comment]
For one the `) : 0x2F,` seems just weird and I dunno what that is for.
Secondly, f-strings probably dont work here. `Byte` is a class instance and not a variable that was parsed. You seem to completely misunderstood this.
Nothing else comes to me at a glance. Good luck.

**Comment by Kelebek1** [comment]
Because they have to be specified backwards? It's there because for example `b'\xFF\x2F\x01'` would parse into the first switch (0xFF), then into the second switch which is the 0x2F case for the first switch, and then into the 0x01 case. If I flip the syntax around as `0x2F : Swtich(Byte, ...),` which is how I wanted to write it, then I get a key error that 0x2F could not be found. 

>Secondly, f-strings probably dont work here. Byte is a class instance and not a variable that was parsed. You seem to completely misunderstood this.

I know this won't work, my question though is how *could* I do this. How would I instantiate the byte so that it's consumed within the Switch?

A couple more things I've noticed with construct so far. RepeatUntil includes the terminating case, is there a way around this?

```python
section_offsets = RepeatUntil(
                    lambda obj,lst,ctx: obj.offset == 0, 
                    Struct(
                        "name" / Computed(lambda ctx: SECTION_NAMES[ctx._index] if ctx._index < len(SECTION_NAMES) else str(ctx._index)),
                        "offset" / Int32ub,
                    )
                ).parse(fd)
```
will include the == 0 case, but I'd like it not to be. is there a way around it besides list slicing the result?

And finally, could `parse()` support an offset? `parsefrom` is already supported for a few constructs, but seemingly not parse itself. Sometimes I can't (or don't want to) always parse an entire file from scratch, and need to jump around a bit. Could you add offsetting when parsing? E.g:

```python
myStruct = Struct("first" / Int32ul, "second" / Int32ul).parse(data, 0x10000)
```
where it would parse the struct at 0x10000 directly, without needing to slice the data.

**Comment by arekbulski** [comment]
As for the RepeatUntil and parsefrom, you would probably need to copy-paste the relevant code to your module and overwrite it with your own code. Man, this is difficult.

**Comment by arekbulski** [comment]
On second thought: maybe instead of this backward nesting and shit, maybe just write your own parsing class?

**Comment by Kelebek1** [comment]
You mean completely separate from construct? I could, that's what I usually do, but construct looked cool so I was using this as my chance to try and learn it so I could use it in the future.

**Comment by arekbulski** [comment]
Not instead of construct but extending it. Just write your own parser but from the existing classes use Byte and such?

**Comment by Kelebek1** [comment]
Alright, I'll try that. Thanks. I'll close the issue.

**Comment by arekbulski** [comment]
The docs say so (since I wrote them duh).
https://construct.readthedocs.io/en/latest/extending.html
