### ISSUE TITLE
Cant open projects made in contrsuct 204.2 stable desktop

### ISSUE THREAD

**Issue by JoseDinis1** [construct/construct#891]
Cant i open projects made in version 204.2 Stable (its a project folder, desktop version of Construct), made a few months ago

Have Chrome 87

Desktop Version 204, doent have the open folder option

Desktop Version 225, says isnt a valid project folder

Desktop Version 229, says isnt a valid project folder

Online Version 225, says isnt a valid project folder

------------------------------------
Method2: Add the files in a zip / Then rename the extension to .c3p

Failed to open project. Check that it is a valid Construct 3 single-file project (.c3p). (Translation from Portugueses pop up)

(I opened another project saved as c3p, to be shure i was zipping the correct way)

The project was made like 10 months ago, and i saved "as folder" bacause i was thinking would be more compatible for the future.

Thanks

Forum: https://www.construct.net/en/forum/construct-3/how-do-i-8/open-project-made-version-204-157243

**Comment by arekbulski** [comment]
You are barking at the wrong tree. This project is not affiliated with construct.net domain in any way. In fact, if just open your fucking eyes and look, on their site there is a menu "Community > Forums" where you can ask your question. Its possible, tho very unlikely, that they are affiliated with Construct 3 which was an admittedly failed spinoff created by previous maintainer. This project is Construct 2, and it will always remain 2.x.

**Comment by JoseDinis1** [comment]
i just saw Construct and there it goes ....  sory man or women, or tree

**Comment by arekbulski** [comment]
LOL yeah. No problem. Got little fired up, hope you dont mind. Good luck there.
