### ISSUE TITLE
Using round on `this` expressions

### ISSUE THREAD

**Issue by matan1008** [construct/construct#895]
Dear lords!

I am using construct 2.10.56, with "Python 3.9.0+ (default, Oct 20 2020, 08:43:38)" and I have the following code:

```python
from construct import *

my_struct = Struct(
    'original' / Byte,
    'computed' / Computed(round(this.original / 3, 4))
)

my_struct.parse(b'\x01')
```

Which yields the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: type BinExpr doesn't define __round__ method
```

In my very humble opinion it seems like a bug in the `ExprMixin` class - Am I right?
If so, I will try submitting a pull request soon.

Thanks in advance!

**Comment by arekbulski** [comment]
No its not a bug. You made a mistake in the code. In fact I just had an identical issue closed.
It should be: `'computed' / Computed(lambda this: round(this.original / 3, 4))`

**Comment by matan1008** [comment]
Thanks for answering so fast!
Perhaps it should be added as a note in the [documentation](https://construct.readthedocs.io/en/latest/misc.html#computed)?

**Comment by arekbulski** [comment]
Main documentation is correctly using this expressions so probably not.

**Comment by Frankkkkk** [comment]
Came here for the same thing. Indeed I tried with `lamba ctx: ... construct.this.xxxx` without really knowing.

A small tip/example would be greatly appreciated :D I might even do a MR

Cheers
