### ISSUE TITLE
Determining which element in Struct is being parsed

### ISSUE THREAD

**Issue by mungewell** [construct/construct#896]
Is there a way to determine which element in a Struct is activity being parsed - like a '_index' in an array?

For example I have a Struct, and want to refer to an array in another area of the binary blob which contains data related to the Struct...
https://github.com/mungewell/uno-drum-utils/blob/main/decode_kit.py#L98
```
DRUMS = Struct(
    "tom1" / DRUM,
    "tom2" / DRUM,
    "rim" / DRUM,
    "cowbell" / DRUM,
    "ride" / DRUM,
    "cymbal" / DRUM,
    "kick1" / KICK1,
    "kick2" / KICK2,
    "snare" / SNARE,
    "closed_hh" / HHAT,
    "open_hh" / HHAT,
    "clap" / CLAP,
    "fx" / FX,
)
```

The 'elements' array controls which sample is being used. I would like to somehow connect this to the data in the Drums Struct.

**Comment by mungewell** [comment]
Found this "solution" (but it's quiet hacky)

```
PCM = Struct(
    "sample" / Enum(Computed(lambda this: this._._.samples[len(this._) - 9]),
        PCM_1 = 1,
        PCM_2 = 2,
        PCM_3 = 3,
        PCM_4 = 4,
        PCM_5 = 5,
        ),
)
```

**Comment by arekbulski** [comment]
Your so called solution is so hackey that I dont understand how it works. And I am the maintainer.

I suggest, as per documentation, that you copy-paste the code for Struct into your module and modify it slightly. Add a line in the loop that sets some constant context key and assigns it the name of the subcon. This is probably a one-liner to add.

PS: I looked into your link and found you are using Embedded. This is just well, wrong. I dropped Embedded in version 10.

**Comment by mungewell** [comment]
Whilst messing around I noticed that `Computed(lambda this: list(this._))` grew as the `_subcons` were parsed... and each was added to end. So that 'hack' is to use the len (minus constant) to fake index into an array
```
    drums = Container: 
        tom1 = Container: 
            debug = ['_', '_params', '_root', '_parsing', '_building', '_sizing', '_subcons', '_io', '_index']
            sample = (enum) PCM_1 1
            level = 127
            tune = 64
            decay = 127
        tom2 = Container: 
            debug = ['_', '_params', '_root', '_parsing', '_building', '_sizing', '_subcons', '_io', '_index', 'tom1']
            sample = (enum) PCM_2 2
            level = 127
            tune = 64
            decay = 127
        rim = Container: 
            debug = ['_', '_params', '_root', '_parsing', '_building', '_sizing', '_subcons', '_io', '_index', 'tom1', 'tom2']
```

I note that `Struct()` mentions `_index` however this is fixed at maximum value, as you mentioned this should be a one liner to have count, as each subcon is parsed.... can I have that in a future release?

```
        context._root = context._.get("_root", context)
        for sc in self.subcons:
            try:
                subobj = sc._parsereport(stream, context, path)
                if sc.name:
                    obj[sc.name] = subobj
                    context[sc.name] = subobj
            except StopFieldError:
                break
```

And on the removal of `Embedded`, guess that makes me old-skool... sure you had good reason to remove. I'll have to clean up the code some more to support head. My local repo is a little old, listing tag: v2.9.45

**Comment by arekbulski** [comment]
Here, since you seem to not know how to fix this I did it for you:
```py
class Struct(Construct):
    def _parse(self, stream, context, path):
        obj = Container()
        obj._io = stream
        context = Container(_ = context, _params = context._params, _root = None, _parsing = context._parsing, _building = context._building, _sizing = context._sizing, _subcons = self._subcons, _io = stream, _index = context.get("_index", None))
        context._root = context._.get("_root", context)
        for index,sc in enumerate(self.subcons):
            try:
                context.parsing = sc.name
                context.parsingindex = index
                subobj = sc._parsereport(stream, context, path)
                if sc.name:
                    obj[sc.name] = subobj
                    context[sc.name] = subobj
            except StopFieldError:
                break
        return obj
```

**Comment by mungewell** [comment]
Thank you for the suggestion.... Yes, I can confirm that this works!
https://github.com/mungewell/uno-drum-utils/blob/struct_parsing_index/decode_kit.py#L29

The next question is whether my use case is too 'odd ball' for this patch to be include in HEAD? Or should I just run it locally?
Simon.

**Comment by arekbulski** [comment]
Yeah, it is too odd ball. I am not keen on merging it. Let us just leave this recipe for others to find. Close the ticket?

**Comment by mungewell** [comment]
Closing, thank you for your help.
