### ISSUE TITLE
Tunneling that automatically chooses compression method

### ISSUE THREAD

**Issue by ali1234** [construct/construct#897]
I am trying to make an adapter like Compressed, except it automatically picks the best compression method. It then needs to store the type of compression used in a field somewhere. It also needs to obey that field when building, so that rebuilding parsed data produces the same result.

This is what I tried:

```py
from math import ceil
import zlib, gzip, bz2, lzma

from construct import Bytes, Const, Int8ul, PaddedString, Prefixed, Struct, Tunnel


compressors = {
    'zlib': zlib,
    'gzip': gzip,
    'bzip': bz2,
    'lzma': lzma,
}


class BestCompressed(Tunnel):
    def _encode(self, obj, ctx, path):
        if ctx._.type == 'none':
            return obj
        elif ctx._.type == 'auto':
            # Try all compression types and pick the best one.
            all_comp = [(k, v.compress(obj)) for k, v in compressors.items()]
            all_comp.append(('none', obj))
            best = min(all_comp, key=lambda x: len(x[1]))
            # Put the best type back into the context. (THIS DOES NOT WORK!!!)
            ctx._.type = best[0]
            print('best type is', best[0], len(best[1]))
            return best[1]
        else:
            return compressors[ctx._.type].compress(obj)

    def _decode(self, obj, ctx, path):
        if ctx._.type == 'none':
            return obj
        else:
            # Fails here because of KeyError: 'auto'
            return compressors[ctx._.type].decompress(obj)


my_struct = Struct(
    'type' / PaddedString(4, 'ascii'),
    'compressed' / Prefixed(Int8ul, Struct(
        'string' / Const(b'PROBLEM?'),
        'data' / BestCompressed(Bytes(0x40)),
    ))
)


b = my_struct.build({'type': 'auto', 'compressed': {'data': b'\x00'*0x40}})

print(hex(len(b)), b.hex(), b)
print(my_struct.parse(b))
```

Output:

```
best type is zlib 12
0x19 6175746f1450524f424c454d3f789c6360a00c000000400001 b'auto\x14PROBLEM?x\x9cc`\xa0\x0c\x00\x00\x00@\x00\x01'
Traceback (most recent call last):
...
  File "cns.py", line 36, in _decode
    return compressors[ctx._.type].decompress(obj)
KeyError: 'auto'
```

This does not work because updating the `ctx._.type` has no effect on the output. It still contains `auto`, and then parsing the result fails because decode does not know what type of encryption was used. What is the correct way to implement this? Changing the binary file format is not possible. This is a minimum viable sample - the real format is more complex.

**Comment by arekbulski** [comment]
Updating context obviously doesnt work. I advise that you try using Adapter+Struct where
```
Struct( "lib"/Enum or String, "len"/Int64, "data"/GreedyBytes)
```
The Adapter would then output during encoding something like
```
dict(lib="zlib", len=XX, data=XX)
```
Its not encryption, its encoding.

**Comment by arekbulski** [comment]
Using tunneling makes it difficult. Its better to use an Adapter and a Struct or... write your own class for this. This approach might actually be best.

**Comment by ali1234** [comment]
Do you mean like this?

```
from math import ceil
import zlib, gzip, bz2, lzma

from construct import Adapter, Bytes, Const, GreedyBytes, Int8ul, PaddedString, Prefixed, Struct, Tunnel


compressors = {
    'zlib': zlib,
    'gzip': gzip,
    'bzip': bz2,
    'lzma': lzma,
}


class BestCompressed(Adapter):
    def _encode(self, obj, ctx, path):
        print(obj)
        if obj['type'] == 'auto':
            # Try all compression types and pick the best one.
            all_comp = [(k, v.compress(obj['compressed']['data'])) for k, v in compressors.items()]
            all_comp.append(('none', obj['compressed']['data']))
            best = min(all_comp, key=lambda x: len(x[1]))
            # Put the best type back into the object.
            obj['type'] = best[0]
            obj['compressed']['data'] = best[1]
            print('best type is', best[0], len(best[1]))
        elif obj['type'] != 'none':
            obj['compressed']['data'] = compressors[obj['type']].compress(obj['compressed']['data'])
        return obj

    def _decode(self, obj, ctx, path):
        if obj['type'] != 'none':
            obj['compressed']['data'] = compressors[obj['type']].decompress(obj['compressed']['data'])
        return obj


my_struct_packed = Struct(
    'type' / PaddedString(4, 'ascii'),
    'compressed' / Prefixed(Int8ul, Struct(
        'string' / Const(b'PROBLEM?'),
        'data' / GreedyBytes,
    ))
)


my_struct = BestCompressed(my_struct_packed)


b = my_struct.build({'type': 'auto', 'compressed': {'data': b'\x00'*0x40}})

print(hex(len(b)), b.hex(), b)
p = my_struct.parse(b)
print(p)
print(my_struct.build(p))
```

This seems to work anyway...

**Comment by arekbulski** [comment]
Well, not in so many code but yes. This is more or less what I had in mind. Also, writing your own class would also be fine. It would probably be even a little less code.

**Comment by arekbulski** [comment]
Prefixed(VarInt, GreedyBytes) would also be fine.

**Comment by arekbulski** [comment]
I edited your code to display using (py) formatter.

**Comment by ali1234** [comment]
Prefixed(VarInt, GreedyBytes)

I might be misunderstanding completely how this all works, but I don't think I can use this because there is stuff in between the size and the data bytes in the file format. I'm following a published spec and I can't simply change it. This is the real Struct I am working with:

```py
struct_blit_image_packed = Struct(
    'header' / Const(b'SPRITE'),
    'type' / PaddedString(2, 'ASCII'),
    'data' / Prefixed(SizeAdapter(Int32ul), Struct(
        'width' / Int16ul,
        'height' / Int16ul,
        'format' / Const(0x02, Int8ul),
        'palette' / PrefixedArray(PaletteCountAdapter(Int8ul), struct_blit_pixel),
        'bit_length' / Computed(compute_bit_length),
        'pixels' / GreedyBytes, # this is the only thing that is supposed to be compressed
    ))
)
```
Note that the outer size field actually contains the size of the entire struct, including the header, type, and size field itself. So I use an adapter to add a constant to it. Also note that there is more than one variable sized field, so the total size is only loosely related to the size of the compressed data. So for this reason I can't simply put a prefix on the compressed data. I think my second attempt at implementing it will work with the real struct though (modulo a few renamed keys).

**Comment by arekbulski** [comment]
Now I get it. You are right, I oversimplified it entirely. 

You could write your own classes instead of adapters. Just saying. Think about it.

**Comment by arekbulski** [comment]
I also didnt mention: Prefixed has an option that is something like "includesizefield". Check it.

**Comment by ali1234** [comment]
I think that could work if the header was all Const stuff, but unfortunately it contains the type field (where the compression type is stored), and I don't know how I could push that information into it if it has to behave like a sizefield, which is effectively just an int and therefore only receives one value, rather than a dict. So then I'd end up writing an Adapter or something equally complex anyway. (There's also PaletteSizeAdapter, because 0 means 256 palette entries, but 1 means 1.)

I don't really want to make my own classes because this struct is used as a subcons in even more complicated things.

Anyway I have a path forward now, thanks.

**Comment by arekbulski** [comment]
Your welcome. For the record, this is what I meant:
```py
my_struct_packed = Struct(
    'type' / PaddedString(4, 'ascii'),
    'data' / Prefixed(Int8ul, GreedyBytes),
)

my_struct = BestCompressed(my_struct_packed)
```
This would simplify your example code a little.

**Comment by arekbulski** [comment]
Could you please leave a link to your repository and the specs you follow? Just so other people can look at what you are doing.

**Comment by ali1234** [comment]
Will do when it gets merged.

**Comment by arekbulski** [comment]
Are the links still not available?

**Comment by ali1234** [comment]
Pull request is here https://github.com/32blit/32blit-tools/pull/57 and specifically https://github.com/32blit/32blit-tools/pull/57/commits/ecc5f6c862ec48073cf62190f3124781b3133a38 but it might get rebased before it is merged.
