### ISSUE TITLE
Purge of Embedded - suggestions for fixing code?

### ISSUE THREAD

**Issue by mungewell** [construct/construct#898]
As noted in another bug, `Embedded` as been removed from Contruct v10... but how do I rework my code?? _Not a criticism of the removal, I'm sure you had valid reasons._

My usage is/was pretty simple, and a attempt to prevent extra typing and duplication which could lead to errors. For example the following is an attempt allow parsing of different format files (Midi data has additional bytes wrapped around the same core). If I was to nest this, then resultant parsed data would have an extra container level.
```py
UNODRP = Struct(
    "samples" / Array(12, Byte),
    Const(b"\x00\x00"),
    "drums" / DRUMS,
    "fx" / FX,
    Const(b"\x00\x00\x64\x5f"),
)

MIDI = Struct(
    Const(b"\xf0\x00\x21\x1a\x02\x02\x00\x37\x00\x00"),
    "unodrp" / Embedded(UNODRP),
    Const(b"\xf7"),
)
```

I know there is a `If` operator, can I configure a call to parse so that it knows about different 'modes'???

I've also used Embedded to "include" the same ENUM def into many separate structs which are all slightly/subtlety different.

**Comment by mungewell** [comment]
Should mention how I call/do the parse....

```
    if options.dump and data:
        if options.midi:
            config = MIDI.parse(data)
        else:
            config = UNODRP.parse(data)
        print(config)
```

**Comment by mungewell** [comment]
Fixed my Embdedded Enums with the trick from here:
https://construct.readthedocs.io/en/latest/api/mappings.html?highlight=enum.IntEnum#construct.Enum
```
class PCM(enum.IntEnum):
        PCM_1 = 1,
        PCM_2 = 2,
        PCM_3 = 3,
        PCM_4 = 4,
        PCM_5 = 5,

DRUM = Struct(
    "sample" / Enum( Computed(lambda this: this._._.samples[len(this._) - 9]) , PCM),
    "level" / Byte,
    "tune" / Byte,
    "decay" / Byte,
    Const(b"\x00"),
)
```

**Comment by arekbulski** [comment]
Here is the IF and IFTHENELSE:
https://construct.readthedocs.io/en/latest/misc.html#if

How do you get rid of embedding? As stated in docs, just nest the structures.
The reason for dropping support for embedding was that it required crazy hacky implementation on the side of Struct (and Sequence). And the old embedding semantics were even more crazy, double crazy impl. I had enough of it so I just removed it. Thats the long story made short.

```py
MIDI = Struct(
    Const(b"\xf0\x00\x21\x1a\x02\x02\x00\x37\x00\x00"),
    "unodrp" / UNODRP,
    Const(b"\xf7"),
)
```

**Comment by mungewell** [comment]
As I mentioned above, I can nest the Struct (that I previously had as Embedded), however this adds an additional later/container - so the underlying code would need to know to hand that difference...

I'll see if I can figure out how to pass keywords and try if "If' can be used to parse/build the extra Consts that the Midi data has.

**Comment by mungewell** [comment]
Keywords offers a solution which would work for me, but freaks out if the keyword is not present.
```
    if options.dump and data:
        '''
        if options.midi:
            config = MIDI.parse(data)
        else:
            config = UNODRP.parse(data)
        '''
        config = UNODRP.parse(data, midi=options.midi)
        print(config)
```
and
```
UNODRP = Struct(
    If(this._params.midi,
        Const(b"\xf0\x00\x21\x1a\x02\x02\x00\x37\x00\x00"),
    ),

    "samples" / Array(12, Byte),
    Const(b"\x00\x00"),
    "drums" / DRUMS,
    "fx" / FX,
    Const(b"\x00\x00\x64\x5f"),

    If(this._params.midi,
        Const(b"\xf7"),
    ),
)
```

**Comment by arekbulski** [comment]
Please use (py) formatter.

**Comment by arekbulski** [comment]
Well, yes. If there is an IF field then you need the context (or the obj dictionary rather) to contain such a key, even if its just false. Missing key raises an exception. Did you expect it to behave differently?

**Comment by mungewell** [comment]
I would like to figure out a cleaner/elegant way to do the including, however my immediate needs are solved so happy to close bug.
Thanks.
