### ISSUE TITLE
Booleans and FormatField

### ISSUE THREAD

**Issue by N3X15** [construct/construct#901]
According to the 3.9.1 [`struct` docs](https://docs.python.org/3/library/struct.html#format-characters), `?` is a valid format, converting to/from `bool`.

```python
import struct

print(repr(struct.unpack('>?', b'\x01')))
print(repr(struct.unpack('>?', b'\x00')))
```
```
$ python structworks.py
(True,)
(False,)
```

Unfortunately, it seems that it's not supported in Construct:
```python
import construct

bool_ = construct.FormatField('>', '?')
```
```
Traceback (most recent call last):
  File "F:\Projects\pyPhoton\constructbug.py", line 3, in <module>
    bool_ = construct.FormatField('>', '?')
  File "C:\Python39\lib\site-packages\construct\core.py", line 1015, in __init__
    raise FormatFieldError("format must be like: f d B H L Q b h l q e", format)
construct.core.FormatFieldError: Error in path ?
format must be like: f d B H L Q b h l q e
```

In addition, there seems to be a lack of anything boolean-ish in terms of Field classes or helper methods.

While this is fairly easy for me to work around, it seems like a pretty big omission.

**Comment by arekbulski** [comment]
Thank you for pointing this out. I was not aware of it. And you are the first person to point this out. 

Have you seen the Flag class?
https://construct.readthedocs.io/en/latest/advanced.html#mappings
https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Flag

**Comment by arekbulski** [comment]
I updated FormatField and added the ? format string.

**Comment by N3X15** [comment]
Yeah, I have seen the Flags class.  It seemed a little out of place and unclear, though, especially since the format I'm <s>reverse-engineering</s> working with relies on `byte > 0` rather than just `byte == 1`.
```shell
$ python -c "import struct;print(repr(struct.unpack('>?', b'\x02')))"
(True,)```

**Comment by N3X15** [comment]
Root cause of issue fixed.
