### ISSUE TITLE
Determine offsets of subcons recursively / GUI tool

### ISSUE THREAD

**Issue by timrid** [construct/construct#903]
Hi,

I am currently working on a GUI in wxpython to display constructs. This should be similar to the "Kaitai IDE" (https://ide.kaitai.io/) in a slightly reduced form, but with the main difference that you can not only display the data but also modify it.

At the moment it looks like this:

![image](https://user-images.githubusercontent.com/6593626/108621960-37505680-7436-11eb-80b9-c7d424f3556d.png)

As soon as one clicks on an entry on the right side, the associated bytes are marked in the hex editor. My problem is that I need to know the bytes offset and the number of bytes in the stream for each entry. 

Currently my implementation is that I do a preprocessing of the construct and add a `Tell` before and after each subconstruct to find out the position in the stream. This runs recursively over all nested structs. But I think this is not a very elegant way, because the original construct has to be modified. Is there another way to determine the offsets without having to modify the construct itself?

My idea would be that in addition to the value in a `Container` automatically also the offset and the size are stored in a separate `dict` inside the `Container`. What do you think about this idea?

**Comment by arekbulski** [comment]
I think inserting Tells is a right way of going about it. The seemingly only alternative would be to modify Struct (also Sequence and some others) as to tell() the stream before and after each subcon and insert the offset into either the output dict or context dict. But this is not different than inserting Tells.

BTW what is that `Bytes[2]`? There is no such a thing in Construct. Its either Bytes(2) or Byte[2] array. 

You can create another package for your GUI if you want. Just tell me what to put into the documentation and I will do it.

**Comment by timrid** [comment]
Yes, the preprocessing of construct is possible, but it relies on internal processing of construct.... So I think this should be better implemented in the construct library as a kind of "metadata" dict inside the output `Container` of a `Struct` and an output `ListContainer` of an `Array` or a `Sequence`. I think this is a cleaner way than what I currently do. Also, this feature may be useful for other users of this library....

If you are open to accepting such a feature, I could implement it and create a PR.

Yes, you are right, it should be `Byte[2]`.

**Comment by arekbulski** [comment]
I dont quite understand what it is that you are proposing so, I think you gonna have to show me some code. It doesnt have to be fully implemented, just the gist of it.

**Comment by timrid** [comment]
I created a PR: #904

**Comment by arekbulski** [comment]
Hmm I am against merging this feature. I think RawCopy and Tell is the right way of obtaining such information.

**Comment by timrid** [comment]
Basically I agree with you, that RawCopy and Tell are the right way. But for uses cases like this gui other implementations are relative complex. This is how my current implementation for the preprocessing looks like. But i don't think i have reached all edge cases yet. Especially for Restreamed and Transformed (so also BitStruct) I haven't found a suitable solution yet except to skip them.

https://gist.github.com/timrid/2d5249ce6b89e123c201660171e2a0f0

**Comment by arekbulski** [comment]
One thing about the gist: instead of modifying it in place you could create a modified deep copy. This way you retain the original in case you need it for later. Oh and a typo in the docstring.

**Comment by arekbulski** [comment]
Its probably obvious but I will say it anyway: you dont need me to merge the PR in order to use the approach. You can copy-pasta the Struct class into your module and modify it the way PR does it. You can override construct imports with your own classes.

**Comment by timrid** [comment]
I don't like a copy-paste approach into my own module, just because I want to have a little something different.

Then I try to perfect my approach from the gist, so that it works with all constructs. Since that doesn't have much to do with this issue I will close it.

When I have a presentable state of the gui, I will release it in a separate package and get back to you.
