### ISSUE TITLE
No error or wrong error thrown on too large values in Int24ul

### ISSUE THREAD

**Issue by timrid** [construct/construct#907]
If I write too large a value in an `Int24ul`, no error is thrown in the first place. I would have expected a `construct.IntegerError`. But if the value is much too large, an `IndexError` is thrown instead of an `IntegerError`.

```python
Int24ul.build(16777215)  # no problem here
Int24ul.build(16777216)  # this should throw an error, but it works
Int24ul.build(16777215000000000)  # this should throw an "IntegerError" but throws an "IndexError: list assignment index out of range"
```

I looked at the internals of of `BytesInteger` and wondered if it isn't better to work with `int.to_bytes` and `int.from_bytes` (https://docs.python.org/3/library/stdtypes.html#int.to_bytes) instead of re-implementing this logic in `construct.lib.integer2bytes`?

**Comment by arekbulski** [comment]
We need to support bitwise equivalent of integer2bytes as well so... I think we should just fix current implementation instead. Do you agree?

**Comment by timrid** [comment]
That would probably be the simplest solution. But I could imagine that the built-in functions in python run more efficiently than the replicated ones. 

The same problem also shows up with the `BitsInteger`:
```python
print(BitsInteger(1).build(0)) # prints: b'\x00'
print(BitsInteger(1).build(1)) # prints: b'\x01'
print(BitsInteger(1).build(2)) # prints (without error): b'\x00
```

**Comment by timrid** [comment]
My idea would be a method like this one, to check the bounds before calling `integer2bytes` (not tested yet)

```python
def check_integer(number, width, signed):
    if signed:
        min = -((2 ** width) / 2)
        max = ((2 ** width) / 2) - 1
    else:
        min = 0
        max = (2 ** width) - 1
    if max < number < min:
        raise IntegerError(f"value {str(number)} is out of range (min={str(min)}, max={str(max)}")
```

**Comment by arekbulski** [comment]
I believe the right way of writing it is:
```py
if not min < number < max:
    rise IntegerError
```

**Comment by arekbulski** [comment]
Also the checking should happen within integer2bytes, not in BytesInteger.

**Comment by arekbulski** [comment]
Also you commited a stupid bug which also happened to me in ZigZag implementation. You used / which is floating point division, not integer division. LOL yeah.

**Comment by timrid** [comment]
Hehe, your right. And the correct comparison is 

```python
if not min <= number <= max:
    raise IntegerError
```

Do you want me to finish this completely and create a PR or do you want to fix this on your own?

**Comment by arekbulski** [comment]
I will fix it on my own, using your code from above. Good catch Timmy!

**Comment by timrid** [comment]
All right.
I'm still working on the GUI from #903 and was a bit surprised that I could enter such large values without an error message ;)

**Comment by arekbulski** [comment]
I will ask you for a review after I fix the integers. Will you partake?

**Comment by timrid** [comment]
Sure. But it may take until the next weekend.

**Comment by arekbulski** [comment]
That is expected anyway. I have committed to a weekly release schedule. This is so that PRs dont wait a year anymore. Tomorrow I will publish things  from last week, and the integers fixes will go next week.

**Comment by arekbulski** [comment]
There is another bug/mistake that you made. BytesInteger passes width in bytes to integer2bytes so its 256**width and not 2**width. Nifty huh? I admit the fault is my own, I didnt describe it in enough detail in integer2bytes docstring.

**Comment by timrid** [comment]
It was intentionally the bit width, so that you can use the same method for integer2bytes and integer2bits. But in integer2bytes you have to multiply it with 8.

**Comment by arekbulski** [comment]
I am done and code is ready for review: except 1 thing, I am unable to import IntegerError from within binary.py so ValueError is raised instead. If you would investigate this, I would appreciate the effort. Otherwise we just stick to current exceptions. 

https://github.com/construct/construct/blob/master/construct/lib/binary.py
https://github.com/construct/construct/blob/master/tests/lib/test_binary.py

**Comment by timrid** [comment]
The problem with `IntegerError` is due to circular imports. The solution is to use another form of import. Write the following in `binary.py`:

```python
import construct
raise construct.IntegerError(...)
```

instead of

```python
from construct import *
raise IntegerError(...)
```

I also noticed that the following line in `integer2bits` is redundant
```python
if number < 0 and not signed:
    raise ValueError(f"negative number {number} not expected")
```
because it is also caught by checking the range a few lines later:
```python
if not min <= number <= max:
    raise ValueError(f"number {number} is out of range (min={min}, max={max})")
```

Everything else looks fine.

**Comment by arekbulski** [comment]
I changed the exponentation into shifts. Wanna check it?
https://github.com/construct/construct/commit/7a026beea8776a6d8dfef50691ce2bf3639f3ed7

**Comment by timrid** [comment]
The changes are correct. However, I have no idea where the time difference comes from.

**Comment by arekbulski** [comment]
Exponentiation looks more readable so I will revert that one commit.

**Comment by arekbulski** [comment]
I have an idea why the timeit results are what they are but its just pure speculation on my part. The exponentiation probably checks if base is 2 and then defers to bitwise shift, so both versions have identical runtime. In principle that is. In practice there is a lot of preemption and interrupting going on in the OS which leads to fluctuations in timings.

**Comment by timrid** [comment]
That is one possible explanation.

I saw that you have now included `ValueError` in the documentation. Why don't you use the `IntegerError`? I have shown how to use it. 
It doesn't make much sense to throw an `IntegerError` directly from `BytesInteger._build()` method when checking 
```python
if obj < 0 and not self.signed:
    raise IntegerError("value %r is negative, but field is not signed" % (obj,), path=path)
```
 and a `ValueError` from `integer2bytes()`. It should be at least the same error type.

**Comment by arekbulski** [comment]
I just did it the way I saw fit.

**Comment by arekbulski** [comment]
This issue fixes were published with version 63. Ready to close?

**Comment by timrid** [comment]
Well, I still don't agree that there is now `ValueError` and `IntegerError` for the same error class. Not a convincing reason you gave. But apparently you don't want to correct that.

**Comment by arekbulski** [comment]
Sorry for delayed reply, been making a dinner.

Yeah, this is a point of contention. My reasoning is that upper layer (eg. BytesInteger) throws IntegerErrors and lower layer (eg. bytes2integer) throws ValueErrors. But this is a pretty arbitrary decision indeed.

**Comment by timrid** [comment]
Okay, if these are your reasons, two alternative suggestions:
1. catch the `ValueError` from the lower level in the higher level and then throw the correct `IntegerError`.
2. in the lower level separate the size check from the conversion in two methods and in the higher level first check if it works and then execute the conversion.

**Comment by arekbulski** [comment]
Okay, I will catch the exception and re-raise an IntegerError. :)

**Comment by arekbulski** [comment]
https://github.com/construct/construct/commit/0d8b00b3256d9d552de064a1f74e3f1f657e61e5
Implemented. Awaiting review.

**Comment by timrid** [comment]
the path is missing when re-raising the exception

**Comment by arekbulski** [comment]
I fixed the path in errors but now the code broke. I dont know what is wrong. Could you take a look at last commit?

**Comment by arekbulski** [comment]
Fixed. Check last commit.

**Comment by timrid** [comment]
Looks good. Thanks for fixing.
