### ISSUE TITLE
BitsInteger has wrong swapped semantic

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#908]
I was fixing some issues with numeric classes (and docstrings and tests etc) and found this defect: the swapped parameter (in BitsInteger) is supposed to mean "swap bytes in bit-string" but currently it swaps bits. This is just just plain damn wrong. This bug is probably 5 years old and noone has reported this?!

@yannayl @timrid 
I welcome your input on this. Will wait with publishing fixes for this till next release cycle.

https://github.com/construct/construct/blob/master/construct/core.py#L1180-L1183
https://github.com/construct/construct/blob/master/construct/core.py#L1195-L1198

The code should use `swapbytesinbits` instead of `swapbytes`.
https://github.com/construct/construct/blob/master/construct/lib/binary.py#L122-L145

**Comment by yannayl** [comment]
I think this comment from two years ago explains in length pretty much everything I can think of bit/byte endianness:
https://github.com/construct/construct/pull/770#issuecomment-475193377

The gist: I believe that all four options little/big bit/byte level endianness should be supported idiomatically. I think the crux here is that `swapped` parameter can mean `bytes_swapped` or `bits_swapped`. To me in the context of `BitsInteger` the least surprise would be `bits_swapped` which is the current implementation. So I'm good with that, and would still like that arbitrary multiple-of-8 restriction to go away as It only makes sense in byte-level. I don't see any reason why `bytes_swapped` in this context is in any way natural.

In the postscript of the comment I linked to I actually said that `swapbytesinbits` is never used 🤷 but it was a really long and tedious comment. I actually used it as a reference few times afterwards when I encountered similar issues.

**Comment by arekbulski** [comment]
Instead of changing swapped semantics, I could add another parameter `byteswapped`. Does this seems a better alternative?

**Comment by arekbulski** [comment]
Damn, you are right @yannayl you did mention this and I didnt listen.

**Comment by yannayl** [comment]
> `byteswapped`

Isn't it equivalent to wrapping it in `ByteSwapped`?

**Comment by yannayl** [comment]
> Damn, you are right @yannayl you did mention this and I didnt listen.

It's all good :)

**Comment by arekbulski** [comment]
To me bit-level swapping seems odd and I cant imagine any real specification to use it. Even computers as old as PDP-11 dont do bit-level endianness AFAIK so my intention is this: I will change swapped to byte-level. If someone wants old semantic, use BitsSwapped wrapper.

**Comment by arekbulski** [comment]
> Isn't it equivalent to wrapping it in `ByteSwapped`?

Yes, it uses swapbytes() internally.

```py
def ByteSwapped(subcon):
    size = subcon.sizeof()
    return Transformed(subcon, swapbytes, size, swapbytes, size)
```

**Comment by yannayl** [comment]
> To me bit-level swapping seems odd and I cant imagine any real specification to use it. Even computers as old as PDP-11 dont do bit-level endianness AFAIK so my intention is this: I will change swapped to byte-level. If someone wants old semantic, use BitsSwapped wrapper.

I had in that issue I linked to a real protocol that uses it, and it's not an exception.
I think that if you have only byte semantics it would force you to swap twice which just feels wrong (iirc)

**Comment by yannayl** [comment]
Oh, and btw the examples which use the `Bitwise` adapter are a bit confusing, I think that it would be better to just show the bits example: 
```python
>>> BitsInteger(2).parse(b'\x00\x01')
1
```

**Comment by arekbulski** [comment]
> Oh, and btw the examples which use the `Bitwise` adapter are a bit confusing, I think that it would be better to just show the bits example:

Could you submit a small PR then? Just dont put much work into it.

**Comment by yannayl** [comment]
Bits aren't really addressed in computers, so bit-endianness is artificial anyway in this realm.

However, most network protocols I am familiar use big-endianness by default for byte-level however they use little endianness for bit level, e.g. ethernet (https://en.wikipedia.org/wiki/Endianness#Bit_endianness)
Also notable - some radio transmissions techniques send multiple bits in a frame and the ordering of them is entirely artificial (QAM?)

**Comment by yannayl** [comment]
> > Oh, and btw the examples which use the `Bitwise` adapter are a bit confusing, I think that it would be better to just show the bits example:
> 
> Could you submit a small PR then? Just dont put much work into it.

sure, will do tomorrow (it's almost midnight on my end)

**Comment by arekbulski** [comment]
And after giving this some thought, there is another ambiguity: if I enable both bit-level and byte-level endianness, there are 2 ways this can be done. Bits first bytes second, or bytes first bits second. Different output depending on the order of endianess-es. Something to sleep over with.

**Comment by yannayl** [comment]
I will catch up tomorrow and see if I can come up with some sane and consistent way to think about it all
Maybe it's better not to put any parameter and let the user wrap it with the adapter she needs explicitly

**Comment by yannayl** [comment]
> And after giving this some thought, there is another ambiguity: if I enable both bit-level and byte-level endianness, there are 2 ways this can be done. Bits first bytes second, or bytes first bits second. Different output depending on the order of endianess-es. Something to sleep over with.

I dont think it can happen if you only restrict byte-level endianess manipulations to multiples of 8

**Comment by arekbulski** [comment]
It does happen. It all depends if you swap bits or after you swap bytes.

**Comment by arekbulski** [comment]
@yannayl  Question for you, since you know protocols:
Should the bits be swapped on each byte independently, or across entire word?

**Comment by arekbulski** [comment]
On the other hand... we could go with my initial idea, the byte-level swapping and only that. That way BytesInteger swapped is analogous to BitsInteger swapped. In particular:
```py
BytesInteger(n, swapped=True)  ==  Bitwise(BitsInteger(8*n, swapped=True))
```
If you ask me, I think the authors of those crazy ass networking protocols should be shot. They invent insane encodings. I see no reason why I should oblige them. In other words: I dont give a damn. 

And if someone requests the old sementics, they can always use BitsSwapped or ByteSwapped or write their own classes.

**Comment by timrid** [comment]
I have not yet formed an opinion on the specific issue and how to best handle the bit/byte endianess. 

However, I think that it is not good to change such fundamental behavior in a minor version. Who knows how many others also rely on the (incorrectly implemented) behavior because it has worked so far. It may break the code of many others.

**Comment by arekbulski** [comment]
You seem to be assuming that I follow semantic versioning which is not the case. I stated that several times although I dont expect you to follow all the issues that go on for years back. Every release is a major release and may break whatever. 

I just applied the changes and will publish them probably tomorrow.

**Comment by arekbulski** [comment]
Docstrings were updated accordingly:
https://construct.readthedocs.io/en/latest/api/numerics.html#construct.BitsInteger

**Comment by yannayl** [comment]
> @yannayl Question for you, since you know protocols:
> Should the bits be swapped on each byte independently, or across entire word?
> My (current) intention is to swap bits in each byte. Therefore order of swapping wont matter.

I think you are right

**Comment by yannayl** [comment]
> On the other hand... we could go with my initial idea, the byte-level swapping and only that. That way BytesInteger swapped is analogous to BitsInteger swapped. In particular:
> 
> ```python
> BytesInteger(n, swapped=True)  ==  Bitwise(BitsInteger(8*n, swapped=True))
> ```

You can. I find it less intuitive. If someone is working in bit level, they expect swapping in bit level.

> If you ask me, I think the authors of those crazy ass networking protocols should be shot. They invent insane encodings. I see no reason why I should oblige them. In other words: I dont give a damn.

The reason they call it Endianness is in reference to a futile argument in Swift's book. Soyou are probably right.

> For completeness: I do believe documentation is superior to implementation. Docstrings used to say it swaps bytes, so this is the way it should go. If docs and implementation differ, the docs are always right.

I believe the opposite. But it's your project friend :)
And I think the intention of the original code was correct but the docstring was copied and not mutated accordingly by mistake.

**Comment by arekbulski** [comment]
Yeah, being project owner has one perk: what I say goes and I dont have to explain myself to anyone. :)
