### ISSUE TITLE
Parse-compiled RepeatUntil does not support a lambda as predicate

### ISSUE THREAD

**Issue by AlexanderStein** [construct/construct#912]
The following test case directly shows the problem:
```python
def test_repeatuntil_compiled():
    d = RepeatUntil(predicate = lambda x,lst,ctx: x == 5, subcon = Byte)
    res = d.parse(b"\x01\x02\x03\x04\x05")
    assert len(res) == 5
    d = d.compile()
    res = d.parse(b"\x01\x02\x03\x04\x05")
    assert len(res) == 5
```
error message:
```
>       c = compile(source, '', 'exec')
E         File "<string>", line 31
E           if (<function test_repeatuntil_compiled.<locals>.<lambda> at 0x7f8865afc048>):
E               ^
E       SyntaxError: invalid syntax
```

Apparently lambdas are not supported when compiling, because when using `obj_` instead this testcase passes:
```
d = RepeatUntil(predicate = obj_ == 5, subcon = Byte)
```

Note: lambdas **do** work when doing non-compiled parsing.

**Comment by arekbulski** [comment]
Yes, lambdas are not supported by the compiler. It says so right in the docs.
https://construct.readthedocs.io/en/latest/compilation.html#restrictions
The expressions like `this obj_ list_` however should work. Although `list_` is not entirely trustworthy.

**Comment by AlexanderStein** [comment]
I see, sorry for the noise then.

`RepeatUntil(predicate = obj_ == 5, subcon = Byte)` or something like this
```python
Struct(
    "id" / Byte,
    "data" / RepeatUntil(this.id == 0xff, Byte)
)
```
works as expected.
