### ISSUE TITLE
Compiled Switch: IntEnum as keys in cases not supported

### ISSUE THREAD

**Issue by AlexanderStein** [construct/construct#913]
If `IntEnum`s are used as keys in the `cases` dict, compiling the parser fails with error:
```py
>       c = compile(source, '', 'exec')
E         File "<string>", line 28
E           factory_1 = {<enum.Zero: 0> : lambda io,this: None, <enum.One: 1> : lambda io,this: formatfield_2.unpack(io.read(1))[0], <enum.Two: 2> : lambda io,this: formatfield_3.unpack(io.read(2))[0]}
E                        ^
E       SyntaxError: invalid syntax
```
Reproducable with the test case:
```py
def test_switch_intenum():
    class enum(IntEnum):
        Zero = 0
        One = 1
        Two = 2
    mapping = {
        enum.Zero: Pass,
        enum.One: Byte,
        enum.Two: Int16ul,
    }

    d = Switch(keyfunc = this.x, cases = mapping)
    common(d, b"", None, 0, x=0)
    common(d, b"\xab", 171, 1, x=1)
    common(d, b"\x09\x00", 9, 2, x=2)
    d = d.compile()
    common(d, b"", None, 0, x=0)
    common(d, b"\xab", 171, 1, x=1)
    common(d, b"\x09\x00", 9, 2, x=2)
```

A _possible_ fix might be replacing `%r` with `%s` in https://github.com/construct/construct/blob/master/construct/core.py#L3835, **but** this breaks once the enumeration (`enum` in this case) provide a `__str__` method.

**Comment by arekbulski** [comment]
Please use py formatted for code blocks. Pretty please. I fixed it for you this time.

**Comment by arekbulski** [comment]
Damn it. I dont know why people use the damn enum34 for everything and then they complain that nothing works. Sorry I didnt make it clear more in the docs. Enum34 is not supported period, not in the compiled, not without it, at all. Use pure Enum construct and get back to me. If it still doesnt work, I will help you out. Meanwhile I will put a warning in the docs not to use this shit.

**Comment by arekbulski** [comment]
I added this to test suite just now. It works all green.
```py

def test_switch_issue_913():
    enum = Enum(Byte, Zero=0, One=1, Two=2)
    mapping = {
        enum.Zero: Pass,
        enum.One: Int8ul,
        enum.Two: Int16ul,
    }

    d = Switch(keyfunc = this.x, cases = mapping)
    common2(d, b"", None, 0, x="Zero")
    common2(d, b"\xab", 171, 1, x="One")
    common2(d, b"\x09\x00", 9, 2, x="Two")
```

**Comment by arekbulski** [comment]
In fact Enum is not needed:
```py

def test_switch_issue_913_without_enum():
    mapping = {
        "Zero": Pass,
        "One": Int8ul,
        "Two": Int16ul,
    }

    d = Switch(keyfunc = this.x, cases = mapping)
    common2(d, b"", None, 0, x="Zero")
    common2(d, b"\xab", 171, 1, x="One")
    common2(d, b"\x09\x00", 9, 2, x="Two")
```

**Comment by arekbulski** [comment]
Or if you want to use integers so much:
```py

def test_switch_issue_913_on_integers():
    mapping = {
        0: Pass,
        1: Int8ul,
        2: Int16ul,
    }

    d = Switch(keyfunc = this.x, cases = mapping)
    common2(d, b"", None, 0, x=0)
    common2(d, b"\xab", 171, 1, x=1)
    common2(d, b"\x09\x00", 9, 2, x=2)
```

**Comment by AlexanderStein** [comment]
Thanks for your code examples. It made some things more clear to me. This syntax made the usage very easy https://github.com/construct/construct/blob/master/construct/core.py#L1812

Using is easy, but unfortunately it broke my regular parser on the switch. It took me a while to strip the problem down to a testcase:
```py
def test_switch_issue_913_intenum():
    class E(IntEnum):
        One = 1
    enum = Enum(Byte, E)
    mapping = { enum.One: Pass }
    d = Struct(
        "id" / Int8ul,
        "data" / Switch(this.id, mapping, default = Int16ul),
    )
    d.parse(b"\x01")
```
IMHO the intention is obvious, but this test fails with
```
        if len(data) != length:
>           raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
E           construct.core.StreamError: Error in path (parsing) -> data
E           stream read less than specified amount, expected 2, found 0
```
Apparently the wrong switch case, default one, is taken. If I use `mapping = { E.One: Pass }` instead, this test will pass.

**Comment by arekbulski** [comment]
Of course it doesnt work. You are using enum34 again.

**Comment by arekbulski** [comment]
Your test case fails for obvious reasons, which I already covered in the last 3 examples. id field gets parsed fine. Then switch takes the id value and looks it up in the mapping dictionary. The dict key is an enum object, not an integer like id value. So it defers to default subcon but since there are no more bytes in the stream, it fails.

Stop using the gorram enum34 and it will work fine.

**Comment by arekbulski** [comment]
PLEASE LEAVE THIS TREAD OPEN, I will close it when I am done with it.
