### ISSUE TITLE
Release Version 2.10.64 not on PyPI

### ISSUE THREAD

**Issue by timrid** [construct/construct#919]
You forgot to upload the 2.10.64 release to PyPI, or was that on purpose?

The upload to PyPI can also be done well via Github Actions, if you create a new release version on Github: https://docs.github.com/en/actions/guides/building-and-testing-python#publishing-to-package-registries

**Comment by arekbulski** [comment]
Ah dang. I must have forgotten. Will publish today.

**Comment by arekbulski** [comment]
Done.
