### ISSUE TITLE
Version 2.5.5 changed PascalString API

### ISSUE THREAD

**Issue by dwfreed** [construct/construct#92]
When PascalString was reimplemented, the `length_field` keyword argument was renamed to `lengthfield` which broke mitmproxy.  Full traceback:

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.main import mitmproxy
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/main.py", line 7, in <module>
    from . import version, cmdline
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/cmdline.py", line 11, in <module>
    from .proxy import config
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/__init__.py", line 3, in <module>
    from .server import ProxyServer, DummyServer
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 12, in <module>
    from ..protocol import Kill
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/__init__.py", line 30, in <module>
    from .tls import TlsLayer
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 11, in <module>
    from ..contrib.tls._constructs import ClientHello
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/contrib/tls/_constructs.py", line 69, in <module>
    PascalString("name", length_field=UBInt16("length")),
TypeError: __init__() got an unexpected keyword argument 'length_field'
```

Reported by @jackmiller334

**EDIT**: corrected name of new field; I reversed the words.  And apparently the old field too.

**Comment by arekbulski** [comment]
The problem is that this argument name **change was intentional**, as part of ongoing architectural changes #80 . I would prefer to stick to it. Is it possible to change the depending project to use the new name? There will be some more similar changes within incoming weeks. You could subscribe to #86 .

**Comment by mhils** [comment]
@mitmproxy maintainer here. It would be very welcome if you could push a patch release that reverts that change. If you do want to rename it, we would be very grateful if you could do so in a major or minor, but not a patch release!

**Comment by arekbulski** [comment]
I will rename it to 2.6.1 and push a release, and add notes that 2.6.x are kind of beta. 2.7 will be the end of API changes and have full polished documentation.

**Comment by mhils** [comment]
To elaborate a bit more on this: When we included construct in mitmproxy, we specified `construct>=2.5.2, <2.6` as a dependency to make sure that our users get all future patch releases, assuming the project follows semantic versioning. If you say that you don't (which would be fine, your project!), we can ship a bug fix release for mitmproxy, but my suspicion is that we may not be the only ones. :relaxed:

**Comment by mhils** [comment]
Great, thanks for the super fast reaction! 😄

**Comment by arekbulski** [comment]
Can you revert to 2.5.3? I will remove the further two and rename them 2.6.1 and 2.6.2.

**Comment by mhils** [comment]
We pin on `>=2.5.2, <2.6`, so that'd work just fine. 🙂

**Comment by arekbulski** [comment]
Releases renamed and marked pre-release both on GitHub and Pypi.
