### ISSUE TITLE
gui tool

### ISSUE THREAD

**Issue by timrid** [construct/construct#922]
This is my first published version of my GUI Tool for this library, based on wxPython:
https://github.com/timrid/construct-editor
It's similar to Kaitai Visualizer, but also allows you to change the structured values (thanks to this library). It doesn't look quite as nice yet, but it already serves its purpose.

Do you think it's worth putting more work into this?

**Comment by arekbulski** [comment]
I really dont know. But I do recognize your efforts and, well, I dont know.

**Comment by jpsnyder** [comment]
This looks really cool! I've always wanted a hex editor with structure editing capabilities similar to [010 Editor](https://www.sweetscape.com/010editor/) but it uses construct instead.

I could see this being useful as a development tool for creating constructs in the reverse engineering domain.

**Comment by timrid** [comment]
Yes, my development work has a similar background. I actually come from the embedded systems area and there we already have a wxPython GUI for a device to read data from the EEPROM. For this I only needed a wxPython widget to display the data in a structured way. The standalone version of the construct-editor was only used to test the constructs.

But the more I worked on it the more I think that the standalone version would also be a good general development tool if you want to define complex constructs. My idea would be to add a mode where you can load python files with the construct definition dynamically to help during the development of the constructs.

Let's see how much free time I have to work on it, since my original purpose is mostly fulfilled for now.

**Comment by jpsnyder** [comment]
Yeah, even a simple file watcher that watches for changes to a file containing a construct spec would be nice.
This would replace the need to use the construct's debugger utility to see my progressive improvements as I write the spec.

**Comment by arekbulski** [comment]
I mentioned your editor in the main docs. Good yeah?
