### ISSUE TITLE
ModuleNotFoundError: No module named 'construct'

### ISSUE THREAD

**Issue by blindb** [construct/construct#924]
downloaded source and tried to install
c:\>py -m pip install Downloads\construct-2.10.66.zip
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\me\AppData\Local\Temp\pip-install-f56xjm1o\construct_a93f447c2c3d46b98365c3103fc654e5\setup.py", line 3, in <module>
from construct.version import version_string
ModuleNotFoundError: No module named 'construct'

$ py -m pip list |grep pip
pip                                21.0.1

$ py -V
Python 3.9.4

**Comment by arekbulski** [comment]
Strange. Have you tried `pip install  constuct` ?

**Comment by arekbulski** [comment]
Also try `python3.8 -m pip install construct` ?

**Comment by blindb** [comment]
yeah, clean 3.8 download and works. I need to clean my env.
Sorry and thanks.
