### ISSUE TITLE
Passing user context to Processing on-the-fly?

### ISSUE THREAD

**Issue by jelledevleeschouwer** [construct/construct#925]
Hi, 

Thank for the great work with this project. I do have a usage scenario I have some questions about:

**What I am trying to achieve:**
- Transformation of a large binary file into another binary file with a different format

**How I am trying to achieve this:**
- Using on-the-fly processing, otherwise `GreedyRange` would try to parse the entire input file in one go and which would require tons of RAM

```python
input_fmt = GreedyRange(Struct(
    "id"        / Enum(Byte, A=1, B=2, C=3),
    "len"       / Byte,
    "data"      / Switch(this.id,
        {
            "A" : Array(this.len, Struct("ts" / Float64n, "t" / Float32n, "h" / Float32n)),
            "B" : Array(this.len, Struct("ts" / Float64n, "x" / Float32n, "y" / Float32n, "z" / Float32n)),
            "C" : Array(this.len, Struct("ts" / Float64n, "n" / Int16un)),
        }),
    ) * processobj, discard=True)
```

- Using a global variable `ostream` to write to from the context of `processobj`

**My question is:**

- Is this the right approach, or is there a better yet?
- I would like to get rid of the global variable `ostream`. Can I pass a user context to the `processobj` callback function to achieve this?

Thanks in advance,
Best regards,

Jelle

**Comment by arekbulski** [comment]
As far as I understand it, you are doing it right. The parse hook takes a context as parameter right? So you could put ostream into the context using Computed or something. But I dont think using global variables is wrong here.

**Comment by jelledevleeschouwer** [comment]
Ahaa, so basically something like:

```python
input_fmt = GreedyRange(Struct(
    "ostream"   / Computed(ostream),
    "id"        / Enum(Byte, A=1, B=2, C=3),
    "len"       / Byte,
    "data"      / Switch(this.id,
        {
            "A" : Array(this.len, Struct("ts" / Float64n, "t" / Float32n, "h" / Float32n)),
            "B" : Array(this.len, Struct("ts" / Float64n, "x" / Float32n, "y" / Float32n, "z" / Float32n)),
            "C" : Array(this.len, Struct("ts" / Float64n, "n" / Int16un)),
        }),
    ) * processobj, discard=True)
```

And then within `processobj`, I can refer to it?

```python
def (obj, ctx):
    print(f"{obj.id}", file=obj.ostream)
```

That did the job, thanks for your swift reply! I have to admit it does feel a bit awkward though, but I cannot come up with a better idea.

Thanks a lot, @arekbulski!

**Comment by arekbulski** [comment]
I think the ostream should be in ctx and not obj, right?

**Comment by jelledevleeschouwer** [comment]
As far as I can tell it got into the `obj`, not in the `ctx`.
