### ISSUE TITLE
Order check in equality operation for Conainer

### ISSUE THREAD

**Issue by ValaJeyhani** [construct/construct#926]
The documentation [here](https://construct.readthedocs.io/en/latest/api/lib.html#construct.lib.Container), mentions that equality doesn't check the order of the fields, which can become problematic if it is used to compare messages. 

Can order check be added to equality operation?

Thanks in advance!

**Comment by arekbulski** [comment]
No, not in the upstream version. This is by design. If you really want order checking then I suggest you copy paste the Container class into your project, modify it to your needs, and override construct imports with it.

**Comment by ValaJeyhani** [comment]
Thanks for your feedback.
