### ISSUE TITLE
Loop over table of offsets with RepeatUntil/Pointer

### ISSUE THREAD

**Issue by zcutlip** [construct/construct#927]
Not sure if this is a feature request, but report, or just a question, but a pattern I encounter quite a lot is a variation on:

- I have a table of offsets
- Each offset points to an object I need to parse
- I need a list of resulting objects
- `RepeatUntil` (or `Array`) + `Pointer` is _almost perfect_ for this except `Pointer` of course restores the stream position. So it processes the same offset value over and over.

Is there a recommended way of handling this?

It would be nice if there was something like an `IndirectPointer` that would take a subcon to parse the offset like:

```Python
"object" / IndirectPointer(Int32ul, object_parser)`
```

By processing the offset subcon first, the stream would advance before the `Pointer` seeks, allowing it to restore the position of the next offset in the table.

And then you could walk the offset table like: 

```Python
"object_list" / RepeatUntil(
    lambda obj, lst, ctx: len(lst) >= ctx.header.obj_count,
    IndirectPointer(Int32ul, object_parser)
)
```

I haven't thought through how this would work the building side, since I'm only parsing.

Thanks!

**Comment by arekbulski** [comment]
Instead of an Array to parse everything at once, use a Pointer in a normal loop to parse one element at a time.

**Comment by zcutlip** [comment]
So you're saying to just use normal Python procedural logic to first parse out the list of offsets, then loop over that list, building a list of objects parsed by a `Pointer`?

Something like:
```Python
def obj_list():
    offsets =  Array(object_count, Int32ul).parse_stream(stream)
    objects = []
    for offset in offsets:
        obj = Pointer(offset, object_parser).parse_stream(stream)
        objects.append(obj)
    return objects
```

I'd hoped to keep it all in `construct`'s declarative syntax, but this solves the problem.

Thanks.

**Comment by arekbulski** [comment]
Yeah you are doing it right. Not as declarative as one would like but it works. Right?

**Comment by zcutlip** [comment]
Yes that works. thank you!

**Comment by zcutlip** [comment]
Thanks! Actually there are a number of interesting patterns in there. Looking forward to exploring further.

**Comment by arekbulski** [comment]
DC3 uses construct, oh wow.
