### ISSUE TITLE
Problem parsing struct with RawCopy and BitsInteger

### ISSUE THREAD

**Issue by thomas-nilsson-irfu** [construct/construct#928]
I am fairly novice in regards to using this package so please forgive me if this is a stupid question.

I was trying to make use of `RawCopy` in a `construct.Struct` (as partly discussed in making the `CheckSum` work in the old issue 813 here on github and it was recommended to use multiple RawCopy in comment in issue 774), but I'm unable to get it working properly..

It appears to me that the `RawCopy` does not fully respect the bit sizes of my defined struct. (My total struct is rather complicated but I highlight with simplified example below).

Example of the problem I run into:
```python3
d = RawCopy(construct.Struct("a"/Byte, "b"/Byte))  # two bytes in a simple struct
d.parse(b"\xff\x00")  # parse two bytes of data
# gives expected result just fine:
 Container(data=b'\xff\x00', value=Container(a=255, b=0), offset1=0, offset2=2, length=2)

# Now for the problematic one
d = RawCopy(construct.Struct("a"/Byte, "b"/BitsInteger(4), "c"/BitsInteger(4)))  # same total size, 2 bytes in total
d.parse(b"\xff\x00")  # try to parse two bytes of same data result in error:
Traceback (most recent call last):
...(omitted a lot of debug)...
  raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> b
stream read less than specified amount, expected 4, found 1

# it apparently requires a lot more bytes now 
d.parse(b"\xff\x01\x02\x03\x04\x05\x06\x07\x08")
# which parses but it is not really what I would have expected given that the Struct consists of "a"=1Byte, "b"=4bit & "c"=4bit. 
Container(data=b'\xff\x01\x02\x03\x04\x05\x06\x07\x08', value=Container(a=255, b=14, c=62), offset1=0, offset2=9, length=9)
```

Am I completely misunderstanding what this `RawCopy` is supposed to do (the documentation contains a line "Size is same as subcon." which does not appear to be the case for me)?

Any help or insight any one of you may be able to provide would be much appreciated!

**Comment by arekbulski** [comment]
No worries. Everyone asks silly  questions at some point. We are all novices at something.

You cannot use BitsInteger outside of Bitwise.

**Comment by thomas-nilsson-irfu** [comment]
Dear @arekbulski,
Ah.. I see, thanks a lot!
