### ISSUE TITLE
Checksums without Embedded

### ISSUE THREAD

**Issue by Schwaneberg** [construct/construct#929]
Hi!

I want to compute a checksum over several fields without being forced to put them in a named substructure.
I am forced to put all variables in a named substructure if I use `RawCopy`:

```python
import hashlib
d = Struct(
    "fields" / RawCopy(Struct(
        "var_1" / Default(Byte, 0),
        "var_2" / Default(Byte, 0),
        "var_n" / Rebuild(Byte, some_method),
    )),
    "checksum" / Checksum(Bytes(64),
        lambda data: hashlib.sha512(data).digest(),
        this.fields.data),
)
d.build(dict(fields=dict(value={})))
```

Instead, I'd like to get the content (in bit or byte mode) with some functionality like `StreamSpy` in this example:

```python
import hashlib
d = Struct(
   "__start" / Tell,
    "var_1" / Default(Byte, 0),
    "var_2" / Default(Byte, 0),
    "var_n" / Rebuild(Byte, some_method),
    "__end" / Tell,
    "checksum" / Checksum(Bytes(64),
        lambda data: hashlib.sha512(data).digest(),
        StreamSpy(this.__start, this__end)),
)
d.build(dict(fields=dict(value={})))
```

Is there any way to do something like this yet?
Thank you in advance.

**Comment by arekbulski** [comment]
Well, let me complain myself a little first. Your complaint is that a RawCopy needs to be named, and yet you are perfectly happy to replace it with two named Tell-s and several named subfields. RawCopy was created to serve exactly this kind of scenario. I see no reason why not to use it.

That said, if you really want it: you can implement StreamSpy on your own with 5-10 lines of code. Feel free to submit a PR once you have a working implementation. Look at Pointer class for some guidance.

**Comment by Schwaneberg** [comment]
Thank you for that fast response! 
In fact, I already implemented it but struggled with getting the parameters as path "this['__start']" instead of receiving the actual integer value.

A little background: We provide an extension of the Robotframework that reads packet definitions from XML files and converts them to construct.Struct objects. These objects are used to communicate with embedded systems under test via multiple buses.
Our testers write tests like this:

```robot
Some Test
    ${timestamp}=    get time
    send message    PKT_EXAMPLE    var_1=42    var_2=4711
    assert message received    after=${timestamp}    timeout=100ms    PKT_RESPONSE    var_n=1337
```

So, PKT_EXAMPLE is mapped to some construct.Struct object. The variables `var_1` and `var_2` are put into a construct.Container(var_1=42, var_2=4711) and this will be used to build the message. We do have some translation in our software. E.g., if a variable is nested in an Array, we use semantics like `N_ITER->M_ITER(1)->Var(1)=1` which translates to `{"N_ITER" [{"M_ITER": [{"Var": 1}]}]}`. Variables that are just part of a checksum computation should be directly addressable. I could also dynamically add names like "_crc_001" and hide that via translation, but I don't really like to.

BTW: We use don't use construct.Checksum, because we need more flexibility. Instead we use something like `"CRC32" / Rebuild(Int32ub, lambda ctx: calc_checksum(ctx, spy.payload, attribute="CRC32", poly=0x12345, init=0, xor=0xffffffff, input_reflection=True, output_reflection=True, num_bits=32))`, were `calc_checksum` scans ctx for "CRC32" and will replace the computed value by a manually defined. Also, by setting parameters like CRC32=POLY(0x54321),INIT(54) we can dynamically replace the checksum computation parameters for each packet. If you like I can also try to transfer some of these functions to construct.Checksum and make a PR for this aswell.

**Comment by arekbulski** [comment]
The one thing I am interested in is how you solved the StreamSpy issue.

**Comment by Schwaneberg** [comment]
We are still using construct 2.8.12. The version that allowed embedding of BitStructs. We had an enhanced version of Struct named `PayloadStruct`. That kind of combined RawCopy and Struct that supplied the raw stream in a payload attribute.
You'll get my PR once I solved it for the current construct version.

**Comment by Schwaneberg** [comment]
I think I cannot implement StreamSpy as I need it. When working in bit mode and putting the struct in a Bitwise subconstruct like `Bitwise(Aligned(8, Struct(...)))`, the stream will automatically be converted to byte mode. So, I cannot define checksum areas that aren't byte aligned.

**Comment by arekbulski** [comment]
That is what you get when you embed bitstructs.

**Comment by Schwaneberg** [comment]
That is why we want to change things...

**Comment by Schwaneberg** [comment]
Yeah, but I cannot accept this limitation. Checksum fields are usually located directly behind their payload, which is often not byte aligned.

**Comment by arekbulski** [comment]
Well  then: RestreamedBytesIO has tell() so if both Tells and StreamSpy are inside bitwise it should work ok too.

**Comment by arekbulski** [comment]
Unfortunately, checksumming with Construct is very very rudimentary. Over the years, people have asked to do (more crazy) things like checksumming non contiguous segments or insert the checksum before or even inside the segment. In all those cases I deemed those schemes either too difficult or just impossible to implement.
