### ISSUE TITLE
read-the-docs broke

### ISSUE THREAD

**Issue by tomerfiliba** [construct/construct#93]
starting with https://readthedocs.org/projects/construct/builds/4389216/ the build broke.

btw, you asked me about construct 3 - the repo is at https://github.com/tomerfiliba/construct3

**Comment by arekbulski** [comment]
Thank you for showing me that builds page. Fixed the docstring into f-string. Passes.

**Comment by arekbulski** [comment]
In case you are still monitoring this thread, Tomer. Would you be willing to add me to construct account owners list? It would make my life easier. Same goes for readthedocs. I am taking good care of the project.
