### ISSUE TITLE
problem to access some named container values by dot

### ISSUE THREAD

**Issue by timrid** [construct/construct#931]
Hello again,

I've run into a problem when I try to have some special names for subcons in a `Struct` and access them in the parsed `Container` via the dot operator. Unfortunately this only works via the access with the square brackets.

The following example makes my problem clear I think:
```python
format = cs.Struct(
    "width" / cs.Int8ub,
    "height" / cs.Int8ub,
    "update" / cs.Int8ub,
    "search" / cs.Int8ub,
)
obj = {
    "width": 1,
    "height": 2,
    "update": 3,
    "search": 4,
}
obj = format.parse(format.build(obj))
print(f"obj.width =         {obj.width}")
print(f"obj['width']=       {obj['width']}")
print(f"obj.height =        {obj.height}")
print(f"obj['height'] =     {obj['height']}")
print(f"obj.update =        {obj.update}")
print(f"obj['update'] =     {obj['update']}")
print(f"obj.search =        {obj.search}")
print(f"obj['search'] =     {obj['search']}")
```

Output:
```
obj.width =         1
obj['width']=       1
obj.height =        2
obj['height'] =     2
obj.update =        <bound method Container.update of Container(width=1, height=2, update=3, search=4)>
obj['update'] =     3
obj.search =        <bound method Container.search of Container(width=1, height=2, update=3, search=4)>
obj['search'] =     4
```

I am aware of where the problem comes from, since these names already exist as methods in the container class. Unfortunately it is not so obvious which names cannot be used via the point operator. Also in the documentation I could not find any hint to this behavior.

Is this behavior intentional? For comparison: In the standard `dataclasses` module of Python, such helper methods were therefore intentionally made as module level functions (Here is an old discussion I found about that: https://github.com/ericvsmith/dataclasses/issues/8).

**Comment by arekbulski** [comment]
It is by design so Yes. If you look at the source, what is in slots cannot be accessed through attribute like this.
https://github.com/construct/construct/blob/master/construct/lib/containers.py#L86-L93

**Comment by arekbulski** [comment]
![Zrzut ekranu z 2021-05-21 21-43-30](https://user-images.githubusercontent.com/5385838/119190408-9a757780-ba7d-11eb-9525-5198822f4fa9.png)

**Comment by timrid** [comment]
All right. But shouldn't this at least appear as a note in the documentation with a listing of the not working names?

**Comment by arekbulski** [comment]
I agree. Will you PR the docs?

**Comment by timrid** [comment]
Yes, I try my best ;)

**Comment by timrid** [comment]
PR #933 is merged
