### ISSUE TITLE
implementation of GreedyBytesEx

### ISSUE THREAD

**Issue by timrid** [construct/construct#934]
Are there any plans to implement GreedyBytesEx mentioned in #701?

**Comment by arekbulski** [comment]
No. And the library is no longer actively developed so no no no.
You probably need to implement it yourself. I would appreciate if you pasted an impl here if you make one.

**Comment by timrid** [comment]
Okay, but would you accept a PR if I implement it by myself?

**Comment by arekbulski** [comment]
Not sure. But you could paste a recipe in this thread for other people to find.

**Comment by timrid** [comment]
I thought a bit more about the `GreedyBytesEx` approach. With this it would be easy to create a footer like this:

```python
d = Struct(
    "data" / GreedyBytesEx(endoffset=-2),
    "footer" / Bytes(2)
)
```

But what if you have e.g. `Compressed` data first, followed by a footer. Then `Compressed` (or the base class `Tunnel`) would also have to get an `endoffset` parameter, since `Tunnel` itself also behaves "greedy".

```python
d = Struct(
    "compressed_data" / Compressed(GreedyBytes, "zlib", endoffset=-2),
    "footer" / Bytes(2)
)
```

Therefore I think it would be better to define a new construct like `OffsettedEnd`, which is implemented similarly to FixedSized and can be used as follows:

```python
d = Struct(
    "data" / OffsettedEnd(-2, GreedyBytes), 
    "footer" / Bytes(2)
)
d = Struct(
    "compressed_data" / OffsettedEnd(-2, Compressed(GreedyBytes, "zlib")), 
    "footer" / Bytes(2)
)
```

What do you think about it?

**Comment by arekbulski** [comment]
I think I must have been stupid and or drunk when I promised to implement GreedyBytesEx. On second thought the whole idea is bollocks and should be abandoned and go straight to trash. The more you ask about it the less sense it makes.

**Comment by timrid** [comment]
And what do you think about the approach with `OffsettedEnd`?

For this I have a concrete usage scenario where I have my own `Tunnel` for an AES encryption followed by a MAC (i.e. the footer). However, there is no length field that says how much data is used for the AES encryption. This can only be calculated from the total length of the stream minus the length of the MAC.

**Comment by arekbulski** [comment]
I have no clue what the semantics for it would be but, why are you asking me about it? The whole Construct package was designed to be extendable with your own classes (and also adapters) so if you need it then just go for it? I only ask that you share with me (us?) the code so I can get a little wiser.

**Comment by timrid** [comment]
When I just asked the code to `OffsettedEnd` did not exist yet, but just the idea how to use it. I just wanted to hear if you might have an alternative idea that solves the problem even better / more elegantly...

Now I implemented `OffsettedEnd` and it works fine:

```python
class OffsettedEnd(Subconstruct):
    r"""
    Parses all bytes in the stream till EOF plus endoffset is reached.

    This is useful when GreedyBytes (or an other greedy construct) is followed by a fixed-size footer.

    Parsing determines the length of the stream and reads all bytes till EOF plus `endoffset` is reached, then defers to subcon using new BytesIO with said bytes. Building defers to subcon as-is. Size is undefined.

    :param endoffset: integer or context lambda, only negative offsets or 0 are allowed.
    :param subcon: Construct instance

    :raises StreamError: could not read enough bytes
    :raises StreamError: reads behind the stream (if endoffset is positive)

    Example::

        >>> d = Struct("data"/OffsettedEnd(-2, GreedyBytes), "footer"/Bytes(2))
        >>> d.parse(b"\x01\x02\x03\x04\x05")
        Container(data=b'\x01\x02\x03', footer=b'\x04\x05')
        >>> d.build(Container(data=b"\x01\x02\x03", footer=b"\x04\x05"))
        b'\x01\x02\x03\x04\x05'
    """

    def __init__(self, endoffset, subcon):
        super().__init__(subcon)
        self.endoffset = endoffset

    def _parse(self, stream, context, path):
        endoffset = evaluate(self.endoffset, context)
        curpos = stream_tell(stream, path)
        stream_seek(stream, 0, 2, path)
        endpos = stream_tell(stream, path)
        stream_seek(stream, curpos, 0, path)
        length = endpos + endoffset - curpos
        data = stream_read(stream, length, path)
        if self.subcon is GreedyBytes:
            return data
        if type(self.subcon) is GreedyString:
            return data.decode(self.subcon.encoding)
        return self.subcon._parsereport(io.BytesIO(data), context, path)

    def _build(self, obj, stream, context, path):
        return self.subcon._build(obj, stream, context, path)
```

Can be used like this:

```python
d = Struct(
    "header" / Bytes(2),
    "data" / OffsettedEnd(-2, GreedyBytes),
    "footer" / Bytes(2)
)
print(d.parse(b"\x01\x02\x03\x04\x05\x06\x07"))
```
```
Container: 
    header = b'\x01\x02' (total 2)
    data = b'\x03\x04\x05' (total 3)
    footer = b'\x06\x07' (total 2)
```

**Comment by arekbulski** [comment]
I merged it.
