### ISSUE TITLE
Header with byte counts of sections of GreedyRanges

### ISSUE THREAD

**Issue by henriquegemignani** [construct/construct#937]
Context: I'm parsing a data format that I can't change (modding an old commercial game)

The file format has a list of "data sections" at the start of the file, with first a count of data sections followed by the size of each in bytes. These data sections are used to different things, including a few arrays whose count depends on the section size.

I currently can parse (and re-build to the same binary!) with the following code:

```python
def DataSection(subcon):
    def get_section_length(context):
        root = context["_root"]
        index = root["_current_section"]
        root["_current_section"] += 1
        return root.data_section_sizes[index]

    return FixedSized(get_section_length, subcon)


Example = Struct(
    flags=Int32ub,
    data_section_count=Rebuild(
        Int32ub,
        lambda context: len(context.material_sets) + len(context.attrib_arrays) + context.surface_header.num_surfaces,
    ),
    material_set_count=Int32ub,
    data_section_sizes=Array(construct.this.data_section_count, Int32ub),
    _=AlignTo(32),
    _current_section=construct.Computed(lambda this: 0),
    material_sets=Array(construct.this.material_set_count, DataSection(MaterialSet)),
    attrib_arrays=Struct(
        positions=DataSection(GreedyRange(Vector3)),
        colors=DataSection(GreedyRange(Color4f)),
        uvs=DataSection(GreedyRange(Vector2f)),
        lightmap_uvs=If(
            construct.this._root.flags & 0x4,
            DataSection(GreedyRange(Array(2, Float16b))),
        ),
    ),
    surface_header=DataSection(Struct(
        num_surfaces=Rebuild(Int32ub, construct.len_(construct.this.offsets)),
        offsets=Array(construct.this.num_surfaces, Int32ub),
    )),
    surfaces=Array(
        construct.this.surface_header.num_surfaces,
        DataSection(Surface),
    ),
)
```

`MaterialSet` and `Surface` definitions don't matter, except that the later uses a GreedySequence, while the former doesn't use any Greedy class.

My current solution is obviously sub-optimal because I need to fill `data_section_sizes` manually which is just pretty bad. The way it depends on changing the `_current_section` value as it parses sounds wrong too.

Any suggestions on how I could improve this?

**Comment by arekbulski** [comment]
It seems to me that the format is just too convoluted for its own good. No obvious improvements that I can suggest.

**Comment by jpsnyder** [comment]
Take a look at the `Iter` recipe found here: https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/mwcp/utils/construct/helpers.py#L978
Perhaps that could be helpful.

**Comment by henriquegemignani** [comment]
That looks interesting, but not really sure how to use it here.

I found an ugly work around. It ignores the value at first, but saves the stream offset and then I use it with a `Prefixed(Pointer())`.

```python

def DataSectionSizes(section_count):
    return Array(section_count, FocusedSeq(
        "address",
        address=Tell,
        value=construct.Seek(4, 1),
    ))


def DataSection(subcon):
    def get_section_length_address(context):
        root = context["_root"]
        index = root["_current_section"]
        root["_current_section"] += 1
        return root._data_section_sizes[index]

    return Prefixed(Pointer(get_section_length_address, Int32ub), subcon)

```

**Comment by henriquegemignani** [comment]
The data structures I'm handling have a lot of some header structures that determines the number of bytes or elements later on.
While just parsing is rather simple, building these is trickier.
My "solution" for these so far is abusing Pointer to update these fields when the actual data is built later on.

For anyone who comes across this issue in the future and is curious: https://github.com/henriquegemignani/Retro-data-structures/blob/main/retro_data_structures/data_section.py#L21

**Comment by arekbulski** [comment]
Sorry I could not be more of help. If you ask me about the core classes, sure I can elaborate. But your classes are too custom tailored for me to know anything about.

**Comment by henriquegemignani** [comment]
No worries, I haven't asked more because in general things are too specific to my use case to be relevant.

If I need to deal with compilation for performance, I might take pieces where I wrote custom construct classes and ask for best practices.
