### ISSUE TITLE
Version numbers/tags mismatch

### ISSUE THREAD

**Issue by Lekensteyn** [construct/construct#94]
Something went wrong in the release process.

- tag v2.5.4 actually contains v2.5.3 in construct/version.py
- tag v2.6.1 actually contains v2.5.4 in construct/version.py

It seems that at some point in the past, the v2.5.4 tag pointed to a different source (which is now called v2.6.1). I observed this issue because the python-construct 2.5.4-1 [package][1] in Arch Linux somehow had no "Magic" class (replaced by `Const`) while the documentation and source repo says otherwise.

What happened? (The tag description is not very extensive.) Semver breakage that had to be "quickly" patched?

 [1]: https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/python-construct

**Comment by arekbulski** [comment]
Entire 2.6 line is beta and API changes are significant. Docstrings are pretty much up to date but docs are not. I will put out a new release today. I reverted the stable releases to a point before API changed.

**Comment by arekbulski** [comment]
Releases 2.6.1 and 2.6.2 removed, and new beta out. Also 2.5.5 released with fixed version.py.

**Comment by arekbulski** [comment]
> Semver breakage that had to be "quickly" patched?

Yeah, it had to be patched. Quickly.

**Comment by arekbulski** [comment]
Arch distribution should "revert" to 2.5.5 which is the newest release on pypi and newest stable on GitHub.

**Comment by Lekensteyn** [comment]
Maybe you need to clarify the status of 2.6.x. The README currently says:
> There are ongoing API and implementation changes. Please use either stable 2.5.x or the beta 2.6.x or wait for a stable 2.7.

What about:
> There are ongoing API and implementation changes which happen on the 2.6.x series. Do not use this in production, stick to the 2.5 series instead or wait for a stable 2.7.

The tag messages could also use some more emphasis to avoid users from taking the "wrong" version.

I'll file a bug with Arch about the current version.

**Comment by arekbulski** [comment]
The releases are marked as beta and have complete description. 

Thank you for taking it to arch.

**Comment by Lekensteyn** [comment]
Well, "Ongoing architectural changes to API and reimplementation" looks like an improvement, not necessary beta :-)

Arch bug is filed at https://bugs.archlinux.org/task/50731

**Comment by arekbulski** [comment]
Docs updated.
