### ISSUE TITLE
How to properly read bits mixed with little-endian integers?

### ISSUE THREAD

**Issue by andrey-yantsen** [construct/construct#940]
I have some network Little-Endian data, my problem with a couple of bytes: `03 40` — in reality, those should represent a 14-bit integer and 2 booleans. The flags are in the highest 2 bits of the second byte, in this case — they're `true` and `false` respectively, while the int value is `3`.

Basically, I need to read the first 8 bits, add to those next 6 bits with SHL 8 and the rest 2 highest bits are the flags.

I tried some strange combinations of `BitsSwapped` and `reverse=True`, and had no luck.

P.S. I tried to use `Computed` to manually combine the value, but the context is empty for `BitStruct`, is it expected?

**Comment by arekbulski** [comment]
I dont see why you cannot just use BitsInteger and Flag-s inside a Bitwise context. Forgive me asking but did you even bother to read the main documentation, the bit-byte chapter?

**Comment by andrey-yantsen** [comment]
Yeah, I did, but I still don't realize how to do this, sorry :( 

```
>>> construct.BitStruct(
  'number' / construct.BitsInteger(14),
  'flag1' / construct.Flag,
  'flag2' / construct.Flag
).parse(b"\x03\x40")
Container(number=208, flag1=False, flag2=False)
```

```
>>> construct.BitsSwapped(construct.BitStruct(
  'number' / construct.BitsInteger(14),
  'flag1' / construct.Flag,
  'flag2' / construct.Flag
)).parse(b"\x03\x40")
Container(number=12288, flag1=True, flag2=False)
```

**Comment by arekbulski** [comment]
Finally we are getting somewhere. If you are looking for little endian integers, BitsInteger has swapped param.
https://construct.readthedocs.io/en/latest/api/numerics.html#construct.BitsInteger
Flag takes only one bit so endianness does not apply. So what is wrong with it then?

**Comment by andrey-yantsen** [comment]
`Swapped` works only for the whole bytes, unfortunately:

```
little-endianness is only defined if 14 is multiple of 8 bits
```

**Comment by arekbulski** [comment]
Ahh yes. I totally forgot about this. Endianess is defined as reordering chunks of 8 bits, so if your number is not a multiple of 8 bits tough luck. You could use some custom Adapter to apply pseudo endianness.

**Comment by andrey-yantsen** [comment]
So, just to double-check if I understood you correctly — there's no built-in way to do what I want, and the best shot for me is to implement a custom `Adapter` for the bits magic, right?

**Comment by arekbulski** [comment]
If we are talking about some pseudo endianness then yes, a custom Adapter would be my suggestion.

**Comment by andrey-yantsen** [comment]
Got it, thank you! I'll share the adapter here later for future generations.

**Comment by andrey-yantsen** [comment]
After all, the only thing I needed — is a good night sleep. Sorry. Simple `ByteSwapped` did the trick.

```
construct.ByteSwapped(construct.BitStruct(
  'flag2' / construct.Flag,
  'flag1' / construct.Flag,
  'number' / construct.BitsInteger(14),
)).parse(b"\x0e\x42")
```
