### ISSUE TITLE
Error parsing paths on a virtual filesystem

### ISSUE THREAD

**Issue by A6GibKm** [construct/construct#941]
I am using pykeepass from inside a Flatpak environment, and when trying to save on a virtual filesystem (e.g. Google Drive on GNOME). 

I get an error of type `construct.core.StreamError` with message `Error in path (building) -> header`. The path of such file is of the form
```
/run/user/1000/gvfs/google-drive:host=domain.com,user=xxxxxx/aosifj--IDAKSK/ASNsakdsuMOS_asoiamaoSKFN
```

**Comment by arekbulski** [comment]
It is doubtful that this is a bug in the core library. You should report it to pykeepass?

**Comment by A6GibKm** [comment]
Just now: https://github.com/libkeepass/pykeepass/issues/266
