### ISSUE TITLE
Meta: use AwkwardForth to improve performance

### ISSUE THREAD

**Issue by agoose77** [construct/construct#942]
When I last properly used construct (which was several years ago!) there was a plan to compile structs into imperative code.
I recently used AwkwardForth to generate a parser that can read binary data. AwkwardForth is a Python-exposed Forth VM. In the Scikit-HEP ecosystem, it will be used by [uproot](https://github.com/scikit-hep/uproot4/) to read ROOT files whose structures are not known at compile time.

I wonder whether something like AwkwardForth would be useful for construct. This library could generate code for a Forth VM, which would then read the data without any of the Python overhead. If it's of any interest, [here's a paper on AwkwardForth](https://github.com/jpivarski-talks/2021-05-17-vchep-awkward-forth/blob/main/main.pdf), and [here is the current documentation](https://github.com/scikit-hep/awkward-1.0/wiki/AwkwardForth-documentation).

I've used it to [read MIDAS tape data](https://github.com/agoose77/midas-tape/blob/master/src/midas_tape/__init__.py).

**Comment by arekbulski** [comment]
Compilation was added to construct years ago. See docs:
https://construct.readthedocs.io/en/latest/compilation.html
