### ISSUE TITLE
BitStruct Little Endian

### ISSUE THREAD

**Issue by gek47** [construct/construct#943]
The following 4 byte bit field is little endian b'\x1F\x19\xC3\x79' the BitStruct description includes both Flags and BitsIntegers that are across byte boundaries.  How do I tell BitStruct that the stream is LE?  Seems like something like the following must happen.  Convert to big endian than apply BitStruct.
Thank You

**Comment by arekbulski** [comment]
Neither Struct not Bitwise have any notion of endianness. Maybe use ByteSwapped wrapper?
