### ISSUE TITLE
struct field index cannot be this._index

### ISSUE THREAD

**Issue by whklhh** [construct/construct#948]
My English is bad, sorry.
I have a data like:
{
  [1, 2], // len_payload1 and len_payload2
  [ 'a' ], // payload1
  [ 'bb' ], // payload2
}
which serialized to "\x01\x02abb"
When I parse it, it raise "TypeError: list indices must be integers or slices, not Path".
Code is :
```python
import construct as cs
s = cs.Struct("len"/cs.Array(2, cs.Int8un), "payload"/cs.Array(2, cs.Bytes(cs.this.len[cs.this._index])))
s.parse(b"\x01\x02abb")
```
the number of payload is unknown in real, which is 2 in sample.
Did I write the wrong code?

**Comment by arekbulski** [comment]
The problem is in Bytes:
```py
cs.Bytes(cs.this.len[cs.this._index])
```
Indexes do not work in this expressions, see docs:
https://construct.readthedocs.io/en/latest/meta.html#known-deficiencies
Use something like:
```py
>>> lambda this: this.list[this.index]
```
Alternative solution would be to use individual fields, not arrays.
