### ISSUE TITLE
Incorrect fields passed to Adapter

### ISSUE THREAD

**Issue by mhsjlw** [construct/construct#95]
I've got code like this:

```python
class AddressAdapter(Adapter):
  def _encode(self, obj, context):
    print(obj.address)
    inet = obj.address.split(".")
    return Container(byte1=inet[0],byte2=inet[1],byte3=inet[2],byte4=inet[3])

  def _decode(self, obj, context):
    print(obj)
    return str(((~obj.byte1)) & 0xff) +"."+ str(((~obj.byte2 & 0xff))) +"."+ str(((~obj.byte3) & 0xff)) +"." + str(((obj.byte4) & 0xff))

address = AddressAdapter(
    Struct("address",
        SBInt8("byte1"),
        SBInt8("byte2"),
        SBInt8("byte3"),
        SBInt8("byte4")
    )
)

AddressPort = Struct("address_port",
  SBInt8("version"),
  Embed(address),
  UBInt16("port")
)
```

But when called like this `AddressAdapter.build(Container(version=4, address="127.0.0.1", port=4123))` it throws an incorrect type error? Any ideas?

**Comment by arekbulski** [comment]
Look at `obj.address.split(".") ` if obj is a string then split returns a list of strings, not a list of ints which is what the struct would require to build. Also this could be done with an array so you can just pass a list without putting it into named keys. I will provide an example in a moment.

**Comment by arekbulski** [comment]
I added this to the test suite. Works OK.

```py
class AddressAdapter(Adapter):
  def _encode(self, obj, context):
    return map(int, obj.split("."))
  def _decode(self, obj, context):
    return "{0}.{1}.{2}.{3}".format(*obj)

AddressPort = Struct("address_port",
    SBInt8("version"),
    AddressAdapter(Array(4, Byte("address"))),
    UBInt16("port"),
)
self.assertEqual(AddressPort.parse(b"\x04\x7f\x00\x00\x01\x10\x1b"), Container(version=4)(address="127.0.0.1")(port=4123))
self.assertEqual(AddressPort.build(dict(version=4, address="127.0.0.1", port=4123)), b"\x04\x7f\x00\x00\x01\x10\x1b")
```

**Comment by arekbulski** [comment]
I should point out that this is based on HEAD code. If you are using the stable 2.5 version then, well, a lot has changed since then.

**Comment by mhsjlw** [comment]
Ah, thanks a lot. Is there an expected release date for the HEAD? Or should I just be installing from the HEAD?

**Comment by arekbulski** [comment]
I put out beta releases at some random points in time but feel free to use HEAD.

**Comment by mhsjlw** [comment]
How does `AddressAdapter(Array(4, Byte("address")))` if there is name overlapping?

**Comment by arekbulski** [comment]
How does it work? Both adapters and Arrays take the name of its subcon, so `address` is used as a name for the outmost adapter. Is that what you asked?

**Comment by mhsjlw** [comment]
Sorry, no. I meant when you have something like this `Array(10, Embed(address_port))` how do you differentiate each port when we're doing things the way we are?

**Comment by arekbulski** [comment]
I dont think using Embed within Array makes any sense. You can use `Array(10, address_port)` just fine. Provide a list of dicts, 10 items long during building. And you get a list of dicts during parsing.

**Comment by arekbulski** [comment]
```py
one = dict(version=4, address="127.0.0.1", port=4123)
self.assertEqual(Array(2,AddressPort).build([one, one]), b'\x04\x7f\x00\x00\x01\x10\x1b\x04\x7f\x00\x00\x01\x10\x1b')

```

**Comment by mhsjlw** [comment]
Wow, I'm creating a lot of test cases here... :smile:

**Comment by arekbulski** [comment]
Oh please do.

**Comment by arekbulski** [comment]
Ah I think you meant how to put many instances into an array. All the `Array Range ...Range` classes take lists or iterables when building.

**Comment by mhsjlw** [comment]
Yeah, perfect, thanks
