### ISSUE TITLE
post processing into string

### ISSUE THREAD

**Issue by Dirt-Nasty** [construct/construct#950]
Is there a way to post process an item after it's been parsed?  Example

Basically my use case is that after parsing the value is a byte string and I want to do a conversion on it and store it in the container with that value.  Is it possible to do it in place?  I've seen other examples of post processing but it looks like they always reference a different item in the container.

```
def post_process(item):
    return str(PublicKey(item))

LAYOUT = cStruct(
    "address" / post_process(Bytes(32)),
)
```

This works below but I'd rather discard the original value and just keep the processed one in place instead of having two fields.

```
  'rawpoolCoinTokenAccount'/ PUBLIC_KEY_LAYOUT,
  'poolCoinTokenAccount' / Computed(lambda this: convert_public_key(this.rawpoolCoinTokenAccount)),
```

**Comment by arekbulski** [comment]
You need an adapter. That is what you are asking.
https://construct.readthedocs.io/en/latest/adapters.html

There something called "on the fly" processing but the name is coincidental. Not what you need.
https://construct.readthedocs.io/en/latest/basics.html#processing-on-the-fly
