### ISSUE TITLE
Unable to use `this._subcons.<member>.sizeof()` when `<member>` is the result of a `Switch`

### ISSUE THREAD

**Issue by lethalbit** [construct/construct#951]
Hello,

So in using construct I found something that appears to be an issue, as one would expect it to work, however it causes the parsing to throw an exception, the minimal test case is as follows:

```py
foo = 'Thing' / Struct(
	'len'  / Int8ul,
	'type' / Int8ul,
	'data' / Switch(
		this.type, {
			1: Int8ul,
			2: Int16ul,
			3: Int24ul, 
		},
		Int32ul,
	),
	'dataLen' / Computed(lambda this: this._subcons.data.sizeof())
)

foo.parse(b'1234567890')
```

The resulting code throws an exception however when `this._subcons.data.sizeof()` is replaced with `this._subcons.type.sizeof()` it parses as expected.

This might have to do with the resultant type of `Switch` but initially expected it to 'just work', as nothing in the documentation eludes to otherwise.

**Comment by arekbulski** [comment]
What you did right: sizeof() method needs to be in a lambda, you got that right. This expression does not work with methods.

What you got wrong: The title is wrong. The <member> is a Switch class instance, not a parsing result of it.

The switch sizeof method call raises a SizeofError right? That is the correct behavior. You see, if you would look into the source code, you would see that sizeof() uses its own empty context and not the parsing or building context. The sizeof call looks for a "type" key, actually it calls the "this.type" this expression on the context, but... it calls it on its own empty context and not the parsing context. So it fails to look it up, hence an exception.

Maybe try using something like: `sizeof(**this)` ?

Best of luck. Sorry for the monthly delay in response.

**Comment by lethalbit** [comment]
Hey, sorry for the long delay in reply, it's been a heck of a year,

Yeah, so modifying `'dataLen' / Computed(lambda this: this._subcons.data.sizeof())` to `'dataLen' / Computed(lambda this: this._subcons.data.sizeof(**this))` works, thanks,
