### ISSUE TITLE
Is there a way around a raw construct

### ISSUE THREAD

**Issue by Frankkkkk** [construct/construct#952]
Hi,

I was parsing a protocol that is like so:

```python3
            "RemainingCapacity" / DivideBy1000(construct.Int16ub),
            "UserDefinedItems" / construct.Int8ub,
            "TotalCapacity" / DivideBy1000(construct.Int16ub),
            "loremipsum" / construct.Int16ub,
```
This works and "UserDefinedItems" is always evaluated to `2`.
However, in some cases, if "UserDefinedItems" is `4` instead of `2`, then the protocol is like so:

```python3
            "RemainingCapacity" / DivideBy1000(construct.Int16ub),
            "UserDefinedItems" / construct.Int8ub,
            "TotalCapacity" / DivideBy1000(construct.Int16ub),
            "loremipsum" / construct.Int16ub,
            "REAL_RemainingCapacity" / DivideBy1000(construct.Int24ub),  # < 24 bits instead of 16 bits
            "REAL_TotalCapacity" / DivideBy1000(construct.Int24ub),  # < 24 bits instead of 16 bits
```

And the first two fields `RemainingCapacity` and `TotalCapacity` do not contain useful information (set to `0xFFFF`). The real info is stored in the last two bigger fields.

What I'd like to do would be to have the same struct for both versions of the protocol: i.e. if `UserDefinedItems == 2` then the "RemainingCapacity" is the first field, else the second one.

I tried using `IfThenElse` on a `Peek` instead but was'nt able to make it work. So the temporary workaround was to use a "nasty" `If` and thus have 2 different structures depending on the proto: https://github.com/Frankkkkk/python-pylontech/blob/277ed51a5d46f591e82f4dde3d584f36a86ef4cb/pylontech/pylontech.py#L92

Would there be a way to make it work nicely without making a custom Construct ?

Many thanks for your hindsight and even more so for your very useful lib !
Cheers

**Comment by arekbulski** [comment]
Yes. How about you wrap the entire Struct with an Adapter that does this: it checks if the REAL fields exist and overwrites the other fields with them. That way, imperative code you write does not need to check it. 

Sorry for the monthly delay. Hope this gives you some useful insight into how things can be done.
