### ISSUE TITLE
How to parse a UUID

### ISSUE THREAD

**Issue by rossburton** [construct/construct#953]
I'm wondering if there's a neat way to parse a UUID from a series of bytes and return a `uuid.UUID` instance directly?

Currently, I have a `Bytes(16)` in my struct which I then manually pass to ``uuid.UUID(bytes=item.uuid)` but I'm thinking Construct can probably do that for me?

**Comment by arekbulski** [comment]
Of course it can. You need an Adapter.
https://construct.readthedocs.io/en/latest/adapters.html

**Comment by rossburton** [comment]
Perfect, thanks!
