### ISSUE TITLE
Old 2.8.12, Embeded build loosing initial context ...

### ISSUE THREAD

**Issue by wtc-peg** [construct/construct#956]
Hello all,
Is ther any advice about the problem explained below .. and its "eventual" paliative (inside update method of class Container) that seems to work ? 

```
def update(self, seqordict, **kw):
        if isinstance(seqordict, dict):
            for k, v in seqordict.items():
                """
                PEG Issue:
                - Loosing initial context (like args = {'rev': '5339'}, passed from first "format.build(obj, args)")
                - Using construct-2.8.12 ...  ;O|
                - This happens on build not on parse 
                - This happens on embeded subconst (Ok we should not use that ;O( ... 
                   but really to many dependent things to upgrade on 2.10 without embeded)
                - When it happens, debugging the upper '_' member, seems to point on itself. 
                  Consequently, its initial context (args) is lost
                
                Palliative that seems to work:
                The single line below is replaced with next 4 lignes  : 
                self[k] = v
                """
                if isinstance(v, Container):
                    self[k] = v.copy()
                else:
                    self[k] = v
        else:
            for k, v in seqordict:
                self[k] = v
        dict.update(self, kw)
```

**Comment by arekbulski** [comment]
Sorry, I dont understand what you are asking.

**Comment by wtc-peg** [comment]
So realy sorry, I did not start the request properly.
I should have start by the problem rather then an hypothetic solution.

Unfortunately this problem concerns version 2.8.12 (The full code as got a lot of embedded).

What I want to is using a context parameter that I transmit to the Format. 
The same, when I parse or when I build. Target is having some "version or other parameters, dependant things to do".

So in the join exemple, I want to use a passed context key/value, the same when I Parse or Build.
Parse works fine, Build fails with an error , dict (with "var" key) from initial context desappears ...

[PEGTest.zip](https://github.com/construct/construct/files/7693792/PEGTest.zip)

**Comment by arekbulski** [comment]
Well, the version of concern is so old that I do not see any point supporting it. You are using Embedded to your own detriment and yours alone.

**Comment by wtc-peg** [comment]
Sniff !!!
That's a pity for us... At the beginning construct usage was just for a try and exemples given to customers.
But it became bigger and bigger and also more and more used ...

https://github.com/Watteco/Codec-Report-Standard-Python/tree/main/srcWatteco

**Comment by arekbulski** [comment]
Yeah I am sorry for not being able to help you. But for the library to become better and better, some stuff had to be removed so the project could move forward. I never *ever* said on this forum that using Embedded was a good idea. In fact I tend to discourage people from using it. But they use it anyway, what else, because "its easier this way". Well, there you have it.

**Comment by wtc-peg** [comment]
I understand very well your position and I'm aware of it from a long time ... your right, it's not a surprise ;O)
2 years ago I start minding about changing all this to v2.9... and it was ... quite cool.
Then I had a long stop and now so many things are developped using the current "let's say more flat" Container input or output of the codec. Then It would be very hard on our side to motivate all users to change their existing developments.

Just in case this could have a "quick" idea obout the problem, here is a simpler code showing the problem:

```
from construct import *

FrameCtrl = Struct(
	"EndPoint" / Byte,
 )
 
STDFrameOK = Struct(
	"FrameCtrl" / FrameCtrl,
	"Value" / Computed(2*this._.var)
)

STDFrameBuildFail = Struct(
	"FrameCtrl" / Embedded(FrameCtrl),
	"Value" / Computed(2*this._.var)
)

Args = dict(var=67)


# Works:
theObj=STDFrameOK.parse(b'\x11\x02',Args)
print(theObj)

# Works
theBytes=STDFrameOK.build(theObj,Args)
print(theBytes)


# Works:
theObj=STDFrameBuildFail.parse(b'\x11\x02',Args)
print(theObj)

# FAILS
theBytes=STDFrameBuildFail.build(theObj,Args)
print(theBytes)

```

**Comment by wtc-peg** [comment]
Hello,
Just to conclude with this post, and in case it would be of interest for any other.
I finally add something to avoid circular reference creation when building embededs.
This is in the updtae method from Container Class.
It is only a palliative, but seems to work in all my uses-cases.

```
    def update(self, seqordict, **kw):
        if isinstance(seqordict, dict):
            for k, v in seqordict.items():
                """
                PEG Issue: https://github.com/construct/construct/issues/956
                - Loosing initial context (like args = {'rev': '5339'}, passed from first "format.build(obj, args)")
                - Using construct-2.8.12 ...  ;O|
                - This happens on build not on parse 
                - This happens on embeded subconst (Ok we should not use that ;O( ... 
                   but really to many dependent things to upgrade on 2.10 without embeded)
                - When it happens, debugging the upper '_' member, seems to point on itself (circular reference). 
                  Consequently, its initial context (args) is lost

                Palliative that seems to work:
                The single line below has been changed to avoid circular reference : 
                self[k] = v
                """
                if not(isinstance(v, Container) and k == '_' and self == v):
                    self[k] = v
        else:
            for k, v in seqordict:
                self[k] = v
        dict.update(self, kw)
```

@arekbulski : Would it be possible to find a way to colaborate on our still increasing usage of Construct ? 
Like, helping us to port existing to 2.10 with maybe specific "things ?" to limit conséquence on existing resulting container structures, optimizing performances, Work on compilation capability ...


Best regards,

Pierre-emmanuel

**Comment by arekbulski** [comment]
Forgive me for getting back to you so late. I did not see your last question. Please do not think I disregarded it.

Of course you can ask for whatever support you need. Just know that the project is not actively developed anymore. I will offer you my expertise in whatever I can easily tell you, but new features? Not likely.

I will help you in transition if possible.

Compilation feature is already done, has been for years.
https://construct.readthedocs.io/en/latest/compilation.html
