### ISSUE TITLE
Parse dynamic message

### ISSUE THREAD

**Issue by onyxPC** [construct/construct#958]
Hello.
Sorry, but i used google translate.

I have frame: [ NumFields(u8) | NumDataBlocks(u8) | Fields | DataBlocks ]

[Fields]
Field size = U8
Field0 = 0x00 | U8
Field1 = 0x01 | U32
Field2 = 0x02 | char[10]
Field3 = 0x03 | double
etc...

[Data]
Block0 [Fields]
Block1 [Fields]
Block2 [Fields]
BlockN[Fields]

Examples(Fields = 2, DataBlocks= 3):
Fields: [Field0, Field1]
Data: Blocks0 [0xAA, 0xA5A5A5A5], Block1 [0x55, 0x5A5A5A5A], Block2 [0x00, 0x11223344]

Frame: [0x02, 0x03, 0x00, 0x01, 0xAA, 0xA5, 0xA5, 0xA5, 0xA5, 0x55, 0x5A, 0x5A, 0x5A, 0x5A, 0x00, 0x11, 0x22, 0x33, 0x44]

Field = Enum(Int8ub, Field0=0, Field1=1, Field2=2, Field3=3)

table = {
  Field.Field0 : Int8ub,
  Field.Field1 : Int32ub,
  Field.Field2 : Bytes(10),
  Field.Field3 : Float64b
}

main_parser = Struct (
   "NumFields" / Int8ub,
   "NumDataBlocks" / Int8ub,
   "Fields" / Array(this.NumFields, Field),
   ??????????
)

How parse it use "construct" ?
Thank you.

**Comment by arekbulski** [comment]
Sorry but you have to be more specific what is it that you want parsed? 

PS. I see no point using an enum just to map byte to byte-like enum.

**Comment by arekbulski** [comment]
Did you read the documentation, entirely?
https://construct.readthedocs.io/en/latest/index.html

**Comment by onyxPC** [comment]
Show me what a parser would look like that can parse this examples:

Examples1:
(Fields = 2, DataBlocks= 3):
Fields: [Field0, Field1]
Data: Blocks0 [0xAA, 0xA5A5A5A5], Block1 [0x55, 0x5A5A5A5A], Block2 [0x00, 0x11223344]
[0x02, 0x03, 0x00, 0x01, 0xAA, 0xA5, 0xA5, 0xA5, 0xA5, 0x55, 0x5A, 0x5A, 0x5A, 0x5A, 0x00, 0x11, 0x22, 0x33, 0x44]
exampleFrame1 =b"\x02\x03\x00\x01\xAA\xA5\xA5\xA5\xA5\x55\x5A\x5A\x5A\x5A\x00\x11\x22\x33\x44"

Examples2:
(Fields = 2 , DataBlocks = 1)
Fields: Field3, Field1
Data: Block 0 [0x0000000000000000, 0x11223344 ]

exampleFrame2 = b"\0x02\x01\x03\0x01\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x11\0x22\0x33\0x44"

I gave the description of the fields above.
The number of fields and the amount of data can change dynamically.

**Comment by arekbulski** [comment]
Sorry, if you have questions which the documentation does not cover then I will do my best to elaborate. But I am not going to do your work for you.

**Comment by onyxPC** [comment]
I am not asking you to do my work for me.
I ask you, as the author of the library, how this problem is solved.
When fields for parsing data are in a message.
What do you recommend? Can it inherit from **Construct** and accept this.Fields as input?

**Comment by arekbulski** [comment]
Sorry but you are not asking me a precise question. Can Construct parse your data? I bet it can. How about this?
```py3
main_parser = Struct (
	"NumFields" / Byte,
	"NumDataBlocks" / Byte,
	"Fields" / Array(this.NumFields, Field),
	"Blocks" / Struct("first"/Byte, "second"/Array(4, Byte), ),
)
```

**Comment by onyxPC** [comment]
main_parser = Struct (
	"NumFields" / Byte,
	"NumDataBlocks" / Byte,
	"Fields" / Array(this.NumFields, Field),
	"Blocks" / Array(this.NumDataBlocks, **_!!!Depends on "Fields"(Dynamic)!!!_** ),
)

Based on 'Fields', the 'Blocks' field should be parsed. Dynamically.
Matching Field -> Type parser in table:
table = {
Field.Field0 : Int8ub,
Field.Field1 : Int32ub,
Field.Field2 : Bytes(10),
Field.Field3 : Float64b
}

Maybe:
main_parser = Struct (
	"NumFields" / Byte,
	"NumDataBlocks" / Byte,
	"Fields" / Array(this.NumFields, Field),
	"Blocks" / Array(this.NumDataBlocks, MyDynamicParser(this.Fields, table)),
)

frame1 =b"\x02\x03\x00\x01\xAA\xA5\xA5\xA5\xA5\x55\x5A\x5A\x5A\x5A\x00\x11\x22\x33\x44"
result1 = main_parser.parse(frame1)

frame2 = b"\0x02\x01\x03\0x01\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x11\0x22\0x33\0x44"
result2 = main_parser.parse(frame2)

But I do not know from which class it is better to inherit MyDynamicParser:
Construct or Subconstruct ? 

P.S. I can't think of a way to use the available classes.

**Comment by arekbulski** [comment]
Inheriting from the 2 abstract classes, Construct and Subconstruct, is advanced stuff that you do not need. What you are asking makes no sense and makes it clear that you did not read or understood the documentation one bit.

**Comment by onyxPC** [comment]
I think you are not trying to understand what they are asking you.

frame1 =b"\x02\x03\x00\x01\xAA\xA5\xA5\xA5\xA5\x55\x5A\x5A\x5A\x5A\x00\x11\x22\x33\x44"
frame2 = b"\0x02\x01\x03\0x01\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x11\0x22\0x33\0x44"

Once I haven't read the documentation. Write one parser(main_parser) for these two frames.
So that print (result1) and print (result2) give the result as above.

**Comment by onyxPC** [comment]
How is it going ? Could you write a parser by reading the documentation?

I'll show you what happened with me:

```python
from construct import *

Field = Enum(Int8ub, Field0 = 0, Field1 = 1, Field2 = 2, Field3 = 3, Field4 = 4)

class DymamicSequenceArray(Construct):
    def __init__(self, count, fields, table, discard=False):
        super().__init__()
        self.count   = count
        self.fields  = fields
        self.table   = table
        self.discard = discard

    def _parse(self, stream, context, path):
        #count = evaluate(self.count, context)
        count = self.count(context) if callable(self.count) else self.count
        if not 0 <= count:
            raise RangeError("invalid count %s" % (count,), path=path)
        discard = self.discard
        table = self.table
		#fields = evaluate(self.fields, context)
        fields = self.fields(context) if callable(self.fields) else self.fields
        args = []
        for field in fields:
            args.append( table[field] )
        sequence = Sequence(*args)
        obj = ListContainer()
        for i in range(count):
            context._index = i
            e = sequence._parse(stream, context, path)
            if not discard:
                obj.append(e)
        return obj
    
    def _build(self, obj, stream, context, path):
        pass 

table = {
    Field.Field0 : Int8ub,
    Field.Field1 : Int32ub,
    Field.Field2 : Bytes(10),
    Field.Field3 : Float64b
}

main_parser = Struct (
    "NumFields" / Int8ub,
    "NumDataBlocks" / Int8ub,
    "Fields" / Array(this.NumFields, Field),
    "Blocks" / DymamicSequenceArray(this.NumDataBlocks, this.Fields, table),
)


frame1 = b"\x02\x03\x00\x01\xAA\xA5\xA5\xA5\xA5\x55\x5A\x5A\x5A\x5A\x00\x11\x22\x33\x44"
result1 = main_parser.parse(frame1)
print(result1)

frame2 = b"\x02\x01\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x11\x22\x33\x44"
result2 = main_parser.parse(frame2)
print(result2)
```
![Parser](https://user-images.githubusercontent.com/96735180/147604921-7c8525f8-f37f-45cb-94e0-ca53c6669809.png)

**Comment by arekbulski** [comment]
Okay... I see you managed to glue together some scrapes... so what is your question exactly?

**Comment by onyxPC** [comment]
Questions was:
1. How did the autor of the library do it?
2. Can you do the same using only classes from the library?
P.S. Any suggestions for improving the code or fixing it?

**Comment by arekbulski** [comment]
Point 1, I *am* the author of Construct. And I dont understand the question.
Point 2, hmm difficult question... I think writing your own class was the right way to go about it. You could refactor it, one way or another, but it does the job so.

**Comment by onyxPC** [comment]
Thank you.
Sorry if I was rude.
You library - COOL !!!
P.S. Do you plan to add such functionality in the future? Not to write your own classes.

**Comment by arekbulski** [comment]
What do you mean by "such" functionality?

**Comment by arekbulski** [comment]
Will I add "DymamicSequenceArray" to the core library? Definately not.

**Comment by onyxPC** [comment]
Why not ?
I would like to have a class that implements this functionality.
I'm not talking about my implementation. She's bad.
I would like to see your implementation of this functionality.
