### ISSUE TITLE
Select does not continue on parse exception

### ISSUE THREAD

**Issue by toreamun** [construct/construct#960]
Select should:   _Parses and builds by literally trying each subcon in sequence until one of them parses or builds without exception._

But if PascalString in a subcon fails with exception, it does not continue to the next subcon. Is this an error?

Example:
```
d = construct.Select(construct.PascalString(construct.Byte, "ascii"), construct.GreedyRange(construct.Byte))
d.parse(bytes.fromhex("060100000281ff"))
...
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 4: ordinal not in range(128)
```

**Comment by arekbulski** [comment]
Check this out for now:
https://github.com/construct/construct/issues/743

**Comment by arekbulski** [comment]
This is indeed a bug and will be fixed shortly. Please stay tuned.

**Comment by arekbulski** [comment]
Fixed.
