### ISSUE TITLE
Construct.sizeof connot calculate dynamic data

### ISSUE THREAD

**Issue by whklhh** [construct/construct#961]
```
S = cs.Struct(
    'data_size' / cs.Int8ul,
    'data' / cs.Byte[cs.this.data_size],
)
s = S.parse(b'\x01a')
S.sizeof(**s)
```
Version-2.10.67 will raise KeyError, while version-2.8 will not.
What am I doing wrong?

**Comment by arekbulski** [comment]
Sorry, the library is not under active development since years now so I cannot really tell why.

sizeof() method is very tricky to get right, especially when you put dynamic stuff into it like Ifs and Switches and such.

How about you just measure the bytes?
```py
data = b"\x01a with additional crap"
print(S.build(S.parse(data)) == 2)
```

**Comment by whklhh** [comment]
The subcons of the struct are correct. 
Just sizeof() method not work.
So if I cannot use sizeof(), is there any way to calculate the size?
like:
```
S = Struct(
    "StreamSize" / Int32ul,
    "data" / Prefixed(Int32ul, GreedyBytes)
)
s = S.parse(b"\x09\x00\x00\x00\x01\x00\x00\x00a")
s.data += b"b"
ss = S.build(s)
print(ss.hex())
```
I want to use Rebuild to auto update StreamSize.
Or I can only use a function to fix size?

**Comment by jpsnyder** [comment]
This is because the wrong context gets passed in when calculating `sizeof()`. 
This is something I fixed here, but never got in, and I imagine it is woefully out of date by now.

Basically, we would need to add better tracking of child contexts so we can use that to pass in the right context in during recursive `sizeof()` calls... if I'm remember it correctly.

**Comment by arekbulski** [comment]
I think we should be measuring the bytes length instead of using sizeof.
```py
len(S.build(S.parse(data)))
or
len(S.build(obj))
```

**Comment by whklhh** [comment]
Considering the container object don't have struct info, I understand.  
But it's not convenience to build subcons in a big and complex struct. Maybe we should make Tell() work in building?

**Comment by arekbulski** [comment]
Tell class does work both during parsing and building.

**Comment by whklhh** [comment]
Ok, I will try again later.
Thanks for your help.
