### ISSUE TITLE
How to have optional parts at start of stream / obtain stream length from context?

### ISSUE THREAD

**Issue by laf0rge** [construct/construct#963]
Sotty to abuse the issue tracker for questions.  Plese let me know if there's a mailing list or forum where questions should rather be addressed.

I frequently run into the problem of having to parse messages with a fixed-length trailer (e.g. 28 bytes) preceded by a variable length optional header.  So basically length of the "header" part is "any bytes in excess of the fixed trailer"

Using Struct('header'/Optional(GreedyBytes), 'trailer/'Bytes(28)) of course doesn't work as the GreedyBytes will grab all of the message.

What is the most elegant approach to solve this situation in Construct? 

One way that would work is if I could access the length of the binary stream to parse from the context somehow.  At that point I could do something like Struct('header'/Optional(Bytes(stream_len-28)), 'trailer/'Bytes(28)) or the like.

Thansk for your input.

**Comment by laf0rge** [comment]
ah nevermind, turns out I can use Optional(Bytes(this._.total_len-28))

**Comment by arekbulski** [comment]
If you read the sticker on main documentation site, it says clearly that the GitHub Issues is the forum to be used to ask questions. You are welcome to ask anything you want.
