### ISSUE TITLE
Building of Struct with variable-length size field before variable-length data

### ISSUE THREAD

**Issue by boozer2** [construct/construct#966]
I'm trying to parse and build a binary file using Structs similar to the following:
```
OneTypeOfThing = Struct(
    'SizeOfTheRestOfThisStruct' / VarInt,
    'TypeOfThing' / VarInt,
    'aBunchOfData' / PascalString(VarInt, "utf8"),
)
```
The first field in the Struct 'SizeOfTheRestOfThisStruct' needs to include the built size of everything after it in the Struct - both 'TypeOfThing' and 'aBunchOfData'. As you can see those are variable-length and as such have no pre-defined size, and can be tens of thousands of bytes.

Parsing works great, but for building is there a way to calculate the size automatically and have it be at the beginning of the struct? I tried using the combination of a Tell, a Default value for size, and a later Pointer to overwrite the size, but since even the size itself is a variable length, it sometimes overwrites fields after when building.

I tried using Rebuild but it doesn't look like that will work due to the variable-length fields within the data.

If use a RawCopy or two Tells around the data, I'm able to get the built length in a field AFTER the data, but I need it to be before since this is a well-defined, existing binary format.

Any suggestion for how to achieve this in a way that works for both building and parsing?

Thanks!

**Comment by arekbulski** [comment]
I think you could just use Prefixed?
https://construct.readthedocs.io/en/latest/tunneling.html#working-with-bytes-subsets

You are welcome.

**Comment by boozer2** [comment]
That solved the problem - I wrapped the Struct in Prefixed (and got rid of the first element) and it builds and parses perfectly. Thanks again.

```
OneTypeOfThing = Prefixed(VarInt, Struct(
    'TypeOfThing' / VarInt,
    'aBunchOfData' / PascalString(VarInt, "utf8"),
)
```
