### ISSUE TITLE
How do I use a nested ._index value properly

### ISSUE THREAD

**Issue by Unknownforce351** [construct/construct#967]
I'm parsing data files and I have the following snippet (from a much bigger Struct())

```
    data_definiton=Array(construct.len_(construct.this.data_offsets),
        Struct(
            s=Int64ul,
            size=Int32ul,
            offset=Int64ul,
        ),
    ),
```

In a later section of the same Struct(), the size value is relevant in terms of how many bytes are in that particular data section.  I'll do more with it later, but for now I just want to use Bytes(size) to capture each data section.

I've tried a whole bunch of different possibilities, but I'm a bit stuck here.

Below is what I "want", but it's not correct.

```
    data=Array(
        construct.len_(construct.this.data_offsets),
        Aligned(8,
            Bytes(construct.this.data_definiton[construct.this._index].size),
        ),
    ),
```

This errors with the fact that construct.this._index is a Path, not an int/slice.

Clearly I'm doing it wrong... How do I read the correct amount of Bytes per each size reference from the original section above that?

I can do them individually by just giving it a value to the index, but that's deterministic and the data files I'm parsing have different counts of these data sections.

**Comment by arekbulski** [comment]
This is easy, because I seen this problem more than once on this forum. Just use a lambda:
```py
Bytes(lambda this: this.data_definiton[this._index].size),
```
https://construct.readthedocs.io/en/latest/meta.html#known-deficiencies

**Comment by Unknownforce351** [comment]
Wow, glad it was so simple, I spend a good couple hours trying so many different combinations haha.  Thanks!
