### ISSUE TITLE
Selecting format depending on data

### ISSUE THREAD

**Issue by twam** [construct/construct#968]
Hello!

I'm trying to decode USB descriptors using formats defined in https://github.com/greatscottgadgets/python-usb-protocol/blob/master/usb_protocol/types/descriptors/standard.py. The configuration descriptor of a USB device consists of of many different descriptors which are concatenated.

Each descriptor starts with a length and a typ, e.g. (from https://github.com/greatscottgadgets/python-usb-protocol/blob/master/usb_protocol/types/descriptors/standard.py) like:
```
DeviceDescriptor = DescriptorFormat(
    "bLength"             / construct.Const(0x12, construct.Int8ul),
    "bDescriptorType"     / DescriptorNumber(StandardDescriptorNumbers.DEVICE),
...
```

My question is now, how can I parse this efficiently, so that I can reuse the format definitions for all descriptor types defined by the `usb_protocol` package. Basically it needs to check the second byte and then re-interpret starting from the first byte with a specific format definition.

Any hints or small examples are appreciated.

**Comment by arekbulski** [comment]
I do not understand the question. What would you want?

**Comment by twam** [comment]
A more concrete example. My FTDI USB serial converter has a configuration descriptor of 
```
09023700020100c000
0904000002ffffff02
07058102000200
07050202000200
0904010002ffffff02
07058302000200
07050402000200
```
I can parse this by
```
descriptor = bytes.fromhex('09023700020100c0000904000002ffffff0207058102000200070502020002000904010002ffffff020705830200020007050402000200')

ConfigurationDescriptor = Struct(
    "bLength"             / Const(9, Int8ul),
    "bDescriptorType"     / Const(0x02, Int8ul),
    "wTotalLength"        / Int16ul,
    "bNumInterfaces"      / Int8ul,
    "bConfigurationValue" / Int8ul,
    "iConfiguration"      / Int8ul,
    "bmAttributes"        / Int8ul,
    "bMaxPower"           / Int8ul,
)

InterfaceDescriptor = Struct(
    "bLength"             / Const(9, Int8ul),
    "bDescriptorType"     / Const(0x04, Int8ul),
    "bInterfaceNumber"    / Int8ul,
    "bAlternateSetting"   / Int8ul,
    "bNumEndpoints"       / Int8ul,
    "bInterfaceClass"     / Int8ul,
    "bInterfaceSubclass"  / Int8ul,
    "bInterfaceProtocol"  / Int8ul,
    "iInterface"          / Int8ul,
)

EndpointDescriptor = Struct(
    "bLength"             / Default(OneOf(Int8ul, [7, 9]), 7),
    "bDescriptorType"     / Const(0x05, Int8ul),
    "bEndpointAddress"    / Int8ul,
    "bmAttributes"        / Int8ul,
    "wMaxPacketSize"      / Int16ul,
    "bInterval"           / Int8ul,
    "bRefresh"           / If(this.bLength  == 9, Int8ul),
    "bSynchAddress"      / If(this.bLength  == 9, Int8ul),
)

fdtiSpecificFormat = Struct(
   "Config"/ConfigurationDescriptor,
   "Interface0"/InterfaceDescriptor,
   "Endpoint0"/EndpointDescriptor,
   "Endpoint1"/EndpointDescriptor,
   "Interface1"/InterfaceDescriptor,
   "Endpoint2"/EndpointDescriptor,
   "Endpoint3"/EndpointDescriptor,
   )

print(fdtiSpecificFormat.parse(descriptor))
```

However I don't want to predefine `fdtiSpecificFormat.parse`, but do this automatically
* by looking at the second byte of these substructs and then map the corresponding definition, e.g. if second byte is 0x04 use the `InterfaceDescriptor` and
* repeating until all bytes are consumed

I hope this makes it more clear.

**Comment by arekbulski** [comment]
After staring at this for a few hours, I think I can help you. Your question is misleading. You said and I quote "I don't want to predefine fdtiSpecificFormat.parse" but you did not define the parse method. The parse method is provided by the Struct class. What you meant is that you do not want to define the Struct, right? 

I see three courses of action:

- use GreedyRange, Struct, Peek, Switch, Computed
- use GreedyRange, Select
- write your own class for parsing

**Comment by twam** [comment]
> What you meant is that you do not want to define the fdtiSpecificFormat struct, right?

Yes!

I tried first with your first idea, but it's unclear to me how to use results of `Peek` for the `Switch`.
However using your second proposal was really easy and works quite well!

Big Thanks.
