### ISSUE TITLE
BitStruct Little Endian where Byte Boundaries are Violated

### ISSUE THREAD

**Issue by dcajacob** [construct/construct#969]
Is there a way to deal with fields that don't obey byte boundaries *and* need an endian swap? For example, this [document](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn031/apn031.pdf) describes a record format with a 32-bit header, followed by a 28 bit field. The 28 bit field and others that we'll ignore for now, are little endian and need to be byte swapped before evaluating. I know construct allows for this with fields that obey byte boundaries. Is there some way to deal with this that I am missing? It seems like you'd want to extract the 28 bits, pad it out, swap the bytes and mask off the 21 bits you need.

I can of course do this myself, but I was hoping there would be some canonical way to do it with construct.

Thanks.

**Comment by arekbulski** [comment]
Well, this question has been raised several times already. The problem with " fields that don't obey byte boundaries and need an endian swap " is that endianess is by definition a permutation of whole octets. If your field is not a multiple of eight bits, then by the damn definition, you cannot permute the bits and call it a "little endianess". Of course, you could just call it "a (custom) bit permutation", and I will be happy with that. 

Second issue is that, and I quote you again, in " fields that don't obey byte boundaries " is that such a field can be of little endianess. Consider a bitstruct with fields of 4+8+4 bits. Is the middle field obeying byte boundaries? No. Can it be little endian? Yes. If you meant fields that are not multi octets, then please use that kind of language. 

Please provide a concrete example of the format in question. I will do my best to provide some suggestions.

**Comment by dcajacob** [comment]
I think I understand your frustration. I wouldn't design a protocol or format this way, but I often have to deal with existing stuff like this. I've never used the term octet before, but I think I understand that it is less ambiguous than byte? Certainly when I say byte, I mean octet.

Here's a simplified example pulled from the document I posted before: We have an Int32ul followed by 28 bits that will be interpreted as an int, so we'll call that BitsInteger(28).

```
data = bytes.fromhex('249c10080e630620')

Fields = BitStruct(
    'field' / BitsInteger(28),
    Padding(4)
)

Record = Struct(
    'header' / Int32ul,
    'record' / Fields
)

Record.parse(data)
```

The trick is that "field" is treated by the creator of this format as if it were Little Endian. So, to actually extract the value I want, you need to extract the 28 bits, which construct does fine, but then you need to pad it out to a length that is multiple of 8 bits. In this case, that can be done by shifting by  4 bits to get 4 octets. Then you mask the result to return the desired 28 bits. See the example below that does the conversion correctly.

`htonl(field << 4) & (2**28 - 1)) # where htonl is byte swapping`

My hope is that there is some nice way to do this with construct, but I haven't found it so far. I do think that I can hack it using Adapters, so it's not a question of whether it can be done any way. I'm just trying to find out if I have missed some built-in way of doing this.

The given example is just a fraction of the real "record". There are other fields of varying lengths exceeding an octet, including 21, etc.

Here's a picture of the larger definition, just for clarification.

![image](https://user-images.githubusercontent.com/3210634/154863011-64c2656c-d102-4e40-a8ef-605a8c4eed8b.png)

**Comment by arekbulski** [comment]
"I've never used the term octet before, but I think I understand that it is less ambiguous than byte?" No. Byte means an octet (eight bits) that respects bytes boundaries. So it always starts at 0 or 8 or 16 bits etc. Its a narrower definition as it carries an additional connotation. 

What I pointed out is that "fields that do not respect byte boundaries" is a wider definition than "fields that are not multiple of 8 bits". First definition contains second definition, among others. 

"The trick is that "field" is treated by the creator of this format as if it were Little Endian." There. You are making the same mistake as before. Little Endian by definition applies only to multiple octets. You cannot call whatever you are doing with the bits, Little Endian. The document uses that term liberally, I know. But it does it wrongly and that does not mean you should do it too. I guess you could use the term Pseudo-little-endianness or some other weird name for it. 

Sorry that I was not very useful. But at least I hope I straightened out your definitions.

Adapters might not cut it. I would write a custom parsing class based on BitsInteger. Please, post your code once you have it working so I can learn from it. 

"I'm just trying to find out if I have missed some built-in way of doing this." No. The core library outright ignores such, forgive the bluntness, bullshit formats.

**Comment by arekbulski** [comment]
```py
htonl(field << 4) & (2**28 - 1)) # where htonl is byte swapping
```

Okay, so you do this:

- Read 28 bits from the stream
- Append 4 zero bits
- Convert bitstream into bytestream
- Swap bytes
- Convert bytestream into bitstream
- Cut off excess of 28 bits

Do I get that right?

**Comment by dcajacob** [comment]
```htonl(field << 4) & (2**28 - 1)) # where htonl is byte swapping```

Here's my interpretation:

- Field is 28 bits read from the stream, expressed as an int
- Append 4 bits (the left shift)
- Swap bytes (htonl is just a byte reversal, but it only works up to 32 bits, so I have scrapped that for another method)
- Mask off excess 4 bits

**Comment by arekbulski** [comment]
My approach uses bytes objects, your uses integers.

**Comment by arekbulski** [comment]
Just wanted to add that you can use helper functions from this module:
https://github.com/construct/construct/blob/master/construct/lib/binary.py

**Comment by arekbulski** [comment]
Why are you using Seeks? Just use one BitStruct (which is a Bitwise Struct) and BitsIntegers.

**Comment by arekbulski** [comment]
Post it with the adapters, the whole code? :)

**Comment by dcajacob** [comment]
That's part of the terrifying revelation: if you look at the worked examples in this [document](https://hexagondownloads.blob.core.windows.net/public/Novatel/assets/Documents/Bulletins/apn031/apn031.pdf), you'll see that you can't just slice up the bits as you would expect based on the diagram. for a non-byte-aligned field, you need to grab a chunk around it that is byte-aligned, swap that, and then bit slice / manipulate. See the PSR field as an example. In spite of the diagram, the preceeding nibble (0x2) is actually part of the PSR field. It took me a while to realize this, but the worked example shows it clearly.

So, the Seeks let me go back and grab the previous byte, which has part of the bits for the new field. Doing it all in a struct for this example is actually useful because it forces you to stay on byte boundaries.

The new Constructor I will make will hide the Seeks inside them so that this can all be done inside a BitStruct in a nicer way. Basically it will be a BitsInteger that allows byte-swapping because under the hood, it will do Seeks to ensure we've grabbed to byte boundaries before doing the swap and it will then do the appropriate bit manipulation. Fingers crossed ;)

By the way, I agree this is an insane way to design a format/protocol. But it exists and I need it. One of the many things I like about Construct is that if you can't do it out of the box, it's probably a bad idea to design a protocol/format that way. I also recently had to deal with another existing protocol that forced me to use the GreedyBytesEx hack someone else posted. It's funny because, while this particular record does this bending-over-backwards act to pack data efficiently, in other places they store a few bits in a Long, multiple times over...

"Post it with the adapters, the whole code? :)"
I will later this afternoon.

**Comment by arekbulski** [comment]
I was suggesting something like the following, plus adapters:
```py
RangeCmp = Bitwise(Struct(
    'header' / BitsInteger(32),
    'dopp' / BitsInteger(28, signed=True),
    'psr' / BitsInteger(36),
    'adr' / BitsInteger(32, signed=True),
    'psr_sig' / BitsInteger(4),
    'adr_sig' / BitsInteger(4),
    'prn' / BitsInteger(8),
    'locktime' / BitsInteger(21),
    'cn0' / BitsInteger(5),
    'glofreq' / BitsInteger(8),
))
```
As long as the fields do not overlap, you do not need seeking. Do they overlap?

**Comment by dcajacob** [comment]
Yep, that is what I had been working with from the start. However, it is not correct, because, as you say, the fields "overlap". And they overlap because the data needs to be byte-swapped to be interpreted correctly. That's why I said the diagram is misleading. But the worked examples make it more clear that you can't just naively slice the bits.

My new BitsInteger-derived Constructor will let you build the structure like you showed because internally, it will understand that  if the start and end of the bit-field don't end on byte boundaries, then it must seek those, then byte-swap on that expanded boundary, and finally shift and mask the result to get the desired bits.

**Comment by arekbulski** [comment]
Btw, how did you arrive at the term Constructor? You are writing it with pascal case which implies its a proper noun which implies that it is refering to an existing entity. But in the library there is no such a thing, never was. I never used this term for anything. The closest thing would be a Construct, an abstract class from which all other parsing classes derive.

How is your progress? Anything I can do to help?

**Comment by dcajacob** [comment]
Apologies. That was me being sloppy. I did mean "Construct."

Here's my current solution. It accomplishes all the goals I had. I only modified parse. I haven't tried touching build, since I don't currently need that and it seems like a hairier problem. Maybe I'll take a look at it later.

Note: this probably only makes sense in the context of a record with fields that need to be byte-swapped, so maybe it should be  named `BitsIntegerLittleEndianAligned` and have the `swapped` option removed. In the non-swapped case, I believe the normal Bitwise Constructs work fine.

```
class BitsIntegerAligned(Construct):

    def __init__(self, length, signed=False, swapped=False):
        super().__init__()
        self.length = length
        self.signed = signed
        self.swapped = swapped

    def _parse(self, stream, context, path):
        length = bit_length = evaluate(self.length, context)
        if length < 0:
            raise IntegerError(f"length {length} must be non-negative", path=path)
        start_pos = stream_tell(stream, path)
        
        left_offset = right_offset = 0
        
        if start_pos % 8: # we're not on a byte boundary
            left_offset = start_pos % 8 # rewind to the last one
            length += left_offset
        
        if (start_pos - left_offset + length) % 8: # we're not on a byte boundary
            #print(start_pos, length)
            right_offset = 8 - ((start_pos - left_offset + length) % 8) # push to the next one
            length += right_offset
            
        # print(-left_offset, right_offset, length)
            
        assert length % 8 == 0
        
        if left_offset:
            stream_seek(stream, -left_offset, 1, path)
        
        data = stream_read(stream, length, path)
        
        stream_seek(stream, -right_offset, 1, path) # rewind back to where we should have ended
        if evaluate(self.swapped, context):
            if length % 8:
                raise IntegerError(f"little-endianness is only defined if {length} is multiple of 8 bits", path=path)
            data = swapbytesinbits(data)
            
        data_int = bits2integer(data, signed=self.signed)
        
        # print(hex(data_int))
        
        # Now do the bitdango
        if self.swapped:
            if left_offset: # with swapping, left becomes right
                data_int = data_int >> left_offset # shift off the unneeded bits
        else: # FIXME this may be bullshit, why would you use this if not byte-swapping? Also untested
            if right_offset:
                data_int = data_int >> right_offset # shift off the unneeded bits
        
        data_int = data_int & (2**bit_length - 1) # mask off theremaining unneeded bits
        
        try:
            #return bits2integer(data, self.signed)
            return data_int
        except ValueError as e:
            raise IntegerError(str(e), path=path)

    def _build(self, obj, stream, context, path):
        if not isinstance(obj, integertypes):
            raise IntegerError(f"value {obj} is not an integer", path=path)
        if obj < 0 and not self.signed:
            raise IntegerError(f"value {obj} is negative but signed is false", path=path)
        length = evaluate(self.length, context)
        if length < 0:
            raise IntegerError(f"length {length} must be non-negative", path=path)
        try:
            data = integer2bits(obj, length, self.signed)
        except ValueError as e:
            raise IntegerError(str(e), path=path)
        if evaluate(self.swapped, context):
            if length % 8:
                raise IntegerError(f"little-endianness is only defined if {length} is multiple of 8 bits", path=path)
            data = swapbytesinbits(data)
        stream_write(stream, data, length, path)
        return obj

    def _sizeof(self, context, path):
        try:
            return evaluate(self.length, context)
        except (KeyError, AttributeError):
            raise SizeofError("cannot calculate size, key not found in context", path=path)

    def _emitparse(self, code):
        return f"bits2integer(swapbytesinbits(io.read({self.length})) if {self.swapped} else io.read({self.length}), {self.signed})"

    def _emitbuild(self, code):
        return f"((io.write(swapbytesinbits(integer2bits(obj, {self.length}, {self.signed})) if ({self.swapped}) else integer2bits(obj, {self.length}, {self.signed}))), obj)[1]"

    def _emitprimitivetype(self, ksy, bitwise):
        assert not self.signed
        assert not self.swapped
        return "b%s" % (self.length, )
```

And here's some test code, with the Adapters for scaling:

```
class DopplerAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return obj / 256

class PsrAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return obj / 128

class AdrAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        
        WAVELENGTH = 0.1902936727984 # for GPS L1
        # WAVELENGTH = 0.2442102134246 # for GPS L2
        
        MAX_VALUE = 8388608
        
        RANGECMP_ADR = obj / 256
        
        ADR_ROLLS = (context.psr / WAVELENGTH + RANGECMP_ADR) / MAX_VALUE
        
        if (ADR_ROLLS <= 0):
            ADR_ROLLS -= 0.5
        else:
            ADR_ROLLS += 0.5

        # At this point integerise ADR_ROLLS # Ceil or Int?
        CORRECTED_ADR = RANGECMP_ADR - (MAX_VALUE * int(ADR_ROLLS))
        
        # return obj / 256
        
        return float(CORRECTED_ADR * WAVELENGTH)

class AdrSigAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return (obj + 1) / 512

class LockTimeAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return obj / 32

class Cn0Adapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return obj + 20

class GloFreqAdapter(Adapter):
    #def _encode(self, obj, context, path=None):
    #    return int(obj*16.0) << 3

    def _decode(self, obj, context, path=None):
        return obj + 7



RangeCmp = Bitwise(Struct(
    'header' / BitsInteger(32),
    'dopp' / DopplerAdapter(BitsIntegerAligned(28, swapped=True, signed=True)),
    'psr' / PsrAdapter(BitsIntegerAligned(36, swapped=True)),
    'adr' / AdrAdapter(BitsInteger(32, swapped=True, signed=True)),
    'psr_sig' / BitsIntegerAligned(4, swapped=True),
    'adr_sig' / AdrSigAdapter(BitsIntegerAligned(4, swapped=True)),
    'prn' / BitsInteger(8),
    'locktime' / LockTimeAdapter(BitsIntegerAligned(21, swapped=True)),
    'cn0' / Cn0Adapter(BitsIntegerAligned(5, swapped=True)),
    'glofreq' / GloFreqAdapter(BitsIntegerAligned(6, swapped=True)),
    Padding(16)
))

RangeCmp.parse(record)
```

Results in:

`Container(header=614207496, dopp=1635.0546875, psr=25098061.265625, adr=-25616805.565820854, psr_sig=0, adr_sig=0.009765625, prn=27, locktime=3188.03125, cn0=44, glofreq=7)
`

**Comment by arekbulski** [comment]
I took the liberty of editing your code, removed build and added syntax highlight.

Does this work correctly with signed fields?
```py
        data_int = data_int & (2**bit_length - 1) # mask off theremaining unneeded bits
```
You can drop the final try-except because the return cannot cause an exception.

**Comment by dcajacob** [comment]
Good question. I will test it against a larger data set where I know there are some negative doppler values. I think it should work though. The length passed in should be the entire field length, including sign, if it is signed.

**Comment by dcajacob** [comment]
It does look like it doesn't handle sign correctly somehow. The first test case is a positive doppler, second is negative, but both come out positive. First one is the correct value, second is not (and sign is incorrect too, of course).

**Comment by dcajacob** [comment]
I think I fixed it. I added a line to the code above. Please let me know what you think.

**Comment by dcajacob** [comment]
Well, this seems to have fixed one field with respect to sign, but broken another...

**Comment by arekbulski** [comment]
Please elaborate?

**Comment by dcajacob** [comment]
Sorry, nevermind. this had nothing to do with the new code. It works fine. I was reading some truth data incorrectly.
