### ISSUE TITLE
IRC channel support

### ISSUE THREAD

**Issue by mhsjlw** [construct/construct#97]
As per https://github.com/construct/construct/commit/55065489fe945b16f507227b77a567f51e6232c1#commitcomment-18978439 Possibly provide support in an IRC channel, I recommend freenode. Possibly `##constructpy`, `#constructpy`, `#construct2` or `##construct2` as `#construct` is taken.

**Comment by arekbulski** [comment]
Thanks for suggesting it. I wont be sitting there all day long so I think the Issues section is the best place. Even when the issues get closed, you can still filter through them by the question label.
https://github.com/construct/construct/issues?utf8=%E2%9C%93&q=label%3Aquestion%20

**Comment by mhsjlw** [comment]
Sounds good :+1:

**Comment by arekbulski** [comment]
I could update the readme/webpage with a link to open/closed question issues. Good idea. :+1:

**Comment by arekbulski** [comment]
Just an afterthought. IRC tends to be pretty hectic, people respond quickly and with oneliners. When a hige chunk of code is of issue, it takes some time and deliberation to solve it. This is why I think IRC is not the best place to go about questions. Just something to consider.
