### ISSUE TITLE
Also release wheels on PyPI 

### ISSUE THREAD

**Issue by pombredanne** [construct/construct#974]
It would be really nice to also publish wheels on PyPI.

**Comment by pombredanne** [comment]
@arekbulski Note that if you do not want to have these that's fine too, but this means that I will have a publish something like a construct2 or construct3 package on PyPI where I can get the pre-built wheels that I need... which IMHO is NOT a sane fragmentation of having more than one construct package on PyPI.

**Comment by pombredanne** [comment]
@arekbulski gentle ping. Do you want a patch?

**Comment by pombredanne** [comment]
The patch is there for you https://github.com/construct/construct/pull/975
You can see the output of the run there https://github.com/pombredanne/construct/runs/5404299579?check_suite_focus=true 
And get the archives of built sdist and wheel here: https://github.com/pombredanne/construct/suites/5517971681/artifacts/176975422

**Comment by pombredanne** [comment]
So my point is that this is rather straightforward. I appreciate that you may had bad experience in the past, but this may no longer be the case today :)

**Comment by arekbulski** [comment]
Yeah, it took me some time to make a decision but I agree with you. Forking the project would be a bad choice and producing wheels should not be such a hassle. I will fix this by the end of the week.

BTW you do not need to at me, I subscribe to the entire repository. I always get notified.

**Comment by ghandic** [comment]
Any progress on this? only tar.qz available on pypi, wheel files are needed when using pants on Mac (M1/M2 processors)
