### ISSUE TITLE
using this with the in operator does not work as expected

### ISSUE THREAD

**Issue by jmgurney** [construct/construct#976]
```
>>> construct.__version__
'2.10.68'
```

The following works as expected:
```
foo = construct.Struct('pref' / construct.BitStruct('prefix' / construct.BitsInteger(6), 'size' / construct.BitsInteger(2)), 'tail' / IfThenElse(this.pref.prefix == 0x20, construct.Const(b'\x05'), construct.Const(b'\x07')))

r = foo.parse(b'\x80\x05')
```

and this case fails correctly:
```
r = foo.parse(b'\x10\x05')
```

But if I use the in operator (that is convert `== 0x20` to `in [ 0x20 ]`):
```
foo = construct.Struct('pref' / construct.BitStruct('prefix' / construct.BitsInteger(6), 'size' / construct.BitsInteger(2)), 'tail' / IfThenElse(this.pref.prefix in [ 0x20 ], construct.Const(b'\x05'), construct.Const(b'\x07')))
```

Then it is always true, and this case does not fail:
```
r = foo.parse(b'\x10\x05')
```

It is possible that I'm not using this properly, if so, please let me know how to check multiple values instead of having to do `this.foo == 1 or this.foo == 2 or ...`

**Comment by arekbulski** [comment]
Already covered in the docs:
https://construct.readthedocs.io/en/latest/meta.html#known-deficiencies

**Comment by jmgurney** [comment]
Thanks for the reference.  I see that now.  Of course just before I checked this again, I was able to make it work w/ lambdas/functions.
