### ISSUE TITLE
Bitwise elements in the middle of a bytewise struct

### ISSUE THREAD

**Issue by nrclark** [construct/construct#978]
I'm still learning `Construct`. It's a fantastic library and I'm super excited to use it. It's going to really improve some tools that I've been building. So - thanks for making it!

I'm trying to parse a file that has one 6-byte section that looks like this:

    Byte 0-1: header (16-bit unsigned little endian)
    Byte 2: counter[7:0]
    Byte 3: output_enable, counter[14:8]
    Byte 4-5: footer (16-bit unsigned little endian)

Here's an example of the file-section with [`output_enable == False`]:

    header = 0xDEAD, footer = 0xBEEF
    counter = 0x1FE
    output_enable = False 

    Packet: AD DE FE 01 EF BE

And here's an example of the file-section with [`output_enable == True`]:

    header = 0xDEAD, footer = 0xBEEF
    counter = 0x1FE
    output_enable = True 

    Packet: AD DE FE 81 EF BE

What's the best way to express this in `Construct`? It's one small section of a larger file that's easy to describe otherwise. I want to describe it in a way where I can access all of the fields.

I originally tried this:

    import construct as ct

    fmt = ct.Struct(
        "header" / ct.Int16ul,
        ct.ByteSwapped(ct.BitStruct(
            "output_enable" / ct.Flag,
            "counter" / ct.BitsInteger(15),
        )),
        "footer" / ct.Int16ul
    )

but building files with it doesn't work. I'm looking for a syntax that would make this succeed:

    fmt.build(header=0xDEAD, footer=0xBEEF, output_enable=True, counter = 0x1FE)

I'm told that `Embedded()` would have been the pre-2.10 way to express this. What's the right way now?

**Comment by arekbulski** [comment]
I see two obvious problems with it. One, you pass values to build as context (kwargs) entries. You need to pass a dict. Second, the middle field is not named. You seem to be assuming some sort of strange implicit embedding semantic which is something that never existed in this library. 
```py
fmt = ct.Struct(
    "header" / ct.Int16ul,
    "middle" / ct.ByteSwapped(ct.BitStruct(
        "output_enable" / ct.Flag,
        "counter" / ct.BitsInteger(15),
    )),
    "footer" / ct.Int16ul,
)

fmt.build(dict(header=0xDEAD, footer=0xBEEF, middle=dict(output_enable=True, counter = 0x1FE)))

```

**Comment by nrclark** [comment]
Gotcha, thanks. You're right about the missing `dict`, that's just an artifact of the contrived example I put together.

Is there any way I could express the file structure without having to use a named subsection like that? I'm not married to my exact syntax, if you have a suggestion that would work a little nicer.

**Comment by arekbulski** [comment]
I dont quite follow what you mean. You seem to be talking about embedding semantics which were removed from the library entirely a long time ago. Well... I guess you could make the entire outer struct a Bitwise Struct and put all members flatly into it.

**Comment by nrclark** [comment]
Fully BitStruct sounds like it's the right path for me, then. Got any quick pointers on how to express "non-adjacent bits are combined into one field"?

The firmware that parses this thing reads the middle as a 16-bit LE unsigned int, and then says "OK, highest-bit is an output-control. The rest is the value of a counter." Which leads to this pattern:

[byte 0] [byte 1] [byte 2 == counter (lowest bits) [ byte 3 == [bool, counter (upper bits)]]

**Comment by arekbulski** [comment]
Hmm yeah I get you. Some of it is easy thing to do bitwise-way but the 15+1 little endian array is tricky. Try something like the following. You may need to experiment with it.
```py
fmt = ct.BitStruct(
    "header" / ct.BitsInteger(16, swapped=True),
    "middle" / ct.ByteSwapped(Bytewise(ct.BitStruct(
        "output_enable" / ct.Flag,
        "counter" / ct.BitsInteger(15),
    ))),
    "footer" / ct.BitsInteger(16, swapped=True),
)
```
Embedding was permanently removed so you would get stuck with the middle thing.

Alternatively you could use an adapter that would take the whole outer struct (dict), and then move the values around to make it flat. Its not difficult, just dumb labor.

**Comment by nrclark** [comment]
Thanks for the advice. I'll give an adapter a try to flatten it.
