### ISSUE TITLE
Syntax for referring to the value of lengthfield in Prefixed

### ISSUE THREAD

**Issue by darmendariz** [construct/construct#979]
I'm writing a program to parse binary replay files from the game Rocket League. The format is documented [here](https://docs.rs/boxcars/latest/src/boxcars/parser.rs.html). The files contain strings prefixed by their size. The sign of the size of a string also tells you its encoding. The formula I'm following for decoding such a string is as follows (given by [lines 20-30](https://docs.rs/boxcars/latest/src/boxcars/parser.rs.html#20-30) in the linked documentation):

1. Read the size of the string as a 32-bit (signed) integer
    1. If the size is positive, then the encoding is utf8, and the number of bytes to read the string is just that size
    2. Else if the size is negative, then the encoding is utf16, and the number of bytes to read the string is size*=-2
2. Consume the number of bytes determined, but drop the last letter (1 byte if utf8, 2 bytes if utf16) which is a null character.

To parse these strings I've written the following:
```python
replaystring = Struct(
    'string_size' / Int32sl,
    'string_content' / IfThenElse(this.string_size > 0, CString('utf8'), CString('utf16'))
)
```
which seems to work fine for some strings in the file but not for others. In an effort to solve my current problems in reading these strings I'd instead like to replace the above with something like:
```python
replaystring = Prefixed(Int32sl, IfThenElse(lengthfieldvalue > 0, CString('utf8'), CString('utf16')))
                                           # ^^^^^^^^^^ not sure what to put here 
```

However, I'm not sure what the syntax is for referencing the `Int32sl` _lengthfield_ value within the `IfThenElse` subcon of Prefixed. I have read the docs and looked at the source code but can't figure it out as I'm a novice programmer. 

Thanks for your help.

**Comment by arekbulski** [comment]
I appreciate the difficulties. You can certainly request support from me, anytime. 

> If the size is positive, then the encoding is utf8,

The docs does not say its UTF8 but rather Windows1252 encoding. Small detail. 

How about this?
```py
replay = Struct(
	"size" / Int32sl,
	"content" / IfThenElse(this.size >= 0, 
		Prefixed(Computed(this.size), CString("windows-1252")),
		Prefixed(Computed(this.size*(-2)), CString("utf-16-le")),
	),
)
```

**Comment by darmendariz** [comment]
> The docs does not say its UTF8 but rather Windows1252 encoding. Small detail.

I did notice that, but also saw in the Construct docs that CString only supports encodings explicitly listed in `possiblestringencodings`, which does not contain Windows1252. I ended up using `Cstring('utf8')` in my original code because upon googling, I read something that said that Windows1252 is a subset of UTF8. But now I see that I misinterpreted that statement since Windows1252 strings are not guaranteed to be valid UTF8 strings, because their [byte-by-byte representation is different](https://stackoverflow.com/a/57484243). Indeed when running your code I get the following error:

```python
Traceback (most recent call last):
  File "/replayfileformat.py", line 28, in <module>
    Prefixed(Computed(this.size), CString("windows-1252")),
  File "/opt/anaconda3/envs/pyrl/lib/python3.8/site-packages/construct/core.py", line 1711, in CString
    macro = StringEncoded(NullTerminated(GreedyBytes, term=encodingunit(encoding)), encoding)
  File "/opt/anaconda3/envs/pyrl/lib/python3.8/site-packages/construct/core.py", line 1596, in encodingunit
    raise StringError("encoding %r not found among %r" % (encoding, possiblestringencodings,))
construct.core.StringError: encoding 'windows_1252' not found among {'ascii': 1, 'utf8': 1, 'utf_8': 1, 'u8': 1, 'utf16': 2, 'utf_16': 2, 'u16': 2, 'utf_16_be': 2, 'utf_16_le': 2, 'utf32': 4, 'utf_32': 4, 'u32': 4, 'utf_32_be': 4, 'utf_32_le': 4}
```

So it appears I have to use either `PascalString` or `GreedyString`. Since strings end with null bytes, I tried using `NullTerminated` in combination with `GreedyString`:

```python
replaystring = Struct(
	"size" / Int32sl,
	"content" / IfThenElse(this.size >= 0, 
		NullTerminated(GreedyString("windows-1252")),
		NullTerminated(GreedyString("utf-16-le"), term=b'\x00\x00'),
	),
)
```

Things appear to be working so far with this solution. However, it's hard to say as there are still other things I need to fix which prevent me from knowing for certain. For instance, there's a data structure in the replay files which is like an array of arrays, and those arrays need `replaystring` to decode strings that they contain. I was getting strange results when parsing those arrays that i thought was due to `replaystring`, but then I realized that my declaration of the array-of-arrays structure was flawed. Once fixed it'll be easier to see if my new solution for `replaystring` works.

**Comment by arekbulski** [comment]
You can add new encodings to `possiblestringencodings` if you want. Just be mindful what it does.
