### ISSUE TITLE
Padding / unnamed member in BitStruct /  'flagbuildnone' ?

### ISSUE THREAD

**Issue by laf0rge** [construct/construct#981]
I'm trying find a way to have some padding in a bitstruct:
```
BitStruct(Bit, 'only_4bytes_res_in_3g'/Bit,
                            'use_sres_deriv_func_2_in_3g'/Bit,
                            'use_opc_instead_of_op'/Bit,
                            'algorithm'/Enum(Nibble, milenage=4, sha1_aka=5, xor=15))
```
While this works for decode, it fails during build,as
```
  File "/usr/lib/python3/dist-packages/construct/core.py", line 2139, in _build
    subobj = obj[sc.name] # raises KeyError
```
Since the 'Bit' field at the beginning has no name, sc.name == None and obj[None] raises the KeyError.

I've tried with Const() and Padding(), but they also fail, either because they don't support BitStruct, or because they have flagbuildnone=False.  I wonder why that is for Padding, for example?  Why would I need to name the padding?

In any case, I'm looking for advice as to how I can have a BitStruct with some "do not care" "padding" or "constant" bits that I don't have to give names to.

Thanks!

**Comment by arekbulski** [comment]
Padding(1) does not work for you?

**Comment by arekbulski** [comment]
Padding seems to work without problems.
```py
In [4]: d = BitStruct(Padding(8))

In [5]: d.build(dict())
Out[5]: b'\x00'
```

**Comment by laf0rge** [comment]
Indeed, Padding(1) seems to work for a single bit.  Not sure what I was doing wrong.  I definitely tried something Padding(), maybe I previously used Padding(0) or something like Padding(Bit) - didn't store all the intermediate non-working states in git, so I cannot reconstruct exactly.  Thanks again for your help.
