### ISSUE TITLE
Help needed: Trying to get RepeatUntil to work

### ISSUE THREAD

**Issue by laf0rge** [construct/construct#982]
I have a data format that looks like this:
* A single Int8ub indicating overall length of the following IEs
* A sequence of TLV information elements (IEs), each
  * Int8ub tag
  * Int8ub length
  * "length" bytes of data
* non-TLV data at the end

I want to use construct to parse this data into
* a list of IEs
* the trailing non-TLV data

Unfortunately, my attempts are failing so far:

```python
# a single IE in the user data header
ie_c = Struct(
  'offset' / Tell,
  'iei' / Int8ub,
  'length' / Int8ub,
  'data' / Bytes(this.length),
)
# parser for the full UDH: Length octet followed by sequence of IEs
_construct = Struct(
  'udhl'/Int8ub,
  # FIXME: somehow the below lambda is not working, we always only get the first IE?
  'ies' / RepeatUntil(lambda obj,lst,ctx: ctx._io.tell() > 1+this.udhl, ie_c),
)
```

This works for
* `027100` (single IE with zero-length IE-data and no trailer)
* `03710110` (single IE with non-zer-length IE-data and no trailer)
* `027100abcdef` (single IE with trailer)

But it fails for something like
* `0571007001ffabcd` (two IEs followed by trailer)

What am I doing wrong? Why is it not repeating until the 5 bytes (indicated in first octet) have been consumed?

**Comment by arekbulski** [comment]
Please use syntax highlithing and spread the struct into one item per line. I will wait.

**Comment by laf0rge** [comment]
github displays the code with syntax highlighting here, odd.  Will split the one line in second.

The odd part is that it even correctly splits the trailer (`abcd` from the preceding TLV section, but 'ies' only contains a single element (the first IE) and not a list of elements (IEs).

**Comment by arekbulski** [comment]
I chenged the highlight myself just now. But I leave the structs to you.

**Comment by laf0rge** [comment]
```python
# a single IE in the user data header
ie_c = Struct('offset'/Tell,
             'iei'/Int8ub,
             'length'/Int8ub,
             'data'/Bytes(this.length))
# parser for the full UDH: Length octet followed by sequence of IEs
_construct = Struct('udhl'/Int8ub,
                # FIXME: somehow the below lambda is not working, we always only get the first IE?
                'ies'/RepeatUntil(lambda obj,lst,ctx: ctx._io.tell() > 1+this.udhl, ie_c))
```

**Comment by arekbulski** [comment]
For one this is not the kind of indentation that Construct guideline dictates, and second please edit the main post instead of appending more and more stuff. You need to keep up your game if you expect the same.

**Comment by laf0rge** [comment]
I am doing full-time open source development for more than 20 years, but I am not familiar with the customs of this specific project, my apologies

**Comment by arekbulski** [comment]
Yeah well, this project usually uses simething like 
```py
Struct(
  "x" / Byte,
)
```
This means all items are 2 spaces indent, first item below the Struct, last item followed by a comma.

**Comment by laf0rge** [comment]
I tried https://construct.readthedocs.io/en/latest/search.html for the search terms "indent", "syntax", "guideline" and "format" and could not find the guideline you are referring to. Can you please point me to it?

**Comment by arekbulski** [comment]
There is no PEP like document that says it. But if you read COnstructs main documentation, as well as docstrings, this format is used for all examples.

**Comment by arekbulski** [comment]
I dropped  most of our conversation because nobody else will care. Now, back to the meat:

I am not entirely sure (yet) what is wrong with it. RepeatUntil does not use a sub BytesIO like some parsing classes do, so dunno. I would say this: your RepeatUntil+tell() are not kosher. How about use use Prefixed+GreedyRange instead?

**Comment by laf0rge** [comment]
Thanks, trying that suggestion. That seems to work.

**Comment by arekbulski** [comment]
You are welcome, anytime.

**Comment by rlaphoenix** [comment]
For anyone else stuck on something similar to this, you may be trying to use `this` in the RepeatUntil expression, which doesn't seem supported. Any operation like `ctx._io.tell() > this.foo` seems to always return False or True (for some reason). It's as if the actual `this.foo` isn't being expanded and is compared against something more high-level.

In OP's example, he may actually have this working by doing `'ies' / RepeatUntil(lambda obj,lst,ctx: ctx._io.tell() > 1+ctx.udhl, ie_c),` (notice `ctx.udhl` instead of `this.udhl`).
