### ISSUE TITLE
How do you assert that a parser has consumed all the input?

### ISSUE THREAD

**Issue by Kodiologist** [construct/construct#983]
I'm had great success using this library to parse an old computer-game file format, but I'm stuck on one very simple thing. By default, if a parser doesn't consume all the input, as in `Byte.parse(b"aa")`, that's not an error; the remaining input is simply discarded. I want to make this a parse failure instead. Is there some combinator or parser object or something to indicate "this is where the input should end", like `\Z` in a regex?

**Comment by arekbulski** [comment]
It is called `Terminated`.
https://construct.readthedocs.io/en/latest/streaming.html#other-fields

**Comment by Kodiologist** [comment]
That's it. Thanks.
