### ISSUE TITLE
Really confused about  `Struct` vs `LazyStruct`

### ISSUE THREAD

**Issue by demberto** [construct/construct#989]
```py
>>> MyStruct = c.Struct(
...     "a" / c.Optional(c.Int32sl),
...     "b" / c.Optional(c.Int32sl),
...     "c" / c.Optional(c.Int32sl))
>>> s = MyStruct.parse(b"\x00\x00\x00\x00")
>>> MyStruct.build(s)
b'\x00\x00\x00\x00'
>>> MyStruct.build(s)
b'\x00\x00\x00\x00'
>>> s.a
0
>>> s["a"]
0
>>> s.a = 1
>>> s.a
1
>>> MyStruct.build(s)
b'\x01\x00\x00\x00'    # alright correct 🎉
s.b
s.b = 1
s.b
1
s["b"]
1
MyStruct.build(s)
b'\x00\x00\x00\x00\x01\x00\x00\x00'   # ♥
```
Fun starts here:
```py
>>> MyStruct = c.LazyStruct(
...     "a" / c.Optional(c.Int32sl),
...     "b" / c.Optional(c.Int32sl),
...     "c" / c.Optional(c.Int32sl))
>>> s = MyStruct.parse(b"\x00\x00\x00\x00")
>>> MyStruct.build(s)
b''     # wut?? 👀❌
>>> s.a
0
>>> MyStruct.build(s)
b''    # wut?? 👀❌
```

I am using `construct v2.10.67` on `Python 3.11.0-rc1`, if that is useful.

`LazyStruct` to me seems *really, really* flaky. Also there seems to be a difference between how `__setitem__` and `__setattr__` works for it.

Also, is there any way to enforce a `__slots__` like behavior for `Struct`s? So that keys outside the ones defined for the struct won't be able to be dynamically defined. Seems like a very common source of errors, *imo*

**Comment by arekbulski** [comment]
For a start, you dedfined a 12 byte Struct (or LazyStruct) but you are parsing only 4 bytes. Try giving a bytes(12) object to parse method and see if it works differently.

**Comment by arekbulski** [comment]
Interesting. LazyStruct builds fine from a normal dict but not from a LazyContainer.
```py
In [1]: from construct import *

In [2]: s=LazyStruct("a"/Optional(Byte))

In [3]: s.parse(bytes(1))
Out[3]: <LazyContainer: 1 items cached, 1 subcons>

In [5]: s.build(dict(a=5))
Out[5]: b'\x05'

In [6]: d=s.parse(bytes(1))

In [7]: s.build(d)
Out[7]: b''
```

**Comment by arekbulski** [comment]
The Optional is the part of the problem. Without it it works fine.
```py
In [12]: s=LazyStruct("a"/Byte)

In [13]: s.parse(bytes(1))
Out[13]: <LazyContainer: 0 items cached, 1 subcons>

In [14]: d=s.parse(bytes(1))

In [15]: s.build(d)
Out[15]: b'\x00'
```

**Comment by demberto** [comment]
Well `Struct` + `Optional` isn't a problem, but `LazyStruct` + `Optional` + insufficient number of bytes is a problem.

> Interesting. LazyStruct builds fine from a normal dict but not from a LazyContainer.
> 
> ```python
> In [1]: from construct import *
> 
> In [2]: s=LazyStruct("a"/Optional(Byte))
> 
> In [3]: s.parse(bytes(1))
> Out[3]: <LazyContainer: 1 items cached, 1 subcons>
> 
> In [5]: s.build(dict(a=5))
> Out[5]: b'\x05'
> 
> In [6]: d=s.parse(bytes(1))
> 
> In [7]: s.build(d)
> Out[7]: b''
> ```

I recall having encountered this, but couldn't reproduce it. I really need a `LazyStruct` compatible with `Optional` and an insufficient number of bytes provided to work like. Since the point of `Optional` is to allow an insufficient number of bytes. Useful for structures whose size you aren't sure of

**Comment by arekbulski** [comment]
Are you sure that LazyStruct is what you need? I made that parsing class specifically for one of our users to be used in Capture The Flag hacking contests. Its not to be used by general audience. Why is Struct not gonna work for ya?
