### ISSUE TITLE
Remove mentions of `enum34` from docs

### ISSUE THREAD

**Issue by demberto** [construct/construct#990]
I found a warning to not use `enum34` at https://construct.readthedocs.io/en/latest/advanced.html#mappings

> Using the enum34 module is deprecated and should not be used.

However, at https://construct.readthedocs.io/en/latest/intro.html#requirements

> Enum34 is optional if you want Enum EnumFlags to take labels from IntEnum IntFlag.

*... and a bunch of other mentions here at https://construct.readthedocs.io/en/latest/search.html?q=enum34*

---

I think since `construct` supports only Python 3.6+ it should probably remove all mentions of `enum34`, since there is an stdlib `enum` module.

**Comment by arekbulski** [comment]
In our documentation, enum34 refers to both the old module that you would have to pip install as well as the standard library module that is present in newer python versions.

**Comment by demberto** [comment]
Wouldn't it be more clear to just replace enum34 with enum, given the Python requirements of this project anyways?

**Comment by arekbulski** [comment]
Done.
