### ISSUE TITLE
Is there no way to use `sizeof` with a `Struct` containing `Optional` fields?

### ISSUE THREAD

**Issue by demberto** [construct/construct#991]
I have certain structs whose all fields are `Optional` but I want to get their size as a whole. Is there no way except like hardcoding a SIZE member somewhere?

**Comment by arekbulski** [comment]
A Struct sizeof() requires all its members to be of a known size. Each Optional is a Select which inherits _sizeof() from Construct abstract class and throws SizeofError. In essence, any Optional member will not allow for the Struct to be sizeable.

You can write your own sizeof2(...) function which will dig through classes. Something alike to this:
https://github.com/construct/construct/blob/ba1718e2e37c0a74c5b3f180daaabb5745a8957f/construct/core.py#L284-L287
