### ISSUE TITLE
`Select` or `IfThenElse` doesn't work in a `GreedyRange`

### ISSUE THREAD

**Issue by demberto** [construct/construct#993]
```py
import construct as c

c.Struct(
    "type" / c.Int32ul,
    "events" / c.GreedyRange(
        c.Struct(
            "id" / c.Int32ul,
            "data" / c.Select(c.PascalString(c.Int64ul, "ascii"), c.Prefixed(c.Int64ul, c.GreedyBytes)),
        ),
    ),
)
```

So basically the struct will look like this in equivalent C code:
```c
struct {
    uint32_t type;
    typedef struct {
        uint32_t id;
        uint64_t length;
        uint8_t data[length];
    } events[];
};
```

Whether `data` is an ASCII string or just a plain byte array depends on `id`, so I tried both `IfThenElse` and `Select`, both don't work. However if `data` is just `c.Bytes` or `c.Prefixed(c.Int64ul, c.GreedyBytes)` the `events` gets parsed.

**Comment by arekbulski** [comment]
In fact, the only thing you need to trigger this bug is a PascalString(ascii) and parse a non-ascii data. I fixed it already but I will release the fix tomorrow. Please do not close this Issue just yet.

**Comment by demberto** [comment]
Ohh, sure

**Comment by arekbulski** [comment]
Sorry, I am not in a shape to be working on this atm.

I think this and other things were fixed in HEAD, just not pushed to PYPI. Check HEAD.

**Comment by arekbulski** [comment]
I believe this was fixed today.
