### ISSUE TITLE
Using `list_` with `Computed`

### ISSUE THREAD

**Issue by demberto** [construct/construct#995]
I am back with an issue ;)

I have a struct like this

```py
c.Struct(
    "count" / c.Int32ul,
    "points" / c.Array(
        lambda ctx: ctx["count"],
        c.Struct(
            "_u1" / c.Bytes(4),
            "offset" / c.Float32l * "Change in X-axis w.r.t last point",
            "position" / c.Computed(
                lambda ctx: ctx["offset"] + position_of_last_point # list_[ctx._index - 1]
            ),
        ),
    ),
)
```

Basically the points are analogous to X, Y co-ordinates, and the offset stores the change in the X co-ordinate with respect to last point. I tried accessing `ctx._` but it seems that the "points" array is not constructed yet.

One possible solution is I maintain a "position" field outside the array and add the offset to it every time, the position field inside the array can then simply copy it as is, but how do I do that?

**Comment by arekbulski** [comment]
You need to study this more carefully:
https://construct.readthedocs.io/en/latest/meta.html

**Comment by demberto** [comment]
That's the first thing I read. It seems like only `RepeatUntil` supports `this_`, `len_` etc.

I cannot catch anything useful there. I even checked construct_typed's callback type annotations and the "Context" object but there's simply nothing

**Comment by arekbulski** [comment]
It says so in yellow: "The list_ expression is implemented but buggy, using it is not recommended at present time."

**Comment by arekbulski** [comment]
> It seems like only RepeatUntil supports this_, len_ etc.

This is nonsense. "len_" is a general thing, and there is no such a thing as "this_".

**Comment by demberto** [comment]
Yea I meant to say `this`. *Quick replies, btw*

> It says so in yellow: "The list_ expression is implemented but buggy, using it is not recommended at present time."

So, is it okay to use it at this time? What exactly is buggy about it?

**Comment by arekbulski** [comment]
> So, is it okay to use it at this time? What exactly is buggy about it?

No, it means DO NOT USE PERIOD. And if I knew what is wrong with it, I would have fixed it. :stuck_out_tongue_closed_eyes:

**Comment by demberto** [comment]
Wished I saw this like an hour ago :sigh:
The past whole hour I have been figuring out how to use `list_`
Seems like I need to fallback to normal parsing?

**Comment by arekbulski** [comment]
Well, I replied within 4 minutes. If you could not be bothered to check for a reply, that is your problem.

The context business is not shady, just that there are significant (really significant) limitations to what this expressions can do. Just use a context lambda, its the most general approach that can do everything that can be done here.

**Comment by demberto** [comment]
> Just use a context lambda,

How can I get the value of a previous element from a context??

**Comment by arekbulski** [comment]
Not sure

sob., 8 paź 2022, 21:03 użytkownik demberto ***@***.***>
napisał:

**Comment by arekbulski** [comment]
Try inserting a Probe() ?

sob., 8 paź 2022, 21:05 użytkownik Arkadiusz Bulski ***@***.***>
napisał:

**Comment by arekbulski** [comment]
Instert a Probe() perhaps and look for keys there?
https://construct.readthedocs.io/en/latest/debugging.html
Maybe use a Tell as well?
https://construct.readthedocs.io/en/latest/streaming.html#pure-side-effects

**Comment by demberto** [comment]
I fail to understand how either of those will help me do what `list_[-1]` can achieve. For instance, the key of the array, "points" is not added into the Container until it is completely parsed, so the context is completely useless.

Is there any way to go back and compute fields after the array is parsed?

**Comment by arekbulski** [comment]
Sorry, not sure.

**Comment by demberto** [comment]
I guess manual parsing is the only real solution here then. :(
Kinda bummer, since I shifted over to construct with the hope that parsing structs like these will be easier than whatever handwritten mess I had.

**Comment by arekbulski** [comment]
You could use a PrefixedArray, at least that would be simpler. ;)

Construct has its limitations like everything else. Sometimes you need to write your own parsers, that is just how it is.

**Comment by demberto** [comment]
> Construct has its limitations like everything else. Sometimes you need to write your own parsers, that is just how it is.

No worries, Construct still has tons of useful features, most of which I will probably never use, but anyways I will post the code once I find a solution without having to fallback to manual parsing.

**Comment by arekbulski** [comment]
The custom parser can reuse much of what you wrote in the initial post, it does not need to be complicated. I will help you with writing it. I just need more details on what it is that it is supposed tp be doing.

**Comment by demberto** [comment]
This is the complete implementation, *although without a setter yet*

```py
@staticmethod
def _get_position(stream: c.StreamType, index: int):
    cur = stream.tell()
    position = 0.0
    for i in range(index + 1):  # repeat till stream position reaches current offset
        stream.seek(21 + (i * 24))  # seek the stream to the next element's offset
        position += c.Float64l.parse_stream(stream)  # accumulate offsets
    stream.seek(cur)
    return position

STRUCT = c.Struct(
    "_u1" / c.Bytes(4),  # 4  # ? Always 1
    "_u2" / c.Bytes(4),  # 8  # ? Always 64
    "_u3" / c.Byte,  # 9
    "_u4" / c.Bytes(2),  # 11
    "_u5" / c.Bytes(2),  # 13  # ? Always 0
    "_u6" / c.Bytes(4),  # 17
    "points"
    / c.PrefixedArray(
        c.Int32ul,  # 21
        c.Struct(
            "_offset" / c.Float64l * "Change in X-axis w.r.t last point",
            "position"  # TODO Implement a setter
            / c.IfThenElse(
                lambda ctx: ctx._index > 0,
                c.Computed(
                    lambda ctx: AutomationEvent._get_position(ctx._io, ctx._index)
                ),
                c.Computed(lambda ctx: ctx["_offset"]),
            ),
            "value" / c.Float64l,
            "tension" / c.Float32l,
            "_u2" / c.Bytes(4),  # Linked to tension
        ),  # 24 per struct
    ),
)
```

I feel there must be a better solution around with a generator function using `yield` magic but that's harder to think of.

**Comment by arekbulski** [comment]
I have a feeling that the "position" field could just be a Tell field.

**Comment by arekbulski** [comment]
Are you aware of what a Pointer parsing class does, btw?

**Comment by demberto** [comment]
> I have a feeling that the "position" field could just be a Tell field.

Uh, don't get confused with the name. It stores the X co-ordinate (and `value` stores the Y co-ordinate)

This is a visual representation of an automation clip, 

![image](https://user-images.githubusercontent.com/65948403/194727954-0a5481a7-4383-4887-810d-493b5e7d6317.png)

Every edge is a "point". Its corresponding `Struct` values are:

```py
[Container(position=0.0, value=1.0, tension=0.0),
Container(position=8.0, value=1.0, tension=0.0),
Container(position=8.0, value=0.0, tension=0.0),
Container(position=16.000000953674316, value=0.0, tension=0.0),
Container(position=24.000000953674316, value=1.0, tension=1.0),
Container(position=32.000000953674316, value=0.0, tension=1.0)]
```

---
I read what `Tell` does and it basically just returns the stream location. I don't know how it can be useful here. I wish I had like some diagram with me to tell how `offset` affects `position` but you can say `offset` is like a **delta** *(I just think I found a better name for the field)*.

So for every next point, the **previous** position needs to be added to the **current** offset. For the 1st point there is no previous, so its position is equal to the offset itself. For the 2nd point, `position_of_point_2 = offset_of_point_2 + position_of_point_1`.

I also tried to use `list_` in `_get_position` but it just prints the the "path" itself. (That's the objects you use internally, if I am correct).

**Comment by arekbulski** [comment]
I think you are making a mistake by trying to move too much computation into parsing classes. If you use the parsing classes only to do what they are designed for which is ...yes parsing... and then compute the positions outside of parsing, everything is gonna be simple. 
```py
STRUCT = c.Struct(
    "_u1" / c.Bytes(4),  # 4  # ? Always 1
    "_u2" / c.Bytes(4),  # 8  # ? Always 64
    "_u3" / c.Byte,  # 9
    "_u4" / c.Bytes(2),  # 11
    "_u5" / c.Bytes(2),  # 13  # ? Always 0
    "_u6" / c.Bytes(4),  # 17
    "points" / c.PrefixedArray(
        c.Int32ul,  # 21
        c.Struct(
            "offset" / c.Float64l * "Change in X-axis w.r.t last point",
            "value" / c.Float64l,
            "tension" / c.Float32l,
            "_u2" / c.Bytes(4),  # Linked to tension
        ),  # 24 per struct
    ),
)
```

**Comment by demberto** [comment]
I have a low level API which basically exposes this struct as well a high level wrapper over it. The struct stores at times a clusterfuck of unrelated data, just combined together by the owner of the format to save global event ID space. Its necessary to separate this information into a proper hierarchy of model classes. Dw if all that didn't make sense 😄

**Comment by demberto** [comment]
I am closing this issue
