### ISSUE TITLE
Parse dynamically typed attributes

### ISSUE THREAD

**Issue by nickger** [construct/construct#996]
I have a tricky file format, where classes may have attributes whose value is not statically typed. The value of such attributes is an integer which encodes the stored type, and the data for this type are placed at the end of the main (host) class. Absolute madness is with nesting when a dynamically defined type has dynamic attributes itself. 
Is there a way to write a parser for this case..?

**Comment by arekbulski** [comment]
I would need to see some details first, to be able to say anything about it.

**Comment by nickger** [comment]
Ok, I will try my best. Say, I have schema with 2 classes:
class_1:
    attr_1: Int32ul,
    attr_2: Flag
class_2:
    attr_1: Flag,
    attr_2: dynamic,
    attr_3: Inst32ul

The data for class_2 in this case would be like:
class_2:
    attr_1: True,
    attr_2: class_1,
    attr_3: 100,
    class_1_attr_1: 500,
    class_1_attr_2: False

Hope, it helps...

**Comment by arekbulski** [comment]
Well, you can nest a Struct inside another Struct. Is that what you are asking?

**Comment by arekbulski** [comment]
The basic question I think is WTF is supposed to dynamic mean? Is that field always a Class 1 instance or can it be whatever?

**Comment by nickger** [comment]
It can be whatever, that's the point. The field value is only the id of the type - in my case "class_1" and the data are stored at the end without any additional markers. So I cannot apply nested structures because of 2 reasons: until the data read I don't know what nested structure to apply (this could be solved by switch operator, but there are 3500 classes) and second, there is no clear markers for data for these classes, so "pointer" also cannot be used...
It must be some kind of "postponed" classes and during parsing the host structure should modify itself, adding these postponed classes to the end, but assigning their values to original places. With serialization it should be other way around.
Maddness, I know.

**Comment by arekbulski** [comment]
I agree, madness does not even cover it. Whoever came up with this data format should be shot.

You will definitely need to write your own parsing class for this. I will support you but I am not yet sure how to write it at this point in time. Construct may be useful to parse simple classes but when it comes to the dynamic thingy, you will not be able to do it declaratively, at least not using core library classes. You need to write your own parsing class(es) for this.

**Comment by arekbulski** [comment]
I have some ideas how to approach the parsing, but I am not in best of moods atm. 

How is it at your end? Btw, do you have any documentation to show regarding the project?

**Comment by arekbulski** [comment]
Any further attempts to contact me outside of GitHub will result in me ending all contact. Your email went straight to spam.

**Comment by nickger** [comment]
Originally the data are from a C++ application, and I try to imagine how they are kept in C++. From this point of view this issue with “dynamic” types becomes clearer – I assume original classes have attributes of pointer types and only point to other classes. Why their data are serialized so weirdly – just at the end of the “main” stream – cannot say. 
Actually, I am not so familiar with object-oriented paradigm – I mostly write scripts with functions – so I cannot even understand what your parser does, not telling to write my own ☹. Currently I am finishing a brute-force script to parse data into dictionaries and fighting with all possible combinations like “Array of dynamic types with nested arrays of dynamic types”. It looks super ugly as I must explicitly control the flow based on dictionary-like data and return them to where they belong in the “host” class. This will work for reading, hopefully, but obviously, not for changing and writing.
Dynamic types themselves is not a big issue, I feel like I miss some elegant idea how to keep “host” and “nested” classes connected both for parsing and for serializing…
