### ISSUE TITLE
RepeatUntil total entries of variable length subconstructs (w/ compile() compatibility)

### ISSUE THREAD

**Issue by StohanzlMart** [construct/construct#997]
Let's say I have the number of result items given like:

```
numResults (Int16ul)
resultItems[numResults]
```
where the `resultItems` is constructed like:
```
ID (does not always increase)
strLen
my_str[strLen]
```
Now I understand, that I have to use `RepeatUntil` but how the repeathandler is supposed to work swooshes right over my head.

# Edit:
I now added debug print statements.

What I have (not working):
```python
import construct as ct
from pprint import pprint

def repeat_handler( x, lst, ctx):
    pprint(f'{x=}, {lst=}, {ctx=}')
    pprint(f'{ctx.numResults=}, {x["ID"]=}')
    return ctx.numResults==x["ID"]

format = ct.Struct(
    'numResults' / ct.Int16ul,
    'resultItem' / ct.RepeatUntil(repeat_handler,
                       ct.Struct(
                            'ID'     / ct.Int16ul,
                            'strLen' / ct.Int16ul,
                            'my_str'    / ct.PascalString(ct.Computed(ct.this.strLen) , 'ISO-8859-1'),
                       ),
          ),
)
```
Please can you explain to me, how the `repeat_handler` is supposed to work, so that it iterates over all the `resultItems`?
# Edit2: got it working for rising ID, but how to do without rising ID?
```python
d = dict(numResults=2, resultItem=[ dict(ID=0, strLen=3, my_str='abc'),
                                    dict(ID=1, strLen=3, my_str='abc'),
                                    dict(ID=2, strLen=3, my_str='abc')]
)

f= format.build(d)
pprint(f)
pprint(format.parse(f))
```
Thank you kind stranger for your time!
([you can earn SO karma for this too if you want](https://stackoverflow.com/questions/74097806/with-construct-package-repeatuntil-total-lenght-of-subconstruct))

**Comment by StohanzlMart** [comment]
The repeat_handler should return this:
`return ctx._index==(ctx.numResults(-1))`

Also for the Pascal String I had to multiply times two and fix the encoding:
`ct.PascalString(ct.Computed(ct.this.strLen*2) , 'utf-16-le'`

Remember kids, a well rested brain is your best ally :)

**Comment by StohanzlMart** [comment]
I wanted to thank the devs of this awesome project for helping me develop an elegant solution!

Please think about adding an example with `ct.RepeatUntil(lambda x,lst,ctx: ctx._index==ctx.subconstructlength, ...`

**Comment by StohanzlMart** [comment]
Bonus Question: How to do this with only `ct.this` to enable the `.compile()` feature?

**Comment by arekbulski** [comment]
Why wont you use PrefixedArray instead of RepeatUntil? I was also going to suggest using a PascalString but you already found that. And the 2x issue with it is obvious. PascalString class expects a number of bytes (not characters) to consume. 

Compilation should work fine then? If not, hail me.
https://construct.readthedocs.io/en/latest/compilation.html

**Comment by StohanzlMart** [comment]
Thank you for your reply Arkadiusz Bulski! Do you mean it like this?

```python
ct.Construct(
        'numResults' / ct.Default(ct.Int16ul,3),
        # this is a minimal example, I will have shit here
        'resultItem' / ct.PrefixedArray(countfield=ct.Computed(ct.this.numResults) , subcon=ct.Construct(
                                'ID'     / ct.Default(ct.Int16ul,0),
                                'strLen' / ct.Default(ct.Int16ul,3),
                                # some more shit
                                'my_str'    / ct.Default(ct.PascalString(ct.Computed(ct.this.strLen) , 'ISO-8859-1'),'abc'),
                        )
                    ),
```
gives
```
Traceback (most recent call last):
[TypeError: __init__() takes 1 positional argument but 4 were given](https://www.google.com/search?q=python%20TypeError:%20__init__()%20takes%201%20positional%20argument%20but%204%20were%20given)
```
I take it cannot access a countfield outside? Unlike PascalString... where I also have unluckily placed other bytes...

**Comment by StohanzlMart** [comment]
Thank you, now it works. I just did what you said and wrote in the readme and then I tried some more with a well rested mind and viola!
```python
ct.Struct(
        'numResults' / ct.Default(ct.Int16ul,3),
        # this is a minimal example, I will have shit here
        'resultItem' / ct.PrefixedArray(countfield=ct.Computed(ct.this._.numResults) , subcon=ct.Struct(
                                'ID'     / ct.Default(ct.Int16ul,0),
                                'strLen' / ct.Default(ct.Int16ul,3),
                                # some more shit
                                'my_str'    / ct.Default(ct.PascalString(ct.Computed(ct.this.strLen) , 'ISO-8859-1'),'abc'),
                        )
                    ),
    )
```

**Comment by arekbulski** [comment]
Compilation feature only works for certain constructions, not all of them. Dont worry about it.
