### ISSUE TITLE
Struct should warn or raise exception when duplicate keys are detected

### ISSUE THREAD

**Issue by demberto** [construct/construct#998]
Because it doesn't, it can lead to surprising errors later on. Sometimes struct aren't small.

**Comment by arekbulski** [comment]
I dont recall anyone making a mistake of duplicating names in struct members however there was a similar problem: people used to use names that were in conflict with Container class members like "update" "keys" "items" etc.

**Comment by demberto** [comment]
imo its better to just warn earlier, it can save a lot of time, from debugging unrelated errors later.
